### ISSUE TITLE
Returning (I,Q,U) tuples makes it really easy to make stupid mistakes that go unnoticed. 

### ISSUE THREAD

**Issue by marius311** [healpy/healpy#113]
Consider the line, 

```
alm = map2alm(map1) + map2alm(map2) 
```

If map1 and map2 are temperature maps only, the return value is an array which is the sum of alms. If map2 and map2 are an (I,Q,U) tuple of maps, the each call returns a tuple, which when added are concatenated into a length-6 tuple, rather than adding the maps. This is a pretty easy mistake to make which is worsened by the fact that if you then call alm2cl(alm) with alm as the length-6 tuple, you don't get an error message (you get the 21 cross spectra). You can make the same mistake with several other function combinations, e.g. synfast/anafast, and operators e.g. +, *, etc..   

A proposed solution would be to make map2alm (and all other such functions) return 2-d arrays, that way the addition operator works the same whether you have just a T map or I,Q,U maps. It would not break anyone's code that was indexing the return values, i.e. map2alm(map)[0] would still work the same.

**Comment by zonca** [comment]
implemented by @keskitalo
