### ISSUE TITLE
healpy 1.7.0 install fails because of install-sh permissions

### ISSUE THREAD

**Issue by larrybradley** [healpy/healpy#154]
The file `healpixsubmodule/src/cxx/autotools/install-sh` in `healpy-1.7.0.tar.gz` is not set as executable, which causes the install to fail (via pip or a local install using the tarball).

**Comment by defjaf** [comment]
I am seeing this problem again trying to install 1.8.3 via `pip install -U healpy`.

1.8.2. worked fine, but note that I also just installed a new setuptools (12.0.1).

Andrew

**Comment by zonca** [comment]
ok, try with .18.4
