### ISSUE TITLE
problem in gnomview when ysize is different xsize

### ISSUE THREAD

**Issue by crosset** [healpy/healpy#17]
the gnomview visualization does not work when called with ysize != xsize.

**Comment by rwogburn** [comment]
This is a problem with inconsistent association of i,j with x,y in gnomview functions in projector.py.  The i index should go from 0 to ysize-1 and the j index from 0 to xsize-1, but in a few places it's the wrong way around.  Will submit a pull request to swap where needed.  The other projections look OK.

**Comment by rwogburn** [comment]
Tested using the following cases:
```
nside = 8
npix = 12*nside*nside
rot=[0,90,0]

# Plot linear ramp of pixel values
v = np.arange(npix)
hp.gnomview(v,rot=rot,nest=False,reso=30,xsize=180,title='xsize=180')
hp.gnomview(v,rot=rot,nest=False,reso=30,xsize=180,ysize=180,title='xsize=ysize=180')
hp.gnomview(v,rot=rot,nest=False,reso=30,xsize=180,ysize=90,title='xsize=180, ysize=90')
hp.gnomview(v,rot=rot,nest=False,reso=30,xsize=180,ysize=200,title='xsize=180, ysize=200')
```

**Comment by zonca** [comment]
thanks! this is a very long standing issue!!

**Comment by rwogburn** [comment]
Thanks, I think this can be closed.
