### ISSUE TITLE
rc configuration file

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#18]
add a configuration file for common parameters, like:
* xsize for mollview and gnomview
* nest to set all functions default to be nest=True

the style should be similar to matplotlibrc or ipythonrc, with a systemwide configuration file overridden by .healpy/healpyrc

please add other useful parameters below.

**Comment by lpsinger** [comment]
> nest to set all functions default to be nest=True

I think that changing the default pixel ordering could be very confusing. Can we close this?

**Comment by zonca** [comment]
ok, let's close it
