### ISSUE TITLE
Installation instructions for Homebrew

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#183]
We need some good installation instructions for Homebrew.

In #168, @SaulAryehKohn reported:

> I get:
> 
> ```
> ~ > pip install --user healpy
> Downloading/unpacking healpy
>   Running setup.py egg_info for package healpy
>     No Cython >= 0.16 found, defaulting to pregenerated c version.
>     ...
>     (bunch of checks)
>     ...
>    Installing collected packages: healpy
>    Running setup.py install for healpy
>     No Cython >= 0.16 found, defaulting to pregenerated c version.
>     error: can't combine user with with prefix/exec_prefix/home or install_(plat)base
>     ....
>    running install
> 
> error: can't combine user with with prefix/exec_prefix/home or install_(plat)base
> ```
> 
> (I know that I actually have Cython 0.18 installed, I just don't know how to point to it). I appreciate you're not a brew pro, thanks for your help all the same!

**Comment by zonca** [comment]
very very old issue, closing
