### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#194]
The README file says:

```
healpy pixel functions, e.g. ang2pix, do not support 32bit platforms, we are working on fixing this issue.
```

What exactly are the issues on 32-bit platforms? If the unit tests do not pass on 32-bit machines, then we either have to fix the issue or restrict the Debian packages to 32-bit architectures.

**Comment by zonca** [comment]
I think it's probably not necessary anymore to support 32 bit platforms should we close this?
