### ISSUE TITLE
Readthedocs build failing

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#219]
I tried locally and the build works.
It has been a while that the documentation fails to build on readthedocs,

see the build log:

https://readthedocs.org/builds/healpy/2102053/

Maybe related to a too old `setuptools`? See https://github.com/rtfd/readthedocs.org/issues/1029

**Comment by lpsinger** [comment]
That's a good guess. I'm not familiar with the readthedocs environment. Are you able to update the version of setuptools with `pip` or `easy_install`?

**Comment by zonca** [comment]
it is failing again: https://readthedocs.org/builds/healpy/2509652/

it is possible that I checked the wrong travis run when I updated ez_setup in #233 . Need to investigate this again.

**Comment by lpsinger** [comment]
OK. Otherwise I think we're ready for healpix-cxx and healpy releases.

**Comment by lpsinger** [comment]
> it is failing again: https://readthedocs.org/builds/healpy/2509652/
> 
> it is possible that I checked the wrong travis run when I updated ez_setup in #233 . Need to investigate this again.

@zonca, I think that you were looking at the correct build. This is very odd; the last successful build was at commit a3e8e928fd016efcd042d0399ae656ca83f6933e. Very little has changed since then on master; see the diff.

**Comment by lpsinger** [comment]
Very odd. The testreadthedocs branch always passes, but master does not. Is there some configuration inside the readthedocs interface that is different for these two branches?

**Comment by zonca** [comment]
hmm, interesting...

tried with a wipe:
https://readthedocs.org/wipe/healpy/latest/

and triggered rebuild manually, let's see what happens

**Comment by lpsinger** [comment]
Yay, it worked!

**Comment by zonca** [comment]
great!
