### ISSUE TITLE
wrapper in pixelfunc.py raises IndexError when passing only keyword arguments

### ISSUE THREAD

**Issue by eirikgje** [healpy/healpy#222]
The wrapper inside accept_ma assumes there are always some *args, so that when calling, e.g.

ud_grade(map_in=inmap, nside_out=1024),

it raises an index error, since it doesn't check for empy *args:

    207     @wraps(f)
    208     def wrapper(*args, **kwds):
--> 209         return_ma = is_ma(args[0])
    210         m = ma_to_array(args[0])
    211         out = f(m, *args[1:], **kwds)

IndexError: tuple index out of range

**Comment by zonca** [comment]
Thanks for reporting this.
I cannot think about any simple way to solve this issue in a general way that would work for any wrapped function.
So I recommend that in this case we just raise an exception and explain to the user that we need the map to be a positional argument.
@eirikgje do you have any suggestion?
could you implement this and create a pull request? (with a unit test would be great!)

**Comment by lpsinger** [comment]
How about declare it as `def wrapper(map_in, *args, **kwds):`?

**Comment by eirikgje** [comment]
@lpsinger : Is this wrapper always applied to functions that must take a map as the first argument? In that case, it seems reasonable to do what you suggest. Otherwise, we could try to figure out what the user did:
    if 'map_in' in kwargs:
        arg = kwargs['map_in']
    else:
        arg = args[0]

or something like that?

**Comment by lpsinger** [comment]
> @lpsinger : Is this wrapper always applied to functions that must take a map as the first argument?

As far as I can tell, yes.

**Comment by eirikgje** [comment]
Ok, I will make a test and pull request, then!

**Comment by lpsinger** [comment]
@eirikgje's pull request is #223.

**Comment by zonca** [comment]
Thanks!
