### ISSUE TITLE
Python 3 incompatibility in projaxes._make_segment() - xrange undefined

### ISSUE THREAD

**Issue by ajhorton** [healpy/healpy#226]
heapy 1.8.4 as installed with pip has a Python 3 incompatibility in projaxes._make_segment().  Line 397 of projaxes.py calls the Python 2 xrange() builtin function but this function is not present in Python 3.  In Python 3 the Python 2 xrange() have been renamed range() and the Python 2 range() has been removed.

An ugly but easy fix would be to add
```Python
try:
    xrange
except NameError:
    xrange = range
```
in the module preamble.

**Comment by lpsinger** [comment]
We're already using `six.moves.xrange` in a few places. Uh-oh, `six` is not listed in the dependencies, though.
