### ISSUE TITLE
Python 3 incompatibilities in visufunc - sub relies on implicit integer division

### ISSUE THREAD

**Issue by ajhorton** [healpy/healpy#227]
The subplot functionality of the visualisation functions in visifunc (mollview(), gnomview(), cartview(), orthview()) does not work correctly with Python 3 because it relies on implicit integer division.  The problematic lines are `c,r = (idx-1)%ncols,(idx-1)/ncols` which calculate the column and row number for the plot.  Under Python 3 `(idx-1)/ncols` will do 'true' division and return fractional values, causing plots in columns after the first to be offset below their correct position.  For compatibility with both Python 2 and 3 explicit integer division should be used, i.e. replace each instance of `(idx-1)/ncols` with `(idx-1)//ncols`

**Comment by lpsinger** [comment]
Yes, we have replaced `/` with `//` in several other places. Would you care to submit a patch?

**Comment by ajhorton** [comment]
I'm happy to submit a patch but I won't be able to get around to it for a while, it's research grant application season.
