### ISSUE TITLE
rename "get_neighbours" and adjust documentation

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#240]
The function "get_neighbours" in pixelfunc.py should be renamed to something like "get_interpol" (which is the name of the corresponding function in the C++ library.
The documentation should be changed from
    """Return the 4 nearest pixels and corresponding weights.
to something like
  """Return the 4 closest pixels on the two rings above and below the location and corresponding weights. Biinear interpolation is carried out along latitude and longitude.

**Comment by lpsinger** [comment]
I'm not sure about the docstring change. This function does not do bilinear interpolation; the existing [`get_interp_val`](http://healpy.readthedocs.org/en/latest/generated/healpy.pixelfunc.get_interp_val.html#healpy.pixelfunc.get_interp_val) function does that.

**Comment by mreineck** [comment]
Ah, OK. Maybe "Weights are provided for bilinear interpolation along latitude and longitude"?

**Comment by lpsinger** [comment]
I like that. Should provide a "see also" link to point to `get_inter_val`.

Should also try to match spelling: no sense abbreviating 'interpolation' with 'interpol' in one place and 'interp' in another place.

**Comment by zonca** [comment]
I'm ok with the docstring change, however not sure about the naming. I would prefer to keep `get_neighbours`, `get_interpol` or `get_interp` look confusing.
If we come up with a better name I'm ok to change it.

**Comment by mreineck** [comment]
I don't have a strong opinion on the new name - it just should not have the name "neighbours" in it, because it does not compute what users typically consider to be neighbours, and because it is very different from the "real" neighbours routine of Healpix C++. And having something like "interpolation" in the name might be useful, since this is about the only purpose for this function I can imagine.

**Comment by zonca** [comment]
ok, so similar to `get_interp_val`, I would call it `get_interp_weights`

**Comment by lpsinger** [comment]
Could we have `get_neighbors` point to `get_interp_weights` with a deprecation warning so that we don't break the API on this release?

**Comment by zonca** [comment]
I think an exception is better. People can quickly fix the problem renaming the function call.

**Comment by lpsinger** [comment]
> I think an exception is better. People can quickly fix the problem renaming the function call.

Common practice would usually be to print a deprecation warning and then remove the function in a future release. That's OK, though.

However, the [Travis build is failing](https://travis-ci.org/healpy/healpy/builds/59632607) because the renamed function was not add to `healpy/__init__.py`.
