### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by astrofrog** [healpy/healpy#251]
It would be great to build a conda package for healpy to make it easier to install. I have some experience with that though what would be new to me here is to have to include the healpix library which is not Python. But it should be doable (I think there should probably be two conda packages: ``healpix`` and ``healpy``).

One can use Travis and Appveyor to automatically build the conda packages, for example:

https://github.com/glue-viz/conda-package-builder

In fact with the Multi-OS feature from Travis, MacOS X is also supported for that example (note that they are currently not accepting new requests for that as they need to ramp up capacity).

This is not something I can work on right now, but I can definitely provide advice. In future, I may find the time to do it.

**Comment by cdeil** [comment]
I briefly talked to @mwcraig at the PyAstro15 conference about whether it would be possible to centralise the wheel and / or conda package creation for many astro packages.
It's a non-trivial set of skills and time investment to configure and maintain this, and it seems wasteful to let many projects (astropy, astropy-affiliated packages, healpy, sextractor, scipy, galsim, iminuit, ... 1000 more) figure that out.

Maybe this issue should be brought up on the conda or scipy or numfocus mailing list?

**Comment by cdeil** [comment]
There's also https://github.com/MacPython by @ChrisBarker-NOAA .

**Comment by astrofrog** [comment]
I agree that it would be good to try and centralize this, though I can't volunteer for that. There's two aspects - one is writing the recipes and one is building the packages.

Recipes can already be centralized here in principle:

https://github.com/conda/conda-recipes

but then there's the question of building. One can't build too many conda packages in a single repo because Travis has build time limitations. But there's nothing to say we *have* to go through conda. For example binstar does have a continuous integration mode but it's not free. However, maybe that's something that e.g. NumFOCUS could fund.

Another side note is that scipy and astropy don't need to worry about this because the conda team deals with those.

**Comment by cdeil** [comment]
@rgommers Is this something that has been discussed in Numfocus? (Sponsoring conda package builds on binstar for scientific Python packages and making it easy to apply for this or help get it done.) Would it be helpful to express this wish on the Numfocus mailing list?

**Comment by astrofrog** [comment]
Just for information, here's the information on setting up builds on binstar:

http://docs.binstar.org/draft/examples.html#SubmitYourFirstBuild

Also if you are logged in and go to:

https://binstar.org/dashboard/builds

It says

*Binstar build is a continuous integration framework that allows you to automate package building. Binstar build provides everyone with a free linux-64 build VM.  With a paid subscription, you can also create windows, osx or any other machine type workers that you want.*

The cheapest organizational plan is $47/month and it's not clear to me if there would be any limit to the number of packages supported by the continuous integration if they are all public packages (maybe @asmeurer could clarify?)

In the mean time, it sounds like we could already try and set this up for just linux 64-bit for testing. So then the workflow would be:

- Add a recipe to the central https://github.com/conda/conda-recipes repo

- Set up the continuous integration to build specific packages

@asmeurer - is it possible to tell the binstar CI to build only some packages from the conda-recipes repo? Or by chance do you already build all recipes in conda-recipes? (that would be even better because then as developers we would just add a recipe file and continuum would deal with putting all these in an e.g. 'contrib' conda channel?)

**Comment by cdeil** [comment]
Why is Astropy at version 0.2 in this recipe?
https://github.com/conda/conda-recipes/blob/master/astropy/meta.yaml#L3
By default one now gets Astropy 1.0 from conda, so this doesn't seem to be what's in use?

**Comment by astrofrog** [comment]
@cdeil - I think you can think of that repo as a kind of 'contrib' list of repos, and as far as I know those aren't the authoritative versions of the recipes. Maybe astropy should be removed from there?

**Comment by rgommers** [comment]
@cdeil I don't remember a discussion on this. A request for support for infrastructure to help ease the maintenance burden for core/supported projects will likely be well-received though. I suggest to summarize what would be needed exactly and send a request (see http://numfocus.org/projects/apply-for-grant.html)

**Comment by mwcraig** [comment]
I'm interested in taking this on starting in a couple of days. My thought was to email astropy-dev and ask about a couple of architectures:

1. Affiliated packages modify their travis/appveyor setup to build and push to a centralized repo, or
2. Setup a builder bot along the lines of what @astrofrog setup prior to astropy 1.0. It would perhaps have a webhook that affiliates could add to trigger a new package build for each new tag.

I don't think the conda-recipes repo is the way to go. Recent [discussion on the conda list](https://groups.google.com/a/continuum.io/forum/#!topic/conda/AoQ7C9BLby4) has focused on setting up a community channel on binstar to which a few people have commit rights that could serve as a place to distribute discipline-specific packages.

That will be the second question to astropy-dev: host on an astropy channel on binstar or on the community channel or both?

**Comment by mwcraig** [comment]
@cdeil -- my take on the conda-recipes repo is that it was started in hopes it would be "the" place that people put their recipes (sort of like homebrew formulae) but it hasn't turned out that way.

**Comment by mwcraig** [comment]
conda-recipes is definitely *not* what the continuum folks build from.

**Comment by astrofrog** [comment]
@mwcraig - for the builder bot part, it would be far easier if we could use binstar's CI since it would automatically take care of all architectures. At the moment it's a bit of a pain to rely on Travis and Appveyor and it's not really what they were designed for. But we can use them in the interim. We should also test out binstar's CI since we can already use it for linux 64-bit.

For the recipes, we shouldn't use https://github.com/astropy/conda-builder because that is an actual bot, but we have https://github.com/astropy/conda-recipes (though we should clear out a lot of those modules that aren't needed and focus on astropy affiliated packages and other dependencies needed by those packages).

@rgommers - thanks for your reply! We'll take a look at the free CI option on binstar for now and once we understand if it will be suitable we will get in touch with NumFOCUS.

**Comment by mwcraig** [comment]
@astrofrog -- my understanding from a few months ago is that binstar.org doesn't provide any build platforms except linux even if you pay. Paying gets you the ability to add your own build machines to their system (see https://groups.google.com/a/continuum.io/forum/#!searchin/conda/binstar$20build/conda/koaY9wf0ibY/XJmj10o2YYkJ).

Agreed that travis/appveyor aren't ideal, though these builds should be fairly infrequent if they are limited to releases. I can kick start things later this week on some local machines if needed. I'm assuming that most affiliated packages will be buildable either with either `python setup.py bdist_conda` or `conda skeleton` to generate the initial recipe followed by some light editing.

**Comment by astrofrog** [comment]
@mwcraig - on my binstar build page, it does say:

*Binstar build is a continuous integration framework that allows you to automate package building. Binstar build provides everyone with a free linux-64 build VM. With a paid subscription, you can also create windows, osx or any other machine type workers that you want.*

Maybe this is something new?

**Comment by mwcraig** [comment]
@astrofrog -- that was what induced me to sign up for a paid plan...but it turned out that "create" meant "make your own and add as a worker". I would ask before paying; if it has changed that would be fantastic!

**Comment by mwcraig** [comment]
@astrofrog -- if you would like I can ask on one of the conda lists, but won't get to it until tomorrow probably.

**Comment by astrofrog** [comment]
@mwcraig - that would be great, thanks!

**Comment by astrofrog** [comment]
It sounds like in any case we should have an astropy-wide repo of all recipes and we can figure out the building separately.

**Comment by cdeil** [comment]
@mwcraig – Thank you for taking this on for Astropy and affiliated packages!!!

To me implementing an astronomy-only solution still seems the wrong long-term approach and someone (that's the tricky part) providing a free (that's the other tricky part) and easy to apply for / setup / maintain build service for scientific Python open-source packages would be better.
@mwcraig – maybe you can poke the numfocus or conda guys about this as well? (I haven't used binstar and don't even know how their build service works ... I guess even if you need an external Mac and Windows box it should still be possible to set up if someone pays for such machines in the cloud?)

**Comment by astrofrog** [comment]
As I mentioned in the other issue related to this, I think that with a paid account (which it looks like numfocus would be open to) we might be able to have the infrastructure to do this for many different projects.

The astronomy-only solution could be a starting point though - there are already going to be dozens of packages, hundreds of conda files, so it would be good to start with that to see if we can scale up?

**Comment by ChrisBarker-NOAA** [comment]
On Tue, May 5, 2015 at 5:43 AM, Thomas Robitaille <notifications@github.com>
wrote:

> I agree that it would be good to try and centralize this, though I can't
> volunteer for that. There's two aspects - one is writing the recipes and
> one is building the packages.
>
> Recipes can already be centralized here in principle:
>
> https://github.com/conda/conda-recipes
>
hmm -- maybe that is where to go, but....


> but then there's the question of building. One can't build too many conda
> packages in a single repo because Travis has build time limitations. But
> there's nothing to say we *have* to go through conda. For example binstar
> does have a continuous integration mode but it's not free. However, maybe
> that's something that e.g. NumFOCUS could fund.
>
Funding would help with ANY CI or build system, I suppose. So that would be
great.

But my latest thought is this, at least for a stopgap:

Aaron set up a binstar channel for community packages -- so that's where we
can put them. But how to manage maintaining the recipes and building the
packages. At the moment, we have a number of people that have taken on that
role for a subset of packages they care about -- but we want to not
duplicate effort, so I suggest:

We have a bunch of individual gitHub repos, each with a subset of packages.
Each of those repos has one or a small handful of people that are taking
responsibility for them. They can be built with a combination of Travis,
etc, and folks simply running the build on their own machines -- for a
dozen or so packages, it's just not a big deal.

I suggest using Obvious-CI to manage the build process:

https://github.com/pelson/Obvious-CI

It's pretty slick.

This is essentially what a bunch of us are already doing -- except we'd put
the built packages in a single shared binstar repo, and then only one of us
would need to maintain a given package.

The other management issue would be keeping track of who is managing which
package -- maybe a gitHub repo for that?, and have it be a simple list --
or can anyone think of a more automagic way to mange it?

This should probably start with an gitHub organization account to put all
this in.

-Chris

>

-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by cdeil** [comment]
From the comment that @ChrisBarker-NOAA posted:

> We have a bunch of individual gitHub repos, each with a subset of packages.
Each of those repos has one or a small handful of people that are taking
responsibility for them. They can be built with a combination of Travis,
etc, and folks simply running the build on their own machines -- for a
dozen or so packages, it's just not a big deal.

This doesn't sound like a good (i.e. good results and low maintenance) long-term solution to me.
The successful package managers like Debian or Macports use a centralised repo for recipes and a centralised build service run by a few experts.
Of course it needs a

**Comment by ChrisBarker-NOAA** [comment]
On Tue, May 5, 2015 at 9:27 AM, Christoph Deil <notifications@github.com>
wrote:

> From the comment that @ChrisBarker-NOAA
> <https://github.com/ChrisBarker-NOAA> posted:
>
> We have a bunch of individual gitHub repos, each with a subset of packages.
> Each of those repos has one or a small handful of people that are taking
> responsibility for them. They can be built with a combination of Travis,
> etc, and folks simply running the build on their own machines -- for a
> dozen or so packages, it's just not a big deal.
>
> This doesn't sound like a good (i.e. good results and low maintenance)
> long-term solution to me.
>
Didn't I call it a stop-gap measure ;-) -- I should have.

 The successful package managers like Debian or Macports use a centralized
repo for recipes and a centralized build service run by a few experts.

Sure -- that would be great -- and, indeed, it is what Continuum is doing
for the official Anaconda packages. But there is a big barrier to entry
here; what I am suggesting is a way to reduce duplication of effort without
needing to spin up a substantial organization.

The centralized build service seems to require funding - so if NumFocus, or
anyone else, can provide that, great!

It also requires a pretty big commitment from the "few experts" that are
going to have commit privileges to the repo, and mange the build service.
If a few folks want to take that on, also great.

Now that I think about it, we should be able to put all build scripts in
one place, though I'm having a bit of trouble figuring how to keep track
of, and manage, who is taking responsibility of what packages. If someone
figures that out and sets up a system, I"ll contribute.

But if all that is not going to happen soon, then what I'm suggesting is a
transitional approach -- it's actually almost exactly the same as what is
currently going on -- we have a half a dozen or so groups that are managing
a set of packages they care about. What I am suggesting is that we all do
exactly that -- with the exception of putting all of them in the same
binstar channel.

The only extra work here is that we need to de-duplicate

And if/when we get a better, more centralized system going, we can take all
the recipes alrady developed and move them on over.

-CHB


-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by cdeil** [comment]
@scopatz – Maybe you could also comment here?
We're looking for a conda build service for astro packages or more generally scientific Python packages.

I remembered there were discussions on the numfocus list about this:
https://groups.google.com/forum/#!topic/numfocus/mVNakFqfpZg
https://groups.google.com/forum/#!topic/numfocus/HUcwXTM_jNY
https://groups.google.com/forum/#!topic/numfocus/mSnWp8dKH2g

Is https://www.batlab.org/ and http://polyphemus.org/ something that could scale to many packages?

**Comment by lpsinger** [comment]
Should we think about making Healpy an Astropy affiliated package and use the Astropy setup helpers? If so, we could reuse a lot of Astropy's setup code for building against external libraries. Using Astropy's mechanism for linking against or building erfa, cfitsio, etc. in Healpy for healpix-cxx and cfitsio may help with #25.

**Comment by scopatz** [comment]
> Is https://www.batlab.org/ and http://polyphemus.org/ something that could scale to many packages?

Hi @cdeil, thanks for asking.  We have moved away from batlab / polyphemus because, while technically capable, it proved too difficult to maintain.  I would recommend doing something more along the lines of what @ogrisel has done for scikit-learn. See his talk from PyCon on this topic http://pyvideo.org/video/3473/build-and-test-wheel-packages-on-linux-osx-win. For most of the projects I work on with C-extensions, we had independently moved in this direction.

**Comment by mwcraig** [comment]
We are trying to get healpy built at openastronomy/conda-channel#3 and are hitting come build errors. 

The one here on linux is particularly odd because it is trying to install nose: https://travis-ci.org/OpenAstronomy/conda-channel/jobs/118622876#L1732

We are also hitting Windows build fails, any input welcome!

**Comment by zonca** [comment]
About windows: we never managed to compile the C++ extension on Windows.

**Comment by lpsinger** [comment]
> We are trying to get healpy built at OpenAstronomy/conda-channel#3 and are hitting come build errors.

I offered a suggestion on OpenAstronomy/conda-channel#3.

> We are also hitting Windows build fails, any input welcome!

As @zonca says, Healpy does not currently support Windows. This is largely my fault. The healpix-cxx is moderately difficult to build correctly because of OpenMP and reliance on some bleeding-edge C++ features. I overhauled the healpix-cxx build as a traditional autotools-driven configure/make/install to make sure that all of the compiler checks were done correctly, then had setup.py simply call configure/make/install. Unfortunately, that means that building for Windows would require either a POSIX support layer like Cygwin or a cross-compiler.

**Comment by mreineck** [comment]
I'm not aware that the C++ package currently imported by healpy uses any feature outside C++98 - if so, I'll have a look and try to fix that. (Future releases will probably require C++11, however.)
OpenMP should not hurt on a non-OpenMP-aware compiler; it will just ignore the #pragma directives.
But I agree that the current compilation infrastructure requires POSIX support. Maintaining Windows-specific configuration tools will be more or less impossible (for me at least), since I don't use the platform.
That said, if you post the build problems you are running into, I might be able to indentify what exactly is going wrong and suggest a workaround.

**Comment by cdeil** [comment]
https://github.com/OpenAstronomy/conda-channel/pull/3 is merged, conda packages for Linux and Mac are now available via `conda install -c openastronomy healpy`.

Close this issue?
(maybe file a new one summarising the status and action items for Windows support?)

Worth mentioning at http://healpy.readthedocs.org/en/latest/install.html ?

**Comment by zonca** [comment]
added to `INSTALL.rst` https://github.com/healpy/healpy/commit/7e9103756c9a2881d2285b7ebd1b3627d701cc75
