### ISSUE TITLE
Add utility functions to work with "cutouts"

### ISSUE THREAD

**Issue by cdeil** [healpy/healpy#252]
Disclaimer – I know almost nothing about HEALPIX ... apologies if this doesn't make sense.

My understanding of the HEALPIX <-> normal WCS projection image reprojection functions in https://github.com/astrofrog/reproject is that the HEALPIX data will always cover the whole sky, i.e. there'll be lots of zeros if the image only covers a small part of the sky.

Would it make sense to add functionality to `healpy` or `reproject` or `pymoc` to efficiently handle this case, i.e. store only the pixel values within a footprint in the HEALPIX data array and FITS file when reprojecting a normal image to HEALPIX?

Another use case would be to produce a cutout of an all-sky HEALPIX image ... I guess this is what the web server does here http://aladin.u-strasbg.fr/hips/ to only send the data to the user that's in the viewport, but it is not easy to do this cutout with `healpy`?

cc @astrofrog as the https://github.com/astrofrog/reproject dev
cc @tboch as the https://github.com/tboch/pymoc dev

**Comment by zonca** [comment]
`healpy` has partial support for explicit pixelization maps, i.e. dictionary where keys are pixel numbers.
see in the projector:

https://github.com/healpy/healpy/blob/a6ae7de250c937b3724985eef4f429502ca90d3f/healpy/projector.py#L185

However it doesn't allow to use the most powerful feature of HEALPix which is the spherical armonic transforms. I never used it.
It would be interesting if you could give it a try to check if it still works.

**Comment by zonca** [comment]
See #254, it would be useful to check if the visualization functions still work with explicit pixelization maps.

It is a corner use case, I won't spend time on this.

Closing for now, please reopen if you want to contribute some test results.
