### ISSUE TITLE
Smoothing invert option unused

### ISSUE THREAD

**Issue by mkolopanis** [healpy/healpy#255]
The optional keyword "invert" in the smoothing and smoothalm functions is currently used in the healpy. Both functions use almxfl to compute the actual smoothing of a healpix map by a beam and the almxfl function does not take the keyword "invert" as an argument. There is also no statement which computes a factor of 1./beam to pass to almxfl as an argument. The source code for smoothalm never appears to check the invert keyword.

**Comment by zonca** [comment]
thanks @mkolopanis I confirm this, would you like to contribute a Pull Request to remove `invert` from the source code?

**Comment by mkolopanis** [comment]
Sure! How would I go about doing this?

**Comment by zonca** [comment]
start from here: https://help.github.com/articles/creating-a-pull-request/

**Comment by zonca** [comment]
fixed in #257
