### ISSUE TITLE
Autodoc broken

### ISSUE THREAD

**Issue by cmbant** [healpy/healpy#263]
Many functions are not being rendered/linked correctly in the documentation, e.g.
http://healpy.readthedocs.org/en/latest/healpy_visu.html - presumably some issue with the sphinx/autosummary config.

(and hence docs for core functions like "mollview" do not appear helpfully when you search).

**Comment by zonca** [comment]
thanks for reporting this, I fixed it, I think the main issue was 9210a1e3944340c530
