### ISSUE TITLE
Problem with healpy

### ISSUE THREAD

**Issue by Tia87ibra** [healpy/healpy#269]
I have installed Healpy following the command sudo port install py27-healpy.
The installation works:

--->  Computing dependencies for py27-healpy
--->  Cleaning py27-healpy
--->  Scanning binaries for linking errors
--->  No broken files found.

However, if I try to import the healpy command this is the problem.

host039-pool27:sfg_icecube mattiadimauro$ ipython
Python 2.7.10 |Anaconda 2.1.0 (x86_64)| (default, May 28 2015, 17:04:42) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import healpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c6580042a8d8> in <module>()
----> 1 import healpy

ImportError: No module named healpy

Does someone know the origin of the problem?

Thank you

**Comment by zonca** [comment]
it looks like you are installing `healpy` with Macports but then using Anaconda.

you should either try to use the Python installation from Macports, or install healpy inside anaconda with `pip install healpy`

**Comment by zonca** [comment]
it looks like an user issue, please use stackoverflow for that.
