### ISSUE TITLE
View plot sizes

### ISSUE THREAD

**Issue by cmbant** [healpy/healpy#270]
The "xsize" argument to orthview et al only seems to be used internally to change the pixel resolution. The actual figure size is always (8.5,5.4). I suggest making the figure size either scale with xsize, or have a new kwarg to set the figure width.

**Comment by zonca** [comment]
I don't think it is a necessary option. however I would merge a pull request if somebody wants to implement it.

You can set figure size beforehand, then run `mollview` with `hold`:

```python
plt.figure(figsize=(16, 10))
hp.mollview(np.arange(12), hold=True)
```

**Comment by cmbant** [comment]
The option you suggest works fine, thanks, but is unobvious to a new user. 
You should at least clarify the docs for xsize (that it does not change the figure size). 

If you want more community involvement, like pull requests, I suggest you don't immediately close suggestions you personally don't like or can't replicate.

**Comment by zonca** [comment]
I'd love a pull request to change the docs of xsize, thanks!
