### ISSUE TITLE
Extracting axes after projected healpix into certain projection

### ISSUE THREAD

**Issue by AstroClimber** [healpy/healpy#285]
Hi I am trying to extract the coordinate information for a healpix map I downloaded, called Haslam Map for the synchroron foreground in the Milky Way. I was able to acquire a ndarray of the map after using the keyword 'return_projected_map' in healpy.cartview. However, now I have no information of the coordinates of the returned map. So far the closest thing I have found is the module healpy.projaxes.MollweideAxes()

However, I have not found any example on how to use it properly. Wonder if you guys can point me in the right direction to proceed. 

Thanks!

**Comment by rwogburn** [comment]
If you want to be sure, and to control the map pixelization, why not choose the latitude and longitude values yourself and then use get_interp_val?

**Comment by zonca** [comment]
No followup, closing this, please reopen if you get back to this.
