### ISSUE TITLE
gnomview does not honor 'degree' argument

### ISSUE THREAD

**Issue by rwogburn** [healpy/healpy#287]
It's simply not used.  Can be fixed by adding following lines in visufunc.py somewhere before line 358:

```
if (degree):
  reso*=60
```

**Comment by lpsinger** [comment]
I'd actually favor just dropping the unused argument. Kind of silly having two arguments just to specify one quantity, the angular resolution per pixel.

**Comment by rwogburn** [comment]
Healpix gnomview doesn't have it, so I suppose it's fine for healpy not to have it either (as long as it's documented correctly).  Although you do end up with a mix of units since the rotation is specified in degrees.

**Comment by rwogburn** [comment]
I have a topic branch to use the degree argument:
https://github.com/rwogburn/healpy/tree/issue287

and one to remove it instead:
https://github.com/rwogburn/healpy/tree/issue287alt

Either could be merged.  Thanks.

**Comment by rwogburn** [comment]
Thanks lpsinger and zonca, this is resolved.
