### ISSUE TITLE
Smoothing numerical values

### ISSUE THREAD

**Issue by mayurisrao** [healpy/healpy#290]
Hello,   
   I looked at a similar issue that was previously closed, but my problem is a little different. I took an all sky HEALPix map and replaced the values of all pixels except one to have a numerical value (temperature) of zero. In my mollview plot, this pixel shows up as a bright red spot where as the rest of the map is cold (zero = blue). I use the 'hist' normalization in mollview. When I now convolve with a gaussian beam such that the final map would have a resolution of 5 degrees, I do see that the shape of the new smoothed point looks okay, like a Gaussian. But I see that the temperature scale has now changed and I see negative numbers. Does 'healpy.sphtfunc.smoothing' do some kind of additional normalization. Convolving with a Gaussian beam should be an averaging operation. How can a map with all zeros and one large positive value result in negative values on smoothing?
I've placed the images before and after smoothing, I am concerned with the values on the scale at the bottom.
Appreciate your replies!

![before_smoothing](https://cloud.githubusercontent.com/assets/5463816/10460176/dc23ff02-71f0-11e5-91fe-07c10d239723.png)
![after_smoothing](https://cloud.githubusercontent.com/assets/5463816/10460183/e04f368c-71f0-11e5-84a0-89c37d73d0b0.png)

**Comment by rwogburn** [comment]
Gaussian beam smoothing isn't applied by averaging pixels, it's applied in spherical harmonics.  I assume the previous issue you looked at was probably #135?
https://github.com/healpy/healpy/issues/135
The question was not the same, but mreineck's advice still applies and explains why there can be negative values after this kind of operation.  When I perform the same test you outlined, I find the negative values are small (order of 10^-12).

**Comment by mayurisrao** [comment]
Thanks rwogburn. So if I understand correctly, although I am using  healpy.sphtfunc.smoothing which in principle operates in a flat space approximation, the convolution operation is still happening in alm space? When I did a different test, i.e. made a map with all pixels having the same value of 100, and performed smoothing using healpy.sphtfunc.smoothing, I get back a map that is all zeros. The documentation of smoothing clearly mentions that 'No removal of monopole or dipole is performed.'. Is there some place where I can read how the smoothing function in HEALPy actually works on data?
- Thanks!

Input map:
![unifrom_input_map](https://cloud.githubusercontent.com/assets/5463816/10475098/173adf22-725d-11e5-967e-f0e2dbfe0e3b.png)
Output map:
![smoothed_output_map](https://cloud.githubusercontent.com/assets/5463816/10475102/17fe67bc-725d-11e5-8ead-b1d5cc949134.png)

**Comment by mayurisrao** [comment]
Hello,
  A quick update. I ran the same code on a different computer which has an older installation of healpy and found I got different results. The mean is not subtracted. Was there possibly an upgrade of the code to subtract a mean, which was not updated on the documentation?
If this is the case, this issue can be closed!
- cheers

**Comment by mreineck** [comment]
Hi mayurisrao,
if you see the monopole vanishing, there is definitely a bug somewhere. I'll double-check the C++ part of the code!
The small negative values are unfortunately really unavoidable...

**Comment by mreineck** [comment]
I don't see anything unexpected in the C++ part...

**Comment by rwogburn** [comment]
It's definitely not a flat sky approximation -- beam smoothing is done correctly for the sphere in spherical harmonic space.  I also checked that smoothing doesn't subtract the monopole when I run it in the current version.  The following lines of code

```
nside = 512
npix = 12*nside*nside

# Set all pix to 100.0
v = 100.0 + np.zeros(npix)

# Smooth with 5 deg FWHM gaussian
w = hp.smoothing(v, sigma=np.deg2rad(5.0)) # , iter=20, lmax=3*nside-1)

# Print diagnostic info
print "Total pixels = "+str(v.size)
print "Pixels < 0   = "+str(np.sum(w<0))
print "Pixels == 0  = "+str(np.sum(w==0))
print "Min pixel    = "+str(np.min(w))
print "Mean value   = "+str(np.mean(w))
print "Max pixel    = "+str(np.max(w))
```

Give the output

```
Total pixels = 3145728
Pixels < 0   = 0
Pixels == 0  = 0
Min pixel    = 99.9998457276
Mean value   = 99.9999988264
Max pixel    = 100.000000001
```

Could you try running the same commands on the computer that gave you different results?

**Comment by zonca** [comment]
No answer, closing this, please reopen if you get back to this.

**Comment by Astro-Falcon** [comment]
Does anyone have a file with all the fwhm parameters required for the smoothing function for different Nsides?
