### ISSUE TITLE
Install issue on OS X 10.11

### ISSUE THREAD

**Issue by jisuoqing** [healpy/healpy#295]
Hi,

I've tried to install healpy with a few ways, but when I imported the module, it says:

```
>>> import healpy
healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
healpy/sphtfunc.py:34: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
healpy/sphtfunc.py:38: UserWarning: Warning: cannot import _healpy_fitsio_lib module
  warnings.warn('Warning: cannot import _healpy_fitsio_lib module')
healpy/sphtfunc.py:42: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
healpy/__init__.py:58: UserWarning: Warning: cannot import query disc module
  warnings.warn('Warning: cannot import query disc module')
healpy/__init__.py:62: UserWarning: Warning: cannot import pixelfunc module
  warnings.warn('Warning: cannot import pixelfunc module')
healpy/__init__.py:69: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
healpy/__init__.py:77: UserWarning: Warning: cannot import pixel lib module
  warnings.warn('Warning: cannot import pixel lib module')
healpy/projaxes.py:36: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
```

I've tried ``pip install healpy`` as well as the development install, but neither of them work.

Thanks!

**Comment by lpsinger** [comment]
@zonca, I think that these conditional imports create a lot of confusion. It's better to stick to a single code path where possible. Why are they necessary? Does it have to do with readthedocs? There may be a cleaner solution.

**Comment by zonca** [comment]
@lpsinger yes, readthedocs, at some point it was also possible to run only the pure python part of healpy (plotting) if you couldn't compile healpix c++, but haven;t tested that in a while.

**Comment by lpsinger** [comment]
Does the readthedocs build environment have a working C/C++ compiler toolchain? If so, is it just a matter of it being slightly wasteful to build the native modules on readthedocs?

**Comment by zonca** [comment]
It looks like still they do not support building C extensions

**Comment by lpsinger** [comment]
> It looks like still they do not support building C extensions

Where do you see that?

**Comment by zonca** [comment]
FAQ http://read-the-docs.readthedocs.org/en/latest/faq.html

**Comment by lpsinger** [comment]
Do you mean [this part](http://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules)? They are not saying that they don't support building C extensions, just that they don't have arbitrary third-party libraries. Healpy comes with source code for all of its own dependencies, so it should work.

**Comment by zonca** [comment]
Ah ok, then we can give it a try

**Comment by lpsinger** [comment]
> Ah ok, then we can give it a try

It worked! See [Readthedocs output](http://lpsingerhealpy.readthedocs.org/en/latest/) for [my branch](https://github.com/lpsinger/healpy/tree/setup_cleanup).

**Comment by zonca** [comment]
Great! PR?

**Comment by lpsinger** [comment]
@jisuoqing, does the developer install fail with the same error message? If so, please pull and try again. #298 won't fix your issue, but it will give us more useful information about what went wrong.

**Comment by jisuoqing** [comment]
@lpsinger Thank you so much! It works -- previously the C files did not get compiled at all.
