### ISSUE TITLE
Install problem with El Capitan (OS X 10.11.1) and anaconda

### ISSUE THREAD

**Issue by DanielLenz** [healpy/healpy#310]
I've just re-installed OS X and cannot manage to install healpy with pip, the traceback is [here](https://gist.github.com/DanielLenz/0ea9da1a232987d9d8fe).

I'm using anaconda 2.4.0, also freshly installed.
gcc is the following:

    MBPR:~ dlenz$ gcc -v
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.0 (clang-700.1.76)
    Target: x86_64-apple-darwin15.0.0
    Thread model: posix

I'd greatly appreciate any help. Let me know if you need further information.

**Comment by DanielLenz** [comment]
I tried using `condo install gcc` as well:

    MBPR:~ dlenz$ gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/Users/dlenz/anaconda/gcc/libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
    Target: x86_64-apple-darwin11.4.2
    Configured with: ./configure --prefix=/Users/dlenz/anaconda/gcc --with-gxx-include-dir=/Users/dlenz/anaconda/gcc/include/c++ --bindir=/Users/dlenz/anaconda/bin --datarootdir=/Users/dlenz/anaconda/share --libdir=/Users/dlenz/anaconda/lib --with-gmp=/Users/dlenz/anaconda --with-mpfr=/Users/dlenz/anaconda --with-mpc=/Users/dlenz/anaconda --with-isl=/Users/dlenz/anaconda --with-cloog=/Users/dlenz/anaconda --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/dlenz/anaconda/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/dlenz/anaconda/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
    Thread model: posix
    gcc version 4.8.5 (GCC)

Still doesn't work, but the [traceback](https://gist.github.com/DanielLenz/4e863af84fed25997b40) is quite different.

**Comment by lpsinger** [comment]
Try cleaning first:

    $ python setup.py clean --all

**Comment by DanielLenz** [comment]
I've previously tried to install via `pip`, but installing via setup.py doesn't work either:

    MBPR:healpy-master dlenz$ python setup.py clean --all
    running clean
    'build/lib.macosx-10.5-x86_64-2.7' does not exist -- can't clean it
    'build/bdist.macosx-10.5-x86_64' does not exist -- can't clean it
    'build/scripts-2.7' does not exist -- can't clean it

    MBPR:healpy-master dlenz$ python setup.py install
    running install
    running bdist_egg
    running egg_info
    writing requirements to healpy.egg-info/requires.txt
    writing healpy.egg-info/PKG-INFO
    writing top-level names to healpy.egg-info/top_level.txt
    writing dependency_links to healpy.egg-info/dependency_links.txt
    pkg-config is not installed, falling back to pykg-config
    checking if configure script for library 'cfitsio' exists
    running 'autoreconf -i' for library 'cfitsio'
    error: [Errno 2] No such file or directory

**Comment by DanielLenz** [comment]
This seems to be related to https://github.com/healpy/healpy/issues/284, but I didn't manage to fix it yet.

**Comment by lpsinger** [comment]
@zonca, could we do a point release to pull in #297 and the various setup.py improvements? That should address this issue.

**Comment by DanielLenz** [comment]
I found that the 64-bit problem which I experience with conda gcc and homebrew gcc does also occur in https://github.com/elixircnx/comeonin/issues/61, they also provide a solution to this.

**Comment by zonca** [comment]
release 1.9.1, can you please test it?

**Comment by DanielLenz** [comment]
Thanks, don't get very far with building from source though:

    MBPR:healpy-1.9.1 dlenz$ python setup.py install
    running install
    running bdist_egg
    running egg_info
    writing requirements to healpy.egg-info/requires.txt
    writing healpy.egg-info/PKG-INFO
    writing top-level names to healpy.egg-info/top_level.txt
    writing dependency_links to healpy.egg-info/dependency_links.txt
    pkg-config is not installed, falling back to pykg-config
    checking if configure script for library 'cfitsio' exists
    running 'autoreconf -i' for library 'cfitsio'
    error: [Errno 2] No such file or directory

Did I get this wrong and I am supposed to build against an existing cfitsio?

**Comment by lpsinger** [comment]
> Did I get this wrong and I am supposed to build against an existing cfitsio?

No, you don't need to install cfitsio yourself (though you can). When you are building from git rather than a source release, [you need some extra tools](https://github.com/healpy/healpy/blob/master/INSTALL.rst#development-install). You are probably missing autoconf/automake.

**Comment by DanielLenz** [comment]
Alright, thanks for the help! Since the issue is fixed and I can use healpy again, I'll close this one.
