### ISSUE TITLE
Looking to access Polarisation from Fits file in Healpy 

### ISSUE THREAD

**Issue by dsiah** [healpy/healpy#311]
From the healpix documentation I know that I am able to access the polarisation convention for a fits object (Planck's data).

<img width="691" alt="screenshot 2015-11-17 22 58 21" src="https://cloud.githubusercontent.com/assets/6362717/11232251/be02644c-8d7e-11e5-824d-cd50107dd8ca.png">

From the Healpy documentation there is nothing written regarding how to access these values however Healpix has a routine called ```getsize_fits``` (pictured above) which can query the polcconv property. It will be a number 0, 1, or 2 which specifies the polarisation convention. Is this data accessible from Healpy?

```
polarisation coordinate convention (see
Healpix primer for details) 0=unknown,
1=COSMO, 2=IAU
```

Any help is greatly appreciated!

Source: http://healpix.jpl.nasa.gov/pdf/subroutines.pdf

**Comment by zonca** [comment]
please post HOWTO kind of questions to stackoverflow instead.

anyway:

    m = hp.read_map("filename.fits", (0,1,2))

m[1] is Q, m[2] is U
