### ISSUE TITLE
Installation error with Python3.4.3

### ISSUE THREAD

**Issue by evanbiederstedt** [healpy/healpy#316]
I think healpy should work with Python3.4. However, I am recently installed healpy for Python version 3.4.3 using 

    sudo pip-3.4 install healpy

However, here is the error I receive when importing healpy in Python 3.4.3:

    Python 3.4.3 (default, Dec  3 2015, 21:59:13) 

    [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin

    Type "help", "copyright", "credits" or "license" for more information.

    >>> import healpy

    >>> /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-   packages/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module

      warnings.warn('Warning: cannot import _healpy_pixel_lib module')

    Traceback (most recent call last):

      File "<stdin>", line 1, in <module>

      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/healpy/__init__.py", line 42, in <module>

        from .sphtfunc import (anafast, map2alm,

      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/healpy/sphtfunc.py", line 31, in <module>

        from . import _healpy_sph_transform_lib as sphtlib

    ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Symbol not found: _GOMP_barrier

      Referenced from: /opt/local/lib/libhealpix_cxx.0.dylib

      Expected in: flat namespace

     in /opt/local/lib/libhealpix_cxx.0.dylib

**Comment by lpsinger** [comment]
Healpy supports Python 2.6, 2.7, 3.2, 3.3, and 3.4.

It looks like `pip` linked against the HEALPix library provided by MacPorts (`/opt/local/lib/libhealpix_cxx.0.dylib`), which was built with OpenMP support. I bet that `pip` used a compiler that doesn't support OpenMP.

Why not try installing Healpy using MacPorts?

    sudo port install py34-healpy

**Comment by evanbiederstedt** [comment]
That's a reasonable approach, i.e. 

    sudo port install py34-healpy

Unfortunately, there are so many defects installing the dependencies for `py34-healpy`, e.g. `py34-cycler`, `py34-parsing`, etc. 

This should work, but the dependent module have issues being installed at the moment via macports. 

So, I'm stuck for the moment.

**Comment by lpsinger** [comment]
> Unfortunately, there are so many defects installing the dependencies for py34-healpy, e.g. py34-cycler, py34-parsing, etc.

It worked just now on my system (OS X 'El Capitan' 10.11.1 + MacPorts). If you have found a bug in a MacPorts port, then you should [report it as a MacPorts bug](https://trac.macports.org/newticket). (I maintain the Healpy port.)

**Comment by evanbiederstedt** [comment]
Hi Leo, 

It's not really a problem with py34-healpy, so I am reporting the bugs to the individuals who maintain the ports which are not installing. If you wish, I could create a py34-healpy report:

Here's what I see:


    $ sudo port install py34-healpy
    Password:
    --->  Computing dependencies for py34-healpy
    --->  Dependencies to be installed: py34-matplotlib py34-cycler py34-dateutil py34-parsing py34-pyobjc-cocoa py34-pyobjc py34-tkinter py34-tornado py34-certifi
    --->  Building py34-cycler
    Error: org.macports.build for port py34-cycler returned: command execution failed
    Error: Failed to install py34-cycler
    Please see the log file for port py34-cycler for details:
        /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_python_py-cycler/py34-cycler/main.log
    Error: The following dependencies were not installed: py34-matplotlib py34-cycler py34-dateutil py34-parsing py34-pyobjc-cocoa py34-pyobjc py34-tkinter py34-tornado py34-certifi
    To report a bug, follow the instructions in the guide:
        http://guide.macports.org/#project.tickets
    Error: Processing of port py34-healpy failed
