### ISSUE TITLE
healpy.rotator.Rotator documentation 

### ISSUE THREAD

**Issue by telegraphic** [healpy/healpy#317]
The documentation for [healpy.rotator.Rotator](http://healpy.readthedocs.org/en/latest/generated/healpy.rotator.Rotator.html) could be improved. 

Specifically, `euler_matrix_new()` does not appear to be a function within healpy :confused:.  I'm assuming the guts of the Rotator are based on [the IDL routine](http://healpix.jpl.nasa.gov/html/idlnode14.htm)?

It wasn't clear to me that to get the same functionality as `hp.mollview(rot=[theta, phi])` you needed to use an `inv=True` flag; an explanation or clarification for this in the text would be nice.

Here's a code snippet I used to figure out what was going on -- I'd be happy for this to be used as an example.

``` python
import pygsm    # Global sky model, https://github.com/telegraphic/pygsm
import healpy as hp
import numpy as np

# Generate a healpix sky model
gsm = pygsm.GlobalSkyModel()
sky = np.log2(gsm.generate(50))

# Generate pix -> angle mapping using pix2ang
n_pix  = hp.get_map_size(sky)
n_side = hp.npix2nside(n_pix)
theta, phi = hp.pix2ang(n_side, np.arange(n_pix))

# Apply the rotation using Rotator and ang2pix
hrot = hp.Rotator(coord=['G', 'C'], inv=True)
g0, g1 = hrot(theta, phi)
pix0 = hp.ang2pix(512, g0, g1)
sky_rotated = sky[pix0]

# Compare mollview coord transform to Rotator 
hp.mollview(sky, coord=['G', 'C'])
hp.mollview(sky_rotated, coord='C')
```
<img width="570" alt="screen shot 2015-12-17 at 3 27 44 pm" src="https://cloud.githubusercontent.com/assets/713251/11885031/cc69e29c-a4d2-11e5-86a3-698ca9247b7c.png">

Thanks!

**Comment by zonca** [comment]
thanks! can you re-do this example without using `pygsm`? then can you do a pull request to `healpy` documentation, maybe in the tutorial? I would be happy to merge it. Closing this issue for now, hope you'll make a PR.
