### ISSUE TITLE
ud_grade doesn't port input map's header info

### ISSUE THREAD

**Issue by aaroncnb** [healpy/healpy#320]
I am writing my own bit of code to do this in a seprate process, 
   but how about adding an option to import the input-map's header, along with the map itself, and then update the NSIDE keyword to reflect the new resolution?

For example, my process now is:

```python 
#Read in original, higher-res  FITS
map_in = hp.read_map("akari_9_4096.fits", nest = True)

#Degrade the hi-res map from NSIDE 4096 to 2048
map_out = hp.pixelfunc.ud_grade(map_in, order_in = 'NESTED',order_out = 'NESTED', nside_out = 2048, pess = True)

#Write a new fits file with the NSIDE=2048 version of the map
hp.fitsfunc.write_map("akari_9_2048.fits", map_out, nest=True,  coord=None, column_names=None, column_units=None)
```
The newly-written .fits file has a freshly-generated header, which indeed shows the correct NSIDE keyword (2048), however other keywords from the original file are lost. Just for smoothness, it'd be nice if hp.pixelfunc.ud_grade had an option to downgrade/upgrade "in-place" and also update just the NSIDE keyword instead of generating a new, minimal header.

cheers,
aaron

**Comment by zonca** [comment]
@aaroncnb unfortunately `healpy` maps are just arrays, so there is no easy way to also carry header information.

you could read explicitly the header using `h=True` in `read_map`, then add that as `extra_header` in `write_map`. Would that work?

**Comment by aaroncnb** [comment]
Thanks for the reply

     I think that will work. I've done that before with IDL. As long the healpy functions are handling the header in the same way as IDL HEALPix, it should work (though I think IDL stores the header under a separate variable, whereas ```healpy.read_map``` appends the header to the map- is this correct?)

(For reference: http://healpix.jpl.nasa.gov/html/idlnode47.htm and http://healpix.jpl.nasa.gov/html/idlnode58.htm)



In trying this however, I ran into another issue when visualizing the loaded map. The issue only arises when I set ```h=True```. Setting ```h=False``` allows me to visualize and process the file without problems (except that the header is not loaded, of course):
   
``` python
#Read the map and append the header
map_in = hp.read_map("../AKARI_HEALPix_orig/akari_65_1_4096.fits", nest = True, h=True)
#Prints expected output without errors:
NSIDE = 4096
ORDERING = NESTED in fits file
```

There's no apparent issue when reading the map, but when I try to visualize it with mollview:

```python
hp.mollview(map_in, title='AKARI All-Sky Map:', nest = True, norm = 'hist')
```
An error is encountered at ```get_map_size```: ``ValueError: Wrong pixel number (it is not 12*nside**2)```

Here's the full error output:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-4-dbbcf7d3522d> in <module>()
----> 1 hp.mollview(map_in, title='AKARI All-Sky Map:', nest = True, norm = 'hist')

/home/aaronb/anaconda/lib/python2.7/site-packages/healpy/visufunc.pyc in mollview(map, fig, rot, coord, unit, xsize, title, nest, min, max, flip, remove_dip, remove_mono, gal_cut, format, format2, cbar, cmap, notext, norm, hold, margins, sub, return_projected_map)
    192                                           copy=True,verbose=True)
    193         img = ax.projmap(map,nest=nest,xsize=xsize,coord=coord,vmin=min,vmax=max,
--> 194                    cmap=cmap,norm=norm)
    195         if cbar:
    196             im = ax.get_images()[0]

/home/aaronb/anaconda/lib/python2.7/site-packages/healpy/projaxes.pyc in projmap(self, map, nest, **kwds)
    649 class HpxMollweideAxes(MollweideAxes):
    650     def projmap(self,map,nest=False,**kwds):
--> 651         nside = pixelfunc.npix2nside(pixelfunc.get_map_size(map))
    652         f = lambda x,y,z: pixelfunc.vec2pix(nside,x,y,z,nest=nest)
    653         return super(HpxMollweideAxes,self).projmap(map,f,**kwds)

/home/aaronb/anaconda/lib/python2.7/site-packages/healpy/pixelfunc.pyc in get_map_size(m)
   1506             return len(m)
   1507         else:
-> 1508             raise ValueError("Wrong pixel number (it is not 12*nside**2)")
   1509 
   1510 def get_min_valid_nside(npix):

ValueError: Wrong pixel number (it is not 12*nside**2)
```
The header of the file-in-question is attached!
[akari65_fits_header.txt](https://github.com/healpy/healpy/files/82008/akari65_fits_header.txt)

**Comment by zonca** [comment]
do:

    map_in, h = hp.read_map(filename)
