### ISSUE TITLE
Healpy install problem(anaconda)

### ISSUE THREAD

**Issue by yinanoom** [healpy/healpy#321]
After installing healpy with pip I had following message.

>>> import healpy
/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/__init__.py", line 42, in <module>
    from .sphtfunc import (anafast, map2alm,
  File "/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/sphtfunc.py", line 31, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: dlopen(/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Symbol not found: _GOMP_barrier
  Referenced from: /opt/local/lib/libhealpix_cxx.0.dylib
  Expected in: flat namespace
 in /opt/local/lib/libhealpix_cxx.0.dylib

And I did deactivate healpix-cxx and reinstall heaIpy.
But I got this.

>>> import healpy
/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/__init__.py", line 42, in <module>
    from .sphtfunc import (anafast, map2alm,
  File "/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/sphtfunc.py", line 31, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: dlopen(/Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Library not loaded: /opt/local/lib/libhealpix_cxx.0.dylib
  Referenced from: /Users/yinanoom/anaconda2/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so
  Reason: image not found

What do I have to do to install healpy?

**Comment by yinanoom** [comment]
And, when I install heaply using macport,

>>> import healpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named healpy

**Comment by lpsinger** [comment]
You're mixing two different Python interpreters. If you want to use Healpy installed with MacPorts, then fire up the MacPorts Python interpreter. If it's not at the top of your path, then you can start it using the absolute path `/opt/local/bin/python2.7`.

**Comment by yinanoom** [comment]
I had two python2.7 versions and I uninstall one of them. Then I did sudo port select python python27 as you said. And I installed heaply successfully. Thanks!

**Comment by yinanoom** [comment]
I uninstalled the python2.7 which I had installed using homebrew.

**Comment by lpsinger** [comment]
You weren't using the Homebrew Python interpreter; you were using Anaconda.

You don't need to delete the multiple Python interpreters necessarily, just be aware of which one you are running by inspecting your `$PATH` environment variable.
