### ISSUE TITLE
1.8.1: Healpy uses floats as index for numpy

### ISSUE THREAD

**Issue by olebole** [healpy/healpy#328]
With the latest beta versions of numpy, the healpix tests fail with errors like
```
  _____________________ TestNoCrash.test_orthview_ma_nocrash _____________________
  
  self = <healpy.test.test_visufunc.TestNoCrash testMethod=test_orthview_ma_nocrash>
  
      def test_orthview_ma_nocrash(self):
  >       orthview(self.ma)
  
  healpy/test/test_visufunc.py:42: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  healpy/visufunc.py:708: in orthview
      cmap=cmap,norm=norm)
  healpy/projaxes.py:700: in projmap
      return super(HpxOrthographicAxes,self).projmap(map,f,**kwds)
  healpy/projaxes.py:689: in projmap
      img = super(OrthographicAxes,self).projmap(map,vec2pix_func,**kwds)
  healpy/projaxes.py:154: in projmap
      img = self.proj.projmap(map,vec2pix_func,rot=rot,coord=coord)
  healpy/projector.py:168: in projmap
      x,y = self.ij2xy()
  healpy/projector.py:862: in ij2xy
      idx = np.outer(np.ones(ysize),np.arange(xsize))
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  shape = 400.0, dtype = None, order = 'C'
  
      def ones(shape, dtype=None, order='C'):
          """[...]"""
  >       a = empty(shape, dtype, order)
  E       TypeError: 'float' object cannot be interpreted as an index
  
  /usr/lib/python2.7/dist-packages/numpy/core/numeric.py:190: TypeError
```
According to the discussion in numpy/numpy#7162, this will be reverted for the final version numpy-1.11. However; using floats as ints is deprecated and will fail with the following release of numpy.
Full error log (also containing other problems, with the new pyfits version) is [here](https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=amd64&ver=1.8.1-1.1%2Bb1&stamp=1456704751).

**Comment by zonca** [comment]
Thanks! If you would like to provide a fix with a pull request that would
be great, otherwise I'll work on this when I have time in the next few
weeks.

**Comment by olebole** [comment]
Sorry, I don't have one. The problem here is that probably one has to review the whole package to find places which use floats as indices (at least, if the tests do not cover the whole code).
As I said, this will not be a problem for numpy-1.11, but the later versions will need integers.

**Comment by zonca** [comment]
it is unclear where in the code this issue is located, I'm closing this for now. @olebole if you'd like to provide more details I could reopen to investigate more.

**Comment by olebole** [comment]
Hmm, I would recommend not to close a bug just because there is no (simple) way to fix it.
The problem is just: although in the moment (numpy <= 1.11, except the 1.11 release candidates) healpy works well, it **will fail** with the next numpy version because numpy decided just to postpone this to 1.12. See numpy/numpy#7162 for a discussion.
If you ignore it now, the problem will re-appear and will create the pressure to fix this quickly -- people are then going to update to numpy-1.12, the Linux distributions will update to 1.12 (and just remove packages that do not work with it).
Please don't close your eyes from a problem just because it works for the moment.

**Comment by zonca** [comment]
Can you please point me to 1 line of code where this happens?

**Comment by olebole** [comment]
As shown in the initial message; [healpy/healpy.py line 850ff](https://github.com/healpy/healpy/blob/master/healpy/projector.py#L850-L855)
```
        ysize=xsize/ratio
        xc,yc=(xsize-1.)/2.,(ysize-1.)/2.
        if i is None and j is None:
            idx = np.outer(np.arange(ysize),np.ones(xsize))
            y = (idx-yc)/yc
            idx = np.outer(np.ones(ysize),np.arange(xsize))
```
`ratio` is a `float`, therefore `ysize` will be a float, and `np.ones` takes this as `shape` argument.

**Comment by zonca** [comment]
In the first message you were saying indexing, do you have an example of
that as well?

**Comment by olebole** [comment]
Sorry for that; it was probably my mistake: In numpy, they always mention indexing, and I took their wording. It is however not limited to indexing. Could you look into the [test log](https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=amd64&ver=1.8.1-1.1%2Bb1&stamp=1456704751) which failures happen there?
