### ISSUE TITLE
1.8.1: Problems with pyfits 3.4

### ISSUE THREAD

**Issue by olebole** [healpy/healpy#329]
With the new pyfits release, the unit tests show errors like
```
________________________ TestFitsFunc.test_write_map_C _________________________

self = <healpy.test.test_fitsfunc.TestFitsFunc testMethod=test_write_map_C>

    def test_write_map_C(self):
>       write_map(self.filename, self.m, fits_IDL=False)

healpy/test/test_fitsfunc.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
healpy/fitsfunc.py:153: in write_map
    tbhdu.header.update('PIXTYPE','HEALPIX','HEALPIX pixelisation')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = XTENSION= 'BINTABLE'           / binary table extension                       ...FORM1  = 'E       '                                                            
args = ('PIXTYPE', 'HEALPIX', 'HEALPIX pixelisation'), kwargs = {}
other = 'PIXTYPE'
update_from_dict = <function update_from_dict at 0x7fa655183ed8>, idx = 0
card = 'P'

    def update(self, *args, **kwargs):
        """[...]"""
    [...]
                else:
                    raise ValueError(
                        'Header update sequence item #%d is invalid; the '
                        'item must either be a 2-tuple containing a keyword '
                        'and value, or a 3-tuple containing a keyword, '
>                       'value, and comment string.' % idx)
E                   ValueError: Header update sequence item #0 is invalid; the item must
            either be a 2-tuple containing a keyword and value, or a 3-tuple containing
            a keyword, value, and comment string.

/usr/lib/python2.7/dist-packages/pyfits/header.py:1017: ValueError
```
According to the pyfits documentation, the calling sequence of pyfits.Header.update() is wrong.
Full error log (also containing the problem described in #328) [here](https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=amd64&ver=1.8.1-1.1%2Bb1&stamp=1456704751)

**Comment by lpsinger** [comment]
LIGO will be transitioning to Debian Jessie and Scientific Linux 7 very soon. That would allow us to depend on astropy >= 0.4.2 or pyfits >= 3.2.4. Will this work with astropy 0.4.2? Could we drop pyfits support and require astropy instead?

**Comment by olebole** [comment]
Changing the code as shown in #330 works with both old an new versions of pyfits (unless you have a _real_ old version) and astropy. I would however recommend to drop pyfits support ASAP, since pyfits is really obsolete and can be completely replaced with astropy (same applies to pywcs, BTW).
```
import astropy.io.fits as pyfits
import astropy.wcs as pywcs
```
should just work directly, even with older astropy versions. #330 is needed then as well, however.

**Comment by lpsinger** [comment]
> should just work directly, even with older astropy versions. #330 is needed then as well, however.

@zonca, let's do it.

**Comment by olebole** [comment]
Just checked with the pyfits changelog: it the new API was introduced with [version 3.1 (2012-08-08)](https://github.com/spacetelescope/PyFITS/blob/master/CHANGES.txt#L1077).

**Comment by olebole** [comment]
@lpsinger could you create a new Debian package as well?

**Comment by zonca** [comment]
ok, merging the PR
