### ISSUE TITLE
"Edit on Github" links from docs are broken

### ISSUE THREAD

**Issue by cdeil** [healpy/healpy#334]
The "Edit on Github" links from the healpy docs are broken.

E.g. if you go to http://healpy.readthedocs.org/en/latest/generated/healpy.pixelfunc.pix2ang.html and click the "Edit on Github" button in the upper right, it points to https://github.com/healpy/healpy/blob/master/doc/generated/healpy.pixelfunc.pix2ang.rst which gives a 404.

Fix or remove this feature?

**Comment by lpsinger** [comment]
Hmm, that's because that particular document is generated by [`sphinx.ext.autosummary`](http://www.sphinx-doc.org/en/1.5.1/ext/autosummary.html).

**Comment by zonca** [comment]
@lpsinger is right, other pages like http://healpy.readthedocs.io/en/latest/tutorial.html work as expected.
