### ISSUE TITLE
Docs build on ReadTheDocs is broken

### ISSUE THREAD

**Issue by cdeil** [healpy/healpy#336]
I now see that the healpy latest docs build on ReadTheDocs has been broken for a while:
http://readthedocs.org/projects/healpy/builds/

The latest one from a months ago ( http://readthedocs.org/projects/healpy/builds/3742755/ ) ends with:

```
subprocess.CalledProcessError: Command '['tar', '-xzf', 'pkg-config-0.28.tar.gz']' returned non-zero exit status 2
```

So I don't know if the other docs-related issues I filed just now (#332, #333, #334) are still present.

**Comment by gregreen** [comment]
This is being discussed in #357.
