### ISSUE TITLE
PARTIAL files and RAM usage

### ISSUE THREAD

**Issue by Goutte** [healpy/healpy#339]
Hello !

First things first, thanks for these python bindings. :+1: 

I'm working with high (`nside=16384`, and growing bigger -- _science !_) resolution partial healpix files, and reading them with `read_map` blows up my memory. Yes, I'm working on a small laptop, and no, I don't want to have to always use the server and its terabytes of RAM. :wink: 

I'm wondering how hard it would be to make `read_map` return sparse arrays (and therefore memory-efficient arrays) when it detects a partial healpix. The specifications should not be any different (`UNSEEN` values where not defined), and I don't want to impose `scipy` (which provides sparse matrices) as a dependency.

I think the least obtrusive way of enabling such a feature would be by adding a new parameter to the `read_map` function, say `sparse=False`.

I've seen the test-suite and I'm currently trying to craft fake partial `FITS` files.

Do you think it's doable ? Would you be open to such a feature ?
Do you see any pitfalls with `read_map` returning sparse arrays ?
Anyone interested by a screenshared peer-programming session to hack in this feature ?

(do you know of any good sparse 1xM matrices python class ? -- scipy will not do I think)

**Comment by Goutte** [comment]
I found https://pypi.python.org/pypi/sparse_list

**Comment by zonca** [comment]
Hi, I generally use pandas.Series for sparse maps. But then always convert
to a full map when interfacing with healpy.
I think an integration of pandas for Partial maps would be nice, using it
as a soft dependency, i.e. the rest would work without pandas.

**Comment by Goutte** [comment]
I managed to clone and run the test-suite. I did not run `python setup.py build_ext --inplace`, but I'm pretty sure I won't need to fool around in the C extensions.

How about a test such as this one ?

``` python
    def test_read_write_partial_sparse(self):
        try:
            import pandas
        except ImportError:
            print("To run the full test suite you need `pandas`.")
            return  # maybe fail ?

        m = self.m.astype(float)
        m[:11 * self.nside * self.nside] = UNSEEN
        write_map(self.filename, m, partial=True)
        read_m = read_map(self.filename, sparse=True)

        self.assertIsInstance(read_m, pandas.Series)
        np.testing.assert_array_almost_equal(m, read_m)
```

**Comment by zonca** [comment]
Something like that would be fine, if you send a pull request, I can
comment on the details.

**Comment by Goutte** [comment]
I tried. The initialization of `SparseSeries` or `SparseArray` is weird and seems to defeat the low-memory-consumption purpose of having sparse arrays in the first place. I don't get it. I'm probably doing it wrong, but I can't find for the life of me how to do it with these classes. I spent a lot of time reading `pandas` internal voodoo and I'm even more confused than before.

I also tried with `sparse_list`, which has a much understandable API, but it does not support getting and setting items with `ndarray` indices. I see how we could hack support for it in a derived class, but I expect it to be excruciatingly slow if we do it in python rather than in C.

Out of despair and frustration, I'm now trying with `scipy.sparse`, which I successfully used in the past for other projects.

**Comment by Goutte** [comment]
Well... Scipy sparse matrices do not support default values other than 0.
They also are 2D and have some `NotImplementedError`s such as _"adding a nonzero scalar to a sparse matrix is not supported"_ that don't play well with the current codebase.
(even `np.testing.assert_array_almost_equal` does not like it)

---

I've added support for `[iterable]` slicing to `sparse_list`, and I will try again with that dictionary-of-keys based sparse vector. Then, I will benchmark and we'll see how slow it actually is.

**Comment by zonca** [comment]
Why don't use pandas Series instead of Sparse matrices?

**Comment by Goutte** [comment]
Well, assuming I figure out how to use `pandas.Series`, there's no default value other than `numpy.nan` for now. So I looked into `pandas.SparseSeries` and `pandas.SparseArray`, that have a `fill_value` parameter, and got even more confused.

---

I'm still trying with `pandas`, because I want to benchmark against `sparse_list` (with whom the test takes up 19 seconds !)

**Comment by Goutte** [comment]
The only way I've successfully instantiated a `pandas.Series` is as follows :

``` python
mnew = UNSEEN * np.ones(sz, dtype=curr_dtype)
mnew[pix] = m
mnew = pandas.Series(mnew).to_sparse(fill_value=UNSEEN)
```

This is not acceptable, as it defeats the whole point of not consuming too much memory.

Ideally, we'd want a sparse vector with a signature akin to this :

```
MySparseVector(indices=[], values=[], size=0, fill_value=0, dtype=None)
```

Am I getting this wrong ?

**Comment by zonca** [comment]
initialize as:

    mnew = pd.Series(map_values, index=valid_pixels)

**Comment by Goutte** [comment]
``` python
mnew = pd.Series(map_values, index=valid_pixels)
assert len(mnew) == len(map_values)  # ok, but not what we want
assert len(mnew) == <npix>  #  not ok, yet we want that
```

I tried that already, but I could not find a way to set either a default value and a total size for the series, and while `pandas.SparseArray` provides a `fill_value`, it has no total size either and furthermore is immutable.

``` python
    def test_read_write_partial_sparse_vector(self):
        try:
            import pandas
        except ImportError as e:
            print("To run the full test suite you need `sparse_list`.")
            print(e)
            return  # maybe fail ?
    
        m = self.m.astype(float)
        m[:11 * self.nside * self.nside] = UNSEEN
    
        write_map(self.filename, m, partial=True)
        read_m = read_map(self.filename, sparse=True, verbose=True)
    
        self.assertIsInstance(read_m, pandas.Series)

>       np.testing.assert_array_almost_equal(m, read_m)
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       (shapes (3145728,), (262144,) mismatch)
```

I managed to get it working using a custom implementation of sparse vectors based on `sparse_list.SparseList` (see https://github.com/johnsyweb/python_sparse_list/issues/3) with decent performance (the above test passes in 1.57 seconds), though.

**Comment by zonca** [comment]
it looks complicated to maintain on our side, we would need a simpler implementation of this functionality to consider merging it in.
