### ISSUE TITLE
Benign unresolved reference in `fitsfunc._get_hdu`

### ISSUE THREAD

**Issue by Goutte** [healpy/healpy#340]
At https://github.com/healpy/healpy/blob/master/healpy/fitsfunc.py#L545 it should be `input_data` instead of `hdulist`.

I fixed that in my branch and can commit that along with my next PR (cf. issue #339), but if you'd rather have it in a different PR for git tree cleanliness (or even do it yourself) I'd understand.

**Comment by zonca** [comment]
Yes please do a separate PR, thanks

**Comment by zonca** [comment]
@Goutte any update on this?

**Comment by Goutte** [comment]
Yes @zonca it is available in PR #353. There may be rebasing issues, tread carefully.
