### ISSUE TITLE
Interpolation: How about allowing bicubic as well as bilinear?

### ISSUE THREAD

**Issue by aaroncnb** [healpy/healpy#344]
Sorry that the issues I post usually boil-down to feature requests, but I have one more that I wonder if anyone has tried to implement.

healpy currently has a function for bilinear pixel interpolation:
``healpy.pixelfunc.get_interp_val``

This function is called by the healpix2wcs in the Python version of Drizzlib  (If the users chooses the bi-linear option rather than nearest-neighbor):

http://cade.irap.omp.eu/dokuwiki/doku.php?id=software#python_version

```    
     ## NEXT -- Two very different methods are available
    if use_bilinear_interpolation:
        # SECOND PASS : bilinear interpolation is fast and easy, but it will
        # yield incorrect results in some edge cases.
        # With that method we only have two passes, and we're done.
        for x in range(int(x_dim)):
            for y in range(int(y_dim)):
                # Coordinates in HEALPix space of the center of this pixel
                # Those are Quantity objects, so we pick their value
                theta = lat_centers[y, x].value
                phi = lng_centers[y, x].value

                # Healpy's bilinear interpolation
                v_interp = hp.get_interp_val(m, theta, phi)

                data[y, x] = v_interp 
```

Has anyone tried to build a function for bicubic inteprolation of healpix maps?

The question was posed to me recently by a collaborator, requesting drizzled cut-outs with a pixel scale that's finer than my highest NSIDE healpix maps. I.e., 0.30 arcminute pixels from the NSIDE 4096 map. I used healpix2wcs (and in turn, healpy) to make the bilinear interpolated map. He found these suitable, but wondered if bicubic interpolation was also available. As far as I can tell, it's not currently a "built-in" option?

**Comment by mreineck** [comment]
I do not think that this can work ... or at least, it will not be a straightforward extension at all.
The problem is that for bicubic interpolation one would need 4*4 neighbouring Healpix cells on a (more or less) regular grid to obtain the interpolation coefficients, and these are not always available. For an example, look at the regions where the 12 base pixels meet. In some cases, even linear interpolation has to be done using three neighbours instead of four.

**Comment by aaroncnb** [comment]
Ah, that makes sense. Thank you very much for the detailed explanation.
Perhaps the most straightforward way is to use healpy/healpix2wcs to make the rectangular map first, and then use something like SWarp for the interpolation.

cheers,
   aaron
