### ISSUE TITLE
Overplotting `hp.mollview` figures with points

### ISSUE THREAD

**Issue by rbiswas4** [healpy/healpy#347]
This is really a reopen of a part of #278 which I cannot do. I wrote a comment, but was unable to open the issue, so I am just copying the problem here:

- I have a set of points (ra, dec) and I can convert them to theta, phi in the range [0, np.pi), [0, 2*np.pi)
- I can find the ids of the healpixels (in say the NEST scheme) these points fall on 

Now, I would like to plot a particular healpixel say healpixel 0 with these point,. together on the usual mollview projection. How can I do this?

To be more definite, within matplotlib I can plot a point on a mollview projection like so:
```
import matplotlib.pyplot as plt
import healpy as hp
fig = plt.figure()
ax = fig.add_subplot(111, projection='mollweide')
theta, phi = hp.pix2ang(nside=1, ipix=0, nest=True)
ax.scatter(theta, phi)
```
```
import matplotlib.pyplot as plt
import healpy as hp
fig = plt.figure()
ax = fig.add_subplot(111, projection='mollweide')
theta, phi = hp.pix2ang(nside=1, ipix=0, nest=True)
ax.scatter(theta, phi) # Bu I would put in a sequence of points
```
```
import healpy as hp
import numpy as np
mymap = np.ones(hp.nside2npix(1))* hp.UNSEEN
mymap[0] = 1.
hp.mollview(mymap, nest=True )
```
which probably use different units/axes. What I want to show is the point and the healpixel together to visually show that such a point falls on the healpixel (I do not particularly care what units, as long as I know them). I am sure this is something that can be done fairly easily and it is perhaps even obvious and I am missing it

I tried your two suggestions:
`plt.gcf()` does return a figure, but it was unclear what to do with it. If I tried to save it to a file using the usual matplotlib savefig, it saved an empty file.

`return_projected_map` returns a numpy masked array. Again it is unclear how to use this to plot up the healpixels.

**Comment by zonca** [comment]
Can you attach a PNG figure to the issue?

**Comment by rbiswas4** [comment]
For the scatter plot I can:
```
fig = plt.figure()
ax = fig.add_subplot(111, projection='mollweide')
theta, phi = hp.pix2ang(nside=1, ipix=0, nest=True)
ax.plot(x)
ax.scatter(np.random.normal(theta, 0.1, size=100), np.random.normal(phi, 0.1, size=100))
fig.savefig('scatter.png')
```

![scatter](https://cloud.githubusercontent.com/assets/2281358/16928912/108d8720-4cea-11e6-9d83-f6e30a9b67e8.png)

How do I save the figure obtained from ?
```
import healpy as hp
import numpy as np
mymap = np.ones(hp.nside2npix(1))* hp.UNSEEN
mymap[0] = 1.
hp.mollview(mymap, nest=True )
```

**Comment by zonca** [comment]
`plt.savefig`

**Comment by rbiswas4** [comment]
Here is the other figure saved using plt.savfig(). It is blank:
![healpix_map](https://cloud.githubusercontent.com/assets/2281358/17114269/fec38412-5262-11e6-9aaf-e44374607672.png)

You can see what I tried here actually: https://gist.github.com/rbiswas4/5daf1d5f1f4f4947ff5551662cfec799

```
hp.__version__ = 1.8.1
```

**Comment by zonca** [comment]
you can try with `projplot` or `projscatter`

**Comment by rbiswas4** [comment]
The first attempts to this did not work. I realized one of doing this by looking at http://balbuceosastropy.blogspot.com/2013/09/representations-of-sphere-and-cosmic.html 

The attempt is at https://gist.github.com/82da5b217592375932d3ffee2b6ba4f1

The problem is getting access instances of axes/figs, so you have to do them right one after the other, as illustrated in the gist above. 

The usual community standard in matplotlib and matplotlib based visualization codes is to give the user access to the figure and axes instances for such operations. Thus, it would be great if one could get access to these, perhaps using `basemap`. While I solved what I needed immediately, I can see myself wanting to tinker with this more.  Is there a plan to do this in healpy? Alternatively, does healpy provide a representation of the tiles as some kind of geometric object (matplotlib.lines /patches)? One could use that to put this together.

**Comment by lpsinger** [comment]
You can use [reproject](http://reproject.readthedocs.io) and [wcsaxes](http://wcsaxes.readthedocs.io/en/latest/) to make HEALPix plots directly with Matplotlib.

**Comment by rbiswas4** [comment]
@Ipsinger 👍   just had a very cursory look: That seems like exactly what I would want and solve many of the things I want! Thanks a lot!                                                
@yoachim this may be of interest to you too.

**Comment by zonca** [comment]
yes, somebody should rewrite all the plotting based on those packages, I
won't have time to dedicate to this.
