### ISSUE TITLE
cfitsio autoreconf problem in healpy 1.9.1

### ISSUE THREAD

**Issue by hivon** [healpy/healpy#350]
Hi,
the installation of healpy 1.9.1 with the setup.py crashes with the message:
```
checking if configure script for library 'cfitsio' exists
running 'autoreconf -i' for library 'cfitsio'
autoreconf: 'configure.ac' or 'configure.in' is required
Traceback (most recent call last):
...
subprocess.CalledProcessError: Command '['autoreconf', '-i']' returned non-zero exit status 1
```
* I have the same problem under MacOSX 10.10.5 with autoreconf 2.69
and under CentOS 6.8 with autoreconf 2.63
* healpy 1.9.0 worked fine on both systems

Cheers

**Comment by lpsinger** [comment]
Did you run `git submodule update`?

**Comment by hivon** [comment]
No, I use the healpy_1.9.1.tar.gz file as it is shipped, which apparently miss the cfitsio and C++ sources …
Things work better if I link to existing cfistio and Healpix/C++ source directories.

Why distributing an incomplete release such as 1.9.1, while 1.9.0 was self-contained ?

If you tell me that it is to save space, then here is my 2nd question:
Why does setup.py needs cfitsio source files to be in the cfitsio directory, 
while a cfitsio library is already installed ?

How about an explicit error message about missing cfitsio and healpixsubmodule ?

Cheers,
Eric

**Comment by lpsinger** [comment]
The latest tarball from https://pypi.python.org/pypi/healpy does contain the cfitsio and healpixsubmodule directories.

**Comment by hivon** [comment]
Good to know.
But the tarball in https://github.com/healpy/healpy/releases does not.
Nothing there says that the pypi repository MUST be used.

And with an automated script getting
https://github.com/healpy/healpy/archive/1.9.1.tar.gz
is much easier than getting
https://pypi.python.org/packages/06/94/de69bbb3e2739f3305ad26a7e827d3d896ffda36c7020c26e8bb579fa010/healpy-1.9.1.tar.gz

**Comment by lpsinger** [comment]
> Good to know.
> But the tarball in https://github.com/healpy/healpy/releases does not.
> Nothing there says that the pypi repository MUST be used.

You're right, that's not spelled out anywhere in the README.

The previous releases has the full source tarballs attached to the tags as downloads. @zonca, is it possible to add the PyPI tarball to the 1.9.1 release tag?

> And with an automated script getting
> https://github.com/healpy/healpy/archive/1.9.1.tar.gz
> is much easier than getting
> https://pypi.python.org/packages/06/94/de69bbb3e2739f3305ad26a7e827d3d896ffda36c7020c26e8bb579fa010/healpy-1.9.1.tar.gz

Very true. You could use http://pypi.python.org/simple/. Also the Debian project has an automatic redirector, which gives you URLs like https://pypi.debian.net/healpy/healpy-1.9.1.tar.gz.

**Comment by zonca** [comment]
ok,  tarball added, https://github.com/healpy/healpy/releases/tag/1.9.1
