### ISSUE TITLE
Improve accuracy of Healpix map analysis

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#356]
I have been working for a long time to improve the accuracy of the Healpix map2alm operation. In its current state there are two approaches:
- without any weigts, and
- with ring weights

These both produce only approximate results for all multipole moments.
A few weeks ago I managed to compute new sets of weights that vary from pixel to pixel. If these are used, Healpix-discretized functions on the sphere which have a band limit of lmax=3/2*Nside can be recovered by map2alm with machine precision. If higher multipoles are present, the result is affected by aliasing, but it should still be better than with the previous methods.

Computing the weight sets for all required resolutions is expensive, but they can be stored and read from disk when needed, similar to the approach used with the ring weights. Due to the various symmetries of the Healpix grid, the size of a weight set at a given Nside is about 1/16th of a full Healpix map.

Is there interest in using these new weights from healpy? If yes, it's probably simplest to just write the methods for reading the weights from disk and applying them to a map in Python. I can provide the FITS files if desired.

**Comment by cjcopi** [comment]
I recently "rediscovered" the inaccuracies and  think this would be a great addition.

Is there a reason to not include this in HEALPix and pick up the addition that way?

Regardless, this would be of great value and I would be happy to (have a student) do some testing/start using the new weights.

**Comment by zonca** [comment]
yes, sure, can you post the weights publicly so people can test it?
what is the size of the full set?
If too large we should probably implement a way to download them after installation.

**Comment by mreineck** [comment]
I can certainly provide you with a few weight sets. Unfortunately, the full set is too large to be distributed with the package. Going up to Nside=4096, we are talking about several 100MB.
I have software in the Healpix repository to compute the weight sets on demand and store them to disk, but for high resolutions this requires a very beefy machine (roughly a few CPU minutes at Nside=128, but hundreds of CPU hours at Nside=2048). So I'm not sure what the best distribution strategy for the data would be.

**Comment by zonca** [comment]
I think the best would be to store them publicly, possibly inside another
GitHub repository and then Implement a way to download only one specific
set as needed.

**Comment by lpsinger** [comment]
How long are we talking for generating them from scratch?

**Comment by mreineck** [comment]
As I said, roughly a minute for Nside=128, but the cost scales with something like Nside^4. I can't give hard numbers on the complexity since there is a CG iteration involved, and I can't predict the necessary number of iterations.

**Comment by lpsinger** [comment]
OK. Since we already depend on astropy, we could use the [`astropy.utils.data` module](http://docs.astropy.org/en/stable/utils/index.html#module-astropy.utils.data) to download and cache the weights.

**Comment by zonca** [comment]
thanks @lpsinger ! that looks like suits our purposes

**Comment by zonca** [comment]
@mreineck do you have any update on this?

**Comment by mreineck** [comment]
Sort of ...
I can send at least a subset of the weight files, but in order to use them from healpy, you either have to
- write a Python version of the C++ function that applies the weights to a map, or
- switch to the current trunk version of Healpix C++, which you probably don't want, because it's in active development and therefore not entirely stable. It also requires C++11 compiler support.

Any volunteers?

Concerning the data files, please let me know how I should provide them.

**Comment by zonca** [comment]
@mreineck can you add a reference to the C++ implementation here? https://github.com/healpy/healpixmirror/tree/trunk

**Comment by mreineck** [comment]
I'm not sure I understand what you want me to do ;-)
The current state of the trunk (commit 51e4b48d007da5fad7259951bce965a51161e381 in the healpixmirror repo) contains all the code necessary for the full weights. Should I somehow tag this?

**Comment by zonca** [comment]
Just link the file here

**Comment by mreineck** [comment]
OK ...
Reading the weight file is at
https://github.com/healpy/healpixmirror/blob/trunk/src/cxx/Healpix_cxx/healpix_data_io.cc#L63
Applying the weights is at
https://github.com/healpy/healpixmirror/blob/trunk/src/cxx/Healpix_cxx/weight_utils.cc#L108

**Comment by mreineck** [comment]
I have a tarball with the full weight maps for Nside=16 to Nside=1024. Any suggestions how I should make them available? Total size is around 8MB.

**Comment by zonca** [comment]
created a new repository, can you create subfolders and upload them there?

https://github.com/healpy/healpy-data

**Comment by lpsinger** [comment]
Are these really *healpy* datasets, or are they necessary for all language flavors?

**Comment by mreineck** [comment]
They will be used by at least C++ and Python. On the other hand, they are so large that I don't expect them to be part of the release tarballs.
For the moment I'm just looking for a convenient place where early adopters can access them and play around with them.

**Comment by zonca** [comment]
@mreineck any news on this?

**Comment by mreineck** [comment]
Sorry for the incredible delay! I thought that more discussions (as well as the implementation of a reader for the weights) would be needed before uploading the weights.

In any case, there are now a few weight files in healpy-data.

**Comment by zonca** [comment]
thanks @mreineck , it would be nice to have a unit test at low nside, do you already have one in HEALPix I can use? Or could you provide an input map and expected output alms?

**Comment by mreineck** [comment]
I have automated tests for this in hpxtest.cc of the C++ package, but writing a unit test inside healpy should be straightforward, following this recipe:
- draw random a_lm up to lmax=96
- run alm2map and create a map with nside=64
- run map2alm with full weights, which should recover the input a_lm up to roughly 1e-7 relative error.

**Comment by Kathryn-Drake** [comment]
I am a doctoral student, and my dissertation research is directly related to this issue. Unfortunately, I've yet to find any explicit explanation of what method is used in the HEALPix map2alm software to compute the alm coefficients. Would anyone be willing to point me in the direction of source code or literature which contains this information? I would greatly appreciate it.

**Comment by mreineck** [comment]
The expressions computed by map2alm are given in
https://arxiv.org/pdf/1010.2084
and
https://arxiv.org/pdf/1303.4945
The code for the transforms themselves can be found in the libsharp/ subdirectory of the Healpix package (e.g. https://sourceforge.net/p/healpix/code/HEAD/tree/trunk/src/cxx/libsharp/) - although this is definitely no fun to read ;)
The "full weights" approach proposed here was inspired by
https://www-user.tu-chemnitz.de/~potts/paper/quadgewS2.pdf

**Comment by zonca** [comment]
implemented in #442
