### ISSUE TITLE
healpy fails on ReadTheDocs

### ISSUE THREAD

**Issue by gregreen** [healpy/healpy#357]
On ReadTheDocs, healpy fails to build. This prevents other packages that depend on healpy from building their own documentation.

[Here](https://github.com/healpy/healpy/blob/69649467330ba013f4a5c560514d990085040ecb/setup.py#L81), healpy detects whether it is on ReadTheDocs, and if it is, attempts to download and compile several packages. As you can see [here](https://readthedocs.org/projects/dustmaps/builds/4524509/), that can cause packages that rely on healpy to also fail to compile on ReadTheDocs.

**Comment by gregreen** [comment]
The reason appears to be that https://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz has been moved to https://pkg-config.freedesktop.org/releases/pkg-config-0.28.tar.gz. Still, the fact that healpy has a different installation procedure on ReadTheDocs is problematic for any package that relies on healpy, but which also wants to host its documentation on ReadTheDocs.

**Comment by lpsinger** [comment]
> The reason appears to be that https://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz has been moved to https://pkg-config.freedesktop.org/releases/pkg-config-0.28.tar.gz.

Good catch! I'm [testing that fix here](https://readthedocs.org/projects/lpsingerhealpy/builds/4528376/).

> Still, the fact that healpy has a different installation procedure on ReadTheDocs is problematic for any package that relies on healpy, but which also wants to host its documentation on ReadTheDocs.

Why?

**Comment by gregreen** [comment]
Great, thanks for fixing this. It will allow healpy's documentation to stay up-to-date.

As for other projects: if they use `sphinx.ext.autodoc` to automatically extract documentation from their code, they have to import all the dependencies. Any dependency that can't be imported causes the build to fail on ReadTheDocs.

However, I didn't realize that there's a way around this: one can avoid loading dependencies during the documentation build process by telling Sphinx to use dummy versions of the dependencies.

**Comment by lpsinger** [comment]
Very strange: the readthedocs build seems to be just sitting there at `cat conf.py`. What does that mean?
