### ISSUE TITLE
Add 'lonlat' option to 'pix2ang' etc.?

### ISSUE THREAD

**Issue by kadrlica** [healpy/healpy#361]
Several of the `rotator` functions take a `lonlat` argument to specify whether the output will be longitude and latitude (deg) or longitude and co-latitude (rad). Is there any reason not to have a similar optional argument for angular functions in `pixelfunc`?  Specifically, I'm thinking of `pix2ang`, `ang2pix`, `vec2ang`, `ang2vec`, `get_neighbours`, `get_all_neighbours` and `get_interp_val`. 

It seems like this could be done pretty simply and non-intrusively with some `numpy` and I'd be happy to help with development.

For reference, from the documentation for [`rotator.vec2dir`](https://github.com/healpy/healpy/blob/fe89eda868feb03bac72cef2444807e6a88e9837/healpy/rotator.py#L439):

```
def vec2dir(vec,vy=None,vz=None,lonlat=False):
    """Transform a vector to angle given by theta,phi.

    Parameters
    ----------
    vec : float, scalar or array-like
      The vector to transform (shape (3,) or (3,N)),
      or x component (scalar or shape (N,)) if vy and vz are given
    vy : float, scalar or array-like, optional
      The y component of the vector (scalar or shape (N,))
    vz : float, scalar or array-like, optional
      The z component of the vector (scalar or shape (N,))
    lonlat : bool, optional
      If True, return angles will be longitude and latitude in degree,
      otherwise, angles will be longitude and co-latitude in radians (default)
    Returns
    -------
    angles : float, array
      The angles (unit depending on *lonlat*) in an array of 
      shape (2,) (if scalar input) or (2, N)
```

**Comment by zonca** [comment]
Sure! Please send a pull request

**Comment by kadrlica** [comment]
Pull request submitted at #362.
