### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by tskisner** [healpy/healpy#364]
Are there any plans to tag a new release in the near future?  In particular one that includes commit 7b92305b24cf35367a71ba9b0a8f45d3c9f11972 .  I redistribute healpix + healpy with autotools (https://github.com/tskisner/healpix-autotools) and the latest healpy release (1.9.1) still has that bug.  I could just sync with a random upstream commit, but it is nicer if you all have a favorite stable point that is tagged :-)  This repackaging allows us to customize the C++ healpix install and then force healpy to use that existing library instead of building its own.  This is useful for some non-standard systems (like Crays).

**Comment by lpsinger** [comment]
There are autotools packages for chealpix and healpix-cxx, but they are not well advertised. See [chealpix-3.30.0.tar.gz](https://sourceforge.net/projects/healpix/files/Healpix_3.30/chealpix-3.30.0.tar.gz) and [healpix_cxx-3.30.0.tar.gz](https://sourceforge.net/projects/healpix/files/Healpix_3.30/healpix_cxx-3.30.0.tar.gz) respectively on SourceForge. I developed and contributed them to ease the process of creating packages for [Debian](https://packages.debian.org/search?suite=sid&searchon=names&keywords=healpix) and [MacPorts](https://www.macports.org/ports.php?by=name&substr=healpix) as well as RPMs. Healpy will already detect a preexisting installation of the healpix-cxx libraries using pkg-config and will link against it.

That said, I bet that the HEALPix developers would be thrilled to have conventional configure-make-install style packages for Fortran, Java, and IDL. Would you consider contributing your build systems for those language flavors upstream?

**Comment by tskisner** [comment]
I previously pointed Martin Reinecke and Eric Hivon to my effort, but they chose to do their own things (which is fine).  The main challenge is that the different language flavors are developed independently by often different people.  My effort was an attempt to unify the build systems into a single package.  When bundling healpy I disable the mechanisms of finding healpix_cxx in setup.py because I want to link to exactly the libhealpix_cxx that I am installing.  All of this works just fine.

Back to the topic though- all I wanted was a newer upstream release of healpy than 1.9.1 from 2015.  It sounds like you guys are not planning on a release any time soon, so I will just pick a recent commit and merge that version into my distribution.  Do you have a favorite recent commit?  :-)

**Comment by lpsinger** [comment]
It's highly likely that @zonca will oblige and create a new package. Would you mind if we borrowed some of your Fortran build stuff in the upstream repo? We could also create a top-level build using [nested packages](https://www.gnu.org/software/automake/manual/html_node/Nested-Packages.html).

**Comment by tskisner** [comment]
Obviously use anything that you find useful!  This update is needed for work at NERSC that involves @zonca, so hopefully he will tag a release ;-)

**Comment by zonca** [comment]
sure, working on it

**Comment by zonca** [comment]
ok, released on `pypi`, please test it, I'll release on github next

**Comment by zonca** [comment]
ok,
https://github.com/healpy/healpy/releases/tag/1.10.1

**Comment by tskisner** [comment]
Thank you @zonca !  This is now integrated downstream:
https://github.com/tskisner/healpix-autotools/releases/tag/v3.31.1
and installed at NERSC.
