### ISSUE TITLE
Import Error: undefined symbol

### ISSUE THREAD

**Issue by Dehde** [healpy/healpy#367]
Hi all,

I run Ubuntu and am using anaconda as environment manager. I installed healpy with pip. When I try to import healpy I get the following error:

>>> import healpy
/home/robin/anaconda2/lib/python2.7/site-packages/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/anaconda2/lib/python2.7/site-packages/healpy/__init__.py", line 42, in <module>
    from .sphtfunc import (anafast, map2alm,
  File "/home/robin/anaconda2/lib/python2.7/site-packages/healpy/sphtfunc.py", line 27, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: /home/robin/anaconda2/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

The problem seems to be very similar to https://github.com/healpy/healpy/issues/140.

When I run ldd on the file I get:

ldd /home/robin/Masterarbeit/healpy-1.10.1/healpy/_healpy_sph_transform_lib.so
	linux-vdso.so.1 =>  (0x00007ffd7c7c5000)
	libpython2.7.so.1.0 => /home/robin/anaconda2/lib/libpython2.7.so.1.0 (0x00007f3343793000)
	libstdc++.so.6 => /home/robin/anaconda2/lib/libstdc++.so.6 (0x00007f334347c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3343156000)
	libgomp.so.1 => /home/robin/anaconda2/lib/libgomp.so.1 (0x00007f3342f47000)
	libgcc_s.so.1 => /home/robin/anaconda2/lib/libgcc_s.so.1 (0x00007f3342d30000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3342b13000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f334274a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3342545000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f3342342000)
	/lib64/ld-linux-x86-64.so.2 (0x00005572fe70f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f334213a000)

So I guess there again is a problem with the linking to anaconda? I am very new to programming though, this is just a guess.

I am using python 2.7, healpy 1.10.1.

Thanks in advance!

**Comment by zonca** [comment]
you have to be sure to compile `healpy` with the Anaconda `gcc` and not the Ubuntu one.
Have you tried to install `healpy` with conda? https://github.com/healpy/healpy/blob/master/INSTALL.rst

**Comment by Dehde** [comment]
I did not know that this was possible. Sorry for the unnecessary Issue! This solution worked perfectly. Thank you very, very much!

**Comment by zjgbz** [comment]
May I reopen it? Because I met the same problem, but cannot be solved even if I install with conda.

**Comment by zjgbz** [comment]
More precisely, I install Anaconda2 4.4.0 on ubuntu 16.04. Then I reload the terminal, and install healpy with 
conda install -c openastronomy healpy
Then I reload terminal, and type python, then import healpy. What I got is

/home/jiangminzhi/.local/lib/python2.7/site-packages/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiangminzhi/.local/lib/python2.7/site-packages/healpy/__init__.py", line 42, in <module>
    from .sphtfunc import (anafast, map2alm,
  File "/home/jiangminzhi/.local/lib/python2.7/site-packages/healpy/sphtfunc.py", line 27, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: /home/jiangminzhi/.local/lib/python2.7/site-packages/healpy/_healpy_sph_transform_lib.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

Another interesting thing is that this method work in my Macbook.
