### ISSUE TITLE
Preparations for compatibility with future Healpix C++ packages

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#372]
In future releases of the Healpix C++ package I intend to make a few changes that might affect the interoperability with healpy, so I'd like to put them up for discussion here...

- Future major releases (not bug fix releases!) will require C++11 support in the compiler. I don't think that this will affect the C++-Python interface, but it might require a few tweaks in setup.py.

- Currently, large data objects (like maps and a_lm coefficients) are passed from healpy to Healpix C++ by constructing a C++ object of type "arr" around a raw pointer to Python-controlled memory. This may be efficient, but it is also extremely low-level and fragile. In the longer term I'd like to abandon arr for C++'s std::vector, which does not permit this kind of trickery. This would mean that data has to be copied at the language interface. Do you think the resulting waste of memory is acceptable? In any case, this switch is not going to happen soon ...

**Comment by zonca** [comment]
thanks @mreineck , 

1.  @lpsinger do you have any experience with C++11 Python extensions?
1. I think copying data around is **not** acceptable. I guess that very soon there will be more users of `HEALPix` via `healpy` than directly, so I hope you and other `HEALPix` developers would always take this into account and find a way to provide a low-level access to the memory locations.

**Comment by mreineck** [comment]
Hmm, aren't you already copying data around inside the Python part with statements like this one in _sphtools.pyx?

alms_c = [np.ascontiguousarray(alm, dtype=np.complex128) for alm in alms]

**Comment by crosset** [comment]
This will copy alm data only if alm is not already a numpy vector. Otherwise, it will return the input without any copy.
So, there should be no copy here in normal use (it’s useful for simple cases where you give a python list instead of a numpy array).
Cyrille.

**Comment by lpsinger** [comment]
> @lpsinger do you have any experience with C++11 Python extensions?

C++11 is fully supported in GCC 4.8.1 and later and Clang 3.3 and later. So this should be fine for Debian stable (jessie) and later, Scientific Linux 7 and later, and Mac OS X 10.8 (using Xcode toolchain) and later.

> I think copying data around is not acceptable. I guess that very soon there will be more users of HEALPix via healpy than directly, so I hope you and other HEALPix developers would always take this into account and find a way to provide a low-level access to the memory locations.

I agree, copying data would be bad. The library handles a lot of very large arrays, so copying arguments would increase memory use dramatically. You might be able to wrap a `std::vector` around an array using a custom allocator.

**Comment by mreineck** [comment]
> I agree, copying data would be bad. The library handles a lot of very large arrays, so copying arguments would increase memory use dramatically. You might be able to wrap a std::vector around an array using a custom allocator.

I fear this won't work, since a vector with a custom allocator is a different data type than a "normal" vector. All Healpix routines would have to be templated to support this (rather a lot of work).

This matter definitely needs a lot of thought, and as I said, this is not urgent. But I thought I'd ask rather sooner than later, in case there are some good ideas already available.

Just curious: if Healpix C++ had opted for an interface style where, e.g., the result of an alm2map() call was returned as a function result, rather than a modifiable function argument, we wouldn't have been able to avoid a copy at all, correct?

Having to consider constraints posed by other languages is really frustrating at times ...

**Comment by zonca** [comment]
> Just curious: if Healpix C++ had opted for an interface style where, e.g., the result of an alm2map() call was returned as a function result, rather than a modifiable function argument, we wouldn't have been able to avoid a copy at all, correct?

Well, unless the result is a pointer.

> Having to consider constraints posed by other languages is really frustrating at times ...

As most users use HEALPix in Python, I see HEALPix C++ mostly as a library mostly to be used by other languages.

**Comment by mreineck** [comment]
> Well, unless the result is a pointer.

Wouldn't help, because Python does not know how to deallocate this pointer in the end, so it would have to call back into C++ to release the data once it's no longer used.

**Comment by zonca** [comment]
@mreineck yes, we can wrap that into an object that calls back C++ when goes out of scope

**Comment by mreineck** [comment]
This would be even uglier than the hack we are using now...

I guess in the end it all boils down to the compromises people are willing to make in order to call Healpix functionality from Python. Performance-wise it seems that they are fine with massive slowdowns (at least a factor of 10 when calling simple functions like pix2ang etc., probably much more), so I had hoped that a factor 2 in memory consumption (in exchange for a much cleaner interface and easier library development) could be acceptable.

**Comment by lpsinger** [comment]
> Well, unless the result is a pointer.
> Wouldn't help, because Python does not know how to deallocate this pointer in the end, so it would have to call back into C++ to release the data once it's no longer used.

The Numpy C-API has the concept of a [base object](https://docs.scipy.org/doc/numpy-dev/reference/c-api.array.html#c.PyArray_SetBaseObject) that tracks the underlying memory via reference counting. What we would do is make a wrapper Python type that knows how to free the underlying C++ data, and set this as the Numpy base object.

**Comment by lpsinger** [comment]
> Performance-wise it seems that they are fine with massive slowdowns (at least a factor of 10 when calling simple functions like pix2ang etc., probably much more), so I had hoped that a factor 2 in memory consumption (in exchange for a much cleaner interface and easier library development) could be acceptable.

A tenfold slowdown would be a deal-breaker for the codes that I work on.

**Comment by lpsinger** [comment]
@mreineck, what would be wrong with returning a *pointer* to a `std::vector`?

**Comment by mreineck** [comment]
> A tenfold slowdown would be a deal-breaker for the codes that I work on.

What I meant to say is that using healpy _already_ incurs a tenfold slowdown for most Healpix functions compared to Healpix C++, but no one seems to be overly concerned about this.

**Comment by mreineck** [comment]
> @mreineck, what would be wrong with returning a pointer to a std::vector?

Nothing fundamental - provided that Python really manages to cleanup this vector correctly, which is a quite nontrivial operation (there may be destructors involved in addition to deallocation). It's still not idiomatic C++ though: a clean interface would work with rvalue references to vectors, and this is a concept that Python most likely does not understand.

The more complicated part is the passing of data from Python to C++; there is no way to construct a vector around an existing pointer to data. I think this was a deliberate design decision, since a vector is supposed to "own" its memory and grow and shrink it as needed.

**Comment by lpsinger** [comment]
> I fear this won't work, since a vector with a custom allocator is a different data type than a "normal" vector. All Healpix routines would have to be templated to support this (rather a lot of work).

Nonetheless, it seems like this is the most straightforward way to do it using STL. There is a [nice StackOverflow thread that discusses some of the options](http://stackoverflow.com/questions/22622013/wrap-existing-memory-with-const-stdvector).

**Comment by lpsinger** [comment]
> What I meant to say is that using healpy already incurs a tenfold slowdown for most Healpix functions compared to Healpix C++, but no one seems to be overly concerned about this.

I'm sorry, I missed something: why is that?

**Comment by crosset** [comment]
Hi Martin,

I am not a C++ expert (far from that), but isn’t it possible not to tie algorithms to a specific container by using iterators ? (a random access iterator in our case). That seems to be what is used by STL algorithms (for example http://en.cppreference.com/w/cpp/algorithm/sort). I don’t know if this is possible/easy in the case of healpix, though.

Otherwise, it will be very complicated to communicate between healpix C++ and any scripting language without making copies (if using std::vector, which as you said is not meant to be used to wrap an existing buffer, but has to control its own memory).

Cheers,
Cyrille.

**Comment by mreineck** [comment]
> I'm sorry, I missed something: why is that?

Disclaimer: I have measured this only a long time ago. Things may have improved in the meantime (I remember tweaking healpy's interface in the meantime), and it would be great to have more current timing information.
If someone knowledgeable with benchmarking Python code could run, say, a test of healpy's ang2pix function to see how many operations it does per second, that would be great. I'm absolutely aware that the length of the input array plays a crucial role ... (just choose the best one, which is probably quite long.)
The C++ numbers are around 25 million calls per second on a five-year-old i3-2120, and around 33 millions per second on a i5-5300U.

**Comment by mreineck** [comment]
> I am not a C++ expert (far from that), but isn’t it possible not to tie algorithms to a specific container by using iterators ? (a random access iterator in our case). That seems to be what is used by STL algorithms (for example http://en.cppreference.com/w/cpp/algorithm/sort). 

This is absolutely correct, and it works beautifully as long as one is carrying out one algorithm on a given set of data specified by those iterators.

The complication in the Healpix case is that the data (on the C++ side) is part of a "Healpix_Map" object, and this object provides operations for resizing (i.e. the nside parameter can be updated after the creation of the object). Of course this implies that the underlying data structure holding the pixel values also needs resizing support, and iterators don't provide this.

Currently I work around this using a horribly ugly trick: the C++ code knows that it doesn't own the pointer to the Python data, so it will never try to deallocate or reallocate it. However, as soon as the map object is resized, a new "regular" storage for the map data is generated in the official way, and the original Python pointer is forgotten on the C++ side.

So the calls from Python into Healpix C++ only work because the functions invoked do not try to do anything fancy with the affected map objects. As I said, it's pretty fragile - and it only works, because I'm using the nonstandard "arr" class as data storage instead of "vector", because I hacked "arr" to support all those dirty tricks.

**Comment by mreineck** [comment]
> Nonetheless, it seems like this is the most straightforward way to do it using STL. There is a nice StackOverflow thread that discusses some of the options.

Thanks for the link!
My currently used approach is nearly identical with one of those presented there.

I guess the takeaway of the discussion is the following
 - I'd like to store the arrays in a std::vector when using the code "normally"
 - With data coming from Python (and if we want to avoid copying), the best I can do is wrap the data in a class that looks in some respects like a std::vector, but isn't exactly.
 - Since these two classes are different, I would have to templatize the Healpix_Map and Alm classes in a way that I can provide this "vector" type as a parameter.

This is possible (and a rather clean approach as well), but it requires substantial changes throughout the sources. I will have to play with that for some time to see how well it works. But as I said at the beginning, this is not something I plan to release soon...

**Comment by mreineck** [comment]
Coming back to the performance question:

I just did some (not very professional) testing, with the following results:
 - for an array length of 10000, healpy ang2pix reaches about 70% of C++ performance
 - at length 1000 it's 50%
 - at length 100 it's 14%
 - at length 10 it's 1.3 %

That means that for array lengths below 100 the calling overhead completely dominates the actual computation.
The good news is of course that if your problem allows computing very many ang2pix()es simultaneously, you don't pay a big performance price.
On the other hand this incurs significant memory overhead, because all the calculations in check_nside() and friends produce a substantial number of temporary arrays.

**Comment by crosset** [comment]
I guess the overhead is due to the machinery to provide numpy « Universal function » behavior, which allows to give scalars or arrays of any shape as input to ang2pix and others. That’s a conveniency provided by python which we want to keep.

Do you see any obvious possible improvement to the code which performs the loop?
  Healpix_Base2 hb;
  long oldnside=-1;
  for(intp i=0; i<n; i++, ip1+=is1, ip2+=is2, ip3+=is3, op+=os)
    {
      long nside = *(long*)ip1;
      if (nside!=oldnside)
        { oldnside=nside; hb.SetNside(nside, scheme); }
      try {
        pointing ptg = pointing(*(double *)ip2,*(double *)ip3);
        ptg.normalize();
        *(long *)op = hb.ang2pix(ptg);
      } catch(PlanckError &e) {
        *(long *)op = -1;
      }
  }

**Comment by mreineck** [comment]
This C++ loop is certainly not the cause of the slowdowns. It might add an overall 10% or so, but that's just the usual price to pay when adjusting data to a specific interface.

I suspect the overhead to consist of the cost Python function calls, and the operations in "check_nside" and "check_theta_valid". This is interpreted code, and it creates and destroys quite many Python objects. For short array lengths this will always dominate the computation time.

**Comment by crosset** [comment]
> This C++ loop is certainly not the cause of the slowdowns. It might add an overall 10% or so, but that's just the usual price to pay when adjusting data to a specific interface.
> 
> I suspect the overhead to consist of the cost Python function calls, and the operations in "check_nside" and "check_theta_valid". This is interpreted code, and it creates and destroys quite many Python objects. For short array lengths this will always dominate the computation time.
> 
Yes, of course you’re right. Note that it’s always possible to bypass these tests by calling directly pixlib._ang2pix_ring (though it is not as easily accessible as ang2pix). Anyway, I am happy that healpy is not a factor 10 slower! Thanks for checking!

**Comment by mreineck** [comment]
> Note that it’s always possible to bypass these tests by calling directly pixlib._ang2pix_ring (though it is not as easily accessible as ang2pix)

Oh wow! That helps big time. At vector length 10 this provides a 15x speedup.

**Comment by zonca** [comment]
I'll close this for now, reopen if you want to discuss more.
