### ISSUE TITLE
Test of `map2alm` use absolute tollerance instead of relative

### ISSUE THREAD

**Issue by dpole** [healpy/healpy#378]
In `test/test_sphtfunc.py`, `test_map2alm` and `test_map2alm_pol` are the only tests using absolute tolerance instead of relative tolerance. Is there a specific reason for this? Is it related to #356?
By the way, switching to `rtol` the test fails even for `rtol=1`.
Thanks!

**Comment by zonca** [comment]
well, it is supposed to be run quickly, so we are using low nside and low lmax, you cannot expect high accuracy, it is mostly for checking we have not bad regressions.

@mreineck , do you agree with this? would you have a better approach to suggest?

see the test here: https://github.com/healpy/healpy/blob/master/healpy/test/test_sphtfunc.py#L102

**Comment by mreineck** [comment]
Using rtol alone will most likely not work. Imagine that one of the pixels in the input map is, say, 1e-3, and the map has pixels with values between -1 and 1. In this scenario, it is quite likely that the pixel in question can only be reproduced with an absolute error of 1e-3 (typical accuracy of Healpix SHTs in this situation), so the relative error is already around 1.
Even worse, if any of the input pixels happened to be exactly zero, its relative error would be infinity, unless it was reconstructed exactly, which is _very_ unlikely.
The cleanest way to check the errors would be to compare the absolute errors to max-min of the input map. If they are all smaller than (roughly) 1e-3 of thet value, the transform was fine.

**Comment by zonca** [comment]
thanks @mreineck ! I see your point, I think for testing purposes here absolute tolerance is suitable, I'll close the issue.

**Comment by dpole** [comment]
Ok, thank you guys for the useful information
