### ISSUE TITLE
doctests not run with python setup.py test

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#380]
@lpsinger it looks like some options for pytest have changed and doctests are not being executed, this affects travis as well

**Comment by lpsinger** [comment]
I had not noticed. Would you be more specific? Would you please point out which tests are not running?

**Comment by zonca** [comment]
unit tests are running, no doctests are running, see for example on travis-ci:

https://travis-ci.org/healpy/healpy/jobs/195086263

there should be more `pytest` lines about doctests for example in `pixelfunc.py`

**Comment by zonca** [comment]
@lpsinger can you take a look at this issue again?
