### ISSUE TITLE
Question regarding the C++ interface

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#381]
I'm trying to get more familiar with Python and Python/C++ interfacing in particular, which is why I am looking at the interface to Healpix C++ in more detail. This has turned up a few questions:

- healpy/src/_healpy_fitsio_lib.cc seems to be unused, i.e the code it contains is not called. Should it be removed?
- Apparenty two different methods are used for the interfacing: cython for _pixelfunc.pyx, query_disc.pyx, sphtools.pyx etc.,  and some (apparently older and more complicated) one for _healpy_sph_transform_lib.cc and _healpy_pixel_lib.cc.

Is it feasible (in your opinion) to re-write the latter files using cython? Would you be willing to merge a pull request implementing such a change?

**Comment by crosset** [comment]
Hi Martin,

When I started to write the python wrapper for healpix, cython did not provide easy integration with C++, as it is now. That explains why the initial (older) wrapper is written in C (actually mix of C and C++ to call Healpix c++ library and Python C API...).

For more recent functions, I used Cython, as it had recently allowed C++ (and it was much easier).
I tested then to rewrite pix2ang with cython (see there <https://github.com/healpy/healpy/blob/master/healpy/src/_query_disc.pyx#L293>s <https://github.com/healpy/healpy/blob/master/healpy/src/_query_disc.pyx#L293>ee there), but
(1) it was slower than the C/C++ wrapper and 
(2) it was not a ufunc (which is a convenient way to have a function working for scalars or arrays using the standard numpy broadcasting rules).

If these two problems can be solved (certainly yes), then we can replace the manual wrapper code by cython code.

Concerning _healpy_fitsio_lib.cc, it can be removed as it only provided a pixwin function which was rewritten in python using the pyfits.

Cheers,
Cyrille.

**Comment by mreineck** [comment]
Hi Cyrille,

many thanks for the explanations!
I guess I'll look at _healpy_sph_transform_lib.cc first, then, since ufuncs shouldn't be needed there, and the calling overhead is probably small compared to the computational time.
After that I can still play around with the pixel functions.

Cheers,
  Martin

**Comment by mreineck** [comment]
I've opened pull request #382. Some tests fail, but (at least to me) it doesn't seem related to my changes.

**Comment by mreineck** [comment]
The Travis tests are marked as failed, but I'm pretty sure this is an intermittent failure due to some problem on the test machine (please have a look at the test logs to convince yourself as well). I'd like to trigger another Travis run, but I don't know how to...

**Comment by mreineck** [comment]
Nah ... seems reproducible. Still, I'm pretty sure I'm innocent :)
Could one of the experts please have a look?

**Comment by mreineck** [comment]
No one able to help me with this? @zonca ? @lpsinger ?

**Comment by zonca** [comment]
ok, thanks for the pull request, I'll left a comment there, then we can merge it, I'll close this.
