### ISSUE TITLE
Problem with write map( astropy.io.fits has no attribute 'new_table')

### ISSUE THREAD

**Issue by jasonfan1997** [healpy/healpy#384]
When I try to write the healpix map back to a fits file,this error message show up.Why will this happen?Can someone explain to me how the write_map function work?

**Comment by lpsinger** [comment]
That function was [removed in Astropy 1.3.1](https://github.com/astropy/astropy/blob/v1.3.1/CHANGES.rst#api-changes). We'll need to update Healpy.

**Comment by lpsinger** [comment]
Ah, we already fixed that in #341 and #346. You just need to update to Healpy 1.10.1 or newer.
