### ISSUE TITLE
Update conda for healpy to the latest

### ISSUE THREAD

**Issue by janerigby** [healpy/healpy#390]
The healpy documentation gives the following instructions to install w conda:
>      conda install -c openastronomy healpy

Unfortunately, that points to an old version, 1.9.1.  conda thinks that numpy needs to be degraded to work with that version:
> The following packages will be DOWNGRADED due to dependency conflicts:
>     numpy:        1.12.1-py27_0                     --> 1.11.3-py27_0   

Where should conda be looking to get the latest version of healpy?

I got the latest healpy using pip, but I'm writing installation instructions for new users, so the more they can do in conda, the better.

**Comment by zonca** [comment]
you should ask to the maintainers of openastronomy, not sure why their system is not picking up newer version of healpy.

https://github.com/OpenAstronomy/conda-channel

**Comment by janerigby** [comment]
Have done so. Thanks!

https://github.com/OpenAstronomy/conda-channel/issues/34
