### ISSUE TITLE
Undefined Symbol in healpy_sph_transform_lib

### ISSUE THREAD

**Issue by mickeyhorn** [healpy/healpy#392]
I am getting this error:

`/home/mickey/anaconda2/envs/HERA/lib/python2.7/site-packages/healpy-1.10.3-py2.7-linux-x86_64.egg/healpy/pixelfunc.py:105: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')`
`Traceback (most recent call last):`
`  File "CST_to_healpix.py", line 4, in <module>`
`    import healpy as hpy`
`  File "/home/mickey/anaconda2/envs/HERA/lib/python2.7/site-packages/healpy-1.10.3-py2.7-linux-x86_64.egg/healpy/__init__.py", line 42, in <module>`
`    from .sphtfunc import (anafast, map2alm,`
`  File "/home/mickey/anaconda2/envs/HERA/lib/python2.7/site-packages/healpy-1.10.3-py2.7-linux-x86_64.egg/healpy/sphtfunc.py", line 27, in <module>`
`    from . import _healpy_sph_transform_lib as sphtlib`
`ImportError: /home/mickey/anaconda2/envs/HERA/lib/python2.7/site-packages/healpy-1.10.3-py2.7-linux-x86_64.egg/healpy/_healpy_sph_transform_lib.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE`

I am running Astropy version 1.3.3 and Numpy version 1.12.1 on Ubuntu 16.04. I get this error when installing Healpy (1.10.3) through pip or the git repo. The conda version is 1.9 and is not compatible with the latest astropy.io.fits (which may be a separate issue) because it was trying to use the deprecated new_table function.

Here is the ldd, which I saw in the similar issue #140 and #367:
 
`linux-vdso.so.1 =>  (0x00007ffcc31e9000)`
`	libpython2.7.so.1.0 => /home/mickey/anaconda2/envs/HERA/lib/libpython2.7.so.1.0 (0x00007ffb174bb000)`
`	libstdc++.so.6 => /home/mickey/anaconda2/envs/HERA/lib/libstdc++.so.6 (0x00007ffb171a4000)`
`	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffb16e85000)`
`	libgomp.so.1 => /home/mickey/anaconda2/envs/HERA/lib/libgomp.so.1 (0x00007ffb16c76000)`
`	libgcc_s.so.1 => /home/mickey/anaconda2/envs/HERA/lib/libgcc_s.so.1 (0x00007ffb16a5f000)`
`	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffb16842000)`
`	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffb16479000)`
`	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffb16274000)`
`	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ffb16071000)`
`	/lib64/ld-linux-x86-64.so.2 (0x0000564935852000)`
`	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffb15e69000)`

**Comment by dannyjacobs** [comment]
@zonca Andrea have you or anyone else heard of linking issues on ubuntu 16? Alternatively, who maintains the conda build? Could that be updated to 1.10?

**Comment by zonca** [comment]
I'm trying to update the conda build to 1.10, https://github.com/conda-forge/healpy-feedstock/pulls

**Comment by zonca** [comment]
the problems is that you are building with the system gcc but then linking to the `libstdc++` `libgomp` and `libgcc` from Anaconda instead.

I just tested on a machine with the same problem and removing the Anaconda libraries out of the way fixes the issue.

A better solution would be to use the CC and GCC variables to instruct `pip` to build `healpy` with the Anaconda Python instead of the system Python.

**Comment by zonca** [comment]
We have updated conda builds please try to use them and reopen if you still have this issue
