### ISSUE TITLE
Incorrect pixel corners from healpy.boundaries?

### ISSUE THREAD

**Issue by cdeil** [healpy/healpy#393]
@adl1995, @tboch and I are starting to work on a Python [hips](https://github.com/hipspy/hips) package this week, and as mentioned [here](https://hips.readthedocs.io/en/latest/drawing_algo.html#naive-algorithm) we plan to use [healpy.boundaries](http://healpy.readthedocs.io/en/latest/generated/healpy.boundaries.html) to compute HiPS tile (which match HEALPix pixel) corner positions and then apply an affine transformation to draw the tiles into a sky image defined by a WCS.

One of our first goals was to prototype the tile drawing using a single HiPS tile, the one with `order=3` and `ipix=450` around the Galactic center shown here:
https://www.aanda.org/articles/aa/full_html/2015/06/aa26075-15/F4.html

We used this code to compute the corner positions of this HiPS tile:
```python
import numpy as np
import healpy as hp
from astropy.coordinates import SkyCoord
nside = hp.order2nside(order=3)
coords = hp.boundaries(nside=nside, pix=450, nest=True)
ra, dec = hp.vec2ang(coords, lonlat=True)
radec = SkyCoord(ra, dec, unit='deg', frame='icrs')
```
and find
```
>>> radec
<SkyCoord (ICRS): (ra, dec) in deg
    [( 242.19350089, -22.6263803 ), ( 270.        , -43.1943471 ),
     ( 226.97382512, -19.37793463), ( 229.39870535, -33.05573115)]>
```
and
```
>>> radec.galactic
<SkyCoord (Galactic): (l, b) in deg
    [( 351.55907245,  21.09375872), ( 349.06587812,  -9.65439747),
     ( 342.01462541,  32.94289257), ( 335.12864085,  20.5241756 )]>
```

This does not match the expectation from https://www.aanda.org/articles/aa/full_html/2015/06/aa26075-15/F4.html where two corners are below the Galactic plane (at negative Galactic b). We tried a few other pixels at order 3 and also got results where not all 4 corners are where we expect them.

Are we doing something wrong or is this a bug in `healpy.boundaries`?

**Comment by tboch** [comment]
I confirm this is unexpected. The code logic seems ok from a first look, but the result is definitely wrong.
I'll have a closer look later tonight

**Comment by tboch** [comment]
OK, I got it, first argument of vec2ang must be transposed:
`ra, dec = hp.pixelfunc.vec2ang(np.transpose(coords), lonlat=True)`

This gives the following correct result:

```
>>> radec
<SkyCoord (ICRS): (ra, dec) in deg
    [( 264.375, -24.62431835), ( 258.75 , -30.        ),
     ( 264.375, -35.68533471), ( 270.   , -30.        )]>
>>> radec.galactic
<SkyCoord (Galactic): (l, b) in deg
    [(   2.70907683,  3.81383515), ( 355.44356947,  4.98219156),
     ( 353.36235549, -2.10918264), (   0.67390004, -3.23622577)]>
```

**Comment by zonca** [comment]
this looks ok, please reopen if I'm mistaken
