### ISSUE TITLE
save the projection map as a 2d numpy array

### ISSUE THREAD

**Issue by jasonfan1997** [healpy/healpy#394]
If I have a healpix map, how can I project it and save as a 2d numpy array. If I use healpy.visufunc.mollview and return_projected_map, it will return a 2d masked array which I have no idea how to deal it. Also, I am wondering how can I turn a projected map to a healpix map.

**Comment by lpsinger** [comment]
I suggest using [`reproject.healpix`](http://reproject.readthedocs.io/en/stable/healpix.html).
