### ISSUE TITLE
More efficient read_map?

### ISSUE THREAD

**Issue by kadrlica** [healpy/healpy#395]
It seems like `read_map` uses `astype` to convert input maps to the desired datatype regardless of whether the map is already the desired dtype:
https://github.com/healpy/healpy/blob/58fe244171f6a7875f85dc437393cfa290487e16/healpy/fitsfunc.py#L346-L352

It seems like a simple check of the current dtype against the desired dtype could reduce the overhead especially for large maps. More generally, is there a reason that the conversion isn't done in place with a `view` rather than copying the entire array with `astype`?

**Comment by kadrlica** [comment]
Here's an example comparing the timing for `read_map`, a raw `pyfits` read, and using [`fitsio`](https://github.com/esheldon/fitsio). It looks like `read_map` is 1.5x slower than `pyfits` and 4x slower than `fitsio`. Usually I'd say a factor of 1.5x isn't a big deal, but the difference between 8s, 20s, and 30s is quite noticeable.

```
import healpy as hp
import numpy as np
import astropy.io.fits as pyfits
import fitsio

npix = hp.nside2npix(4096)
m0 = np.zeros(npix,dtype=int)
m0[:1000] = 1
hp.write_map('tmp.fits.gz',m0,dtype=int)
```
```
>>> %timeit hp.read_map('tmp.fits.gz',dtype=int,verbose=False)
1 loops, best of 3: 32.7 s per loop
>>> m1 = hp.read_map('tmp.fits.gz',dtype=int,verbose=False)
>>> print( (m0 == m1).all() )
True
>>> %timeit pyfits.open('tmp.fits.gz')[1].data['I'].ravel()
1 loops, best of 3: 20.6 s per loop
>>> m2 = pyfits.open('tmp.fits.gz')[1].data['I'].ravel()
>>> print( (m0 == m2).all() )
True
>>> %timeit fitsio.read('tmp.fits.gz',ext=1)['I'].ravel()
1 loops, best of 3: 7.98 s per loop
>>> m3 = fitsio.read('tmp.fits.gz',ext=1)['I'].ravel()
>>> print( (m0 == m3).all() )
True
```

**Comment by zonca** [comment]
Can you prepare a pull request with an improvement and benchmark that?

**Comment by kadrlica** [comment]
I can try to take a look at this over the next few weeks. However, the fact that `pyfits` itself is extremely inefficient might mean that I just wrap my own functions using `fitsio`. I assume that `healpy` would prefer not to switch from `pyfits` to `fitsio`?

**Comment by lpsinger** [comment]
> I can try to take a look at this over the next few weeks. However, the fact that pyfits itself is extremely inefficient might mean that I just wrap my own functions using fitsio. I assume that healpy would prefer not to switch from pyfits to fitsio?

Seems like it would be easier just to change the existing code to use `astype(..., copy=False)`.

**Comment by kadrlica** [comment]
@lpsinger  `astype(..., copy=False)` is much, much slower than `view` for changes between compatible types.
```
>>> m = np.arange(hp.nside2npix(4096),dtype=int)

>>> %timeit m.astype(int,copy=False)
1000000 loops, best of 3: 811 ns per loop
>>> %timeit m.astype(float,copy=False)
1 loop, best of 3: 3.17 s per loop

>>> %timeit m.view(int)
1000000 loops, best of 3: 612 ns per loop
>>> %timeit m.view(float)
1000000 loops, best of 3: 595 ns per loop
```

**Comment by lpsinger** [comment]
> @lpsinger thanks for the suggestion, but astype(..., copy=False) is much, much slower than view for changes between compatible types.
> 
> >>> m = np.arange(hp.nside2npix(4096),dtype=int)
> 
> >>> %timeit m.astype(int,copy=False)
> 1000000 loops, best of 3: 811 ns per loop
> >>> %timeit m.astype(float,copy=False)
> 1 loop, best of 3: 3.17 s per loop
> 
> >>> %timeit m.view(int)
> 1000000 loops, best of 3: 612 ns per loop
> >>> %timeit m.view(float)
> 1000000 loops, best of 3: 595 ns per loop

Looks pretty comparable to me when the types are compatible: 811 ns versus 612 ns. It's only when you are converting between incompatible dtypes that there is a significant speed difference, and that can't be helped because it actually does take CPU cycles to convert ints to floats or vice versa.

If you rewrite this using `.view` but also include your own test of the compatibility of the dtypes, then you might just break even. Besides, don't forget that this is a function for reading a file. In what circumstance will the 200 ns that you would save make a noticeable difference in the overall performance of the function?

> As a side note, I don't think this is anywhere near the heart of the many efficiency in pyfits (I personally avoid pyfits like the plague when possible).

You should be using `astropy.io.fits` anyway. Pyfits is defunct.

**Comment by kadrlica** [comment]
Yes, sorry, incompatible types are the fast ones, so I agree `astype` should be fine. `astropy.io.fits` is what I'm using (see import above), just old fashioned in referring to it at as `pyfits`.

**Comment by lpsinger** [comment]
> Yes, sorry, incompatible types are the fast ones, so I agree astype should be fine.

OK, good! Still, patches that make things faster or easier to use are always welcome. For what it's worth, [for my own very specialized HEALPix use case, I am using astropy itself instead of `healpy.read_map`](https://github.com/lscsoft/lalsuite/blob/master/lalinference/python/lalinference/io/fits.py#L422-L538).

> astropy.io.fits is what I'm using (see import above), just old fashioned in referring to it at as pyfits.

Pyfits *is* a pain to use, but fortunately it gets better with each astropy release.

**Comment by kadrlica** [comment]
Sorry, why is this issue closed? Don't we still need to make the change to `astype(..., copy=False)` (or did you submit a PR)?

re pyfits: yeah, though I care more about the performance than the ease of use.

**Comment by lpsinger** [comment]
> Sorry, why is this issue closed? Don't we still need to make the change to astype(..., copy=False) (or did you submit a PR)?

Oh yeah. Sorry. Would you care to submit a PR?

**Comment by kadrlica** [comment]
Yeah, can do.
