### ISSUE TITLE
Comparing phi to None with ==

### ISSUE THREAD

**Issue by ktausch** [healpy/healpy#398]
Recently, I have noticed an error when using the get_interp_weights function in healpy/pixelfunc.py. The error points to (what is my) line 1295, which contains the statement "if phi == None:". Since I pass phi as an array, this is attempting to check whether each element of phi is None instead of checking whether phi itself is None.

For a while, this was appearing to me as a warning instead of an error, but it appeared as an error when I updated numpy.

**Comment by zonca** [comment]
I don't see this in master, see https://github.com/healpy/healpy/blob/master/healpy/pixelfunc.py 
It must have been already fixed.
We'll release a new `healpy` version soon
