### ISSUE TITLE
Draw latitude lines in mollview? 

### ISSUE THREAD

**Issue by nkasmanoff** [healpy/healpy#401]
Hi, I'm using mollview to create a heat map of sorts, and one issue I'm having is figuring out how to add tickmarks to the side of the figure showing the latitude/longitude lines (more concerned with latitude though). I've attached where I'm at with my code, and I couldn't find anywhere in the healpy documentation how I could fix add in these lines. 

<img width="828" alt="screen shot 2017-07-20 at 9 44 08 am" src="https://user-images.githubusercontent.com/22650065/28420531-7222edb0-6d30-11e7-88b6-435207b326f6.png">

**Comment by zonca** [comment]
this is not supported, there is an experimental version of `mollview` here if you want to test it, but it might be buggy. https://github.com/healpy/healpy/blob/master/healpy/newvisufunc.py

also, see the thread at #109

**Comment by nkasmanoff** [comment]
Thanks, I got it. No bugs on my end, but I'm only using mollview feature of it so can't say for certain.
