### ISSUE TITLE
Error installing healpy

### ISSUE THREAD

**Issue by CrazyGaby** [healpy/healpy#405]
Hello,

I'm trying to install healpy in a virtual environment (virtualenv 15.0.1) with `pip install healpy` and I get this error:

`Command "/home/gaby/hw-env/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hfVPUW/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i7ndgy-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gaby/hw-env/venv/include/site/python2.7/subprocess32" failed with error code 1 in /tmp/pip-build-hfVPUW/subprocess32/
`
Please, can you help me to know what I am doing wrong?

**Comment by zonca** [comment]
Have you tried installing with conda instead? See the installation
instructions

**Comment by CrazyGaby** [comment]
No, I have not do it but I will do it right now and I will comment the result

**Comment by zonca** [comment]
close for now, please reopen if you still cannot install
