### ISSUE TITLE
 Add overwrite keyword to write_map

### ISSUE THREAD

**Issue by JulienPeloton** [healpy/healpy#412]
Hi,

In the last version (1.11.0), the keyword overwrite has been added to the write_map routine.
This is a great feature to have I think, but is there any reason of having it False by default - given that it never existed before? With the current setup, there is no compatibility between old and new versions while having overwrite=True by default would solve it naturally.

Best,
Julien

**Comment by zonca** [comment]
thanks, I think you are right, unfortunately 1.11.0 has been around for more than a month, at this point it would be too confusing to revert to the old behavior, so I think better leave it as it is now.

**Comment by JulienPeloton** [comment]
Thanks for the quick reply.
I understand your point, although I think this introduces more problem than it solves ;-)

Best,
Julien
