### ISSUE TITLE
Log plots of single data value   

### ISSUE THREAD

**Issue by rusholme** [healpy/healpy#422]
Hi,

Plotting with norm='log' fails (in projaxis subroutine) if the data only has one value (or rather no min/max range). For example:

```
%matplotlib inline
import healpy as hp
import numpy as np
nside = 64
npix = hp.nside2npix(nside)
m = np.full(npix, 1.0)
hp.mollview(m)
hp.mollview(m, norm='log')
```

This is admittedly an edge case, but I am plotting logarithmic hit maps and have occasional days with only a single observation.

This problem exists in both:
healpy                    1.11.0              np112py27_0    conda-forge
healpy                    1.9.1               np110py27_0    conda-forge

Thanks!

**Comment by zonca** [comment]
No time to look into this, if you'd like to investigate and prepare a pull request I would be happy to review it. I will close this issue. Thanks.
