### ISSUE TITLE
alm values are not correct

### ISSUE THREAD

**Issue by khharut** [healpy/healpy#424]
I have calculated alm-s for Planck's 70 GHz map and found out that they are not correct. Every alm if m>0 must be complex number with no-zero imaginary part, but that alm-s were real numbers with 0 imaginary parts. I think it is not normal. Because of that I have got wrong results in my calculations.

**Comment by zonca** [comment]
not enough details

**Comment by khharut** [comment]
import healpy as hp
import matplotlib
import matplotlib.pyplot as plt
import numpy as np


input_file = 'LFI_SkyMap_070_2048_R2.01_full'

lfi_70_map = hp.read_map(input_file + '.fits', nest = False)

lfi_70_alms = hp.sphtfunc.map2alm(maps = lfi_70_map, lmax = 8192, iter = 1, pol = False, use_weights = False, gal_cut = 20)

**Comment by khharut** [comment]
Here is the code I used. Why not enough details. Please reopen issue.

**Comment by zonca** [comment]
the beginning of the array is ok to have 0 imaginary part, look at the rest of the array.

**Comment by zonca** [comment]
I see 94% of the array immaginary part is nonzero:

    (np.abs(lfi_70_alms.imag) > 1e-9).sum()  / len(lfi_70_alms) * 100
    94.341240539997941

The issue looks solved, so I will close it. If you have other comments add them below here. I will then come back when I have time and reopen it. **No need to open other issues**.

**Comment by khharut** [comment]
The problem is that for lmax=8192 all alm-s have zero imaginary part. Try this sum(map(lambda x: abs(x.imag), lfi_70_alms[:8192])). They are most important ones, others not. Even for power-spectrum.

**Comment by khharut** [comment]
I even checked for version 1.9 of healpy, the same problem exists there.

**Comment by khharut** [comment]
Please, fix this problem.

**Comment by khharut** [comment]
Thank you in advance.

**Comment by zonca** [comment]
sorry, I don't think this is a healpy issue. I think you do not have a good understanding of Alms.
