### ISSUE TITLE
Issue in writing map

### ISSUE THREAD

**Issue by SimoneAmmazzalorso** [healpy/healpy#425]
Hi,

I have noticed a problem in writing maps: it seems that with the latest version of pyfits the function "new_table" has been removed and substituted by "BinTableHDU.from_columns".
Changing the line in the healpy function "write_map" 
`tbhdu = pf.new_table(cols)`
with
`tbhdu = pf.BinTableHDU.from_columns(pf.ColDefs(cols))`
and  changing the way the header is updated from e.g.
`tbhdu.header.update('PIXTYPE','HEALPIX','HEALPIX pixelisation')`
to
`tbhdu.header['PIXTYPE'] = ('HEALPIX','HEALPIX pixelisation')`
now it works fine. Were you aware of this issue?

All the best,
Simone Ammazzalorso
PhD Student
University of Torino & INFN

**Comment by zonca** [comment]
No, can you please send us a pull request with the fix?

Il mer 20 dic 2017, 15:42 SimoneAmmazzalorso <notifications@github.com> ha
scritto:

**Comment by SimoneAmmazzalorso** [comment]
Hi,

I've sent the pull request. But I noticed that the changes were already present. Was it a fresh change? Another possibility is that for some reasons I have installed an old version of healpy (I don't know how since I've only run the "pip install" command)

All the best,
Simone

**Comment by zonca** [comment]
my bad, I didn't remember someone already fixed that. I will close this issue and the pull request and I will release a new healpy version
