### ISSUE TITLE
Question of toolzoom

### ISSUE THREAD

**Issue by Xavier1946** [healpy/healpy#429]
Hello,
I have just a simple question, when I compile the command:
zoomtool.mollzoom(mask1, fig=None, rot=None, coord=None, unit='', xsize=784, title='Mollweide view', nest=False, min=None, max=None, flip='astro', remove_dip=True, remove_mono=True, gal_cut=0, format='%g', cmap=cmap, norm=None, hold=False, margins=None, sub=None)

Appears two images,the full CMB map and the zoom at the equator, but I only want to have the zoom image  without  labels or the full sky map neither. How can I do that?

Thank you.

**Comment by DanielLenz** [comment]
Do you need it to be interactive, or do you just want to plot a zoomed-in region of the full sky?

**Comment by zonca** [comment]
no feedback from @Xavier1946 , please reopen if needed.
