### ISSUE TITLE
healpy in mybinder 

### ISSUE THREAD

**Issue by ggreco77** [healpy/healpy#431]
Hi all, 
healpy  does not work in mybinder, any suggestions?

best,
Giuseppe

**Comment by zonca** [comment]
Thanks for reporting, can you please send a link for instructions to make it easier to reproduce this?

**Comment by zonca** [comment]
For -> or

**Comment by ggreco77** [comment]
![mybinder_healpy](https://user-images.githubusercontent.com/11920251/38388220-e10ab60c-391a-11e8-9dca-56cdd32163e0.jpg)
I get this error when healpy is in the requirements.txt file. I also open an issue in the binder chat.

thanks

**Comment by lpsinger** [comment]
It would probably reduce the frequency of build issues if we started uploading binary wheels when we do releases.

**Comment by ggreco77** [comment]
@fomightez suggests to install healpy using conda.  Now it properly works using such method.

**Comment by zonca** [comment]
this should be fixed now
