### ISSUE TITLE
Second derivatives of Healpy map

### ISSUE THREAD

**Issue by alessiospuriomancini** [healpy/healpy#433]
Hi,

Is there a way  in Healpy to get the second derivatives in theta and phi of a Healpy map?
(ideally both the mixed derivative theta phi  and   the derivatives theta theta, phi phi)

Something like the optional output `der2` of the `alm2map_der` function for the Fortran version of Healpix.

Thanks in advance

**Comment by zonca** [comment]
not currently, if this function is available in the C++ version of HEALPix, then it would not be difficult to call it from Python in https://github.com/healpy/healpy/blob/master/healpy/src/_sphtools.pyx, if you'd like to implement it I am happy to review and merge your Pull Request

**Comment by mreineck** [comment]
Unfortunately, the C++ library does not support second derivatives. Implementing them in an elegant way is really hard, and I didn't have the time for it...

**Comment by zonca** [comment]
thanks @mreineck 
@alessiospuriomancini if you'd like to port the functionality from FORTRAN to C++, you can send the patch to @mreineck to be included into HEALPix, then we can wrap it in `healpy`.

**Comment by mreineck** [comment]
@zonca This would be a _very_ daunting task :)
I know libsharp by heart, and I was not brave enough to do it myself ...
