### ISSUE TITLE
Circular aperture photometry feature?

### ISSUE THREAD

**Issue by aaroncnb** [healpy/healpy#434]
Hi, for my PhD project I made a crude translation of the circular aperture photometry code in IDL, by Clive Dickinson et al. You can access the original IDL code (and a C++ version) here:
http://irsa.ipac.caltech.edu/data/Planck/release_1/software/

It takes a list of target coordinates with aperture radii for the background annulus and source aperture, and a list of input healpix maps, and returns photometry for each target in each map.

I'm just curious what the `healpy` community thinks about building such functionality into `healpy` itself.
The core functionality is in fact already provided by `healpy.query_disc()` 

I can share the code I've written as a starting point. However as I'm not exactly a python expert (little experience even in dealing with classes, etc.), I'm sure someone else could write up something more clever and organized.

**Comment by zonca** [comment]
Planck! nice!

I think it would be better to keep it as a separate project, we can host it under the `healpy` organization if you think it would make it easier to find.
I can also provide some feedback on how to improve the implementation.

**Comment by zonca** [comment]
please reopen if you'd like to request to add a repository to `github.com/healpy`

**Comment by zonca** [comment]
@aaroncnb  even if you do not want to create a new package, it would be nice if you can share the code online and post the link here

**Comment by aaroncnb** [comment]
@zonca The code in its current state is here:
https://github.com/aaroncnb/circular-photometry
_**WARNING: This was literally the first piece of python I ever wrote!**_

Apologies for the delay. I planned to make improvements to the code but unexpectedly got accepted to for an overseas summer research placement.

The code replicates the core functionality of the original IDL version. It gets the flux of an aperture, and subtracts a background flux based on a surrounding annulus. I'm extremely open to suggestions on how to improve it, even if just in terms of organization. Otherwise feel free to pull it or use however you want :)

**Comment by zonca** [comment]
to better organize the package the best would be to start from the `astropy` package template: http://docs.astropy.org/projects/package-template

**Comment by aaroncnb** [comment]
Ok! Thanks for the suggestion.
