### ISSUE TITLE
ringinfo documentation issues

### ISSUE THREAD

**Issue by cjcopi** [healpy/healpy#439]
The documentation to `ringinfo` has two issues/errors

1. It is claimed that the parameter `ring` can be an int, scalar or array-like.  This not the case, `ring` **must** be a one-dimensional `ndarray`.  This is encoded in the signature of the function.  I do not know enough about Cython to know if there is a way to work around this.  If not, a pure Python wrapper could be written that does the type conversions and calls the underlying function.  Alternatively, the documentation could just be changed.
1. The example calls
```hp.ringinfo(nside, np.arange(4*nside-1))```
but as the documentation states, rings are specified by a positive integer, `1 <= ring <= 4*nside-1`.  Though the output shown is correct for this call, it is misleading.  (I did not know that the Healpix_base class accepted out of range ring numbers.) What would be better is
```hp.ringinfo(nside, np.arange(1,4*nside))```

**Comment by zonca** [comment]
thanks, could you send a pull request to fix this?

**Comment by zonca** [comment]
thanks for the fix
