### ISSUE TITLE
Standardize default FITS extensions name across HEALPix

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#445]
Agreed with @mreineck and @hivon to set default names of the FITS extensions to:

‘TEMPERATURE’, ‘Q_POLARISATION’, ‘U_POLARISATION’

The same will be used in C++, IDL and F90

**Comment by zonca** [comment]
@mreineck @hivon, in `healpy` we also have:

* `["II", "IQ", "IU", "QQ", "QU", "UU"]` default names when a map array is of length 6, possibly a covariance matrix.
* `COLUMN_n` with `n` from 0 to the number of components for any other number of components

Do you have anything similar somewhere else in HEALPix?

**Comment by hivon** [comment]
Hi Andrea,

> On 28 May 2018, at 15:49, Andrea Zonca <notifications@github.com> wrote:
> 
> @mreineck @hivon, in healpy we also have:
> 
> 	• ["II", "IQ", "IU", "QQ", "QU", "UU"] default names when a map array is of length 6, possibly a covariance matrix.
> 	• COLUMN_n with n from 0 to the number of components for any other number of components
> Do you have anything similar somewhere else in HEALPix?
no, there is no default in that case in F90 or IDL.
It is up to the user to name the columns outside the I, IQU or IQU+derivatives cases.
Note that FITS numbers its column starting at 1 (TTYPE1, …)

Eric

**Comment by kadrlica** [comment]
I'll just point out that these default extension names make very little sense for those of us using `healpy` with optical survey data.

**Comment by zonca** [comment]
thanks @kadrlica how many columns and which names do you generally use for that?

**Comment by kadrlica** [comment]
I don't think that there is a well established convention in optical surveys (at least, not one that spans across scientific collaborations). Within the Dark Energy Survey, healpix maps are generally used to store survey characteristics as a function of sky position (i.e., magnitude limit, coverage fraction, sky brightness, airmass, PSF size, etc.). These are commonly distributed as compressed nside=4096 maps with one map per file (using default EXTNAME `xtension`). These maps usually contain one data column with an additional pixel column when in explicit format.

I know that the gamma-ray community is also using healpix for storing counts maps (and probably also survey characteristics). This is true of both the Fermi Gamma-ray Space Telescope and the Cherenkov Telescope Array. Maybe @cdeil could comment more on the use in `gammapy`.

Maybe someone familiar with the LIGO use case could also weigh in (@lpsinger)?

**Comment by cdeil** [comment]
> Maybe @cdeil could comment more on the use in gammapy.

@woodmd developed the HEALPix formats described [here](http://gamma-astro-data-formats.readthedocs.io/en/latest/skymaps/healpix/index.html) and they are mostly supported by [gammapy.maps](http://docs.gammapy.org/dev/maps/index.html).

It seems that this issue is discussing polarisation, we don't have anything for that.

So I don't have anything to add here, except maybe the general sentiment that it would be really nice if some HEALPix FITS formats were standardised; e.g. with WCS or TIME this happened, but for HEALPix it hasn't so far.

**Comment by zonca** [comment]
@kadrlica I see your point, but our main use case is CMB so we'd like to have consistency with the other HEALPix packages. Anyway it is not a key feature.

@cdeil I've found a lots of references on Google about standardization, too many...can you please point me to a simple or more similar to HEALPix example?
Or do you mean an official and comprehensive version of this http://gamma-astro-data-formats.readthedocs.io/en/latest/skymaps/healpix/index.html?

**Comment by cdeil** [comment]
> @cdeil I've found a lots of references on Google about standardization, too many...can you please point me to a simple or more similar to HEALPix example?

Not sure what you mean.

My point was just that HEALPix FITS files are used not in different sub-domains of astronomy, yet HEALPix is not in the FITS standard (https://fits.gsfc.nasa.gov/fits_standard.html) or a registered convention (https://fits.gsfc.nasa.gov/fits_registry.html). E.g. when I tried to learn about HEALPix and even find out something as simple as which header keyword to use for the sky frame (e.g. RADEC or GALACTIC) it wasn't easy. IMO it would be nice to have a short document (1 page?) for HEALPix FITS that describes some things.

http://gamma-astro-data-formats.readthedocs.io/en/latest/skymaps/healpix/index.html could be one thing to look, but it has gamma-ray specific stuff, it's most likely not suitable for other domains like e.g. CMB data.

The question is of course if it is possible to have a useful set of things specified in a HEALPix standard document, or if use cases / formats in the wild are too diverse.

**Comment by zonca** [comment]
thanks @cdeil, I see also a older discussion on `healpix-support` about this: https://sourceforge.net/p/healpix/mailman/message/35721937/

let me ask again on the mailing list

**Comment by zonca** [comment]
@hivon is preparing a document, it will be published soon

**Comment by hivon** [comment]
Hi @cdeil, @kadrlica, @zonca, @lpsinger, @mreineck 
the promised document describing the FITS format currently used in Healpix tools to exchange sky maps is in  https://healpix.sourceforge.io/data/examples/healpix_fits_specs.pdf

**Comment by zonca** [comment]
Standard default column names `‘TEMPERATURE’, ‘Q_POLARISATION’, ‘U_POLARISATION’` were implemented in:

https://github.com/healpy/healpy/commit/d1dec6233fe523deeaa1103dc6f782167d14f2ba

and agree with @hivon's document.

In that document there is no mention of maps with 6 components (possibly covariance matrices)
