### ISSUE TITLE
Install failure with Python 3.6.2 on windows

### ISSUE THREAD

**Issue by TianchengTang** [healpy/healpy#451]
Hi, 

I have encountered this error while trying to install the package: TypeError: environment can only contain strings. Any thoughts?

Thanks,
Kingsley

**Comment by zonca** [comment]
unfortunately we do not support windows, see #25

**Comment by TianchengTang** [comment]
Hi,

Thanks for letting me know.

Regards,
Kingsley

2018-06-04 1:21 GMT-07:00 Andrea Zonca <notifications@github.com>:
