### ISSUE TITLE
Optional degrees argument for pixelfunc.max_pixrad

### ISSUE THREAD

**Issue by kadrlica** [healpy/healpy#452]
It'd be nice to have an optional argument to return the value from [`pixelfunc.max_pixrad`](https://github.com/healpy/healpy/blob/a391ad9fc3b0a60a1f2603d92d32154d6abfd0c3/healpy/pixelfunc.py#L1345) in degrees rather than radians. This would parallel the call to [`pixelfunc.nside2pixarea`](https://github.com/healpy/healpy/blob/a391ad9fc3b0a60a1f2603d92d32154d6abfd0c3/healpy/pixelfunc.py#L994).

**Comment by mreineck** [comment]
Wouldn't it be cleaner to just say
`np.degrees(pixelfunc.max_pixrad(...))`
This avoids duplication.

**Comment by kadrlica** [comment]
@mreineck how is this "cleaner" and what "duplication" does it avoid? The suggested form is:
```
pixelfunc.max_pixrad(nside, degrees=True)
```

@zonca yes, I can submit a PR.

**Comment by mreineck** [comment]
Well,
`np.degrees(pixelfunc.max_pixrad(nside))`
is actually shorter than
`pixelfunc.max_pixrad(nside, degrees=True)`
and it doesn't require additional code in healpy.

**Comment by zonca** [comment]
the best solution would be to use `astropy.units`, but it would require significant work, I can't commit to this but if somebody volunteers I'd love to review a pull request about that.

**Comment by mreineck** [comment]
I'm sorry if my comments above seem to be unnecessarily destructive ... they definitely were not meant that way.
My idea is that code functionality should be as orthogonal as possible, i.e. if there already is a simple way to achieve something, the code should not be enlarged to support another way of achieving it. In the long run this leads to feature creep and very hard-to-maintain code.
Unfortunately, the `np.degrees()` approach does not apply well to `pixelfunc.nside2pixarea`, I admit.

**Comment by kadrlica** [comment]
@zonca yeah, astropy units would be nice, assuming that the decision has been made to broadly incorporate astropy as a dependency and that it doesn't add much overhead in calculations. Unfortunately, I also don't have time to implement this right now.

@mreineck I don't think your comments were destructive. My main feeling is that this change would preserve parallelism in the API.

**Comment by kadrlica** [comment]
Along similar lines, there is also [`pixelfunc.nside2resol`](https://github.com/healpy/healpy/blob/a391ad9fc3b0a60a1f2603d92d32154d6abfd0c3/healpy/pixelfunc.py#L951), which has the optional argument `arcmin`.

```
def nside2resol(nside, arcmin=False)
```

Not sure what (if anything) to do with this.

**Comment by zonca** [comment]
`astropy` is already a dependency for fits reading. Also I would start doing units on all those small functions and leave maps for last, anyway, for the future.
