### ISSUE TITLE
Compilation error on OSX for healpy 1.12.0

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#455]
I am trying to build a conda package for OSX, but I get a compilation error:

```
+ source /Users/travis/miniconda3/bin/activate /Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env
+ /Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env/bin/python -s /Users/travis/miniconda3/conda-bld/healpy_1528849173188/test_tmp/run_test.py
/Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env/lib/python3.6/site-packages/healpy/pixelfunc.py:107: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn("Warning: cannot import _healpy_pixel_lib module")
import: 'healpy'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/healpy_1528849173188/test_tmp/run_test.py", line 2, in <module>
    import healpy
  File "/Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env/lib/python3.6/site-packages/healpy/__init__.py", line 81, in <module>
    from ._query_disc import query_disc, query_strip, query_polygon, boundaries
ImportError: dlopen(/Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so, 2): Symbol not found: __ZN14T_Healpix_BaseIlE8SetNsideEl23Healpix_Ordering_Scheme
  Referenced from: /Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/travis/miniconda3/conda-bld/healpy_1528849173188/_t_env/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so
TESTS FAILED: healpy-1.12.0-py36_1.tar.bz2
```

@mreineck would you have a suggestion on what could be the problem? It was compiling fine 1.11.0

See full log here: https://travis-ci.org/conda-forge/healpy-feedstock/jobs/391491099
The source code is in https://github.com/conda-forge/healpy-feedstock

**Comment by mreineck** [comment]
No idea at all, sorry. From the logs it doesn't seem as if there were any problems during the C++ compilation phase, and the Cython part is just black magic to me ...

**Comment by zonca** [comment]
@keskitalo have you updated on OSX to 1.12.0? Does it work fine on your machine?

**Comment by keskitalo** [comment]
@zonca on OSX 10.13.5 the current master branch fails to compile with
```
healpy/src/_sphtools.cpp:602:10: fatal error: weight_utils.h: No such file or directory
 #include "weight_utils.h"
```
I see `weights_utils.h` under `healpixsubmodule/src/cxx/Healpix_cxx/weight_utils.h` along with two other header files also included by `healpy/src/_sphtools.pyx`.

Could the problem be that the build system is trying to use an existing installation of `healpix_cxx` that does not include the latest updates?

**Comment by zonca** [comment]
yes, correct, could you temporarily uninstall `healpix-cxx` and try again?

**Comment by keskitalo** [comment]
I manually installed healpix_cxx from `healpixsubmodule/src/cxx/autotools` and now healpy compiles and installs just fine. I just had to uninstall my own copy of `libsharp`. It seems that the `libsharp` github repository is incompatible with the latest `healpix_cxx`. This will be an issue for any project that uses the Python bindings from `libsharp` *and* tries to install `healpy`.

**Comment by zonca** [comment]
Thanks @keskitalo, it looks like also @hivon is experiencing the same issue described above. Not sure how to debug. @keskitalo are you compilimg with gcc or clang?

**Comment by keskitalo** [comment]
@zonca I'm using gcc7 installed through macports.

**Comment by keskitalo** [comment]
@mreineck are the any plans of updating the `libsharp` repository to be compatible with the `libsharp` that is bundled with `healpix_cxx`?

**Comment by mreineck** [comment]
I'll have a look, but I expect they will always be slightly different because the "standalone" version has functionality that Healpix doesn't need.
To be honest, I originally didn't expect that the standalone libsharp would ever be installed system-wide by someone, because it's such a custom-tailored piece of software...

**Comment by hivon** [comment]
It seems that there are 2 problems: one tied to libsharp, one with the C++ compiler:
I compiled and installed healpy 1.12.0 from sources, on MacOSX 10.13.4 (I don't have any preinstalled libsharp).
When using gcc 5.3 or clang 9.1, the compilation and installation went smoothly, but the 'import healpy' failed because the symbol __ZN14T_Healpix_BaseIlE8SetNsideEl23Healpix_Ordering_Scheme was not found.
However, everything is fine with gcc 8.1 (installed from http://hpc.sourceforge.net/).
So, together with @keskitalo experience: gcc 7 and 8 are OK, but not gcc 5.3 nor clang 9.1.

**Comment by mreineck** [comment]
This smells very strongly like some subtle ABI changes in the compiler over time. Cython apparently tracks them, but now seems to get things wrong for older compilers.

What's "clang 9.1"? According to llvm.org, the most recent version should be 6.0.

**Comment by hivon** [comment]
I guess Apple is confusing things with version numbers:
/usr/bin/clang -v    returns
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0

**Comment by lpsinger** [comment]
I bet that you are somehow building the C++ library with one compiler and Healpy with another.

**Comment by mreineck** [comment]
You are right ... that could easily have such an effect. Let's hope this is the reason - although it means that we need to keep track of which compiler was used to compile every component, which may be tedious.

**Comment by lpsinger** [comment]
This is not a problem that is unique to us; any project that contains C++ code suffers from the fact that (unlike C) different C++ compilers generally do not produce ABI compatible code because of differences in name mangling.

**Comment by hivon** [comment]
I don't see how replacing gcc-5 with gcc-8 would suddenly force a single C++ compiler to be used everywhere more efficiently than when only gcc-5 was installed.

**Comment by core-dd** [comment]
I've got it running via
"CC=gcc-8 CXX=g++-8 LD=gcc-8 python3 setup.py install --user"
having gcc-8 installed via homebrew.
It looks like python is using clang to build the healpixsubmodule and might be using gcc for the cython magic.

**Comment by zonca** [comment]
I see that in the Travis-CI log of the conda build it is actually using clang and clang++ both for the healpix submodule and for compiling the Python extensions, see:

https://api.travis-ci.org/v3/job/398841745/log.txt

**Comment by cdeil** [comment]
I'm also getting this error on MacOS:
```
(gammapy-dev) hfm-1804a:gammapy deil$ conda list | grep healpy
healpy                    1.12.2           py36h7127e17_0    conda-forge
(gammapy-dev) hfm-1804a:gammapy deil$ python -c 'import healpy'
/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/healpy/pixelfunc.py:107: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn("Warning: cannot import _healpy_pixel_lib module")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/healpy/__init__.py", line 81, in <module>
    from ._query_disc import query_disc, query_strip, query_polygon, boundaries
ImportError: dlopen(/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so, 2): Symbol not found: __ZN14T_Healpix_BaseIlE8SetNsideEl23Healpix_Ordering_Scheme
  Referenced from: /Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so
```
using this conda [environment.yml](https://github.com/gammapy/gammapy/blob/master/environment-dev.yml).

😢

**Comment by cdeil** [comment]
Is there a known workaround, e.g. downgrading to some older version?

**Comment by zonca** [comment]
yes, you can downgrade to 1.11.

I asked conda forge to remove that package, I cannot do it: https://github.com/conda-forge/healpy-feedstock/issues/15

**Comment by ludwigschwardt** [comment]
I just got hit by the missing symbol issue on macOS too (still on 10.11.6 with Apple LLVM 8... 😄).

My humble suggestion is to move to wheels, especially for macOS. It saved me lots of debugging of extremely weird system setups for python-gnureadline - see some of my journey to wheels at ludwigschwardt/python-gnureadline#46. The matplotlib maintainers have been very helpful with this.

Oops, I only saw #479 now :-)

**Comment by pkgw** [comment]
There was one more problem that surfaced in CI: the healpix_cxx configure script can try to add `-std=gnu++11` as a compiler flag, which can result in different name mangling being used for those symbols as compared to the C++ extension modules. This is probably more easily fixable by correct choice of CXXFLAGS in the build environment, and/or using a more recent compiler where the default compilation mode will use the same mangling scheme.

(Both of these problems normally would lead to link-time errors, except that Python extension modules are compiled with a flag to ignore undefined symbols since they're supposed to pick up the various symbols provided by the Python interpreter at load time.)

**Comment by bsipocz** [comment]
I've just run into this issue. Do you plan to provide wheel for the more recent versions, too, to workaround this issue? Following #479 I figured out that I specifically need to install a version where wheels were built, but it took quite a while since first saw the original traceback using 1.12.8.

**Comment by zonca** [comment]
I see macosx wheels for 1.12.8 at https://pypi.org/project/healpy/#files, is there anything wrong with those?

**Comment by zxzhai** [comment]
> On the other hand 1.12.5 works well.

Just tried, 1.12.5 worked without error
