### ISSUE TITLE
Import from six library in setup.py causes installation failure

### ISSUE THREAD

**Issue by dragoon** [healpy/healpy#456]
We are building the library on docker and the fact that the setup.py script requires import from six library which is not installed yet makes the setup crash with "ModuleNotFound" exception.

line 399 of setup.py: from six.moves import builtins

**Comment by zonca** [comment]
can you please share the Dockerfile?

**Comment by dragoon** [comment]
Yes, I cannot share the whole file, here is the most important part I guess

```
FROM python:3

# Add our code
ADD ./mylib1 /mylib1
ADD ./web.py /web.py
ADD ./tmp/mylib2 /tmp/mylib2
ADD ./tmp/assets /assets

RUN pip install /tmp/mylib2

ADD ./requirements.txt /tmp/requirements.txt

RUN pip install -qr /tmp/requirements.txt
...
```

**Comment by zonca** [comment]
can you create the simpler example I can just run to reproduce the problem
on my machine?

**Comment by zonca** [comment]
@dragoon  can you please check if #457 fixes your issue?

**Comment by dragoon** [comment]
It a bit complicated for us to test the build with a custom branch of a library, but I think this would solve the problem if I understand this correctly.

**Comment by zonca** [comment]
I merged into master

Il mar 26 giu 2018, 14:12 Roman Prokofyev <notifications@github.com> ha
scritto:
