### ISSUE TITLE
Strange results with healpy.Rotator.rotate_map

### ISSUE THREAD

**Issue by ziotom78** [healpy/healpy#460]
@NicolettaK pointed me that Planck LevelS implements a code (`cxxtools/HPXconvert_cxx.cc`) to convert polarization maps from one coordinate system to another. Therefore, I have been finally able to run some extended check on `Rotator.rotate_map`.

Here is what I did:

1. I took a CMB map and computed the EE spectrum
2. I rotated this map from Galactic to Ecliptic using `healpy.Rotator.rotate_map` (the real coordinate conversion is meaningless here, as it is a pure CMB map)
3. I rotated the same map in point 1 using `HPXconvert_cxx`
4. I computed the three power spectra using `healpy.anafast`

What I see is that maps 1 and 3 have EE spectra that look the same (apart from some lack of power in map 3 probably due to the interpolation of pixel values). But the EE spectra for map 2 looks quite different:
![corel006](https://user-images.githubusercontent.com/377795/42041448-3d128970-7af2-11e8-9a48-31a05a94e1e7.png)

I had a look at the implementation of `HPXconvert_cxx.cc`, and it seems to me that it follows the very same approach used by `Rotator.rotate_map`, so it should be something trivial.

**Comment by zonca** [comment]
can you check if #459 fixes the issue?

**Comment by ziotom78** [comment]
Yes, it does!

![ee_healpy](https://user-images.githubusercontent.com/377795/42073407-c2ae9622-7b66-11e8-99e3-f37ef14f5b96.png)

It is not completely clear to me why the spectrum of the rotated map shows a reduction in amplitude with increasing $\ell$, however: might it be due to the use of `healpy.get_interp_val`?

**Comment by ziotom78** [comment]
Ok, finally I was able to run the test. Here is what I did:

- I created a Cl spectrum using CAMB (with r=0, so no B-modes)
- I used `healpy.synfast` to produce *two* maps from the Cl, one with `NSIDE=128` and another with `NSIDE=512`
- I rotated both maps (using `healpy.Rotator(coord=`EG`)`)
- I compared the five power spectra: the one from CAMB, the two for the *unrotated* maps, and the two for the *rotated* maps.

Results show that rotation does not affect TT, but it affects E/B mode computation by introducing some E->B leakage: E-mode spectrum is damped, while B-mode polarization appears.

![tt](https://user-images.githubusercontent.com/377795/42359611-3e288e30-80e3-11e8-9adf-dbe6a9db8f75.png)
![ee](https://user-images.githubusercontent.com/377795/42359610-3e0c718c-80e3-11e8-9fc3-53b196089e22.png)
![bb](https://user-images.githubusercontent.com/377795/42359609-3de893f2-80e3-11e8-9f66-7906570027b5.png)

As a reference, here is the result from LevelS: the leakage is only present in the `NSIDE=128` case, and it is much smaller.

![levelstt](https://user-images.githubusercontent.com/377795/42360084-bd899798-80e6-11e8-93f1-a4274e5bcb0a.png)
![levelsee](https://user-images.githubusercontent.com/377795/42360083-bd6d5542-80e6-11e8-818b-200d5729ab51.png)
![levelsbb](https://user-images.githubusercontent.com/377795/42360082-bd4cbd82-80e6-11e8-86b6-3a04242665a6.png)

Here is the relevant part of the code in LevelS which implements the transformation:
```c++
 Healpix_Map<float> inmapT, inmapQ, inmapU;
 read_Healpix_map_from_dmc(infile,inmapT,inmapQ,inmapU);
 Healpix_Map<float> outmapT (inmapT.Nside(), inmapT.Scheme(), SET_NSIDE),
                    outmapQ (inmapT.Nside(), inmapT.Scheme(), SET_NSIDE),
                    outmapU (inmapT.Nside(), inmapT.Scheme(), SET_NSIDE);

 for (int m=0; m<inmapT.Npix(); ++m)
   {
   pointing pt = outmapT.pix2ang(m), pt2;
   double dpsi;
   tr.rotatefull(pt,pt2,dpsi);
   fix_arr<int,4> pix;
   fix_arr<double,4> wgt;
   inmapT.get_interpol(pt2,pix,wgt);
   outmapT[m] = inmapT.interpolation(pix,wgt);
   float valq = inmapQ.interpolation(pix,wgt),
         valu = inmapU.interpolation(pix,wgt);
   outmapQ[m] = float(cos(2*dpsi)*valq + sin(2*dpsi)*valu);
   outmapU[m] = float(cos(2*dpsi)*valu - sin(2*dpsi)*valq);
   }
 write_Healpix_map_to_dmc(outfile, outmapT, outmapQ, outmapU);
```

Object `tr` is of type `Trafo`, and it is implemented in `cxxsupport/trafos.cc`. It relies on function `orientation` (in `geom_utils.h`):
```c++
/*! Returns the orientation when looking from point \a loc on the unit
    sphere in the direction \a dir. \a loc must be normalized. The result
    ranges from -pi to pi, is 0 for North and pi/2 for West, i.e. the angle
    is given in mathematically positive sense.

    If \a loc is the North or South pole, the returned angle is
    \a atan2(dir.y,dir.x). */
inline double orientation (const vec3 &loc, const vec3 &dir)
  {
// FIXME: here is still optimization potential
  if (loc.x==0 && loc.y==0)
    return (loc.z>0) ? safe_atan2(dir.y,-dir.x) : safe_atan2(dir.y,dir.x);
  vec3 east (-loc.y, loc.x, 0);
  vec3 north = crossprod(loc,east);
  return safe_atan2(-dotprod(dir,east),dotprod(dir,north));
  }
```
This is used in `Trafo::rotatefull`:
```c++
void Trafo::rotatefull (const pointing &ptg, pointing &newptg,
  double &delta_psi) const
  {
  vec3 vec (ptg);
  vec3 east (-vec.y,vec.x,0.);
  vec3 newvec = operator()(vec);
  vec3 neweast = operator()(east);
  delta_psi = orientation(newvec,neweast)+halfpi;
  newptg = newvec;
  }

void Trafo::rotatefull (const vec3 &vec, vec3 &newvec, double &delta_psi) const
  {
  vec3 east (-vec.y,vec.x,0.);
  newvec = operator()(vec);
  vec3 neweast = operator()(east);
  delta_psi = orientation(newvec,neweast)+halfpi;
  }
```

**Comment by mreineck** [comment]
No, the proposed alternative interpolation would not be a good choice in this concrete case.

It requires knowledge of the C_l (and therefore the a_lm), and if these are known, then we already have the perfect way to rotate the map: just rotate the a_lm and run alm2map.
(As far as I understand, this wouldn't be any slower than the proposed interpolation method.)

Generally: if a high-quality rotated map is needed, this can only be done if the map is band-limited. And if it is band-limited, there is no reason not to go via harmonic space.

**Comment by mreineck** [comment]
BTW, LevelS also contains a code called `rotmap_cxx`, which does the rotation via harmonic space, so you may want to give it a try.

**Comment by ziotom78** [comment]
Thanks for the hint, @mreineck , I wasn't aware of the existence of `rotmap_cxx`. I think that it would be really useful to have both methods to rotate a map in `healpy`: it's true that going through harmonic space would save us from E/B mixing, but a pixel-space code has the advantage of being easy to use with partial maps.

**Comment by ziotom78** [comment]
Oh, I wasn't advocating the implementation of Lavaux&Wandelt, my desire was only to improve the current implementation of `rotate_map` (using the same approach as LevelS) alongside the implementation of a new function which performs rotations on the harmonic space.

**Comment by mreineck** [comment]
Ah, OK! :)
