### ISSUE TITLE
Issue in Healpy 1.12.2 import (MacOS)

### ISSUE THREAD

**Issue by StanisLaRochelle** [healpy/healpy#463]
I have an issue while importing the Healpy package after upgrading to 1.12.2 with Conda. Now it returns the following error:

![screen shot 2018-07-02 at 15 57 29](https://user-images.githubusercontent.com/35338641/42168211-a695049c-7e10-11e8-914e-eb716c7377be.png)

Any ideas of where can it arise from? I tried with uninstalling and re-installing the package but the result is still the same..

Thank you!

**Comment by kjacks21** [comment]
I just want to second this issue. I just installed via conda-forge on MacOS and getting the same exact error.

**Comment by zonca** [comment]
yes, see #455, in the thread there is also a suggestion on how to fix it building from source.
Unfortunately we don't know yet how to fix this.

Also, there must be a bug in conda-forge, those broken packages failed the tests and shouldn't have been posted on conda-forge.
