### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by DanielLenz** [healpy/healpy#468]
Similar to the discussion in the astropy community (https://github.com/astropy/astropy/issues/6234), it would make sense to develop a healpy version (say 1.13) that drops support for python 2.x.

Just blatantly stealing their to-do list:

- [x] Remove __future__ imports
- [x] Make sure we remove the unicode_literals text fixture
- [x] Search for and remove any 'six' imports and in some cases replace by the appropriate Python 3 import.
- [x] Search for and remove any if six.PY2 blocks and also search for sys.version_info or any usage of minversion or Looseversion.
- [x] Update CI configuration to not run tests on Python 2
- [x] Search for comments that mention Python (either 2 or 3 or none of them) to see if anything can be updated
- [ ] Remove python2 related info from the documentation

**Comment by DanielLenz** [comment]
I've started a branch that removes all items related to python2 [here](https://github.com/DanielLenz/healpy/tree/python3only).

**Comment by DanielLenz** [comment]
Closing this for now because python2.7 support is likely to critical to drop yet. Happy to re-open once we decide to take that step.

**Comment by DanielLenz** [comment]
Given the recent discussions about Python2 support in the PyData Universe, I thought it would be good to re-open this and to discuss our strategy for dropping Python 2.

Here's a list of all the projects that [will do this before 2020](https://python3statement.org/#sections30-projects).

Some questions:
- Can we afford to remove Python2 in the next months, are there any major drawbacks to that?
- What changes need to be made? I think the list in the first post is still correct, there isn't too much work to be done.
- Which min. Python3 version should we go with? 3.5, 3.6?
- Should we have a major release (X.0) or a minor (1.XX) release for that?

**Comment by zonca** [comment]
I think that we can wait for now, the only thing I am worried about is if we need any feature of astropy 3 that is not available in astropy 2.

But for now I think we do not have any pressing issue and we can evaluate this again in the summer.

**Comment by zonca** [comment]
@DanielLenz I'll take care of this one starting from your branch

**Comment by lpsinger** [comment]
Python 2 is now well past end of life. Can we please revisit this one?

**Comment by zonca** [comment]
ok @lpsinger, do you want to take care of it? otherwise I will

**Comment by lpsinger** [comment]
Please go ahead. I would also suggest dropping Python 3.4, which is past end of life and getting difficult to support.

**Comment by zonca** [comment]
implement in #658
