### ISSUE TITLE
flexible set parameters of subgraph

### ISSUE THREAD

**Issue by FriendsJessica** [healpy/healpy#472]
Hello! I want to plot many subgraphs in one figure. How to:
1. set the position of the colorbar
2. set the tick and ticklabel of colorbar
3. set the position and size of the subgraph
I want to plot figure like this 
    
![1](https://user-images.githubusercontent.com/38579624/43531203-e6885930-95e1-11e8-8a47-7f0c0c8848c1.png)
but usually I just plot like this 
![tim 20180801232437](https://user-images.githubusercontent.com/38579624/43531313-16355b88-95e2-11e8-8624-ce4e704b4a08.png)
Could anyone help me out?
A similar python code and its' result are as follow:
     import numpy as np
import healpy as hp
degree=4
NSIDE =2**degree
Num_Pixel=hp.nside2npix(NSIDE)
m=np.arange(Num_Pixel)
Margins=[[0.02,0,0,0],[0.01,0,0,0],[0.01,0,0.01,0],\
         [0.02,0,0,0],[0.01,0,0,0],[0.01,0,0.01,0],\
         [0.02,0.05,0,0],[0.01,0.05,0,0],[0.01,0.05,0.01,0]]
Title=['Equinox','Jun. Solstice','Dec. Solstice',\
       '','','','','','']
for ifig in range(1,10):
    if ifig<7:
       hp.cartview(m,sub=330+ifig,margins=Margins[ifig-1],cbar=False,title=Title[ifig-1])
    else:
       hp.cartview(m,sub=330+ifig,margins=Margins[ifig-1],cbar=True,title=Title[ifig-1])
       

![tim 20180801232732](https://user-images.githubusercontent.com/38579624/43531519-869bd118-95e2-11e8-97e8-cd6904d8aba9.png)
    
I wander could we plot each subgraph at chosen axes to deal with this problem, I have tried subplot(3,3,ifig), but it fails!
Thanks help!

**Comment by zonca** [comment]
sorry we don't have resources to provide support for plotting issues.
please try to post to stackoverflow.com with the `healpy` tag and hope somebody will answer there.
