### ISSUE TITLE
Add Daniel Lenz as maintainer

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#477]
@lpsinger @mreineck  @crosset 

I would like to add @DanielLenz as a new maintainer on `healpy`.
He already contributed several Pull Requests and is working on a couple more: <https://github.com/healpy/healpy/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Adaniellenz>

Please let me know if you have any feedback, otherwise I'll add him next week.

**Comment by DanielLenz** [comment]
Thanks, really looking forward to learn more about the package and to contribute to its development!

**Comment by zonca** [comment]
@DanielLenz I added you to the `Core` team, welcome!!
