### ISSUE TITLE
Build binary wheels

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#479]
Generate universal binary wheels for Linux and macOS and upload to PyPI. It should be possible to have Travis automate this process upon release. This would go a long way to making it easier to install healpy by making it unnecessary to build from source.

It may even be possible to build for Windows using Appveyor.

**Comment by mreineck** [comment]
Just curious: is it possible to install different wheels depending on whether the target computer supports AVX? If not, many people will lose a factor 2 in performance when running SHTs.

**Comment by ludwigschwardt** [comment]
I had a quick look at what other people did for TensorFlow, e.g. https://github.com/mind/wheels.

This suggests that the standard wheels would be the lowest common denominator without AVX support (at least on Linux with manylinux1 -  macOS might be easier to upgrade to AVX). Performance-sensitive users could still install specific AVX wheels via pip, it seems.

**Comment by lpsinger** [comment]
> Just curious: is it possible to install different wheels depending on whether the target computer supports AVX? If not, many people will lose a factor 2 in performance when running SHTs.

No. If performance is essential, then the best approach would be to have the optimal code path for the current architecture selected at runtime.

**Comment by mreineck** [comment]
> If performance is essential, then the best approach would be to have the optimal code path for the current architecture selected at runtime.

Starting from the next Healpix C++ version, I might be able to provide this (if gcc/g++ is used).

**Comment by lpsinger** [comment]
Here are instructions for macOS + MacPorts:

```
sudo port -N install py{27,35,36,37}-{matplotlib,numpy,six,astropy,scipy,pytest-runner,six,setuptools,pip,wheel}
for PIP in pip-{2.7,3.5,3.6,3.7}; do $PIP wheel --no-deps healpy==1.12.4; done
python3.7 -m venv --system-site-packages delocate
source delocate/bin/activate
pip install delocate
for WHEEL in *.whl; do delocate-wheel -w wheelhouse $WHEEL; done
```

In both the Linux and macOS cases, upload all of the files in the `wheelhouse` directory to PyPI (e.g. using [`twine`](https://twine.readthedocs.io/)).

**Comment by zonca** [comment]
@lpsinger are you `lsinger` on PYPI? @DanielLenz what is your PYPI username?
I'm going to add you as owners on the `healpy` package

**Comment by lpsinger** [comment]
> @lpsinger are you `lsinger` on PYPI?

Yes, I'm lsinger on PyPI. Would you like me to upload the wheels for this release?

I'm eager to get the wheels uploaded because we have a LIGO science outreach event coming up and these will make it much easier for people to install Healpy. In a future release, we can work on automating the wheels using CI/CD.

**Comment by zonca** [comment]
yes of course, please go ahead

**Comment by DanielLenz** [comment]
Thanks, I'm DanielLenz on PyPI

**Comment by lpsinger** [comment]
I've [uploaded wheels to testpypi](https://test.pypi.org/project/healpy/#files). Please try them out in your favorite Linux or macOS Python environment:

    pip install --index-url=https://test.pypi.org/simple healpy

**Comment by zonca** [comment]
I have an issue in a clean conda env on linux with just python 3.6 and numpy,

```
pip install --index-url=https://test.pypi.org/simple healpy
Looking in indexes: https://test.pypi.org/simple
Collecting healpy
  Downloading https://test-files.pythonhosted.org/packages/04/b5/8c95cbea93098dd9b69766002dd1c5184031d560b58d048ed7421e01d68d/healpy-1.12.4-cp36-cp36m-manylinux1_x86_64.whl (13.6MB)                                                                                       100% |################################| 13.6MB 1.2MB/s 
Collecting six (from healpy)
  Downloading https://test-files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz                                                                                                                         Collecting astropy (from healpy)
  Downloading https://test-files.pythonhosted.org/packages/13/04/279627b71a95358b954fcd05ca64ced7ec20aca8bcde852e20ef30529531/astropy-1.0.1.post1.dev12058.tar.gz (7.7MB)                                                                                                   100% |################################| 7.7MB 3.6MB/s 
Collecting scipy (from healpy)
  Downloading https://test-files.pythonhosted.org/packages/68/72/eb962a3ae2755af6b1f31f7a94dccc21bfc41bb1637c5877a043e711b1d7/scipy-0.1.tar.gz                                                                                                                          Collecting matplotlib (from healpy)
  Could not find a version that satisfies the requirement matplotlib (from healpy) (from versions: )
No matching distribution found for matplotlib (from healpy)
```

instead if I have `matplotlib` already installed no problem.

**Comment by zonca** [comment]
Yeah that was it

**Comment by lpsinger** [comment]
What OS and Python distribution did you test?

**Comment by zonca** [comment]
Linux Python 3.6 Anaconda

**Comment by lpsinger** [comment]
On macOS, I got the following error:

```
/tmp/miniconda/envs/hp/lib/python3.7/site-packages/healpy/pixelfunc.py:107: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn("Warning: cannot import _healpy_pixel_lib module")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/miniconda/envs/hp/lib/python3.7/site-packages/healpy/__init__.py", line 81, in <module>
    from ._query_disc import query_disc, query_strip, query_polygon, boundaries
ImportError: dlopen(/tmp/miniconda/envs/hp/lib/python3.7/site-packages/healpy/_query_disc.cpython-37m-darwin.so, 2): Symbol not found: __ZN14T_Healpix_BaseIlE8SetNsideEl23Healpix_Ordering_Scheme
  Referenced from: /tmp/miniconda/envs/hp/lib/python3.7/site-packages/healpy/_query_disc.cpython-37m-darwin.so
  Expected in: flat namespace
 in /tmp/miniconda/envs/hp/lib/python3.7/site-packages/healpy/_query_disc.cpython-37m-darwin.so
```

Rebuilding using `CC=gcc-mp-8 CXX=g++-mp-8` from MacPorts worked, though. I think that this had something to do with which C++ standard library is in use. Would be good to actually understand this...

**Comment by lpsinger** [comment]
Uploaded to PyPI.

**Comment by zonca** [comment]
posted instructions to permanent place https://github.com/healpy/healpy/pull/508
@lpsinger should we close this?
