### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by gregreen** [healpy/healpy#483]
I can't find any correct information on how to install `healpy` any more. The pip installation seems to be broken (on Ubuntu 16.04, Ubuntu 18.04, CentOS 6 and OSX), and building from source fails as well. Both methods fail with the message, `configure: error: cannot run C compiled programs`. I've tried this on several computers, running different operating systems, and also heard from others that they run into the same installation problems.

Is there a procedure that is known to work right now?

**Comment by zonca** [comment]
What about conda?

**Comment by gregreen** [comment]
That's the one method I'd really like to avoid using, since I don't generally use `conda`. I was hoping there was a more vanilla installation method, either building from source or using `pip`.

**Comment by zonca** [comment]
Getting the right configuration for the compilers is getting more complex with new compilers, I don't know why.
We will try to provide pip wheels, there is another open issue about that, you might want to subscribe to it.
Until then, the current installation instructions to build from source work fine for vanilla Ubuntu 16.04 systems. Where the environment is more complicated you need to experiment with changing the compiler used by Python to build the extension

**Comment by gregreen** [comment]
I'm on a fresh installation of Ubuntu 18.04, but when I run `python3 setup.py install` in a virtual environment, I get an error like this:

    /bin/sh /home/greg/Downloads/healpy-1.12.3/cfitsio/configure --prefix=/home/greg/Downloads/healpy- 
    1.12.3/build/temp.linux-x86_64-3.6 --disable-shared --with-pic --disable-maintainer-mode
    configure: WARNING: unrecognized options: --disable-shared, --with-pic, --disable-maintainer-mode
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for gcc... x86_64-linux-gnu-gcc -pthread
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/home/greg/Downloads/healpy- 
    1.12.3/build/temp.linux-x86_64-3.6/cfitsio':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.

Any idea what's going wrong?

**Comment by zonca** [comment]
See https://github.com/healpy/healpy/issues/432

**Comment by gregreen** [comment]
Thanks. This worked:

    CC=gcc CXX=g++ CFLAGS='-fPIC' CXXFLAGS='-fPIC' python3 setup.py build
    CC=gcc CXX=g++ CFLAGS='-fPIC' CXXFLAGS='-fPIC' python3 setup.py install

**Comment by zonca** [comment]
thanks, can you please make a Pull Request to add this as a suggestion to the installation documentation?
