### ISSUE TITLE
Smoothing maps with nside > 8192

### ISSUE THREAD

**Issue by j-erler** [healpy/healpy#484]
Hello,

I recently encountered an overflow error when smoothing large all-sky maps with nside = 16384. I posted the exact error message further below. My best guess is that the number of pixels in the map exceeds the largest allowed 32 Bit integer. The error occurs in the C++ backend of sphtools. I could not find any mention of a maximum allowed nside for smoothing in the documentation. A fix would be very welcome.

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-26-8263d6ac3959> in <module>()
----> 1 all_sky_map_smoothed = hp.sphtfunc.smoothing(all_sky_map, fwhm = fwhm_rad, lmax = 2*16384-1, iter = 0)

/home/Anaconda3-5.0.1/lib/python3.6/site-packages/healpy/pixelfunc.py in wrapper(map_in, *args, **kwds)
    261         return_ma = is_ma(map_in)
    262         m = ma_to_array(map_in)
--> 263         out = f(m, *args, **kwds)
    264         return ma(out) if return_ma else out
    265 

/home/Anaconda3-5.0.1/lib/python3.6/site-packages/healpy/sphtfunc.py in smoothing(map_in, fwhm, sigma, beam_window, pol, iter, lmax, mmax, use_weights, datapath, verbose)
    744         alms = map2alm(map_in, lmax = lmax, mmax = mmax, iter = iter,
    745                        pol = pol, use_weights = use_weights,
--> 746                        datapath = datapath)
    747         smoothalm(alms, fwhm = fwhm, sigma = sigma, beam_window = beam_window,
    748                   inplace = True, verbose = verbose)

/home/Anaconda3-5.0.1/lib/python3.6/site-packages/healpy/sphtfunc.py in map2alm(maps, lmax, mmax, iter, pol, use_weights, datapath, gal_cut)
    157         alms = _sphtools.map2alm(maps, niter = iter,
    158                                  datapath = datapath, use_weights = use_weights,
--> 159                                  lmax = lmax, mmax = mmax, gal_cut = gal_cut)
    160     else:
    161         # info >= 2 and pol is False : spin 0 spht for each map

healpy/src/_sphtools.pyx in healpy._sphtools.map2alm (healpy/src/_sphtools.cpp:4335)()

healpy/src/_sphtools.pyx in healpy._sphtools.mkmask (healpy/src/_sphtools.cpp:9080)()

OverflowError: value too large to convert to int

**Comment by DanielLenz** [comment]
I should look into this in a bit more detail, but I strongly suspect that this is because the ring weights used for the smoothing are only being provided for an nside of up to (and including) 8192.

Totally agree that we should make sure it exists more gracefully, though. For that, we also need the bookkeeping on which operations can be performed up to which nside.

**Comment by mreineck** [comment]
I don't know what exactly happens in the Cython part of healpy, but if it uses the `Healpix_Map` type of Healpix C++ internally, it will only work up to an Nside of 8192. Memory-resident full-sky maps of higher resolution are not foreseen in Healpix C++. They can be added very easily, but so far I was not aware of any experiment requiring them.

**Comment by j-erler** [comment]
Thanks for the responses. Having the capability of working with maps with Nside > 8192 is very useful for mapping and  processing high resolution surveys with large sky coverage on the sphere. For my particular application that involves the GMRT TGSS data I can think of a work around, but it would be helpful to at least add the maximum Nside to the documentation like DanielLenz suggested.

**Comment by DanielLenz** [comment]
What would be the best location to implement the checks and to document the nside limitation?  Feels redundant to add it to every function in `sphtfunc.py`, but it might be more straightforward than adding it to the C++ or the cython layer.

**Comment by mreineck** [comment]
The C++ classes already perform this kind of check in the constructor (at least if Nside is a power of 2, as is the case here), so I expect that the exception happens before the call into the C++ library.

I think the Nside check would need to go at the beginning of the public functions of sphtfunc.py, in a very similar fashion to how it's done in pixelfunc.py (just with a reduced maximum Nside of 8192).

**Comment by DanielLenz** [comment]
Thanks @mreineck , I've implemented the checks.
