### ISSUE TITLE
Feature request: hotspot

### ISSUE THREAD

**Issue by javicarron** [healpy/healpy#493]
I have noticed that this F90 facility provided by HEALPix is not implemented in healpy. The (short) documentation is in [https://healpix.jpl.nasa.gov/html/facilitiesnode8.htm](https://healpix.jpl.nasa.gov/html/facilitiesnode8.htm).

This is a function that takes a map as input and reports the location (and value) of the maxima and minima. I think it uses the nearest neighbours function that is already implemented in healpy, but I do not know enough to translate the code.

Maybe it is not worth it to implement it, but I just wanted to let you know in case this is useful and someone wants to have a look at it.

**Comment by zonca** [comment]
implemented in #593
