### ISSUE TITLE
Support pathlib for i/o

### ISSUE THREAD

**Issue by DanielLenz** [healpy/healpy#500]
The preferred way to handle paths in python>=3.4 is by using [pathlib](https://docs.python.org/3.6/library/pathlib.html).

```python

from pathlib import Path

path = Path('/home/data/')

hpxmap = hp.read_map(
    path.joinpath('myfile.fits')
)
```

If we try to use `hp.read_map()` with a `Path` object, it is not parsed correctly and an exception is raised:

    TypeError: First argument should be a input_data, HDUList instance, or HDU instance

It would be great to add that functionality for any I/O functions. I have a lot on my plate right now, but can look into this once that changes.

**Comment by lpsinger** [comment]
It might make more sense to make this work at the level of astropy.io.fits.

**Comment by DanielLenz** [comment]
I've already looked into this, the problem is that we explicitly check if the filename is one of `six.str_types`.

Below is a fix to that, for which I still have to add tests and documentation.

```bash

import six
+import sys
 import warnings
+
+if sys.version >= "3.4":
+    import pathlib
 import astropy.io.fits as pf
 import numpy as np

@@ -607,8 +611,11 @@ def _get_hdu(input_data, hdu=None, memmap=None):
     fits_hdu : HDU
         The extracted HDU
     """
+    allowed_paths = tuple(six.string_types)
+    if sys.version >= "3.4":
+        allowed_paths += (pathlib.Path, pathlib.PosixPath)

-    if isinstance(input_data, six.string_types):
+    if isinstance(input_data, allowed_paths):
         hdulist = pf.open(input_data, memmap=memmap)
         return _get_hdu(hdulist, hdu=hdu)

@@ -624,7 +631,7 @@ def _get_hdu(input_data, hdu=None, memmap=None):
         fits_hdu = input_data
     else:
         raise TypeError(
-            "First argument should be a input_data, HDUList instance, or HDU instance"
+            "First argument should be a input_data (str or pathlib.Path), HDUList instance, or HDU instance"
         )

     return fits_hdu

```

**Comment by DanielLenz** [comment]
Merged in https://github.com/healpy/healpy/pull/523
