### ISSUE TITLE
Dynamic AVX support for SHTs 

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#502]
This is just a heads-up for a feature I'm working on...

So far binary releases of Healpix C++ had the problem that they could only support SSE2 on 64bit platforms in order to be portable. This meant a performance loss of roughly a factor 2 for SHTs if the target CPU actually supports AVX.

After some messing around I think I'm now able to produce portable binaries which dynamically switch to AVX if it is present on the executing CPU. As you can imagine, this can go wrong in many ways, so I would need volunteers to test this on as many configurations as possible. Anyone interested?

**Comment by mreineck** [comment]
No one available to give it a go? This should be of particular interest since we are providing binary wheels now. @lpsinger?
Anyway, I'm attaching an experimental distribution tarball of Healpix C++.


[healpix_cxx-3.49.0.tar.gz](https://github.com/healpy/healpy/files/2548088/healpix_cxx-3.49.0.tar.gz)

**Comment by lpsinger** [comment]
Is this in svn as well?

**Comment by lpsinger** [comment]
How portable is the __builtin_cpu_supports intrinsic across clang, icc, pgi, etc.?

**Comment by mreineck** [comment]
Besides gcc, no other compiler should get to see this code ... unless it defines __GNUC__ to be >=5 and __x86_64__, in which case it would be a compiler bug if it didn't understand the statements.

I tried with a few different icc and clang versions, which ignore the code as expected.

**Comment by mreineck** [comment]
It seems that there might be a new Healpix release in roughly a week from now - mostly for bug fixes in the Fortran part, but we could use the occasion to slip this feature in as well.

Any opinions?

**Comment by zonca** [comment]
can we test if this runs on travis fine?

**Comment by mreineck** [comment]
Travis will run the tests on some emulated hardware, I guess. Not sure whether this hardware provides AVX.
In any case, as long as the currently existing tests don't fail, the patch at least won't hurt. So if everything runs as it did so far, I'd vote to switch to the new release.

**Comment by zonca** [comment]
thanks @mreineck, could you create a branch on
https://github.com/healpy/healpixmirror with that code?
then I can create a PR on healpy and test the build on travis

**Comment by mreineck** [comment]
Sure. But I don't know what the policy for this package is...
The code in question is on `trunk` in the Healpix main repository; does that mean I can put it on the `trunk` of `healpixmirror` as well? Or will I break something by doing that?

**Comment by zonca** [comment]
ok, this is now in 1.12.6 and .7

**Comment by lpsinger** [comment]
I'm working on building and testing the wheels. I've hit a snag on macOS:

```
    CC       libsharp/sharp_core_avx.lo
  {standard input}:42:no such instruction: `vzeroupper'
  {standard input}:97:no such instruction: `vmulpd %ymm2, %ymm0,%ymm4'
  {standard input}:169:no such instruction: `vbroadcastsd (%rax), %ymm3'
  {standard input}:176:no such instruction: `vmulpd %ymm3, %ymm4,%ymm4'
  {standard input}:183:no such instruction: `vbroadcastsd 8(%rax), %ymm3'
  {standard input}:193:no such instruction: `vmulpd %ymm1, %ymm3,%ymm1'
  {standard input}:200:no such instruction: `vsubpd %ymm1, %ymm4,%ymm4'
  {standard input}:245:no such instruction: `vbroadcastsd (%rax), %ymm1'
  {standard input}:252:no such instruction: `vmulpd %ymm4, %ymm0,%ymm5'
  {standard input}:257:no such instruction: `vmulpd %ymm1, %ymm5,%ymm5'
...
```

It appears that the [standard assembler on macOS does not support AVX instructions](https://stackoverflow.com/questions/9840207/how-to-use-avx-pclmulqdq-on-mac-os-x). I am trying some of the workarounds suggests on that post.

**Comment by mreineck** [comment]
Oh ... does that mean that builds with "-march=native" on macOS did not work at all so far (if the CPU supported AVX)?

**Comment by lpsinger** [comment]
Yes, that's right. But we definitely wouldn't want to build wheels with `-march=native` anyway.

**Comment by mreineck** [comment]
Absoutely! I was just thinking about people doing manual, optimized builds.

**Comment by lpsinger** [comment]
OK, that worked. I updated RELEASE.md to document the necessary compiler flags.
