### ISSUE TITLE
Import errors on Python 3.6 and 2.7 but not on 3.4 and 3.5

### ISSUE THREAD

**Issue by msyriac** [healpy/healpy#505]
I help maintain a library that depends on healpy and installs the latest version from PyPI. Recently, with healpy 1.12.4, our builds stopped working but only for Python versions 3.6 and 2.7, and not for 3.4 and 3.5. In these builds, healpy installs without error, but the following import error occurs when healpy is imported for 3.6 and 2.7 (I attach the relevant part of the traceback for 2.7):
https://pastebin.com/1XF7dHqE

I can confirm this doesn't happen for healpy 1.12.3.

**Comment by zonca** [comment]
We just created some wheels for healpy, can you test to install with
--no-binary to disable prebuilt wheels?

**Comment by msyriac** [comment]
Yes, that works, and all tests (including those that call healpy functions) pass. It would be great if the pre-built wheels worked out of the box since healpy is usually the longest compile step. 
Thanks!

**Comment by zonca** [comment]
Can you please post which version of numpy you were using when it was
failing?

**Comment by msyriac** [comment]
I can't check manually since the failing builds were on travis. Here are the raw logs for two failed builds.
Python 2.7: https://api.travis-ci.org/v3/job/450647286/log.txt
Python 3.6: https://api.travis-ci.org/v3/job/450647283/log.txt
(not sure how long those logs will live)

**Comment by lpsinger** [comment]
I think that what we need to do is build the wheels using the oldest version of Numpy that we support. What is the minimum version of Numpy that we require?

**Comment by zonca** [comment]
let's use 1.13, it is requirement for astropy
https://github.com/astropy/astropy/blob/master/pip-requirements
and it was caused issues in the travis logs reported here.

**Comment by lpsinger** [comment]
Could we do a release today please? We are going to have a LIGO/Virgo science outreach event on November 15 and will likely be introducing some new people to Healpy.

**Comment by zonca** [comment]
ok, I'll do the tagging on github than you can do the release on Pypi

**Comment by lpsinger** [comment]
Please go ahead and do the source release on PyPI too. I will do the binary wheel upload for PyPI.

**Comment by zonca** [comment]
see the same numpy error on Travis:

https://travis-ci.org/healpy/healpy/jobs/454717287

just on Python 2.7, just with external CFITSIO

**Comment by msyriac** [comment]
Yes, all builds pass now even after switching to wheel. Thanks!

**Comment by zonca** [comment]
thanks @lpsinger and @msyriac
