### ISSUE TITLE
Smoothing produces unexpected results at edges

### ISSUE THREAD

**Issue by ezavarygin** [healpy/healpy#509]
I get an unexpected result with hp.smoothing in case of the incomplete sky coverage. Below is a simple example that illustrates of the problem. 
The input map has 1 in all pixels that belong to the two patches. Other "empty" pixels are set to hp.UNSEEN and are shown with the grey colour in the figures below. The input (unsmoothed) and two maps smoothed with FWHM=7 and 30 degrees are shown below:
![1](https://user-images.githubusercontent.com/18361119/48542220-a5108e00-e8cf-11e8-9478-8fc0ae8229f6.png)
![2](https://user-images.githubusercontent.com/18361119/48542237-b0fc5000-e8cf-11e8-9784-22c34f2efab4.png)
![3](https://user-images.githubusercontent.com/18361119/48542263-c5d8e380-e8cf-11e8-8be0-e80488e7d538.png)
I would expect to see 1 (or very close to it) in the smoothed maps in all the pixels that belong to the two patches but clear edge artefacts are seen. Am I missing something?

**Comment by mreineck** [comment]
This is actually expected. Smoothing is applied by convolution in the harmonic domain, and all undefined pixels are set to 0, so you see a drop in values towards the edge.

Performing the smoothing in pixel space would be a very expensive operation.

**Comment by mreineck** [comment]
I don't know how to correct for this in general. However, if your partial map is more or less uniform, you might subtract the average before smoothing and re-add it afterwards...

**Comment by ezavarygin** [comment]
Yes, right. It would be nice to have an option for setting this filling value manually as an argument of hp.smoothing() rather than have it hard-coded. Setting this value to the average would be equivalent to the workaround that you suggested. In any case, thanks for your explanation. I am closing this issue.

**Comment by mreineck** [comment]
At such a point I would really prefer if the routine would simply refuse to run in the presence of undefined pixels and raise an exception that explains why. Then the user could fix the map in the way that is appropriate for the given problem. Silently doing something "clever" will always take people by surprise at some point, but this seems to be the Python way of doing things :-/

**Comment by DanielLenz** [comment]
I've been using the following to smooth a masked map with non-zero mean (effectively using weights):

```python
def masked_smoothing(map_in, fwhm_deg):
    """Smooth a map in which a mask is represented by `np.nan` in the map.
    In this function, these masked regions are ignored and not set to zero,
    which would be the default for the healpy smoothing function.

    Parameters
    ----------
    map_in : 1D array
        Input HEALPix map, must have valid nside. Masked values must be set to
        np.nan.
    fwhm_deg : float
        Smoothing kernel as FWHM in degrees.

    Returns
    -------
    map_out : 1D array, same dtype and shape as map_in
        Smoothed map
    """
    V = map_in.copy()
    V[np.isnan(map_in)] = 0
    VV = hp.smoothing(V, fwhm=np.radians(fwhm_deg), verbose=False)
    W = np.ones_like(map_in)
    W[np.isnan(map_in)] = 0
    WW = hp.smoothing(W, fwhm=np.radians(fwhm_deg), verbose=False)

    map_out = VV / WW

    return map_out
```

**Comment by mreineck** [comment]
Very interesting approach! But shouldn't `map_out` be masked again at the end? Otherwise you might get very interesting patterns in the masked area :)

**Comment by DanielLenz** [comment]
Thanks, good point, slightly modified the function above!
I've always done that outside the function, but this is much saver.

**Comment by ezavarygin** [comment]
Thanks Daniel for sharing your solution! The map in the figures is just a made up example to illustrate the edge effect. I noticed that issue in real data with non-zero mean.
