### ISSUE TITLE
undefined symbol: __cpu_model error

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#516]
`readthedocs` fails with:

```
ImportError: /home/docs/checkouts/readthedocs.org/user_builds/healpy/envs/stable/local/lib/python2.7/site-packages/healpy-1.12.6-py2.7-linux-x86_64.egg/healpy/_healpy_sph_transform_lib.so: undefined symbol: __cpu_model
```

See full log:
https://readthedocs.org/projects/healpy/builds/8204487/

I guess this is related to the new AVX code, it wasn't failing before, @mreineck any suggestion?

**Comment by mreineck** [comment]
Was this built with gcc 5? I find similar reports on the net; things should be fixed starting with gcc 6.
If necessary, I can change the code so that dynamic AVX only triggers with version 6 or later.

**Comment by mreineck** [comment]
BTW, the oldest gcc version maintained by GNU is gcc 7...

**Comment by zonca** [comment]
thanks @mreineck, if that is not too complicated can you please add it?

**Comment by mreineck** [comment]
It's now in, revision 1003.

**Comment by mreineck** [comment]
So, does that mean this is needed in Healpix C++ 3.50?
If so, will there be a healpy 1.12.8 that we should include in the 3.50 release?

**Comment by zonca** [comment]
This is mostly affecting only read the docs so I don't think we need to release another version of healpy. Unless you prefer me to do that anyway it doesn't take much.

**Comment by hivon** [comment]
Hi Andrea,
I have been postponing the Healpix release all day to know that answer...
Can you make the healpy 1.12.8 release so that it is ready for me to pack on Monday morning (Paris time) ?

**Comment by zonca** [comment]
sorry @hivon, I feel guilty you passed all day staring hopelessly at the screen due to my negligence to read email between 1am and 8am...
I'll release 1.12.8 today or tomorrow.

**Comment by zonca** [comment]
1.12.8 released
