### ISSUE TITLE
Using an old header from NumPy

### ISSUE THREAD

**Issue by mattip** [healpy/healpy#520]
In [_healpy_pixel_lib.cc](https://github.com/healpy/healpy/blob/master/healpy/src/_healpy_pixel_lib.cc#L36) you include `numpy/noprefix.h`. I am trying to deprecate that file, and your code came up as one that uses it. Could you try replacing that file with `numpy/ndarrayobject.h`? This may require changing some of the "bare" numpy typedefs by adding the prefix `npy_`.

xref numpy/numpy#12402

**Comment by mreineck** [comment]
I've opened a pull request that should fix this.

**Comment by zonca** [comment]
thanks @mattip , 
@mreineck fixed it in #521
