### ISSUE TITLE
maptype() in pixelfunc.py crashes when first element is masked

### ISSUE THREAD

**Issue by israelmcmc** [healpy/healpy#526]
Here's a minimal example:

```
import healpy	as hp
import numpy	as np

#This works
hp.maptype( hp.ma( 1.*np.array( [0, hp.UNSEEN, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] )))

#This doesn't work
hp.maptype( hp.ma( 1.*np.array( [hp.UNSEEN, 1 , 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] )))
```

This happens because in `maptype()` uses `hasattr(m[0], "__len__")` to check if the first element is a map in  sequence or a value in a map. A masked value happens to have that attribute while not being a "sized object". This problem propagates to `get_nside()`, which then propagates to multiple other methods.

**Comment by zonca** [comment]
thanks for tracking this down! it would be great if you'd like to contribute a fix, otherwise I'll take a look at this in the next weeks

**Comment by israelmcmc** [comment]
I made a pull request (#527). I also noticed that the help says that it'll return -1 if the map is not valid, while it just raises an error. I'll leave to the devs if you want to change the help of the functionality (which requires various changes to other functions)

**Comment by zonca** [comment]
thanks!
