### ISSUE TITLE
LinearSegmentedColormap vs. ListedColormap

### ISSUE THREAD

**Issue by DanielLenz** [healpy/healpy#533]
Trying to pass a custom colormap to any of the plotting functions:
```python
>> cm = plt.get_cmap('viridis')
>> type(cm)
matplotlib.colors.ListedColormap
>> hp.mollview(arr, cmap=cm)
```
This falls back to the standard `cmap` set in the `rcParams`.
The underlying reason is the following in `projaxes.py`:

```python
def create_colormap(cmap):
    if type(cmap) == str:
        cmap0 = matplotlib.cm.get_cmap(cmap)
    elif type(cmap) == matplotlib.colors.LinearSegmentedColormap:
        cmap0 = cmap
    else:
        cmap0 = matplotlib.cm.get_cmap(matplotlib.rcParams['image.cmap'])
```
A custom `mpl.cm` is only accepted if it is a `LinearSegmentedColormap`, but not for a `ListedColormap`. Is there a reason to exclude the latter?

**Comment by zonca** [comment]
no, we can change it

**Comment by DanielLenz** [comment]
Great, I'll make a PR.
