### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [healpy/healpy#546]
Hi @healpy Good day! I am a graphic artist and would like to contribute by offering a logo design for free as a gift to the project..I noticed that the project doesn't have a logo yet.If you will permit me, I would be glad to do it. Thanks and best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by zonca** [comment]
thanks for your offer, although I don't think we need a logo
