### ISSUE TITLE
Healpy query_polygon RuntimeError: Unknown exception

### ISSUE THREAD

**Issue by mbelveder** [healpy/healpy#549]
I'm using `healpy.query_polygon` to get a list of healpix indexes inside a polygon. According to the documentation: 

>vertices: Vertex array containing the vertices of the polygon, shape (N, 3).

But when I try to get all indexes from the following polygon, a `RuntimeError: Unknown exception` appears:

In[1]:
```
import healpy as hp

vertex_array = np.array([[0.65, -0.04, 0.76], [0.58, 0.38, 0.72], [0.91, -0.29, 0.31],[0.91, 0.18, 0.38]])

print(vertex_array.shape)
vertex_array
```
Out[1]:
```
(4, 3)
array([[ 0.65, -0.04,  0.76],
       [ 0.58,  0.38,  0.72],
       [ 0.91, -0.29,  0.31],
       [ 0.91,  0.18,  0.38]])
```
In[2]:
```
healpix_indexes_test = hp.query_polygon(4, vertex_array)
```
Out[2]:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-63-5a14f69cb078> in <module>
----> 1 healpix_indexes_test = hp.query_polygon(4, vertex_array)

healpy/src/_query_disc.pyx in healpy._query_disc.query_polygon()

RuntimeError: Unknown exception
```
[Here](https://www.geogebra.org/3d/edpd5pbs) you can see visualisation of these dots lying on a sphere.

Just for fun I tried to transpose the input array, so its shape became  (3, 4). The `Unknown exception` problem disappeared. But input like this contradict the documentation, so I don't believe it.

In[1]:
```
print(vertex_array.T.shape)
vertex_array.T
```

Out[1]:

```
(3, 4)
array([[ 0.65,  0.58,  0.91,  0.91],
       [-0.04,  0.38, -0.29,  0.18],
       [ 0.76,  0.72,  0.31,  0.38]])
```

In[2]:
```
healpix_indexes_test_1 = hp.query_polygon(4, vertex_array.T)

healpix_indexes_test_1
```
Out[2]:
```
array([ 42,  58,  75, 107, 123, 140])
```

I'll be gratefull for any suggestions.

**Comment by mreineck** [comment]
If I interpret the plot correctly, the polygon formed by these points is self-intersecting. The undelying Healpix C++ library only supports regular polygons. If it encounters such a situation, it will print an error message and throw an exception. Maybe it is possible to pass the message somehow back to Python, but I don't know enough about Cython to do this.

**Comment by mbelveder** [comment]
It helped!

So, the order of the vertices matters. I didn't think about it.

Thanks a lot!

**Comment by ekitanidis** [comment]
I'm running into the same issue, but I don't think my polygon is self-intersecting, so I'm a bit stumped.

```
nside = 2**4

ra_l, ra_r = 100, 280
dec_l, dec_u = -20, 40

v_ll = hp.ang2vec(np.pi * (0.5 - dec_l / 180), ra_l / 180 * np.pi)
v_ul = hp.ang2vec(np.pi * (0.5 - dec_u / 180), ra_l / 180 * np.pi)
v_ur = hp.ang2vec(np.pi * (0.5 - dec_u / 180), ra_r / 180 * np.pi)
v_lr = hp.ang2vec(np.pi * (0.5 - dec_l / 180), ra_r / 180 * np.pi)

vertices = np.vstack((v_ul, v_ll, v_lr, v_ur))

hp.query_polygon(nside, vertices)
```
I get this error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-eed87d993ab2> in <module>()
----> 1 hp.query_polygon(nside, vertices)

healpy/src/_query_disc.pyx in healpy._query_disc.query_polygon (healpy/src/_query_disc.cpp:2666)()

RuntimeError: Unknown exception

```

Here is what my vertices look like:

![Screen Shot 2020-04-07 at 11 59 51 AM](https://user-images.githubusercontent.com/13126107/78708673-5c43e580-78c7-11ea-9f90-b3673929a9a6.png)

Any suggestions? Thanks in advance!

**Comment by mreineck** [comment]
Unless I'm mistaken, all of these four vertices lie on a single great circle, and since the edges between polygon vertices are given by great circle arcs, your polygon geometry is degenerate.

**Comment by ekitanidis** [comment]
Hmm, I see. I assumed the purpose of query_polygon was to identify pixels intersecting with a polygon drawn on the surface of the sphere onto which the map is projected (like an extension of query_strip). Clearly, I misunderstood what this function is meant to do! Thanks for clarifying.

**Comment by mreineck** [comment]
> Hmm, I see. I assumed the purpose of query_polygon was to identify pixels intersecting with a polygon drawn on the surface of the sphere onto which the map is projected

This can only be unambiguous in combination with a projection, so that would lead to a more complicated interface.

I _think_ that these functions were originally introduced to address concrete problems encountered in astronomy. `query_disc` exists to deal with full-sky data where the Milky Way needs to be cut out, and `query_polygon` will typically be used by astronomers for very small polygons, where the sky is essentially flat and great circles are the only obvious connection between two points.
