### ISSUE TITLE
citing the joss paper?

### ISSUE THREAD

**Issue by rbiswas4** [healpy/healpy#550]
Your citation instructions don't seem to include the joss entry. Maybe you might want to add a bibtex to your citation section?

**Comment by DanielLenz** [comment]
We're waiting for the paper to get indexed by the astrophysics data system (ADS), which can take up to three weeks:

From their [FAQ](http://adsabs.github.io/help/data_faq/):
> Q: How often do new articles get added to the database?
This depends on the source. We ingest from arXiv daily; from astronomy journals and other sources weekly, over the weekend; and from physics journals and other sources about once every 3 weeks, also over a weekend.

We'll then simply use their bibtex entry, JOSS currently doesn't provide one directly (see https://github.com/openjournals/joss/issues/410)

**Comment by rbiswas4** [comment]
Thanks for your reply. I was trying to cite your paper. 

BTW: If you put it on the arXiv, you can get an arXiv bibtex from ADS in a much shorter time scale, and they get linked with the article entry (don't know about JOSS specifically). One could, of course, also make a bibtex  format themselves.

**Comment by zonca** [comment]
I was googling around and found this service: https://www.doi2bib.org

it works great:

```
@article{Zonca2019,
  doi = {10.21105/joss.01298},
  url = {https://doi.org/10.21105/joss.01298},
  year = {2019},
  month = mar,
  publisher = {The Open Journal},
  volume = {4},
  number = {35},
  pages = {1298},
  author = {Andrea Zonca and Leo Singer and Daniel Lenz and Martin Reinecke and Cyrille Rosset and Eric Hivon and Krzysztof Gorski},
  title = {healpy: equal area pixelization and spherical harmonics transforms for data on the sphere in Python},
  journal = {Journal of Open Source Software}
}
```

**Comment by zonca** [comment]
I'll add this to CITATION, then we can update it when we have ADS index it

**Comment by rbiswas4** [comment]
Thanks! I will use this currently.
