### ISSUE TITLE
Broken installation on Mac OS with pip

### ISSUE THREAD

**Issue by laurenmarietta** [healpy/healpy#561]
I'm trying to install `healpy` as a dependency for the `jwst_backgrounds` package (https://github.com/spacetelescope/jwst_backgrounds). However, `healpy` is failing the installation: spacetelescope/jwst_backgrounds#3

While investigating that issue, I've found that I cannot actually `pip install` healpy at all. I'll include the (long!) traceback as an attachment to this issue.

I can't say how universal this problem is, but here are some of my specs:
- OS: MacOSX 10.13.6 (though my issue seems to be different from #465)
- Python: 3.6.8
- pip: 19.1.1

Ultimately, installing with `conda-forge` was a solution for me, but it would be great if there could be a note added to the installation documentation about `pip` being a problem.

---
**Traceback:**
[pip_install_healpy_traceback.txt](https://github.com/healpy/healpy/files/3253017/pip_install_healpy_traceback.txt)

**Comment by zonca** [comment]
the issue is not `pip`, it is MAC OS, I added a note to the installation docs https://github.com/healpy/healpy/commit/a5514d1f1283fc78de3d9efbad16423e42fa33f6

**Comment by lpsinger** [comment]
The binary wheel from pip should work just fine.

**Comment by laurenmarietta** [comment]
Thank you for clarifying in the docs!
