### ISSUE TITLE
Problem in mollview dimensions of figure

### ISSUE THREAD

**Issue by ffranchina** [healpy/healpy#570]
Hello everyone!
First of all, I wanted to thank you for maintaining this very useful package!

I wanted to signal a weird behavior I run into every time I need to plot a sequence of `healpy.mollview()`, it's not critical at all, it's just to point out and maybe be able to give a small feedback.

Running the following code you'll notice that the first figure will appear bigger than the others, this is somehow annoying when I want all the plots to be of the same size.
```python
import healpy as hp
import numpy as np
import matplotlib.pylab as plt
from matplotlib import cm

data = np.random.rand(1024)
map1 = np.full(3072, hp.UNSEEN)
map1[:1024] = data
map2 = np.full(3072, hp.UNSEEN)
map2[1024:2048] = data

fig = plt.figure(figsize=(9, 9))
hp.mollview(map1, cmap=cm.Reds, sub=111, min=0, max=1)
plt.show()
plt.clf()
hp.mollview(map2, cmap=cm.Greens, sub=111, min=0, max=1)
plt.show()
```
It seems that the first call to `mollview` produces a bigger figure.

Thanks in advance for looking into this.
Let me know if I can help somehow to fix this (I would need a bit of guidance before submitting a PR to this project) :)

**Comment by DanielLenz** [comment]
That appears to come from your line `fig = plt.figure(figsize=(9, 9))`, which sets the figure size for the first figure, but not for the second. If you repeat it, you'll get consistent figure sizes:
```
fig = plt.figure(figsize=(9, 9))
hp.mollview(map1, cmap=cm.Reds, sub=111, min=0, max=1)
plt.show()
plt.clf()
fig = plt.figure(figsize=(9, 9))
hp.mollview(map2, cmap=cm.Greens, sub=111, min=0, max=1)
plt.show()
```

**Comment by DanielLenz** [comment]
@ffranchina , did the above solution work out for you?

I'm closing this for now, please feel free to re-open if there are any other issues.

**Comment by ffranchina** [comment]
Hey @DanielLenz, thanks for looking into this!
Yes, it actually solved my point even if I found it a bit counter-intuitive (shouldn't it keep drawing on the same figure?).
Thanks for your time!
