### ISSUE TITLE
macports installation issue

### ISSUE THREAD

**Issue by DanielBThomas** [healpy/healpy#571]
Hi

I think this might be similar to some other issues, but I'm afraid I couldn't work out how to solve it.
I'm running MacOS 10.13.6, and attempted to install healpy as advised, using "sudo port install py27-healpy". This appears to complete correctly, and port selfupdate, port upgrade outdated and port rev-upgrade all suggest everything is up to date with no linking errors. I've also checked that py27 is the active python.

However, if I try to import healpy, I get the following error:

/Users/dt/Library/Python/2.7/lib/python/site-packages/healpy-1.12.8-py2.7-macosx-10.13-x86_64.egg/healpy/pixelfunc.py:107: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn("Warning: cannot import _healpy_pixel_lib module")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dt/Library/Python/2.7/lib/python/site-packages/healpy-1.12.8-py2.7-macosx-10.13-x86_64.egg/healpy/__init__.py", line 82, in <module>
    from ._query_disc import query_disc, query_strip, query_polygon, boundaries
ImportError: dlopen(/Users/dt/Library/Python/2.7/lib/python/site-packages/healpy-1.12.8-py2.7-macosx-10.13-x86_64.egg/healpy/_query_disc.so, 2): Symbol not found: __ZN14T_Healpix_BaseIlE8SetNsideEl23Healpix_Ordering_Scheme
  Referenced from: /Users/dt/Library/Python/2.7/lib/python/site-packages/healpy-1.12.8-py2.7-macosx-10.13-x86_64.egg/healpy/_query_disc.so
  Expected in: flat namespace
 in /Users/dt/Library/Python/2.7/lib/python/site-packages/healpy-1.12.8-py2.7-macosx-10.13-x86_64.egg/healpy/_query_disc.so

Any ideas?

Thanks
Dan

**Comment by lpsinger** [comment]
It's importing from `/Users/dt/Library/Python/2.7`, not `/opt/local/Library/Python/2.7`. It looks like you have another version of Healpy that you have installed previously with `pip install --user healpy`. Try uninstalling that.

**Comment by zonca** [comment]
no more feedback closing this.
