### ISSUE TITLE
hp.alm2cl is broken for nside=8192

### ISSUE THREAD

**Issue by msyriac** [healpy/healpy#572]
Healpy version: 1.12.9

The output of this snippet:
```
for nside in [256,512,1024,2048,4096,8192]:                                                                                                                                                   
    lmax = 3*nside - 1                                                                                                                                                                        
    s = hp.Alm.getsize(lmax)                                                                                                                                                                  
    alms = np.zeros((s,)) + 0j                                                                                                                                                                
    cls = hp.alm2cl(alms)                                                                                                                                                                     
    print("nside %d with lmax %d returns Cls with length %d" % (nside,lmax,len(cls)))
```

is 

```
nside 256 with lmax 767 returns Cls with length 768
nside 512 with lmax 1535 returns Cls with length 1536
nside 1024 with lmax 3071 returns Cls with length 3072
nside 2048 with lmax 6143 returns Cls with length 6144
nside 4096 with lmax 12287 returns Cls with length 12288
/home/msyriac/.local/lib/python3.7/site-packages/healpy/sphtfunc.py:685: RuntimeWarning: invalid value encountered in sqrt
  cls = _sphtools.alm2cl(alms1, alms2=alms2, lmax=lmax, mmax=mmax, lmax_out=lmax_out)
nside 8192 with lmax 24575 returns Cls with length 0
```
If the correct lmax is passed explicitly to alm2cl, then it returns sensible results, so clearly something is going wrong in the lmax inferring step.

**Comment by zonca** [comment]
@DanielLenz would you have any time to look into this?

**Comment by DanielLenz** [comment]
I took a quick look at the cython code yesterday and couldn't immediately find the reason for that behavior. Will take a closer look!

**Comment by DanielLenz** [comment]
It appears to come down to an int overflow in `_sphtools.alm_getlmax(int s)`, where the line `x=(-3+np.sqrt(1+8*s))/2` results in a negative sqrt for very large sizes (hence the RuntimeWarning above).

The cython `int` is 32bit by default; I could take a shot at replacing this by a `long`, but this might also be a good opportunity to identify and fix other locations in the codebase where we will encounter trouble in the high-nside future.

**Comment by zonca** [comment]
thanks @DanielLenz, as you prefer, depending on how much time you have available

**Comment by mreineck** [comment]
Alternatively you could replace `8*s` by `8.*s` ... the argument of `np.sqrt` will be converted to `double` anyway, and that gives you 52 bits of mantissa.

**Comment by msyriac** [comment]
Thanks for the fix @DanielLenz ! I'm not sure how this team manages deployments, but I would think that this fix totally warrants a version bump and PyPI deployment, because the current version of healpy is not usable for nside>=8192. Also, is it totally infeasible to have the test suite do a few operations at nside=8192? synalm and alm2cl for the sort of high lmaxes that can lead to overflow errors are not actually that slow. map2alm and alm2map are probably very slow -- but I'm not sure how much you care about Travis test times.

**Comment by zonca** [comment]
@msyriac I'll make a release next week, there is another thing users were asking for.

@msyriac a bit slower tests on Travis would be fine, could you provide a PR for those tests you are proposing?
