### ISSUE TITLE
Change color of masked pixels in partial sky map? `badcolor`?

### ISSUE THREAD

**Issue by capolitsch** [healpy/healpy#574]
I would like to replace the default 'gray' mask with a lighter color in `mollview` and `orthview` and am finding this quite troublesome. A past commit introduced the `badcolor` arg for this purpose but it seems to now be deprecated. Any help would be much appreciated!

**Comment by DanielLenz** [comment]
Looks like we merged https://github.com/healpy/healpy/pull/551 in April, a month after the latest (12.9) release.

At this point, you could either 1) wait until we release 12.10 (perhaps @zonca has an idea of the timeline) 2) install the latest version from source or 3) build your own colormap as such (the key is `set_under()` and `set_bad()`:

```
from matplotlib import colors
CMAP_DISCRETE_RED = colors.ListedColormap(["orange", "red"])
CMAP_DISCRETE_RED.set_under("white")
CMAP_DISCRETE_RED.set_bad("grey") 

hp.mollview(hpxmap, cmap=CMAP_DISCRED_RED)
```

**Comment by zonca** [comment]
I'll make a release next week

**Comment by capolitsch** [comment]
Thank you!
