### ISSUE TITLE
No mrdfits and mwrfits in v1.12.9 

### ISSUE THREAD

**Issue by giuspugl** [healpy/healpy#575]
Why there is no more the mrdfits and mwrfits in the latest version of healpy ? I know we can use astropy for that, but it was very useful  for me to have it within healpy .

**Comment by zonca** [comment]
they are just wrappers around `astropy`, we do not want to maintain unnecessary code.
See https://github.com/healpy/healpy/commit/133c3d6380494601caa54ec600f096468a125548
