### ISSUE TITLE
nside2npix is missing the check for a valid nside

### ISSUE THREAD

**Issue by dpole** [healpy/healpy#578]
The behavior of `nside2npix` is different from what the doc says:

https://github.com/healpy/healpy/blob/d1e9ac45a97a6b4857a5f7c601d9dcaccbc31e21/healpy/pixelfunc.py#L954

I'll fix the following
- [ ] add the check for a valid nside
- [ ] fix the example with the invalid nside

**Comment by zonca** [comment]
thanks @dpole we did it on purpose, see https://github.com/healpy/healpy/issues/499.
In fact there is also a doctest with nside 7.
can you provide a PR removing reference to raising that exception?

**Comment by dpole** [comment]
Ok, thank you @zonca for the clarification. Sure, I'll fix the docstring
