### ISSUE TITLE
Releasing healpy 1.12.10

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#580]
Release:
* [x] Github: https://github.com/healpy/healpy/releases/tag/1.12.10
* [x] PyPI: https://pypi.org/project/healpy/1.12.10/
* [x] conda-forge: waiting for bot
* [x] wheels on PyPI: 

```
healpy-1.12.10-cp27-cp27m-manylinux1_x86_64.whl   healpy-1.12.10-cp35-cp35m-manylinux1_x86_64.whl
healpy-1.12.10-cp27-cp27mu-manylinux1_x86_64.whl  healpy-1.12.10-cp36-cp36m-manylinux1_x86_64.whl
healpy-1.12.10-cp34-cp34m-manylinux1_x86_64.whl   healpy-1.12.10-cp37-cp37m-manylinux1_x86_64.whl
```

@DanielLenz @hivon @mreineck @lpsinger

**Comment by mreineck** [comment]
Sorry, can't have a detailed look right now, as I'm on vacation for two weeks.

**Comment by zonca** [comment]
ok, all builds on conda-forge worked, see https://anaconda.org/conda-forge/healpy

**Comment by DanielLenz** [comment]
I'll test everything later today or tomorrow.

**Comment by lpsinger** [comment]
I built and uploaded wheels for macOS. Please add that to your checklist in the future.

**Comment by lpsinger** [comment]
Oh, darn it. I built macOS wheels for 1.12.10 by mistake. Fixing it now.

**Comment by zonca** [comment]
ok @lpsinger is there any change compared to the procedure in https://github.com/healpy/healpy/blob/master/RELEASE.md?

**Comment by lpsinger** [comment]
Just that I had to change the Healpy version in that command, like you and @DanielLenz did for the Linux build instructions.

Would be great to have the CI script do all of this for us.

**Comment by lpsinger** [comment]
Updated MacPorts in macports/macports-ports@e93f3a215d27eb3586fb30df2f54e633a8aff412.
