### ISSUE TITLE
anafast: datapath argument is ignored for pixel weights

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#582]
I'm trying to compute `map2alm` transforms with custom pixel weight files, but it seems that for pixel weights, `healpy`'s `anafast` ignores the `datapath` parameter.
Internally there is a special parameter containing the name of the pixel weight file, but the user has no influence on it.
Overall, I'd feel much better if `healpy` wouldn't download data from the net without explicit user consent, and if the user could just specify the name of the file to be used - especially in the case if pixel weight files where there is no "single best choice". (There is a tradeoff between lmax and the maximum achievable accuracy, for example.)

**Comment by zonca** [comment]
yes, we could use `datapath` and check if the pixel weight file is available there first, and then download it from the internet. I won't have time to work on this though.

**Comment by mreineck** [comment]
OK. This only addresses a part of the problem though.

I'm planning to update the weight files soon - no change in format, just improved accuracy. With the current approach, only new users will see these files; everyone who already downloaded them will not get an update, unless I'm misunderstanding something.

**Comment by zonca** [comment]
> OK. This only addresses a part of the problem though.
> 
> I'm planning to update the weight files soon - no change in format, just improved accuracy. With the current approach, only new users will see these files; everyone who already downloaded them will not get an update, unless I'm misunderstanding something.

we can test if `astropy.utils.data` handles this case automatically by checking hashes, I cannot find details in the docs, otherwise we can change the filenames.

**Comment by mreineck** [comment]
> we can test if astropy.utils.data handles this case automatically by checking hashes

I definitely hope not ... I wouldn't be happy at all about healpy phoning home every time I do a map analysis; also the potential waiting for timeouts without net connection would be quite bad.

**Comment by zonca** [comment]
fixed by #611
