### ISSUE TITLE
Obtaining a power spectrum from a reprojected healpix map

### ISSUE THREAD

**Issue by apssingh** [healpy/healpy#587]
Is it possible to generate an angular power spectrum from a reprojected `Healpix` map?
I recently tried to perform deconvolution of a non-circular beam from a reprojected `Healpix` map using [healpy.projector.CartesianProj](https://healpy.readthedocs.io/en/latest/generated/healpy.projector.CartesianProj.html#healpy.projector.CartesianProj) and it worked well, but needless to say, an angular power spectrum is necessary to analyze the map and the effectiveness of the deconvolution method.
It would even be fine if I could get back the map in the `HEALPix` format(i.e. as 1d array). Is this kind of back conversion possible somehow?

Or is it just a bad idea to deconvolve the map after reprojecting it?

**Comment by zonca** [comment]
I think you should try to use https://github.com/simonsobs/pixell
