### ISSUE TITLE
Build error: No rule to make target cxxsupport/announce.cc

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#591]
@mreineck I can't build healpy with healpix 3.60 on a Ubuntu 16.04 machine.
I get: 

```
make: *** No rule to make target '/home/zonca/p/software/healpy/healpixsubmodule/src/cxx/autotools/cxxsupport/announce.cc', needed by 'cxxsupport/announce.lo'.  Stop.
```

Is it possible the compiler is too old?

```
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
autoreconf --version
autoreconf (GNU Autoconf) 2.69
pkg-config --version
0.29.1
```

**Comment by zonca** [comment]
yeah, updating to gcc 7 fixes the problem.
@mreineck do you know the minimum gcc version supported by HEALPix 3.60?

**Comment by mreineck** [comment]
The error message you are getting doesn't really indicate an old compiler, and I would actually expect gcc5 to compile Healpix 3.60. Can you please post the full output of the Healpix C++ `configure` command?

**Comment by zonca** [comment]
cannot debug this anymore as I have updated the compiler.
