### ISSUE TITLE
Signal to noise ratio 

### ISSUE THREAD

**Issue by Gabriel-Ducrocq** [healpy/healpy#598]
Hi everyone,

I am trying to replicate the setting given in the following paper, section 4:
https://arxiv.org/pdf/1512.06619.pdf

However, using a 13' FWHM gaussian beam with noise 1.84e-3 uK^2 and the Planck best fit L-CDM power spectrum found there:
http://pla.esac.esa.int/pla/#cosmology

doesn't give me a SNR of 1 at l = 900 but at l= 1200.

Here is my code:

```
import matplotlib.pyplot as plt
L_MAX_SCALARS= 2508
cls_ = np.loadtxt('Planck_Test_Ideal/PlanckPowerSpectrum/PlanckPowerSpec.txt', skiprows=1)[:, 1]
scaling = np.array([l*(l+1)/(2*np.pi) for l in range(2, L_MAX_SCALARS+1)])
cls_ /= scaling
noise_covar = 1.84e-3
fwhm_arcmin = 13
fwhm_radians = (np.pi/(180*60))*fwhm_arcmin
theta_b = fwhm_radians/np.sqrt(8*np.log(2))
bl_gauss = hp.gauss_beam(theta_b, lmax=L_MAX_SCALARS)[2:]
plt.plot(cls_*(bl_gauss**2)/noise_covar)
plt.axhline(y=1)
plt.show()
```

Am I using healpy correctly ? Or maybe I missed something in the units of the power spectrum (which I assumed to be in uK^2) ?

Thank you !

**Comment by mreineck** [comment]
Why are you applying a correction to the beam FWHM?
`theta_b = fwhm_radians/np.sqrt(8*np.log(2))`

If I read the documentation correctly, it should be OK to just pass `fwhm_radians` to `hp.gauss_beam`.

**Comment by Gabriel-Ducrocq** [comment]
Oh yes, you're right, I just passed `fwhm_radians` before I added the rescaling by 2pi/l(l+1) and then added the correction on the advices of more knowledgeable person with the library.
Removing this correction gives SNR = 1 for l = 897.

Thank you !
