### ISSUE TITLE
Inconsistency with  pixelfunc when using `lonlat=True`

### ISSUE THREAD

**Issue by giuspugl** [healpy/healpy#602]
Hello, 
I found an inconsistency  when using `pixelfunc. ang2pix`, `pixelfunc.ang2vec`, etc... when they are used with `lonlat=True`.  In which case,   the conversion into `theta, phi ` radians coordinates is performed in https://github.com/healpy/healpy/blob/4a22677d882fde7a738a9f597c8d2fb065c1d41f/healpy/pixelfunc.py#L159 ,  and it  is done as if theta is a longitudinal coordinate, and phi as a co-latitude one, whereas should be the other way around.
Indeed I get a `ValueError: THETA is out of range [0,pi]`, when I run the code below : 
 `
 lon = 200  ;
 lat = -90   ;    pix = hp.ang2pix(theta=lat, phi=lon, nside=1024, lonlat=True )
 `
On the other hand, I don't when 
` hp.ang2pix(theta=lon, phi=lat, nside=1024, lonlat=True ) ` 

 I think the documentation here is a bit misleading since it says to use theta as the latitude coordinate,and phi as the longitudinal one .

**Comment by zonca** [comment]
thanks, can you please provide a minimal example I can just copy-paste and
execute?

**Comment by giuspugl** [comment]
``` 
import healpy as hp
lon = 200 ;
lat = -90 ; 
try : 
    print("Run ang2pix as  described in  \n https://healpy.readthedocs.io/en/latest/generated/healpy.pixelfunc.ang2pix.html ") 
    pix = hp.ang2pix(theta=lat, phi=lon, nside=1024, lonlat=True ) 
except ValueError : 
    print("Exception rose, \n running ang2pix with  lon as co-latitude coordinate  and lat as longitude.  ") 
    pix = hp.ang2pix(theta=lon, phi=lat, nside=1024, lonlat=True )
```

**Comment by zonca** [comment]
it is strange that we basically switch the coordinates when we use `lonlat=True`, but I think it is consistent with the docs, and for backwards compatibility I wouldn't change it.

It would be useful if you can provide a pull request to clarify the docs, but we don't want to change behavior.

**Comment by mreineck** [comment]
There are communities which swap the angle names, unfortunately. According to https://en.wikipedia.org/wiki/Spherical_coordinate_system, using theta for longitude and phi for colatitude is typically done by mathematicians.
Had I been aware of this earlier, Healpix C++ would be using "colat" and "lon" to avoid any potential misunderstanding ...

**Comment by zonca** [comment]
@giuspugl I'll close for now, please consider submitting a pull request to clarify the documentation.
