### ISSUE TITLE
Make graticules appear behind partial sky map?

### ISSUE THREAD

**Issue by capolitsch** [healpy/healpy#603]
Hello,

Thank you in advance for your help. This likely isn't so much an issue with healpy as it is a limitation of my own knowledge of python/matplotlib. I am plotting a partial sky map (~25%) and I would like to add graticules, but I would like the partial sky map to be in the foreground, so the graticules are visible in the masked (~75%) region but do not appear of the mapped region. Any help would be much appreciated.

I've added a minimal working example below which plots a response variable (flux_contrast) with graticules overlaid.

Thank you!

`import matplotlib.pyplot as plt
import numpy as np
import healpy as hp

cmap = plt.cm.RdBu
cmap.set_bad('#00FFFFFF')
hp.mollview(flux_contrast, rot = [115,0], cmap = cmap, xsize=  6000, unit=r'$\delta_F$', norm = 'hist', min = -1, max = 1.3, badcolor = "#ECF0F1", nest = False)
hp.graticule(lw = 3/8, color = "#626567", linestyle = ":")`

**Comment by zonca** [comment]
apologies, given little time, I try to focus on bugs, for plotting issues try stackoverflow or you have to try debug yourself.
