### ISSUE TITLE
healpy.smoothing doesn't work

### ISSUE THREAD

**Issue by jinyiliu** [healpy/healpy#605]
Hello,

I find my `hp.smooth` just doesn't work. I first generate a set of TQU maps using `hp.alm2map` and `hp.synalm` . Then I try to smooth them with 10 arcmin fwhm. There are 2 ways to do this smoothing
```python
maps_smoothed = hp.smooth(maps, fwhm=fwhm, pol=True)
maps_smoothed = hp.alm2map(hp.map2alm(maps), nside, fwhm=fwhm, pol=True, verbose=True)
```
I think there should be no difference between these two in principle because they both call the function `hp.smoothalm`. But the power spectra really differ with each other. The following  Cl_TT plot shows the difference
<img width="596" alt="bug" src="https://user-images.githubusercontent.com/23398808/75952855-e7a61180-5eea-11ea-8345-24345411ee42.png">
The blue line comes from maps smoothed by `hp.alm2map` and the orange line by `hp.smooth`. So it seems like that `hp.smooth` doesn't work at all.

I've checked both my code and the healpy source code, but couldn't find anything wrong due to my limitations.

Thank you so much!

**Comment by zonca** [comment]
I don't see you calling `smoothalm`

**Comment by zonca** [comment]
please provide a complete executable snippet of code that creates a simple map on the fly and demonstrates this.

**Comment by jinyiliu** [comment]
Sorry, my bad! 
I've uploaded the executable code together with the input Cl data in this zip file [smooth.zip](https://github.com/healpy/healpy/files/4292266/smooth.zip). Cl data contains tt, ee, bb, te power spectra. 
```python
import pickle as pk
import healpy as hp
import numpy as np
import matplotlib.pyplot as plt

# cl dict with tt ee bb te power spectra
f = open('cls.pk', 'rb')
cls = pk.load(f)
f.close()

# parameters
nside = 2048
fwhm = 10/60/180 * np.pi # radians
scale = lambda ell : ell * (ell + 1) / 2 / np.pi

np.random.seed(1)
alms = hp.synalm([cls['tt'], cls['ee'], cls['bb'], cls['te']], new=True)
maps = hp.alm2map(alms, nside, pol=True, verbose=True)
# preview Tmap via healpy
# hp.mollview(maps[0], cmap="viridis", min=-300, max=300)

# smoothing by function hp.smoothing and hp.alm2map
maps_by_smoothing = hp.smoothing(maps, fwhm=fwhm, pol=True)
maps_by_alm2map = hp.alm2map(alms, nside, fwhm=fwhm, pol=True, verbose=True)

# only calculate cltt for speed
cltt_by_smoothing = hp.anafast(maps_by_smoothing[0])
cltt_by_alm2map = hp.anafast(maps_by_alm2map[0])

# plot
ell = np.arange(1, 3000, dtype=int)
plt.figure()
plt.plot(ell, scale(ell) * cltt_by_smoothing[ell], label='hp.smoothing')
plt.plot(ell, scale(ell) * cltt_by_alm2map[ell], label='hp.alm2map')
plt.legend()
plt.show()
```

Basically I want to smooth the TQU maps (here I set fwhm = 10 arcmin) and then make some power spectra plots. And I tried with 2 ways to achieve this
- smooth the alms directly by setting the parameter fwhm in function `alm2map` to get the maps
- smooth the maps by function `smoothing`

Both `alm2map` and `smoothing` call the function `smoothalm` so I think there should be no difference between them. But the power spectra actually imply a difference. Here I only show Cl_TT for demonstration.
![bug](https://user-images.githubusercontent.com/23398808/75978256-133ff080-5f19-11ea-8a55-5c431bbed398.png)
The blue line comes from maps smoothed by `smoothing` and the orange line by `alm2map`. So it seems like function `smoothing` does nothing.

I hope I make it clear. Thank you very much!

**Comment by DanielLenz** [comment]
Hi @jinyiliu , thanks for taking the time to point this out for providing the great reference code.

To save time, I set `lmax` to 2000. The minor code changes are below. 

```
lmax = 2000
cltt_by_smoothing = hp.anafast(maps_by_smoothing[0], lmax=lmax-1)
cltt_by_alm2map = hp.anafast(maps_by_alm2map[0], lmax=lmax-1)

ell = np.arange(1, lmax+1, dtype=int)
plt.plot(ell, scale(ell) * cltt_by_smoothing, label='hp.smoothing')
plt.plot(ell, scale(ell) * cltt_by_alm2map, label='hp.alm2map')
```

I've just run this in a new conda env and couldn't reproduce the error, both the smoothed maps and the power spectra look identical.

Could you run this and see if this solves your problem? Perhaps computing up to the default of 3*2048-1 is an issue.

**Comment by jinyiliu** [comment]
I tried your code, and the power spectra still look different. However, I couldn't reproduce the error either after reinstalling healpy. So I think that's because I changed the healpy source code before by accident.

Many thanks!
