### ISSUE TITLE
ud_grade() boosts the power spectrum at small scales?

### ISSUE THREAD

**Issue by yaojian95** [healpy/healpy#607]
Hi, here I want to use _ud_grade_ function to downgrade the resolution, say from nside=512 to 256, using something like `hp.ud_grade(cmb512, nside_out= 256)`, but finding that this process will enhance the power spectrum at large multipoles very significantly, as the following plot shows.

![image](https://user-images.githubusercontent.com/14847517/77342559-54cef900-6d6b-11ea-9420-331d6a593d66.png)

In this plot, _512 real_ is the power spectrum of the original resolution map with nside = 512. 
_256_from_512_ is the result of the downgraded map, which has a boosted tail compared to the original one. 
And I'm also told that we should actually smooth the map to the size of the downgraded map to get correct results. So I did this like

 `alm512 = hp.map2alm(cmb512); `
`cmb256_512alm = hp.alm2map(alm512, nside = 256, fwhm = 2*0.229/180*np.pi)`

in which 0.229 degree is the pixel size when nsize=256 and get the green line which also has a obvious boost at small scales.

Have you got any experiences with something similiar like this ?

**Comment by LiQiaoling** [comment]
Based on theory on spectral analysis or Fourier transform, the maximum frequency of the wave is double of the sampling frequency. it's natural that the loss of the high frequecy when you low down the resolution. So you should take proper sampling frequency based on the characteristic of the thing you study.

**Comment by LiQiaoling** [comment]
Based on theory on spectral analysis or Fourier transform, the maximum frequency of the wave is double of the sampling frequency. it's natural that the loss of the high frequecy and different shape of power spectrum when you low down the resolution. So you should take proper sampling frequency based on the characteristic of the thing you study.

**Comment by mreineck** [comment]
Sorry for the late response...

It seems that the power spectrum of your original map does not fall off for increasing multipoles. If you downgrade such a map, I expect that the power on the small scales will be aliased to lower multipoles, leading to the increase you are seeing.

If you downgrade a map from, say, nside_hi=512 to nside_lo=256, you can only expect the power spectrum to stay roughly the same, if the power spectrum of the original map has fallen off to more or less zero at a multipole of (roughly) 2*nside_lo. This is just a rule of thumb, but works reliably in practice.

**Comment by zonca** [comment]
no more feedback
