### ISSUE TITLE
Temperature power spectrum posterior shape and healpy

### ISSUE THREAD

**Issue by Gabriel-Ducrocq** [healpy/healpy#608]
Hi everyone,

I am trying to replicate the experiment given section 4.1 in the following paper:
https://iopscience.iop.org/article/10.1088/0004-637X/697/1/258/meta

However, using the same settings I get different posterior shapes with a non negligible part of the mass truncated at 0.

Here is my code. Am I using all the healpy parts correctly ?

In the following, I took NSIDE = 512, L_MAX = 1000, and a noise RMS of sqrt(40) muK - I think the 40 muK rms in the paper is a typo, because I can't have a SNR of 1 at around l=550 for any of the WMAP beam - and use the Q-band beam size with FWHM of 0.51 deg.
This gives me a SNR of 1 around l = 522.

The formula for the posterior is given equation (22) of the above mentioned paper. However, I assume there are several typos: the C_{l} should be replaced by C_{b} and before each C_{b} there should be a factor 2*pi/(l*(l+1)) in the case we are binning, as given equation (21).
I make the corrections in my code.

```python
import numpy as np
import healpy as hp
from scipy import stats

L_MAX_SCALARS = 1000
NSIDE = 512
Npix = 12*NSIDE**2
w = 4*np.pi/Npix
noise_var = 40
fwhm_deg = 0.51

#Loading the Cls generated using Class with cosmo params:
#NAMES = ["n_s", "omega_b", "omega_cdm", "100*theta_s", "ln10^{10}A_s", "tau_reio"]
#Values= np.array([0.9665, 0.02242, 0.11933, 1.04101, 3.047, 0.0561])
data = np.load(path_data, allow_pickle=True)
data = data.item()
Cls = data["cls_"]

#Generating beam and map
bl_gauss = hp.gauss_beam(fwhm=(np.pi/180)*fwhm_deg, lmax=L_MAX_SCALARS)
d = hp.synfast(Cls, lmax=L_MAX_SCALARS, nside=NSIDE, fwhm=(np.pi/180)*fwhm_deg, new = True) + np.sqrt(noise_var)*np.random.normal(size=Npix)

# Compute the likelihood of each (possibly) binned power spectrum component: (product of) inverse gamma.
def compute_likelihood(x, alphas, betas, locs, bl_gauss, l_start, l_end):
    return np.prod(stats.invgamma.pdf(x, a=alphas[l_start:l_end], scale=betas[l_start:l_end], loc=locs[l_start:l_end])
                  /bl_gauss[l_start:l_end]**2)


#Trace the posterior of each (possibly) binned power spectrum component
def trace_posterior(d, bins, max_range):
    l_start, l_end = bins
    scale_dl = np.array([l*(l+1)/(2*np.pi) for l in range(L_MAX_SCALARS+1)])
    power_spec = hp.anafast(d, lmax=L_MAX_SCALARS, alm=False)
    power_spec *= scale_dl/bl_gauss**2
    #Compute the parameters of each of the inverse gamma:
    betas = np.array([(2*l+1)*pow_sp/2 for l, pow_sp in enumerate(power_spec)])
    alphas = np.array([(2*l-1)/2 for l in range(L_MAX_SCALARS+1)])
    locs = - w*noise_var*scale_dl/(bl_gauss**2)
    
    #Getting the normalising constant
    norm, err = scipy.integrate.quad(compute_likelihood, a=0, b=np.inf, args=(alphas, betas ,locs, bl_gauss, l_start, l_end))
    
    steps = max_range/10000
    xs = np.arange(0, max_range ,steps)
    y = []
    for x in xs:
        result = compute_likelihood(x, alphas, betas, locs, bl_gauss, l_start, l_end)
        y.append(result)
        
    return np.array(y), xs, norm


bins = [855, 1001]
y, x, norm = trace_posterior(d, bins, 20000)


plt.plot(x, y/norm)
plt.title("Binned posterior ell range " + str(bins[0]) +"-"+str(bins[1]))
plt.show()

```

This code gives me the following posterior for the binned power spectrum [855-1000]:
<img width="411" alt="Capture d’écran 2020-03-24 à 13 50 17" src="https://user-images.githubusercontent.com/10798127/77427333-7c0ee000-6dd6-11ea-8420-5aee962a671c.png">

which is in contrast with figure 4 of the paper... I have no idea why I observe such a difference.

Am I using every healpy parts correctly ? The way I create the beam or generate the data ? Or compute the observed power spectrum ?

Thanks,

Gabriel.

**Comment by DanielLenz** [comment]
Hi Gabriel,

for general questions such as this, we recommend you post it on stackoverflow and include the healpy tag. This goes beyond the scope of github issues.

Thanks, Daniel
