### ISSUE TITLE
Alm.getlm does not check for index bounds

### ISSUE THREAD

**Issue by msyriac** [healpy/healpy#616]
If the (l,m) corresponding to an index that is out of the alm array bounds is requested, ideally it should be raising an exception. Instead, getlm returns garbage. The following is with healpy version 1.13.0 :

```
In [29]: hp.Alm.getsize(500)
Out[29]: 125751

In [30]: hp.Alm.getlm(500,125750)
Out[30]: (500, 500)

In [31]: hp.Alm.getlm(500,125751)
~/.local/lib/python3.6/site-packages/healpy/sphtfunc.py:579: RuntimeWarning: invalid value encountered in sqrt
  ((2 * lmax + 1) - np.sqrt((2 * lmax + 1) ** 2 - 8 * (i - lmax))) / 2
~/.local/lib/python3.6/site-packages/healpy/sphtfunc.py:582: RuntimeWarning: overflow encountered in long_scalars
  l = i - m * (2 * lmax + 1 - m) // 2
Out[31]: (4611686018427513655, -9223372036854775808)
```

**Comment by zonca** [comment]
Thanks @msyriac, can you take a look at #618?

**Comment by msyriac** [comment]
Ok, it raises a FloatingPointError now, but ideally an "index out of bounds" would be more informative. Your call.

**Comment by zonca** [comment]
@msyriac can you check now?

**Comment by msyriac** [comment]
Thanks, I get "AssertionError: Invalid index, it should less than the max alm array length of 125751" now. This looks good.
