### ISSUE TITLE
Make default verbose=False?

### ISSUE THREAD

**Issue by adrn** [healpy/healpy#619]
It looks like the default behavior for functions (e.g., `healpy.smoothing()`) is `verbose=True`. Should the default be changed to `verbose=False`? I frequently use `healpy` from an IPython notebook, and the output is often clogged by verbose output, especially when looping over maps. Just raising this for discussion - I don't feel very strongly about this!

**Comment by zonca** [comment]
In that case less experienced users would never see the messages.

My proposal would be to switch all functions to use `warnings` (`smoothing` is not),
and then explain in the docs how to do:

    warnings.filterwarnings(action='ignore', module='healpy' )

to suppress them.
Any better suggestion? @lpsinger?

**Comment by lpsinger** [comment]
I agree with @adrn. Functions in Python modules should be silent by default.

**Comment by zonca** [comment]
no-one would ever set all verbose to True, so they would be useless, their purpose is to help the novice users when running interactively.
I think my proposal is good enough, it allows more advanced uses to just stop all `healpy` verboseness with just 1 line of code. I implemented also a small function to make it easier.

```
In [5]: hp.smoothing(np.arange(12), fwhm=1)                                                                                          
/home/zonca/zonca/p/software/healpy/healpy/sphtfunc.py:823: UserWarning: Sigma is 1459.876638 arcmin (0.424661 rad) 
  sigma * 60 * 180 / np.pi, sigma
/home/zonca/zonca/p/software/healpy/healpy/sphtfunc.py:828: UserWarning: -> fwhm is 3437.746771 arcmin
  sigma * 60 * 180 / np.pi * (2.0 * np.sqrt(2.0 * np.log(2.0)))
/home/zonca/zonca/p/software/healpy/healpy/sphtfunc.py:823: UserWarning: Sigma is 0.000000 arcmin (0.000000 rad) 
  sigma * 60 * 180 / np.pi, sigma
/home/zonca/zonca/p/software/healpy/healpy/sphtfunc.py:828: UserWarning: -> fwhm is 0.000000 arcmin
  sigma * 60 * 180 / np.pi * (2.0 * np.sqrt(2.0 * np.log(2.0)))
Out[5]: 
array([0.97237589, 1.96986319, 2.68512681, 2.84879047, 4.85208202,
       4.59814393, 5.64311657, 7.05682575, 7.65126875, 8.64875605,
       9.36401967, 9.52768333])

In [6]: hp.disable_warnings()                                                                                                        

In [7]: hp.smoothing(np.arange(12), fwhm=1)                                                                                          
Out[7]: 
array([0.97237589, 1.96986319, 2.68512681, 2.84879047, 4.85208202,
       4.59814393, 5.64311657, 7.05682575, 7.65126875, 8.64875605,
       9.36401967, 9.52768333])
```

**Comment by zonca** [comment]
Please take a look at #630 and send me some feedback

**Comment by zonca** [comment]
see #630
