### ISSUE TITLE
Numpy recommends representing matrices as ndarray rather than matrix

### ISSUE THREAD

**Issue by alurban** [healpy/healpy#620]
With numpy-1.18.4 and healpy-1.13.0 installed on my MacBook (in a Conda environment running python-3.7), the `healpy.rotator.Rotator` class raises this warning:

```bash
  /path/to/python3.7/site-packages/healpy/rotator.py:285: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return np.matrix(self._matrix)
```

It seems this line in `healpy/rotator.py` just needs to be replaced with:

```python
    return np.asarray(self._matrix)
```

(or similar), though I'm not sure how many other places in the code are affected by this change.

**Comment by zonca** [comment]
thanks!
