### ISSUE TITLE
Unable to change default color map

### ISSUE THREAD

**Issue by robspearman** [healpy/healpy#621]
I am unable to change what seems to be the default viridis color map.  Here is an example trying to select another color map.

`galacticArray = hp.cartview(map_Cel, coord=['C','G'], cmap='gray', return_projected_map=True, xsize=1920, norm='None', min=0, max=maxFlux, nest=False)
`
There are no errors, it just does not change the color map.

The documentation is also confusingly misformated for cmap and nearby options at:  
https://healpy.readthedocs.io/en/latest/generated/healpy.visufunc.mollview.html

My platform is CentOS 8, Python 3.6.8.

I actually have R, G, B values I would like to output as my own color, but there is no "truecolor" option like with cartview app?

**Comment by zonca** [comment]
too rude

**Comment by robspearman** [comment]
I am sorry if I was not clear.  I appreciate this project and your work, but these are real bugs that I am seeing.

Attached is a screenshot showing that there are missing spaces in the documentation link referenced (Firefox screenshot).

![bad-formatting](https://user-images.githubusercontent.com/2320065/85913106-a9f52d80-b7e6-11ea-8a74-cc0149e2cd54.png)
