### ISSUE TITLE
Healpy modifies default colormap

### ISSUE THREAD

**Issue by kadrlica** [healpy/healpy#622]
It appears that in some cases healpy modifies the users default matplolib colormap. This been a consistent behavior for at least a few years, but I figured it would be good to document.

The minimal working example is a bit complex, since the figures need to be rendered individually.
```
import numpy as np
import pylab as plt
plt.ion()

x=np.linspace(-10,10,51)
y=np.linspace(-10,10,51)
xx,yy = np.meshgrid(x,y)
zz=xx**2 + yy**2
zz = np.ma.array(zz, mask=zz<100)

plt.figure(); plt.title("Figure 1")
plt.imshow(zz)
```
The resulting figure is here (note that the nan pixels are rendered in white):
![fig1](https://user-images.githubusercontent.com/5605123/86488985-79eae480-bd28-11ea-91ca-48859fc53f51.png)

If you then import healpy (v1.13.0), draw a map, and then try to make the simple figure again, the nan values get rendered as gray.
```
import healpy as hp
pix = np.arange(hp.nside2npix(128))
hp.mollview(pix)

plt.figure(); plt.title("Figure 2")
plt.imshow(zz)
```
![fig2](https://user-images.githubusercontent.com/5605123/86489080-c504f780-bd28-11ea-97b8-6244dcb43415.png)

I'm guessing this is because `create_colormap` here:

https://github.com/healpy/healpy/blob/6dc4a6f825fd6dc5618121a62b67bc8d82ad0d78/healpy/projaxes.py#L891-L910

is modifying the "image.cmap" in place. Possibly even more confusing is that if you then try to get the colormap explicitly by name ("viridis" in this case), it is returning the same object, which has had it's badval updated.

```
plt.figure(); plt.title("Figure 3")
plt.imshow(zz,cmap='viridis)
```
![fig3](https://user-images.githubusercontent.com/5605123/86489568-5b85e880-bd2a-11ea-8989-25a15434af26.png)

I've confirmed that I can grab the viridis colormap and reset the colors for bad, over, and under values; however, I think that it would be preferable if healpy were not modifying matplotlib's builtin colormaps.

I've implemented a quick solution that just copies the built-in colormap before modifying and this appears to work. In particular, creating a deep copy [here](https://github.com/healpy/healpy/blob/6dc4a6f825fd6dc5618121a62b67bc8d82ad0d78/healpy/projaxes.py#L900) with something like:
```
import copy
cmap0 = copy.deepcopy(cmap0)
```

**Comment by zonca** [comment]
thanks, do you know what is the proper way to implement this?

**Comment by zonca** [comment]
oh, sorry, the `deepcopy` you are mentioning should work, would you create a PR with that?

**Comment by kadrlica** [comment]
Yeah, I can create a PR and a test.
