### ISSUE TITLE
Release of healpy 1.14.0

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#623]
I'd like to start preparing the release of healpy 1.14.0, jointly with a HEALPix release.
@hivon, @mreineck are you fine with that? what will be the HEALPix version tag?

can I get the current trunk from SVN as the HEALPix C++ that will released with the next version of HEALPix?

**Comment by mreineck** [comment]
No changes in Healpix C++ since the last healpy release, as far as I see :)

**Comment by hivon** [comment]
@mreineck : there was an edit in libsharp automake files to set the library version number, which changes the libsharp.so file name.
And how about the rotmatrix.h and pointing.h name conflicts discussed in https://sourceforge.net/p/healpix/bugs/104/ ?
Will we go with the suggested path specification for Heasoft or rather change the path to those *.h files ?

@zonca : the next Healpix release is 3.70 and should come out by July 17 (or July 24 at worst) or otherwise wait until late August.

**Comment by mreineck** [comment]
Ah, thanks for pointing this out ... somehow my `svn log` didn't show up anything relevant and I had forgotten about that change already! (It's getting hard to remember how svn works; I'm only using it a few times per year)

Concerning the header files: I'd leave them as they are for the moment.  I'm currently consolidating all my C++ code into a single directory structure (from which sub-packages can be extracted at need), and there I'm using a directory scheme and namespaces to avoid this kind of collision in the future. If you are interested, have a look at https://gitlab.mpcdf.mpg.de/mtr/ducc.
But this is still in an early stage, and the focus is currently on providing Python interfaces for the relevant functionality. I don't even have a working `autotools` machinery for it yet.

**Comment by zonca** [comment]
ok, thanks @hivon, not sure I'll make it by July,

anyway, sometime in July or August, I'll update the C++ sources with current trunk, finish up some of the open issues, and release 1.14.0

**Comment by hivon** [comment]
Hi @zonca,

do you have a clearer idea of when healpy 1.14 will be ready to ship out ?
As for Healpix it is either by July 26 (this Friday), or after Aug 24.
It would be better to avoid Healpix and healpy releases just 1 or 2 
weeks apart.

Cheers,
Eric

**Comment by zonca** [comment]
@hivon I'll let you know tomorrow

**Comment by zonca** [comment]
@hivon I'll release `healpy` 1.14.0 either today or tomorrow, then you can package it up into HEALPix on Friday

**Comment by hivon** [comment]
Hi @zonca,

thanks !
As you would guess, the sooner the better ;-)

**Comment by zonca** [comment]
sure, I am at a good point already, I'll release later today

**Comment by zonca** [comment]
ok

- [ ] source release on PyPI <https://pypi.org/project/healpy/1.14.0/>
- [ ] wheels on PyPI
- [ ] conda packages for Linux
- [ ] conda packages for Mac OS

**Comment by mreineck** [comment]
> main difference in the packaging is that building cfitsio now requires openssl.

I know I'm a bit late to mention this, but the jungle of dependencies that cfitsio has been growing lately is getting a bit out of hand...
When you are building it yourself, it might be an option to just configure it in such a way that it doesn't pull in openssl and libcurl etc. I don't expect many people will use `healpy` to load Healpix maps via https over the internet.

**Comment by zonca** [comment]
ok, thanks @lpsinger for making pypi wheels for Mac OS as well.

This release is included in HEALPix 3.70 https://healpix.sourceforge.io/downloads.php#SECTION_370_10000000000000000
