### ISSUE TITLE
Conda installation failing in MacOSX 10.15.5

### ISSUE THREAD

**Issue by fnoviello** [healpy/healpy#625]
Hi

I read in the installation guide that there are issues installing Healpy 1.13.0 in MacOSX 10.15.5 with pip and from source. 

Just to let you know I'm also experiencing issues with conda install, which just "hangs" when solving the environment (I had to keyboard interrupt the installation). I'm pasting a screenshot, should it help.

Thanks,
Fabio
----------------------------------------------------------------------------------------------------------------
(base) fabionoviello@Fabios-MacBook-Air ~ % conda activate env_healpy        

(env_healpy) fabionoviello@Fabios-MacBook-Air ~ % conda install healpy --channel conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

Collecting package metadata (repodata.json): done
Solving environment: / \ failed with initial frozen solve. Retrying with flexible solve.

(keyboard interrupt here)

**Comment by zonca** [comment]
can you test with a brand new environment?

**Comment by fnoviello** [comment]
That was a quick reply!

Actually env_healpy was brand new. Anyhow, I created a brand new env_healpy_2, with the same result. As a last resort, I've tried installing into base.

It's conda 4.8.2 btw, should it help.

thx, F

**Comment by zonca** [comment]
try:

    conda create --verbose -n env_healpy_3 python=3.7 healpy

and paste log here

**Comment by fnoviello** [comment]
This worked thx. The log file is attached for info. I've also tested my Healpy installation and it appears to be ok. 

I've run some tests and there appears to be some clash between conda install and this latest version of macOSX  (it doesn't seem to solve plenty of stuff, not just Healpy, and this also happens in the base environment). So, for instance, I then had to install Jupyter and Spyder via Navigator.

My personal suggestion (to be accepted/rejected by others) would be  to add the following workaround to the "installation" Healpy webpage (once conda-forge is added to the channel list:

conda create -- -n my_env python=3.7 healpy jupyter spyder 

(or whatever interface the end user might like). This would be, in my view, be the most direct way to install Healpy atm (especially for users who only installed mininconda). 

[conda_healpy_3_output copy.pdf](https://github.com/healpy/healpy/files/4907503/conda_healpy_3_output.copy.pdf)

**Comment by zonca** [comment]
Can you make a pull request to the installation docs to suggest this for
Mac osx?

**Comment by fnoviello** [comment]
Done.

**Comment by zonca** [comment]
thanks, see #629
