### ISSUE TITLE
healpy build failing in MacPorts 

### ISSUE THREAD

**Issue by olivierdore** [healpy/healpy#628]
Hello friends,

It looks like healpy does not build properly anymore with macport (it used to work just fine of course but I had to do a clean install for other reasons). I tried with several version of python (just in case) and the issue remains. The MacPorts team could reproduce this failure too. They suggest an issue with the latest numpy maybe but not sure.

The key line in the log is the following (it appears many times of course):
:info:build healpy/src/_healpy_pixel_lib.cc:400:3: error: address of
overloaded function 'ufunc_ang2pix' does not match required type 'void
(char **, const long *, const long *, void *)'
:info:build   ufunc_ang2pix<RING>
:info:build   ^~~~~~~~~~~~~~~~~~~
:info:build healpy/src/_healpy_pixel_lib.cc:42:3: note: candidate template
ignored: could not match 'void (char **, npy_intp *, npy_intp *, void *)'
(aka 'void (char **, long *, long *, void *)') against 'void (char **,
const long *, const long *, void *)'
:info:build   ufunc_ang2pix(char **args, npy_intp *dimensions, npy_intp
*steps, void *func)
:info:build   ^

Thanks!

Olivier 

PS: I attach the full log here.

[main.log](https://github.com/healpy/healpy/files/4907517/main.log)

**Comment by zonca** [comment]
Which version are you building?

**Comment by olivierdore** [comment]
Hey Andrea. The latest one from MacPorts which is 1.13.0 it seems. https://ports.macports.org/port/py38-healpy/summary

**Comment by zonca** [comment]
@mreineck any suggestion?

**Comment by mreineck** [comment]
This seems related to #624 and should be fixed already in the latest sources.

**Comment by zonca** [comment]
Ok, thanks, I'm going to release healpy 1.14 in the next weeks.

**Comment by olivierdore** [comment]
Thank you all for the quick answers. @zonca what do you suggest I do now?

**Comment by zonca** [comment]
Build from master

**Comment by zonca** [comment]
Or install a older version

**Comment by lpsinger** [comment]
I am the MacPorts maintainer of that port. Is there a MacPorts issue that I can refer to?

**Comment by lpsinger** [comment]
MacPorts issues should be reported here: https://github.com/macports/macports-ports

I was able to do a MacPorts build from source right now. If you are still having this problem, then please open a MacPorts issue, and I'll help you with it right away. Thanks!
