### ISSUE TITLE
cfitsio fails to build on conda-forge

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#634]
I am trying to build conda packages for `healpy`, but `cfitsio` fails to build.

The error is exactly the same I was getting when I updated to `cfitsio` to 3.47 (https://github.com/healpy/healpy/pull/597).

See the build log: https://gist.github.com/zonca/d916b96aa570ff2f52b5dca992ad35b0#file-log-txt-L2389

However, this is already using the patched version of `cfitsio.pc` which has `-lcurl`, so I don't understant what else could be wrong.

@mreineck would you have suggestions? thanks

**Comment by mreineck** [comment]
No clue whatsoever :-/
Is there any chance of accessing the `config.log` that was generated on the server during the build?

**Comment by lpsinger** [comment]
Isn't there a conda package for cfitsio? We should link against that.

**Comment by zonca** [comment]
Fixed

**Comment by Rigel7** [comment]
Hi, I am encountering the same problem. Can you tell me how did you fix it?
