### ISSUE TITLE
Documentation for Rotator.rotate_map_alms says [Q,U] is valid input

### ISSUE THREAD

**Issue by ashill** [healpy/healpy#636]
The documentation for `Rotator.rotate_map_alms` says that if the input map has 2 maps, they are considered [Q, U]. However, inputting two maps causes a crash because `map2alm` requires 1 or 3 maps if `pol` is true; it doesn't seem to accept only [Q,U] as an input.

**Comment by zonca** [comment]
thanks for reporting this, I had copied the docstring from the method in pixel space...
