### ISSUE TITLE
Using projscatter function in conjunction with mollview "sub" argument

### ISSUE THREAD

**Issue by MitaliDamle** [healpy/healpy#637]
Hello all,

I have a dataset for an ensemble of 3 different ions and 3 different simulations (so, in total, 9 different data sets) from which I generate mollview maps. I use the mollview map argument "sub" in order to place each of these 9 maps in a grid fashion, in one single matplotlib figure (akin to using the plt.subplot feature). 

I further want to also place some scatter points (for which I use hp.projscatter function) for each of these maps. Each set of the scatter points is unique to each individual mollview map. However, in the final plot, I get a 3x3 grid of mollview maps in a single figure but with ALL the scatter point sets showing up in each mollview map. 

Here is a snippet of my code: 

#List_PlotResultFile is a list of 9 previously saved hdf5 files containing data corresponding to each dataset.

for Ion_i in range(len(List_PlotResultFile)):
    PlotResultFile = List_PlotResultFile[Ion_i]
    Dict,Header = Misc.Papaya.ReadPapayaHDF5(PlotResultFile)

#Here I use the "sub" argument to place each individual mollview map within a single figure.

    HISkymap = hp.mollview(numpy.log10(Dict['x']), min=12.0, max=16.0,sub=int('33'+str(Ion_i+1)),cmap='RdYlBu_r',cbar=False,margins=(0.009,0.009,0.009,0.009)) 

#This is where the problem arises, wherein the scatter points for each individual dataset somehow end up appearing in all the mollview subplots.

    hp.projscatter(MW_Coords[Ion_i][0],MW_Coords[Ion_i][1],marker='o',s=2,color='black',facecolor='none') 
    hp.projscatter(M31_Coords[Ion_i][0],M31_Coords[Ion_i][1],marker='o',s=2,color='black',facecolor='none')
    hp.projtext(MW_Coords[Ion_i][0],MW_Coords[Ion_i][1],'MW',fontsize=6)
    hp.projtext(M31_Coords[Ion_i][0],M31_Coords[Ion_i][1],'M31',fontsize=6)

    fig = plt.gcf()
    ax = plt.gca()
    ax.text(0.86,0.05,ax.proj.coordsysstr,fontsize=5,fontweight='bold',transform=ax.transAxes)
    ax.set_title(r"$\log N_{\rm %s}$ [cm$^{-2}$]"%(Header['ThisAtom.Linename'].split('_')[0]),fontsize=10)
    image = ax.get_images()[0]
    cbar_ax = fig.add_axes([0.03, 0.028, 0.93, 0.016])
    cb = fig.colorbar(image, cax=cbar_ax,orientation='horizontal')
    font_size=5
    cb.ax.tick_params(direction='in', labelsize=font_size)

    hp.graticule()
    plt.savefig('OxygenSubplt.pdf')

I have attached the figure generated from this code, for reference.
[OxygenSubplt.pdf](https://github.com/healpy/healpy/files/5123342/OxygenSubplt.pdf)

I tried checking up on literature and possible such issues cropping up elsewhere on the internet but was unable to find any. 
Any help is much appreciated! Thanks in adv.

**Comment by zonca** [comment]
See https://github.com/healpy/healpy/issues/895
