### ISSUE TITLE
Inputting random seed for synfast in healpy (difference from HEALPix)

### ISSUE THREAD

**Issue by jyothischandran1597** [healpy/healpy#638]
While using synfast to check for the fact that the current estimators of mean and variance are good or not, I encountered a problem in creating n number of realizations with the theoretical CMB power spectrum. 

The problem was that synfast in healpy, unlike that in HEALPix, did not have an option to input the random seed in the function to ensure that each realization is different. BUT, I found out that if i call a different random seed suing numpy before calling the function, synfast will detect that random seed and use that for random number generation.

Another thing was that this difference between healpy and HEALPix functions were not mentioned in the documentation. It would be usefule for beginners starting directly from healpy and have not used HEALPix before for this information to be included in the healpy documentation.

**Comment by zonca** [comment]
thanks for suggesting this!
