### ISSUE TITLE
Use alice3 from HEALPix C++

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#639]
@mreineck included the `alice3` patches from #617 to support line integral convolution into HEALPix C++,
and I have updated the https://github.com/healpy/healpixmirror to the last version of HEALPix from SVN.

**NB**: `healpy` master is still pointing to the last released HEALPix and will change that only when HEALPix is ready for the next release.

It would be useful to have a Pull Request that:
* updates the `healpixsubmodule` to the tip of `healpixmirror`
* removes the C++ files added in https://github.com/healpy/healpy/pull/617
* properly imports directly from HEALPix C++

@mpetroff would you like to take care of this? no hurry, I'll need it in a couple of months.

**Comment by mpetroff** [comment]
Yes, I can look at this. I already have a partial patch in https://github.com/healpy/healpy/pull/617#issuecomment-662594550.
