### ISSUE TITLE
clip alm function

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#644]
@mreineck I wanted to add a simple function to clip a set of alms to a lower ellmax,
for the simple case of mmax=lmax, the code is:

```python
clipping_indices = []
for m in range(lclip+1):
    clipping_indices.append(hp.Alm.getidx(lmax, np.arange(m, lclip+1), m))
clipping_indices = np.concatenate(clipping_indices)
```

even for lclip 2000, it only takes 35ms to run.

is there something similar in HEALPix C++ or libsharp already? or should I just implement it in Python?

**Comment by mreineck** [comment]
No, there is currently no analogous functionality in the C/C++ codes. If this kind of clipping operation is needed there, I would just copy the relevant coefficients from one a_lm object to the other with a loop, and avoid the memory overhead for the index array.

**Comment by zonca** [comment]
see `resize_alm` https://github.com/healpy/healpy/blob/main/healpy/sphtfunc.py#L1437
