### ISSUE TITLE
Get higher resolution pixels from a list of indices

### ISSUE THREAD

**Issue by Algirdyz** [healpy/healpy#647]
Given a list of indices and an NSIDE, is there a function that returns a list of indices for a much higher NSIDE?

I've tried using `ud_grade` but it seems to require the entire map to work and I only need to upgrade a small amount of pixels. If I use the whole map at the NSIDE I need, i just run out of memory.

**Comment by mreineck** [comment]
If you are using NESTED scheme, you can compute this trivially. If you have index `i` at `nside1`, and you want all corresponding indices at a higher `nside2`, then the result is the interval `[i<<(2*(nside2-nside1)); (i+1)<<(2*(nside2-nside1))[`.
In RING scheme things are admittedly a bit more complicated.

**Comment by mreineck** [comment]
Hmm, in RING scheme,  you could simply do a `ring2nest` before and a `nest2ring` afterwards ... this is pobably also what I would do inside the library.

**Comment by Algirdyz** [comment]
Thanks for the reply!

Is that interval correct?

If my high res nside is 2^19 and low res 2^10, the bitshift is gonna be a bit high...
Or am I misunderstanding something?

**Comment by mreineck** [comment]
Ah, sorry, I was thinking in terms of "map order", not `nside`. The map order is simply `log_2(nside)`.
So basically for each doubling in `nside` you get a factor 4 in pixel index.
Oops :-)

**Comment by Algirdyz** [comment]
OK I see. This works!

Thanks a lot!
