### ISSUE TITLE
ValueError: truth value of numpy boolean array is ambiguous 

### ISSUE THREAD

**Issue by Sebastian-Belkner** [healpy/healpy#651]
**Issue**
When using a map with an UNSEEN pixel, `_sphtools.pyx` throws an error at [L115](https://github.com/healpy/healpy/blob/39b74fb4e69d5180be769318f20f4875ad713aa2/healpy/src/_sphtools.pyx#L115).

This does not happen, when I use maps without UNSEEN pixels (e.g. any of the other lightweight maps)

**Usage**
Q and U maps of the lightweight [100Ghz Planck-map](http://pla.esac.esa.int/pla/#maps) and [healpy.map2alm_spin()](https://github.com/healpy/healpy/blob/39b74fb4e69d5180be769318f20f4875ad713aa2/healpy/src/_sphtools.pyx#L68).

Error:
` File "XXX", line 21, in map2alm_spin
    return hp.map2alm_spin(maps, spin, lmax=lmax, mmax=mmax)
  File "healpy/src/_sphtools.pyx", line 115, in healpy._sphtools.map2alm_spin_healpy
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Why**
Checking for UNSEEN pixels of both, the Q and U maps, indeed give me a single, unseen pixel.
This shouldn't be an issue for healpy, as `_sphtools.pyx`  deals with UNSEEN pixels by setting them to 0.0, but L115 makes a truth comparison on a numpy boolean array, which is ambigious.

**Fix**
Perhaps, one could change L115 to:
`if mask.any():`

**Comment by zonca** [comment]
thanks @Sebastian-Belkner 
can you please provide a snippet of code that shows the error?

**Comment by Sebastian-Belkner** [comment]
**Input**
```
import healpy as hp
q = hp.read_map("data/map/frequency/HFI_SkyMap_100-field_2048_R3.00_full.fits", field=1, dtype=None)
u = hp.read_map("data/map/frequency/HFI_SkyMap_100-field_2048_R3.00_full.fits", field=2, dtype=None)
pnside = hp.npix2nside(q.size)
lmax = 4000
lmax_mask = 8000
elm, blm = hp.map2alm_spin(
    [q, u],
    2,
    lmax=min(3 * pnside - 1, lmax + lmax_mask))
```

**Output**
```
Traceback (most recent call last):
  File "test/snippet.py", line 10, in <module>
    elm, blm = hp.map2alm_spin(
  File "healpy/src/_sphtools.pyx", line 115, in healpy._sphtools.map2alm_spin_healpy
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by zonca** [comment]
test snippet:

```
import numpy as np
import healpy as hp
m = np.ones((2, 12))
print(hp.map2alm_spin(m, 2))
m[1][2] = hp.UNSEEN
print(hp.map2alm_spin(m, 2))
```

thanks it should be fixed now
