### ISSUE TITLE
Is pixel window function applied to hp.anafast result by default?

### ISSUE THREAD

**Issue by SergeiDBykov** [healpy/healpy#653]
Hello and thanks for the great package healpy!

I was wondering if [the pixel window function](https://healpix.jpl.nasa.gov/html/intronode14.htm), which modifies the true underlying angular power spectrum, is applied to the results of anafast function by default? 

Let me demonstrate it in a simple example:

It is known that the poisson distribution of sources on the sky has a flat (constant) angular power spectrum (so called shot-noise). I am trying to check if it is true by healpy and it is indeed true, but only if I use the results of anafast witout dividing by the square of the pixel window function power spectrum wl (see link above).

In the code below I create poissonian map and calculate the power spectrum of it.

```
import numpy as np
from numpy import rad2deg
import healpy as hp
import matplotlib.pyplot as plt

def cat2hpx(lon, lat, nside=16385):
    """
    https://stackoverflow.com/questions/50483279/make-a-2d-histogram-with-healpix-pixellization-using-healpy
    Convert a catalogue to a HEALPix map of number counts per resolution
    element.

    Parameters
    ----------
    lon, lat : (ndarray, ndarray)
        Coordinates of the sources in degree. If radec=True, assume input is in the icrs
        coordinate system. Otherwise assume input is glon, glat

    nside : int
        HEALPix nside of the target map

    radec : bool
        Switch between R.A./Dec and glon/glat as input coordinate system.

    Return
    ------
    hpx_map : ndarray
        HEALPix map of the catalogue number counts in Galactic coordinates

    """

    npix = hp.nside2npix(nside)

    l, b = lon, lat

    # conver to theta, phi
    theta = np.radians(90. - b)
    phi = np.radians(l)

    # convert to HEALPix indices
    indices = hp.ang2pix(nside, theta, phi)

    idx, counts = np.unique(indices, return_counts=True)

    # fill the fullsky map
    hpx_map = np.zeros(npix, dtype=int)
    hpx_map[idx] = counts

    return hpx_map



nside=128



N=10000 #number of random sources

phi = np.random.rand(N)*2*np.pi  #uniform azimuthal angle
theta=np.arccos(np.random.uniform(-1,1,N)) #longitude angle, for unifrom distribution on the sphere



wl=hp.pixwin(nside) #pixel window function

hpx_map = cat2hpx(np.rad2deg(phi), 90-np.rad2deg(theta), nside=nside) #create healpy map of sources

hp.mollview(hpx_map,remove_mono=False,remove_dip=False,title='Poisson data',unit='sources / healpy pixel')


fig=plt.figure()
cl = hp.anafast(hpx_map,pol=False) #calculating ang. power spectrum
laxis=np.arange(len(cl))
plt.loglog(laxis,cl,label='anafast Cl')
plt.loglog(laxis,cl/wl**2,label='anafast Cl / wl^2') #cl but divided by the square of pixel window function

plt.xlabel('l')
plt.ylabel('C_l')
plt.legend()

```
the results are
sky map:
![issue_sky](https://user-images.githubusercontent.com/60148493/105217596-5bc5c400-5b54-11eb-9625-d04e46355c6e.png)

power spectrum: 

![issue_cl](https://user-images.githubusercontent.com/60148493/105218546-92e8a500-5b55-11eb-85e3-29e909350a40.png)

It is clear that the the pixel window function drags a flat spectrum upwards significantly, even within l<2*nside region.

Thus my question is: does anafast apply pixel window correction by default? I see no arguments controlling this, so I suppose it does not.

**Comment by DanielLenz** [comment]
> Thus my question is: does anafast apply pixel window correction by default? I see no arguments controlling this, so I suppose it does not.

That is correct, `anafast` does not correct for the pixel window function. The map that you generate in your example is not convolved with the pixel window function either, so simply applying anafast to compute the power spectrum yields the expected flat curve.

**Comment by SergeiDBykov** [comment]
Thank you very much @DanielLenz.
