### ISSUE TITLE
Odd results when smoothing polarisation maps

### ISSUE THREAD

**Issue by mpeel** [healpy/healpy#672]
I've been testing the different ways to smooth polarisation maps, and have come across an inconsistency that I'm not sure what to make of. I've been using 'wmap_band_iqumap_r9_9yr_K_v5.fits' as a test case, adding 1° of smoothing. I have four methods I've been comparing:

METHOD 1: smooth each map independently
maps = hp.read_map('wmap_band_iqumap_r9_9yr_K_v5.fits',field=(0,1,2))
alms = hp.map2alm(maps)
for i in range(0,3):
	alms[i] = hp.sphtfunc.smoothalm(alms[i], fwhm=1.0*np.pi/180.0,pol=False)
newmap = hp.alm2map(alms, nside,verbose=False)

METHOD 2: smooth all maps at once
maps = hp.read_map('wmap_band_iqumap_r9_9yr_K_v5.fits',field=(0,1,2))
alms = hp.map2alm(maps)
alms = hp.sphtfunc.smoothalm(alms, fwhm=1.0*np.pi/180.0,pol=False)
newmap2 = hp.alm2map(alms, nside,verbose=False)

METHOD 3: smooth all maps at once, with pol=True
maps = hp.read_map(inmap,field=(0,1,2))
alms = hp.map2alm(maps)
alms = hp.sphtfunc.smoothalm(alms, fwhm=1.0*np.pi/180.0,pol=True)
newmap3 = hp.alm2map(alms, nside,verbose=False)

METHOD 4: use smoothing_cxx (v3.50)
smoothing_cxx infile=wmap_band_iqumap_r9_9yr_K_v5.fits fwhm_arcmin=60.0 outfile=test_smooth_wmap.fits polarisation=true nlmax=1536

Methods 1 and 2 agree with each other. Methods 3 and 4 also agree with each other. Method 4 is what people have been using for years, I believe (if you don't set polarisation=true then it just smooths the intensity map). However, the Healpy documentation for smoothalm says 'pol : bool, optional If True, assumes input alms are TEB. Output will be TQU maps.' In this case, the input maps are TQU, so pol should be False?

The difference is nominally due to whether you include spin or not, which is 2 for polarisation and 0 for intensity. However, isn't that only for polarisation if it is EB not QU?

Either something's gone wrong in the Healpy documentation, or something has been coded incorrectly in Healpix for quite a while - or I'm completely misunderstanding what's happening!

**Comment by mreineck** [comment]
Whenever you convert TQU maps to a_lm with pol=True, you get TEB a_lm (there is no QU in the spherical harmonic domain, as far as I understand). So the documentation is correct, I think.

**Comment by mreineck** [comment]
Concerning methods 1 and 2: I'm pretty sure you should never do any processing on a Q or U map on its own; it always has to be processed together with the other component. Note that you inadvertently do this even in methods 1 and 2, but only in the `map2alm` direction, since you are not setting `pol` to `False` explicitly.

**Comment by mpeel** [comment]
Ah, OK, I didn't realise map2alm had pol=True by default, and that it generated TEB a_lm.. Normally I convert each map (I, Q, U) into alms separately to smooth them, which is what I was trying to demonstrate in method 1, but if I code that then I do get different results from the other methods anyway... Sounds like I need to rewrite my code. :(

**Comment by mreineck** [comment]
> Sounds like I need to rewrite my code. :(

Yes, I fear so ... this is an aspect that I didn't grasp either for quite some time: Q/U and E/B are so tightly intertwined that they should always be treated as a single quantity.
(There is one exception: E and B a_lm can be rotated separately in spherical harmonic space without breaking anything.)

**Comment by mpeel** [comment]
All recoded and seems to be working OK now. Thanks for your help!
