### ISSUE TITLE
healpy enabling warnings

### ISSUE THREAD

**Issue by kadrlica** [healpy/healpy#675]
This is a continuation of discussions about the default verbosity (#619) and the implementation of the `warnings` module to control verbosity (#630).  

I've found that [healpy.enable_warnings](https://github.com/healpy/healpy/blob/8b853d89062f0f704231dbc2770ea29028beacbc/healpy/__init__.py#L121) resets other UserWarning filters outside the healpy module. Looking at the code, this isn't surprising:

https://github.com/healpy/healpy/blob/8b853d89062f0f704231dbc2770ea29028beacbc/healpy/__init__.py#L121-L122

A simple example:
```
import warnings
import healpy as hp

warnings.simplefilter("ignore", category=UserWarning)
warnings.warn("Warning 1") # this is ignored

hp.enable_warnings()
warnings.warn("Warning 2") # this is not ignored
```

I don't think this is the desired behavior. I think that `hp.enable_warnings` should be the inverse of `hp.disable_warnings` and should act only on warnings from the `healpy` module.

**Comment by zonca** [comment]
Sure, would you be able to provide a pull request fixing this?

**Comment by lpsinger** [comment]
IMHO, Healpy rather overdoes it with warnings. I think in many cases, what are presented as warnings should in fact be log messages presented with the `logging` module, and hidden by default (eg. debug level). I subscribe to the opinion that libraries should be silent by default.

**Comment by kadrlica** [comment]
I was not going to get into this, but... I completely agree with @lpsinger and @adrn about both the verbosity and (mis)use of `warnings`. I think that the `logging` module is the way to go. Novice users (the undergrads I work with for example) freak out when they get blasted with warnings...

**Comment by kadrlica** [comment]
Regarding the PR, I'm not an expert on warning control, but would it be enough to just invert the `disable_warnings` call? This implementation seems to work on my simple test case (at least as a monkey patch). However, I'm not sure if it is turning on other warnings that we don't want to turn on. Any idea what tests we'd want to implement?

```
def enable_warnings():
    warnings.filterwarnings(action="always", module="healpy")
```

**Comment by zonca** [comment]
see #679
