### ISSUE TITLE
Suggestion for experimenting: improved map analysis

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#676]
The code below implements a new approach at map analysis which should be more intuitive to use and also faster in many cases. Instead of specifying iterations, the user rather specifies a tolerance (measured as the L2 norm of the residual a_lm divided by the L2 norm of the result), and the algorithm iterates until this threshold is reached (or an iteration limit is reached, which can also be specified by the user).
As iteration scheme, the conugate gradient method is employed, which is much more efficient than the one currently used by all Healpix implementations. Its only drawback is that it needs more temporary variables and therefore consumes somewhat more memory during iteration; I have tried to limit this as much as possible, which makes the code look a bit awkward in places.
I'm not using an off-the-shelf algorithm from e.g. `scipy` to demonstrate that the entire algorithm is fairly compact and can easily be implemented in many programming languages if necessary.

Comments very welcome!

```
def hp_map_analysis(map, lmax, mmax, tol=1e-10, maxiter=20):
    alm = healpy.map2alm(map, lmax, mmax, iter=0)
    almnorm = np.vdot(alm,alm).real
    nalm = alm.shape[0]
    nside = healpy.npix2nside(map.shape[0])
    op = lambda x: healpy.map2alm(healpy.alm2map(x, nside, lmax, mmax),
                                  lmax, mmax, iter=0)

    # check if we are fine with just standard map2alm
    # (tol value still needs tuning!)
    if lmax <= 2*nside and tol>=1e-3:
        return alm

    r = op(alm)
    r *= -1
    r += alm
    rdotr = np.vdot(r,r).real
    print(np.sqrt(rdotr/almnorm))
    if rdotr <= tol**2*almnorm:
        return alm

    p = r.copy()
    iter = 1
    while iter<maxiter:
        iter += 1
        apk = op(p)
        alpha = rdotr/np.vdot(p, apk).real
        apk *= alpha
        r -= apk
        del apk
        p *= alpha
        alm += p
        rdotr_old = rdotr
        rdotr = np.vdot(r,r).real
        print(np.sqrt(rdotr/almnorm))
        if rdotr <= tol**2*almnorm:
            return alm
        beta = rdotr/rdotr_old
        p *= beta/alpha
        p += r

    return alm
```

**Comment by zonca** [comment]
Thanks, I think it would be useful to look at a version using `scipy`

**Comment by mreineck** [comment]
Sure, here it is:
```
def hp_map_analysis_scipy(map, lmax, mmax, tol=1e-10, maxiter=20):
    import scipy.linalg
    import scipy.sparse

    almtmp = healpy.map2alm(map, lmax, mmax)
    nalm = almtmp.shape[0]
    nside = healpy.npix2nside(map.shape[0])

    # check if we are fine with just standard map2alm
    # (tol value still needs tuning!)
    if lmax <= 2*nside and tol>=1e-3:
        return almtmp

    # build the square "map2alm*alm2map" operator
    def apply(almx):
        return healpy.map2alm(healpy.alm2map(almx, nside, lmax, mmax),
                              lmax, mmax)
    op = scipy.sparse.linalg.LinearOperator(shape=(nalm,nalm), matvec=apply,
                                            dtype=np.complex128)

    # solve CG on the normal equations
    alm, _ = linalg.cg(op, almtmp, x0=almtmp, tol=tol, atol=0., maxiter=maxiter)
    return alm
```

**Comment by mreineck** [comment]
Sorry, this is still broken, because the `map2alm` calls contain iterations. Will fix asap.

**Comment by mreineck** [comment]
I don't understand why, but I don't get the `scipy` version to work when I set the number of iterations to 0. I fear I'll need more time to debug this.
Meanwhile the first version should be a good demonstration of the capabilities at least...

**Comment by mreineck** [comment]
OK, it seems that the minimization problem has to be fed into `scipy` as real-valued, not complex-valued...

```
def hp_map_analysis_scipy(map, lmax, mmax, tol=1e-10, maxiter=20):
    import scipy.linalg
    import scipy.sparse

    nside = healpy.npix2nside(map.shape[0])
    alm = healpy.map2alm(map, lmax, mmax, iter=0)
    nalm = alm.shape[0]

    # check if we are fine with just standard map2alm
    # (tol value still needs tuning!)
    if lmax <= 2*nside and tol>=1e-3:
        return alm

    # build the square "map2alm*alm2map" operator
    def apply(x):
        return healpy.map2alm(healpy.alm2map(x.view(np.complex128), nside, lmax, mmax),
                              lmax, mmax, iter=0).view(np.float64)
    op = scipy.sparse.linalg.LinearOperator(shape=(2*nalm,2*nalm), matvec=apply,
                                            dtype=np.float64)

    # solve CG on the normal equations
    alm, _ = scipy.sparse.linalg.cg(op, alm.view(np.float64), x0=alm.view(np.float64), tol=tol, atol=0., maxiter=maxiter)
    return alm.view(np.complex128)
```

**Comment by mreineck** [comment]
Here is a version that takes care of the fact that a_lm with m=0 should only have half the weight of the others, This improves convergence at lower `lmax/nside` but makes no real difference otherwise.

```
def hp_map_analysis2(map, lmax, mmax, tol=1e-10, maxiter=20):
    nside = healpy.npix2nside(map.shape[0])
    a2m = lambda x: healpy.alm2map(x, nside, lmax, mmax)
    m2a = lambda x: healpy.map2alm(x, lmax, mmax, iter=0)
    op = lambda x: m2a(a2m(x))
    almdot = lambda a1, a2 : (np.vdot(a1[:lmax+1],a2[:lmax+1]) + 2*np.vdot(a1[lmax+1:],a2[lmax+1:])).real

    alm = m2a(map)
    almnorm = almdot(alm,alm)
    nalm = alm.shape[0]

    # check if we are fine with just standard map2alm
    # (tol value still needs tuning!)
    if lmax <= 2*nside and tol>=1e-3:
        return alm

    r = op(alm)
    r *= -1
    r += alm
    rdotr = almdot(r,r)
    if rdotr <= tol**2*almnorm:
        return alm

    p = r.copy()
    iter = 1
    while iter < maxiter:
        iter += 1
        apk = op(p)
        alpha = rdotr/almdot(p, apk)
        apk *= alpha
        r -= apk
        del apk
        p *= alpha
        alm += p
        rdotr_old = rdotr
        rdotr = almdot(r,r)
        if rdotr <= tol**2*almnorm:
            return alm
        beta = rdotr/rdotr_old
        p *= beta/alpha
        p += r

    return alm
```

**Comment by mreineck** [comment]
I think it would be a great project for any mathematically-inclined student to think about a good preconditioner for the minimization above. If there is one, it may indeed become possible to go up to `lmax=3*Nside`, which would be a big step forward for many projects.

**Comment by mreineck** [comment]
There don't seem to be any volunteers for the preconditioner ...
Still, I believe that the code in its current form is a strict improvement over the iterative map analysis which is currently available in `healpy`. @zonca, do you think we could/should provide this as some additional option in map2alm,or maybe as a standalone function?

**Comment by zonca** [comment]
yes, I would suggest an option for `map2alm` and make it also available in `anafast`

**Comment by ntessore** [comment]
@mreineck From the above and #725 it sounds as if this is the best (only?) option to get angular power spectra at 2.5 NSIDE, is that true?

If so, is there anything that can be done to get the adaptive code ready for production use? Is looking at the minimisation still relevant?

**Comment by mreineck** [comment]
> @mreineck From the above and #725 it sounds as if this is the best (only?) option to get angular power spectra at 2.5 NSIDE, is that true?

I would say yes. In principle it's of course also possible to use the traditional iterative analysis, but that should be much more expensive.

> If so, is there anything that can be done to get the adaptive code ready for production use?

I would already trust the latest code snippet above for production use. If it has remaining weaknesses, we'll probably only find them in specific real-life situations.

Of course the question remains what will happen if one tries to analyze a map which is intrinsically not bandlimited. In that case the above code will most likely run for the maximum iterations and then return an incorrect result. On the other hand, no other method will produce a correct result either, because it simply does not exist...

> Is looking at the minimisation still relevant?

For lmax=2.5*Nside not so much, though saving one or two iterations is of course always nice. With a better preconditioner it may just be possible to move the "pain threshold" closer to lmax=3*Nside.

**Comment by ntessore** [comment]
Doing some quick real world usage in my project, I'm not getting as good results from this function. I haven't spent too much time analysing what I'm seeing, but I believe it might be due to that we are in fact solving `m2a(map) - op(alm)`. Since `m2a` is not injective, having `alm == m2a(map)` does not necessarily mean we have found the alm of the given map, but perhaps of a slightly different map `map'` with `m2a(map) == m2a(map')`.

An experiment seems to bear this out:

```py
nside = 32
lmax = 3*nside - 1

print(f'# nside = {nside}')
print(f'# lmax = {lmax}')

alm = np.zeros(hp.Alm.getsize(lmax), dtype=complex)
alm.real = np.random.randn(alm.size)
alm.imag[lmax+1:] = np.random.randn(alm.size-lmax-1)

a2m = hp.alm2map(alm, nside)
m2a = hp.map2alm(a2m, iter=0)

alm_cg = hp_map_analysis2(a2m, lmax, lmax, maxiter=100000)
a2m_cg = hp.alm2map(alm_cg, nside)
m2a_cg = hp.map2alm(a2m_cg, iter=0)

print('# ---')
print('# conjugate gradient')
print(f'# iter = {iter}')
print(f'# Δalm = {np.max(np.abs(alm_cg - alm))} at (l, m) = {hp.Alm.getlm(lmax, np.argmax(np.abs(alm_cg - alm)))}')
print(f'# Δa2m = {np.max(np.abs(a2m_cg - a2m))}')
print(f'# Δm2a = {np.max(np.abs(m2a_cg - m2a))} at (l, m) = {hp.Alm.getlm(lmax, np.argmax(np.abs(m2a_cg - m2a)))}')

# nside = 32
# lmax = 95
# ---
# conjugate gradient
# iter = 274
# Δalm = 9.701440378273797e-07 at (l, m) = (85, 49)
# Δa2m = 3.0144725648995063e-07
# Δm2a = 1.008406262991991e-09 at (l, m) = (95, 42)
```

To verify that a good solution could be found, here's the same result for a dense LS estimate (which is much too large to be useful):
```py
# ---
# dense least squares
# Δalm = 3.2104455710661537e-14 at (l, m) = (87, 47)
# Δa2m = 8.43769498715119e-13
# Δm2a = 2.3092638912203256e-14 at (l, m) = (69, 0)
```

The point is the difference in the CG method between `Δalm` and `Δm2a`, i.e. the error in the alm before and after passing through `m2a`. The difference appears to get bigger for higher `nside` values.

```py
# nside = 64
# lmax = 191
# ---
# conjugate gradient
# iter = 9096
# Δalm = 0.013717963829609745 at (l, m) = (165, 86)
# Δa2m = 6.153781531992308e-05
# Δm2a = 1.794894399842444e-09 at (l, m) = (191, 132)
```

Like I said, I haven't put too much thought into this, so it might not be relevant in the end. But if the above was a problem, it might be worth looking into `op(x) = a2m(m2a(x))`, even though that is rank-deficient,

(Of course, the ideal case would be a sparse least squares solution with `op(x) = a2m(x)`, but how to do that without the transpose operation?)

**Comment by ntessore** [comment]
> `m2a` only has a useful meaning for maps that are band-limited to the `lmax` in question, and for those the correspondence between map and `a_lm` should be one-to-one.

While that's true for the ideal `map2alm`, I am specifically thinking the nonideal `m2a(x) = map2alm(x, iter=0)` operation is the problem. Because if we have good initial `alm` to compare against, e.g. because `lmax` is not at the limit, there's no need for any of this.

> As far as I can see, the situation improves quickly when lmax is reduced, and greater accuracy can also be obtained by tweaking the `tol` parameter.

Isn't the point of this approaching the `lmax = 3*nside` limit, though? And tweaking the tolerance doesn't improve matters, see the latter example for CG. The difference in alm is 7 orders of magnitude higher than the stated tolerance.

**Comment by mreineck** [comment]
We may be talking at cros-purposes here, because I'm not absolutely sure I understand your argumentation ... if so, let me apologize in advance!

> While that's true for the ideal map2alm, I am specifically thinking the nonideal m2a(x) = map2alm(x, iter=0) operation is the problem. Because if we have good initial alm to compare against, e.g. because lmax is not at the limit, there's no need for any of this.

My problem is that we have no clear definition of what `map2alm(x, iter=0)` should do; all we have is "this should provide some sort of approximation to the inverse of `map2alm`"; even without iteration, `healpy` provides several different implementations for it, depending on which weights are chosen. And even for lmax far beyond the theoretical limit, the result of `map2alm(alm2map(x),iter=0)` will always differ from the input `x` by an appreciable amount; far more than can be explained by just numerical noise. This is a fundamental consequence of the HEALPix tesselation and can only be fixed up to `lmax=1.5*lmax` using pixel weights.

> Isn't the point of this approaching the lmax = 3*nside limit, though?

I'd say pushing this limit is not of interest in real-world code. Instead of spending huge amounts of time trying to squeeze out the last bit of information from a map at given `nside`, why not just work at higher `nside`? The individual transforms will be more expensive, but the much smaller amount of iterations required will lead to an overall reduction of CPU time.

This is also thereason why I never understood the default value of lmax in `healpy's` SHT functions; they potentially lead users to wrong conclusions how they should choose their map sizes and band limits.

> And tweaking the tolerance doesn't improve matters, see the latter example for CG. The difference in alm is 7 orders of magnitude higher than the stated tolerance.

On the spherical harmonic side, yes. But in the real-world case the user doesn't know the `a_lm` beforehand and simply asks "give me a set of a_lm that produces my map to some given accuracy"; the only comparison criterion can be how closely the maps match, and for an ill-conditioned system it's quite possible that you get extremely similar maps with really different `a_lm`.

**Comment by mreineck** [comment]
I have started thinking about this once more...

> My problem is that we have no clear definition of what `map2alm(x, iter=0)` should do

Perhaps a good definition for `map2alm` would be: provide the set of `a_lm` which, when converted to a map with `alm2map` will have (within a user-provided tolerance) the smallest possible quadratic difference over all pixels in question. This is also valid in non-bandlimited cases.

Note that this definition can easily be generalized to partial maps; here the quadratic difference in masked-out pixels is multiplied by 0 (or if the mask is unsharp, by a factor between 0 and 1).

I wonder whether this can be useful in situations where apodization is currently performed; with this iterative approach apodization should be no longer necessary.

There are specific minimization algorithms for this kind of problem: see, e.g. https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lsmr.html and https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lsqr.html

**Comment by ntessore** [comment]
@mreineck That was also my goal, to have a least squares solution in the sense of `|map - alm2map(alm)|^2`, which is what you do for any family of orthogonal polynomials. My problem was obtaining the transpose linear operator, since building the Vandermonde matrix explicitly isn't feasible. But that would be much nicer than "squaring" the linear operation by transforming back and forth.

**Comment by mreineck** [comment]
But we have the transpose (or rather adjoint) linear operator to `alm2map` ... it's actually `map2alm` with no weights and no iterations, multiplied by `npix/(4*pi)`.
There are a few technicalities to be observed, since `alm2map` takes a complex-valued input and produces a real-valued output, but these can be workedaround quite easily.

**Comment by mreineck** [comment]
The advantage of `lsqr/lsmr` over the algorithm above is that it recognizes when it has reached a solution, which is not a perfect inverse, but least squares, and does not iterate forever if the map is not band limited. I'll try to provide a demo code for this.

**Comment by mreineck** [comment]
Here is a version calling the `scipy` algorithm.
(If you have `ducc0` installed, you can set `use_ducc0=True` for hopefully faster SHTs.)

```
import healpy as hp
import numpy as np

use_ducc0 = False
if use_ducc0:
    import ducc0


# helper functions to convert between real- and complex-valued a_lm
def alm2realalm(alm, lmax):
    res = np.zeros(len(alm)*2-lmax-1)
    res[0:lmax+1] = alm[0:lmax+1].real
    res[lmax+1:] = alm[lmax+1:].view(np.float64)*np.sqrt(2.)
    return res

def realalm2alm(alm, lmax):
    res = np.zeros((len(alm)+lmax+1)//2, dtype=np.complex128)
    res[0:lmax+1] = alm[0:lmax+1]
    res[lmax+1:] = alm[lmax+1:].view(np.complex128)*(np.sqrt(2.)/2)
    return res

def hp_map_analysis_lsq(map, lmax, mmax, tol=1e-10, maxiter=20, nthreads=1):
    from scipy.sparse.linalg import LinearOperator, lsqr, lsmr
    nside = hp.npix2nside(map.shape[0])
    def a2m2(x):
        if use_ducc0:
            base = ducc0.healpix.Healpix_Base(nside, "RING")
            geom = base.sht_info()
            talm = realalm2alm(x, lmax).reshape((1,-1))
            return ducc0.sht.experimental.synthesis(alm=talm, lmax=lmax, spin=0, nthreads=nthreads, **geom)[0]
        else:
            talm = realalm2alm(x, lmax)
            return hp.alm2map(talm, lmax=lmax, nside=nside)
    def m2a2(x):
        if use_ducc0:
            base = ducc0.healpix.Healpix_Base(nside, "RING")
            geom = base.sht_info()
            talm = ducc0.sht.experimental.adjoint_synthesis(map=x.reshape((1,-1)), lmax=lmax, spin=0, nthreads=nthreads, **geom)[0]
        else:
            talm = hp.map2alm(x, lmax=lmax, iter=0)*((12*nside**2)/(4*np.pi))
        return alm2realalm(talm, lmax)

    #initial guess
    alm0 = m2a2(map)/len(map)*(4*np.pi)
    op = LinearOperator(matvec=a2m2, rmatvec=m2a2, shape=(len(map),len(alm0)))
    res = lsqr(A=op, b=map, x0=alm0, atol=tol, btol=tol, iter_lim=maxiter, show=True)
#    res = lsmr(A=op, b=map, x0=alm0, atol=tol, btol=tol, maxiter=maxiter, show=True)
    return realalm2alm(res[0], lmax)

np.random.seed(42)
nside = 1024
lmax = int(2.2*nside)
iter = 30


print(f'# nside = {nside}')
print(f'# lmax = {lmax}')


alm = np.zeros(hp.Alm.getsize(lmax), dtype=complex)
alm.real = np.random.randn(alm.size)
alm.imag[lmax+1:] = np.random.randn(alm.size-lmax-1)

a2m = hp.alm2map(alm, nside)
#a2m[0] = 5
#a2m = np.random.normal(size=len(a2m))
m2a = hp.map2alm(a2m, lmax=lmax, iter=0)

alm_cg = hp_map_analysis_lsq(a2m, lmax, lmax, tol=1e-12, maxiter=iter, nthreads=8)
a2m_cg = hp.alm2map(alm_cg, nside)
m2a_cg = hp.map2alm(a2m_cg, lmax=lmax, iter=0)

print('# ---')
print('# conjugate gradient')
print(f'# iter = {iter}')
print(f'# Δalm = {np.max(np.abs(alm_cg - alm))} at (l, m) = {hp.Alm.getlm(lmax, np.argmax(np.abs(alm_cg - alm)))}')
print(f'# Δa2m = {np.max(np.abs(a2m_cg - a2m))}')
print(f'# Δm2a = {np.max(np.abs(m2a_cg - m2a))} at (l, m) = {hp.Alm.getlm(lmax, np.argmax(np.abs(m2a_cg - m2a)))}')
```

**Comment by ntessore** [comment]
> But we have the transpose (or rather adjoint) linear operator to `alm2map` ... it's actually `map2alm` with no weights and no iterations, multiplied by `npix/(4*pi)`.

I don't see how this is true, in the sense that I don't understand it, not that I don't believe it. Do you have simple explanation or a reference for this?

**Comment by mreineck** [comment]
I don't think that a clear reference exists. But I know (from implementing the algorithms several times over the last 15 years or so) that the algorithmic steps in `map2alm` are simply the adjoint steps from `alm2map` in reverse order.

You can test the two operations for adjointness using the method from
http://sepwww.stanford.edu/sep/prof/pvi/conj/paper_html/node9.html

As I said, special care must be taken for the `a_lm` side, because they are complex and we are omitting some values due to symmetr reasons. But with the "real" a_lm from the example above, the test should work fine.

**Comment by mreineck** [comment]
There is a very short mention of adjoint synthesis vs. analysis in section 4.5 of https://arxiv.org/abs/1303.4945.

**Comment by ntessore** [comment]
That is fantastic, thank you for this information.

FWIW my function using lsmr, which didn't work because I missed the npix/4pi scaling, is essentially the same as yours. Using the correct scaling, it seems to be quite fast and robust!

**Comment by mreineck** [comment]
Here is a self-contained version of the function, with the kind of interface I'd propose for `healpy`. It does not only return the computed `alm`, but also a measure how well they approximate the input map.
Still missing: The same functionality for nonzero spins.

```
def hp_map_analysis_lsq(map, lmax, mmax, tol=1e-10, maxiter=20):
    """Runs an iterative map analysis up to (lmax, mmax) and returns the result
    including its quality

    Parameters
    ----------
    map : numpy.ndarray(float)
        The input map
    lmax, mmax : int
        The desired lmax and mmax parameters for the analysis
    tol : float
        The desired accuracy for the result. Once this is reached, the iteration
        stops.
    maxiter : int
        maximum iteration count after which the minimization is stopped

    Returns
    -------
    alm : numpy.ndarray(complex)
        The reconstructed a_lm coefficients
    rel_res : float
        The norm of the residual map (i.e. `map-alm2map(alm)`), divided by the
        norm of `map`. This is a measure for the fraction of the map signal that
        could not be modeled by the a_lm
    iter : int
        the number of iterations required
    converged : bool
        if True, convergence was reached
    """
    from scipy.sparse.linalg import LinearOperator, lsmr
    nside = hp.npix2nside(map.shape[0])

    # helper functions to convert between real- and complex-valued a_lm
    def alm2realalm(alm):
        res = np.zeros(len(alm)*2-lmax-1)
        res[0:lmax+1] = alm[0:lmax+1].real
        res[lmax+1:] = alm[lmax+1:].view(np.float64)*np.sqrt(2.)
        return res
    def realalm2alm(alm):
        res = np.zeros((len(alm)+lmax+1)//2, dtype=np.complex128)
        res[0:lmax+1] = alm[0:lmax+1]
        res[lmax+1:] = alm[lmax+1:].view(np.complex128)*(np.sqrt(2.)/2)
        return res
   
    def a2m2(x):
        talm = realalm2alm(x)
        return hp.alm2map(talm, lmax=lmax, mmax=mmax, nside=nside)
    def m2a2(x):
        talm = hp.map2alm(x, lmax=lmax, mmax=mmax, iter=0)*((12*nside**2)/(4*np.pi))
        return alm2realalm(talm)

    #initial guess
    alm0 = m2a2(map)/len(map)*(4*np.pi)
    op = LinearOperator(matvec=a2m2, rmatvec=m2a2, shape=(len(map),len(alm0)))
    res = lsmr(A=op, b=map, x0=alm0, atol=tol, btol=tol, maxiter=maxiter)
    istop = res[1]
    niter = res[2]
    normres = res[3]
    return (realalm2alm(res[0]), normres/np.linalg.norm(map), niter, istop<7)
```

**Comment by mreineck** [comment]
@zonca, would you like to have this functionality included? If yes, I'll try to provide a PR, probably including support for spin maps and IQU maps. The only interface change would then be that `map` can have the shape `(nmap, npix)` and that an optional `spin` parameter can be passed (default=0).

**Comment by zonca** [comment]
thanks @mreineck , sure, this would be useful to have in `healpy`
useful also to have a longer docstring that explain more in detail the functionality and has links to learn more.

**Comment by mreineck** [comment]
Absolutely! I'll try to get to it soon.

**Comment by ntessore** [comment]
Since they are going to be essentially implemented anyway, it would be nice to finally have a pair of real-valued spherical harmonic transforms. With the sqrt(2) weighting above, all real modes have Cl variance.

**Comment by ntessore** [comment]
I'm not aware of any existing implementations that would produce such real alms.

I would think that grouping the results by `l` is the more useful scheme, because then you can compute the angular power spectra as `mean(alm1[start:end]*alm2[start:end])`, and sample alms from Cls by concatenation.

On the other hand, changing from grouping by `m` to grouping by `l` means a lot of memory being shuffled around, so I don't know what the right answer is, either.

**Comment by zonca** [comment]
Follow implementation in https://github.com/healpy/healpy/pull/734
