### ISSUE TITLE
Does healpy smoothing works only on RING ordered maps ?

### ISSUE THREAD

**Issue by MaudeCharmetant** [healpy/healpy#677]
Dear Healpy team,

I was investigating some RING/NESTED problems recently and I have stumble across something weird about healpy.sphtfunc.smoothing(). It seems to me that the function only works on RING-ordered maps, but I might have misunderstood something. Could you help me get that straight? Here is the small test I did :

I create an empty Healpy map, containing the number of pixels associated to Nside = 2048. Using the Healpy NESTED scheme I cut the map the maps into several big rhombus/fields containing many pixels. For that, I take Nside_tess=4 which gives me a total of 192 fields each of them containing A = Npix/Nfield = 262144 pixels. I set all the pixels or the first field to 1. Basically, I just select a big rhombus full of 1 on an empty map of Nside=2048.

This looks like that and the map is of course is NESTED ordering.

![HP1](https://user-images.githubusercontent.com/58000492/113257356-c9b40780-92ca-11eb-9b81-c3f54eb78e9c.png)

If I smoothed this map using the function healpy.sphtfunc.smoothing(), this is what I get :

![HP2](https://user-images.githubusercontent.com/58000492/113257406-dc2e4100-92ca-11eb-9c5a-3a9373c61101.png)'

Which is not the result I expect from the smoothing of the rhombus I have. And setting nested = False in mollview even though the map is in NESTED ordering in the fits file does not solve the problem. It gives the correct smoothing but I lose my field shape. 

![HP4](https://user-images.githubusercontent.com/58000492/113258249-003e5200-92cc-11eb-824c-34fb32d95428.png)

If I select the same rhombus/field as above but this time reorders the map using healpy.pixelfunc.reorder() to reorder it from NESTED to RING before smoothing it, I get what I expect from smoothing a rhombus.

![HP3](https://user-images.githubusercontent.com/58000492/113257864-7bebcf00-92cb-11eb-8169-8af6a2cea240.png)

Did I understand the RING/NESTED scheme interaction with the smoothing wrong?  Or is it really that the smoothing function expect RING ordered map  ? if that's the case this is not specified in the description of the function itself and I would be interested in creating a fork to implement a nested=True/False argument in the smoothing function so that when the map is in NESTED ordering the smoothing still does the correct thing.

PS : I have observed the same thing using Planck maps. The ones I have are in NESTED ordering in their fits file, for 100GHz, the map looks like that : 

![HP5](https://user-images.githubusercontent.com/58000492/113258806-b43fdd00-92cc-11eb-8fb7-03112bcc973a.png)

if I keep the map in NESTED ordering and smooth it, here is what I get : 

![HP6](https://user-images.githubusercontent.com/58000492/113259031-f9640f00-92cc-11eb-9e67-0e1d32d56c60.png)

If I reorder the map to RING ordering and then smooth it here is what I get : 

![HP7](https://user-images.githubusercontent.com/58000492/113259078-041ea400-92cd-11eb-90ec-44c7ef1a98c6.png)

**Comment by mreineck** [comment]
This looks like an oversight in the docstring for `smoothing`; it should state that the input map(s) must be in RING ordering, since it internally calls `map2alm` which has this requirement.

**Comment by MaudeCharmetant** [comment]
Thank you so much for the quick reply ! I have been working in a fork of healpy to implement a new "nest=False/True" in the smoothing function so that if the inputs map is in NESTED ordering the smoothing function, reorder it to RING before doing the smoothing and reorder it back to NESTED just before the output. 

I have tested it in a Jupyter notebook and it seems to work fine with maps that have only one field but also on maps that contain (T,Q,U). But I want to test it once more in the full package before proposing it to you.

**Comment by zonca** [comment]
let's switch to https://github.com/healpy/healpy/pull/678 for discussing this
