### ISSUE TITLE
Change in total sum of output cartesian pixel values with changing xsize.

### ISSUE THREAD

**Issue by Thomas-Venville** [healpy/healpy#682]
Good day! My bug is thus: when utilizing the visufunc.cartview function to generate cartesian projections, the total integrated pixel values across the cartesian projection (the sum of all of the pixel values) varies when the specified 'xsize' of the map is varied.

As expected, this behaviour does not occur when the total summed pixel values of the normal pixelization (generated using healpy.ang2pix and subsequent summing of particles in pixels) are summed with varying nside. Regardless of the specified nside, the total summed pixel values for this default mollweide projection remains constant.

Accordingly, I suspect there is an error during the generation of the cartesian projection where the pixel values are calculated. As detailed below, I note that there is a linear relation in log space between the total sum of the cartesian pixel values and the specified xsize.

Below I will demonstrate this behaviour with an arbitrary particle distribution with uniform weights. My healpy version number is 1.12.9, my matplotlib version number is 3.1.3, my numpy version number is 1.18.1, and my astropy version number is 4.0.1.post1.

I have attached the error in a short Jupyter notebook if required. However, I have also written the code and illustrated the issue below this text. Thank-you for in advance for any assistance!

[Healpy_Cartesian_Projection_Bug_Report_condensed.ipynb.zip](https://github.com/healpy/healpy/files/6340578/Healpy_Cartesian_Projection_Bug_Report_condensed.ipynb.zip)
 
--- Beginning of code section ----
```
import astropy as astropy
from astropy import units as u
from astropy import coordinates as coord
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import healpy
```
First I will generate a fairly simple particle distribution, with uniform weights, for input into the pixelization procedure.
```
N_particles = np.int(1e5)
ICRS_cooordinates= coord.ICRS(ra=(10.*np.random.random(N_particles))*u.deg,dec=(10.*np.random.random(N_particles))*u.deg,distance=np.ones(N_particles)*u.kpc)
ICRS_cooordinates= ICRS_cooordinates[(ICRS_cooordinates.ra.value-5)**2 + (ICRS_cooordinates.dec.value-5)**2 <= 25]
```
Here is what the example particle distribution looks like in ICRS coordinates.
```
plt.plot(ICRS_cooordinates.ra,ICRS_cooordinates.dec,'o')
plt.xlim([-5,15])
plt.ylim([-5,15])
plt.xlabel(r'$\alpha$ (deg)')
plt.ylabel(r'$\delta$ (deg)')
plt.title('Example particle distribution')
plt.show()
```
![Example_particle_distribution](https://user-images.githubusercontent.com/29851033/115337173-d948b100-a1e3-11eb-840e-a7bdc0bd3ad6.png)
Secondly, I use the HEALPix pixelization scheme as implemented in the healpy package to bin the particles in HEALPix pixels.
```
healpix_horz_rad = ICRS_cooordinates.transform_to(coord.Galactic).l.wrap_at(360. * u.deg).radian
# healpy uses colatitude (north pole 0) instead of latitude
healpix_vert_rad = 0.5*np.pi-ICRS_cooordinates.transform_to(coord.Galactic).b.radian
NSIDE=128
pixels = healpy.ang2pix(NSIDE, healpix_vert_rad, healpix_horz_rad)
# Identify the pixels with entries - this is key to avoiding zeroes in hitmap later
unempty_bins = np.unique(pixels)
# The number of pixels for a given NSIDE
NPIXELS = healpy.nside2npix(NSIDE)
# Create and populate a hitmap - empty map with non-hit pixels convention of UNSEEN number.
hitmap = np.ones(NPIXELS) * healpy.UNSEEN
#Assigning non-empty pixels to the hitmap. I have set the weights for each coordinate to one.
pixels_binned = np.bincount(pixels, weights=np.ones(len(ICRS_cooordinates.ra.value)))
hitmap[unempty_bins] = pixels_binned[unempty_bins]
```
Lastly, I will produce output to show the relationship between the sum of cartesian pixel values for a series of xsize values. This should be constant.
```
#Producing output - the total sum of the cartesian and hitmap pixel values.
# Both should be invariant with changing xsize.
#Placeholder arrays to store data.
xsize_array = np.array([180,360,787,1572,3600])
Total_sum_of_mollweide_pixel_values_array = np.zeros_like(xsize_array)
Total_sum_of_cartesian_pixel_values_array = np.zeros_like(xsize_array)

#A loop to produce total sum of pixel values with changing xsize.
for xsize_array_ind in np.arange(len(xsize_array)):
    
    Cartesian_projection = healpy.visufunc.cartview(healpy.pixelfunc.ma(hitmap,healpy.UNSEEN),coord='G',return_projected_map=True,
                                                    xsize=xsize_array[xsize_array_ind],min=None,max=None)
    Total_sum_of_cartesian_pixel_values = np.sum(Cartesian_projection.data[Cartesian_projection.data>=0])
    Total_sum_of_mollweide_pixel_values = np.sum(hitmap[unempty_bins])
    
    Total_sum_of_mollweide_pixel_values_array[xsize_array_ind] = Total_sum_of_mollweide_pixel_values
    Total_sum_of_cartesian_pixel_values_array[xsize_array_ind] = Total_sum_of_cartesian_pixel_values
```
Plotting these data arrays to illustrate the relationship between total sum of cartesian pixel values and xsize.
```
plt.plot(np.log10(xsize_array),np.log10(Total_sum_of_cartesian_pixel_values_array))
plt.title('Total summed cartesian pixel value vs xsize')
plt.xlabel('log10(xize)')
plt.ylabel('log10(Total summed cartesian pixel value)')
plt.show()
```
Which gives:
![Cart_pixel_val_relation](https://user-images.githubusercontent.com/29851033/115337479-67249c00-a1e4-11eb-9984-7703f886664f.png)
Unsurprisingly, the relation between the summed mollweide hitmap pixel values and xsize is constant. This is also constant with changing nside.
![Mollweide_pixel_relation](https://user-images.githubusercontent.com/29851033/115337595-a18e3900-a1e4-11eb-911f-a63e370bda22.png)

**Comment by hivon** [comment]
Hi Thomas,

your log-log plot shows that sum = xsize^2.
This is because cartview was only designed for visualisation.
It samples (or interpolate) the input Healpix map at the center of each 
output cartesian pixel,
without correcting for the relative area of the output and input pixels.
Said otherwise, if your input Healpix map was a monopole of 1,
the cartesian map would be 1 everywhere for any xsize,
hence a sum = xsize*ysize.

Whether the map should be corrected for the pixel area depends on what you
want to do with it,
either simply look at it (in which case *no* correction gives a better 
feeling of the map value,
especially close to the poles)
or do science and flux analysis (in which case it should be corrected).

Cheers,
Eric

**Comment by zonca** [comment]
It is more appropriate to use https://healpy.readthedocs.io/en/latest/generated/healpy.pixelfunc.get_interp_val.html if you want to reproject a map to a rectangular grid.

Yet another option is to transform to `alm` with `map2alm` and then antitransform with a rectangular pixels package like `pixell`, see https://pixell.readthedocs.io/en/latest/reference.html?highlight=alm2map#pixell.curvedsky.alm2map

**Comment by Thomas-Venville** [comment]
Very well, thank-you for your assistance.
