### ISSUE TITLE
document `map2alm_spin` and `alm2map_spin`

### ISSUE THREAD

**Issue by ntessore** [healpy/healpy#701]
It looks like the pair of functions `map2alm_spin` and `alm2map_spin` have been available since 2014 (#76) but don't show up in the documentation currently.

Their interface is also different from that of `map2alm` and `alm2map`, but that is perhaps a separate issue.

**Comment by ntessore** [comment]
absolutely, I can open a PR if that's desired

**Comment by zonca** [comment]
yes please!
