### ISSUE TITLE
Rotate a mask together with the map in hp.ma() and separately produce different results

### ISSUE THREAD

**Issue by MinhMPA** [healpy/healpy#705]
Hi,

I would like to understand a bit better the behavior of rotate_map_pixel() in this particular case. Below I try to provide a minimal toy example:

```
map = hp.ma(hp.read_map(mapFile))
map.mask = np.logical_not(hp.read_map(maskFile))
rot = hp.Rotator(coord=['G','C'])
map = rot.rotate_map_pixel(map)
mask = hp.read_map(maskFile)
mask = rot.rotate_map_pixel(mask)
```

This produces a slightly different `map.mask` and `mask`. By "different", I mean
```
skycut = np.where(map.mask[obj_pix]==False))
```
and
```
skycut = np.where(mask[obj_pix]==1.)
```
or
```
skycut = np.where(np.isclose(mask[obj_pix],1.))
```
all produce different `skycut`. I'd guess this is due to the interpolation procedure?

If I wish to use the mask for selection purpose, what should I do?

**Comment by zonca** [comment]
see on stackoverlow
