### ISSUE TITLE
sign convention for alm2map_spin and map2alm_spin

### ISSUE THREAD

**Issue by ntessore** [healpy/healpy#707]
*[As far as I can tell, this is in fact a HEALPix issue, but I very much don't want to create a SourceForge account.]*

The HEALPix spin [definition](https://healpix.sourceforge.io/html/sub_alm2map_spin.htm) is as follows:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/3993688/121680122-1416e900-cab1-11eb-86b3-6514d31ad5f8.png">

However, the definition of the sign in (4) and (5) does not match the output of `alm2map_spin`:

```py
import numpy as np
import healpy as hp
import matplotlib.pyplot as plt

nside = 32
lmax = 3*nside - 1

pix = np.arange(hp.nside2npix(nside))
alm = hp.map2alm(pix)

alm_plus = -alm
alm_minus = np.zeros_like(alm)

pix_plus, pix_minus = hp.alm2map_spin((alm_plus, alm_minus), nside, 0, lmax)

plt.figure(figsize=(15, 10))
plt.subplot(221)
hp.mollview(pix, title="$S$", hold=True)
plt.subplot(223)
hp.mollview(pix_plus, title="$S^+$", hold=True)
plt.subplot(224)
hp.mollview(pix_minus, title="$S^-$", hold=True)
plt.show()
```

<img width="901" alt="image" src="https://user-images.githubusercontent.com/3993688/121681535-dc10a580-cab2-11eb-8401-a153200b92be.png">

**Comment by mreineck** [comment]
Is this possibly due to the strange "(-1)^H" sign convention mentioned in eqs(11) and (12) of https://arxiv.org/abs/1010.2084?
I don't know why this exists, but I decided to follow prior codes...

**Comment by ntessore** [comment]
Not very insightful, but my gut feeling here was that the code is correct and the negative sign in (4) and (5) should not be there in general, but has something to do with polarisation being spin -2 rather than 2 in these terms. But I haven’t done the maths.

**Comment by hivon** [comment]
The -1 sign was present in the original papers of Zaldarriaga and Seljak of 1997 on CMB polarization.
As noted by Lewis 2005, it is consistent with the ouput of CMBFAST and CAMB and insure that the large scale TE correlation is positive. The same convention was extended to all s.

**Comment by ntessore** [comment]
Yes, surely any sign in front of either (4) or (5) is only an arbitrary convention for the definition of the +/- alms. But do you agree that HEALPix/healpy currently does not follow its own stated convention?

**Comment by hivon** [comment]
Not following that convention would have been noticed in the case of polarization and TE.
Now, both HEALPix and healpy now rely on libsharp.
Looking at that code it seems that libsharp is so smart that ,when s=0, it stops using that minus sign,
and has alm_plus = alm_0  
(instead of alm_plus = -alm_s "usually")
@mreineck, is that correct ?

**Comment by mreineck** [comment]
Yes, that is certainly the plan. I'm applying the extra minus only for transforms with |s|>0, not for s=0.
While writing libsharp I always tested the results against the already existing implementations.
It's of course possible that I have introduced a sign flip at some point by mistake, but I would be surprised if that had gone entirely unnoticed by the community ...

**Comment by ntessore** [comment]
Yes, my point is only that HEALPix is not following the convention when s = 0, which is the case explicitly mentioned in the documentation.

**Comment by mreineck** [comment]
Ahh, I think I understand your point now! Are you talking about calling `alm2map_spin` with a spin of 0? This scenario should actually not be supported, as far as I understand ... how did you do this?

**Comment by mreineck** [comment]
Sorry, I completely forgot about your initial example ... no, that's not what you mean either. Sorry for the confusion.

**Comment by mreineck** [comment]
If `healpy` accepts `alm2map_spin` with a spin of 0 (and your example proves that it does), then that is an unintended "feature". We need to either fix the routine for that case, or disable it.

**Comment by ntessore** [comment]
Unless I’m misremembering things, I have been using the spin 0 transform for years to work with complex spin-0 fields. After all, if spin 0 is not supported, why explicitly mention it in the (Fortran) docs?

And since it does seem to work I would much rather fix the sign convention than disable the feature.

**Comment by mreineck** [comment]
The one reason not to use `alm2map_spin` with s=0 is that it is more expensive than two standard `alm2map` transforms (working with "normal" spherical harmonics allows many shortcuts compared to spin spherical harmonics.
But you are right, that is something we can also implement under the hood.

I'm not sure how soon I will be able to look into this, but I'll try my best.

And sorry for talking at cross purposes so much ... I was multitasking and didn't give this as much attention as it deserved!

**Comment by zonca** [comment]
so for now should we throw an exception if the user calls `alm2map_spin` with `s=0`?

**Comment by mreineck** [comment]
Probably the best quick fix would be to flip the sign of the output of both `alm2map_spin` and `map2alm_spin` if they are called with `s=0`.

(according to the docstring in `_sphtools.pyx` only spins 1, 2, and 3 were valid inputs, but I don't think they are user-visible. In principle everything in the range 0<=s<=lmax should work.)

**Comment by zonca** [comment]
ok, @ntessore could you please make a pull request on that?

**Comment by ntessore** [comment]
I can do that and I think that this is the cleanest solution.

On the other hand, this behaviour has supposedly been in place for quite a while now, so it is likely there are codes out there that depend on it. While more awkward, changing the definition for s = 0 would solve the problem without invalidating any existing code.

**Comment by mreineck** [comment]
I really don't expect many people to have used the spin SHTs with `s=0` so far; this is the first time I ever heard of that. My new routines in `ducc0` actually raise an error if this happens, and I haven't had a complaint so far.
Also, as you noticed, the spin routines weren't even officially documented so far (and their internal docstrings said they only accept spins 1-3), so I wouldn't feel bad about breaking unofficial behaviour.
A note in the ChangeLog would probably be a good idea though.

**Comment by ntessore** [comment]
Ok, I can provide a PR with the explicit flip and a note in the changelog.

**Comment by mreineck** [comment]
Thanks a lot!

**Comment by ntessore** [comment]
As discussed in #708, the `spin=0` transform is currently not supported by libsharp, which silently ignores the complex component.

**Comment by mreineck** [comment]
Thanks!
I have added analogous checks to the Fortran and C++ ports. But having them on the Python side is definitely preferable, since this produces cleaner exceptions.

**Comment by ntessore** [comment]
I would still make the plea to restore the correct spin-0 behaviour eventually. It makes it so much easier to write code for generic spin-weighted spherical functions without having to deal with the special case. If I understood you correctly, two non-spin function calls are anyway more efficient than one spin function call, so perhaps the spin functions could just do that internally.

**Comment by mreineck** [comment]
I'll do my best to provide this functionality in the SHT library I'm currently working on. For the classic `libsharp` C interface it's unfortunately not really doable, since the value of `s` determines the number of components the code expects to be working on (1 for s==0, else 2).
I'm also thinking about adding a flag which disables the (to most people rather surprising) CMB sign convention. SHTOOLS and ssht appear not to use it, for example, and it may be nice to have a compatibility mode.
