### ISSUE TITLE
read_map fails to read a fits file with no NSIDE info in the header

### ISSUE THREAD

**Issue by carlosggarcia** [healpy/healpy#709]
Hi, 

I have found that reading a map that lacks the NSIDE information in the header returns the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-36828aa213a5> in <module>
----> 1 m = hp.read_map('Downloads/mask_DR12v5_CMASS_North.fits.gz')

~/.local/lib/python3.9/site-packages/healpy/fitsfunc.py in read_map(filename, field, dtype, nest, partial, hdu, h, verbose, memmap)
    389         nside = int(nside)
    390     if verbose:
--> 391         warnings.warn("NSIDE = {0:d}".format(nside))
    392 
    393     if not pixelfunc.isnsideok(nside):

TypeError: unsupported format string passed to NoneType.__format__
```
I think the problem is that, after raising the Warning https://github.com/healpy/healpy/blob/eb29716a06ddb65f177d0a09608b0430faadf3a3/healpy/fitsfunc.py#L374-L376

`nside` is not obtained from the length of the array, as it is claimed.

The file I was using can be found here: https://data.sdss.org/sas/dr12/boss/lss/mask_DR12v5_CMASS_North.fits.gz

Best,
Carlos

**Comment by zonca** [comment]
thanks, can you please provide a fix using `hp.npix2nside`?

**Comment by carlosggarcia** [comment]
Done. Just for the record, I realized later that the map I was reading is not in healpix format, so the fix rises an error when converting array length to `nside` (as expected).
