### ISSUE TITLE
Error when trying to use cbar 

### ISSUE THREAD

**Issue by alexreevesy** [healpy/healpy#721]
Dear all, 

I am getting the following error: 
in mollview(map, fig, rot, coord, unit, xsize, title, nest, min, max, flip, remove_dip, remove_mono, gal_cut, format, format2, cbar, cmap, badcolor, bgcolor, notext, norm, hold, reuse_axes, margins, sub, nlocs, return_projected_map, alpha)
    288                     boundaries=b,
    289                     values=v,
--> 290                     format=format,
    291                 )
    292             else:

...

TypeError: You must first set_array for mappable

When trying to use Mollview on a map that I have read in from a .fits file. Is there any reason in particular why I can't have a colorbar for this map? 

Best wishes, 

Alex

**Comment by zonca** [comment]
Please provide a snippet where I can reproduce the error

**Comment by zonca** [comment]
No feedback from the user
