### ISSUE TITLE
Not compatible with cfitsio 4.0.0 (via healpixsubmodule)

### ISSUE THREAD

**Issue by pkgw** [healpy/healpy#722]
cfitsio 4.0.0 was [released in May](https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt). It doesn't look like too much has actually changed, but the new version number causes problems for the healpy build:

```
$work/healpixsubmodule/src/cxx/cxxsupport/fitshandle.cc:802:42: error: too many decimal points in number
    802 |       int v_header  = nearest<int>(1000.*CFITSIO_VERSION),
```

*Hopefully* that's the only issue ...

**Comment by pkgw** [comment]
@mreineck Looks like it might just be a matter of making sure that fix is reflected in the `healpy/healpixmirror` repo here on GitHub, then updating the Git submodule here to bring it in to the version vendored in this repo.

**Comment by hivon** [comment]
Hi @zonca, I need a healpy-1.15.1.tar.gz file (with the correct version numbers at all the right places), that I can integrate into Healpix 3.81.

**Comment by zonca** [comment]
yes, @hivon, will let you know when it is ready

**Comment by zonca** [comment]
The build on Github actions, which is needed to build the release binary packages on PyPI, is broken.
I can't release without that working, need to first finalize https://github.com/healpy/healpy/pull/728.

**Comment by hivon** [comment]
Hi @zonca, any news on 1.15.1 ?

**Comment by zonca** [comment]
no, sorry, I haven't had time yet to fix the Github actions system.
