### ISSUE TITLE
Why there is a negative sign on `rot[1]` in `get_rotation_matrix`?

### ISSUE THREAD

**Issue by astrojhgu** [healpy/healpy#729]
https://github.com/healpy/healpy/blob/c34d032edaef6e1b755929aa76cf0cc933fcc677/healpy/rotator.py#L875

The help function of `Rotator`, `get_rotation_matrix` calls `eular_matrix_new`, but the sign of `rot[1]` is negative, but `rot[0]` and `rot[2]` are not. Is it on purpose and what is the reason?

Thanks.

**Comment by zonca** [comment]
I think it is due to the "ASTRO" convention, see `mollview` docstring for example:

> flip{‘astro’, ‘geo’}, optional
> Defines the convention of projection : ‘astro’ (default, east towards left, west towards right) or ‘geo’ (east towards right, west towards left)

Does that cause any problem?

**Comment by astrojhgu** [comment]
> Does that cause any problem?

Thank you for your apply. Actually its fine. I'm just implementing a new healpix rotating code and when I compare the result with healpy I notice the difference.

**Comment by zonca** [comment]
ok, so make sure you are getting the convention on the projection equivalent to `healpy`, you can double-check with `astropy` coordinate transforms possibly.
