### ISSUE TITLE
How to continue?

### ISSUE THREAD

**Issue by FraPardi** [healpy/healpy#730]
Due to the pandemic many of us have project students working from home on Windows machines on projects needing healpy.  I was able to get it installed via the Windows Subsystem for Linux, and available in a jupyter notebook.  

In case useful to others I've put instructions below.

1. Restart your computer, and follow the instructions (which appear before windows starts) to enter BIOS.  
Usually this means pressing DEL or F2 just after powering on.
Find the option to enable virtualization (exact name will depend on your system, can google your machine brand name + "enable virtualization" for instructions)

2. Follow these instructions to install Windows Subsystem for Linux:
 https://docs.microsoft.com/en-us/windows/wsl/install-win10 
Following the instructions for WSL version 2, and choosing Ubuntu from the store.

3. Restart machine
4. Open the newly installed Ubuntu application from the Start menu and follow the setup instructions.
5. When they are complete, run these commands:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3 python3-pip

6. Quit ubuntu, restart it, and run:

pip3 install numpy jupyter matplotlib healpy ipython jupyter

7. Quit ubuntu again, restart it, and run:
ipython notebook --no-browser

8. Copy and paste the line starting 
http://localhost:8888/?token= 
into your normal windows web browser.

_Originally posted by @joezuntz in https://github.com/healpy/healpy/issues/25#issuecomment-704806192_

Hi, I'm trying to install Healpy in Windows as suggested by @joezuntz. I've done all the things that are listed. Once I open the Jupyter notebook, how should I continue? Thanks for your patience.
Greetings

**Comment by zonca** [comment]
You should be able to run:

    import healpy as hp

And then use healpy normally

**Comment by zonca** [comment]
For example, running commands that are in the tutorial

**Comment by FraPardi** [comment]
Ok, and I am bound to use and to run through Jupyter? That is, anytime i need healpy, should i upload to jupyter and use that as a interface with WSL, where everything happens?

**Comment by zonca** [comment]
no, you can execute scripts with:

    python3 yourscript.py
