### ISSUE TITLE
Add convenience function producing Gaussian beam a_lm?

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#733]
Maybe I'm not looking in the right places, but I don't think that `healpy` has a function like

`def blm_gauss (fwhm, lmax, pol=False)`

which simply produces a_lm of a circular Gaussian beam. (I know there is one for producing a Gaussian window function, but that's slightly different.)  If this is really missing, would you like me to provide one? I think it could be a useful helper function.

**Comment by zonca** [comment]
yes, sure, thanks
