### ISSUE TITLE
Release of healpy 1.15.1/1.15.2 and HEALPix 3.81

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#741]
Tracking the release of healpy 1.15.1, the main purpose is to support CFITSIO 4.0.0

It was delayed by the Github Action CI system being broken.
@lpsinger fixed it in #740.

I am now going to finalize all the open pull request and then release it.

> Hi @zonca, I need a healpy-1.15.1.tar.gz file (with the correct version numbers at all the right places), that I can integrate into Healpix 3.81.

_Originally posted by @hivon in https://github.com/healpy/healpy/issues/722#issuecomment-960582386_

**Comment by zonca** [comment]
We also want to update the bundled CFITSIO to 4.0.0 https://github.com/healpy/cfitsio/pull/10

**Comment by lpsinger** [comment]
We also need to fix the cibuildwheel timeout so that all of the binaries are built and uploaded.

**Comment by lpsinger** [comment]
@zonca, what date do you expect to do the release?

**Comment by zonca** [comment]
we could release now,
I would wait a couple of days to check if we can also squeeze https://github.com/healpy/healpy/pull/735 in,
so let's schedule release by this Friday.
@hivon can you release HEALPix 3.8.1 in the next 2/3 weeks?

**Comment by hivon** [comment]
Hi @zonca, yes, I can do that.

**Comment by zonca** [comment]
https://github.com/healpy/healpy/pull/735 is almost done, I'll release later today or tomorrow

**Comment by zonca** [comment]
Release:
* [ ] Github: https://github.com/healpy/healpy/releases/tag/1.15.1
* [ ] PyPI: https://pypi.org/project/healpy/1.15.1/
* [ ] conda-forge: https://anaconda.org/conda-forge/healpy
* [ ] wheels on PyPI for linux and Mac OS

**Comment by zonca** [comment]
@hivon as usual take the tgz from https://pypi.org/project/healpy/1.15.1/

**Comment by lpsinger** [comment]
@mreineck would you please generate and upload autotools tarballs for healpix-cxx so that I can update the Debian and MacPorts packages?

**Comment by mreineck** [comment]
Should be uploaded now. Please let me know if anything doesn't work as expected!

**Comment by zonca** [comment]
Okay. Also the conda packages are on the repository.

**Comment by zonca** [comment]
@hivon please hold on, @lpsinger found an issue in the C++ library API,
@mreineck already fixed it,
I'm waiting for https://github.com/healpy/healpy/pull/746 to run the tests, then later today I'll release 1.15.2 with that fix.

**Comment by zonca** [comment]
Release **1.15.2**:

* [x] Github: https://github.com/healpy/healpy/releases/tag/1.15.2
* [ ] PyPI: https://pypi.org/project/healpy/1.15.2/
* [ ] conda-forge: https://anaconda.org/conda-forge/healpy
* [ ] wheels on PyPI for linux and Mac OS

**Comment by zonca** [comment]
@hivon, you can use https://pypi.org/project/healpy/1.15.2/#files

**Comment by zonca** [comment]
ok, released also HEALPix 3.8.1 https://healpix.sourceforge.io/downloads.php#SECTION_381_10000000000000000
