### ISSUE TITLE
norm='log' or 'hist' does not work in hp.projview: NotImplementedError

### ISSUE THREAD

**Issue by skoldobskiy** [healpy/healpy#747]
Hello!

It looks like the normalization of the colorbar is currently not implemented.
I don't know if I should report that or if you already know about it.

Thanks

**Comment by zonca** [comment]
https://github.com/F-Tomas would you like to take a look into this?

**Comment by F-Tomas** [comment]
Yes, will check it.

**Comment by zonca** [comment]
@F-Tomas `log` in particular would be useful to have

**Comment by zonca** [comment]
implemented in #751
