### ISSUE TITLE
hp.mollview giving error when plotting

### ISSUE THREAD

**Issue by aishrimc** [healpy/healpy#749]
I downloaded a healpix map from [LAMBDA](https://lambda.gsfc.nasa.gov/product/foreground/l). The map is being read fine when doing `a = hp.read_map(name_of_map.fits)`, but doing `hp.mollview( wmap_map_I, coord=["G", "E"], title="Histogram equalized Ecliptic", unit="mK",  norm="hist", min=-1, max=1) ` is giving error (full trace back provided in attached text file). I got the same error on following the example provided in [healpy tutorial](https://healpy.readthedocs.io/en/latest/tutorial.html#Reading-and-writing-maps-to-file). 
The details of system and software are:
Healpy version- 1.15.0
ipython - 6.5.0
python - 3.7.0
anaconda3
OS - CentOS-7

[healpix_err.txt](https://github.com/healpy/healpy/files/8177653/healpix_err.txt)

**Comment by zonca** [comment]
Please use stackoverflow.com and provide the full code snippet for help
