### ISSUE TITLE
Smoothing doesn't preserve power/energy

### ISSUE THREAD

**Issue by pagano-michael** [healpy/healpy#759]
Hi Healpy team,

I am convolving a Gaussian beam with a radio map of the sky ( [this radio sky map](https://lambda.gsfc.nasa.gov/product/foreground/fg_2014_haslam_408_info.html) but any other map can be used instead)  using the healpy sphtfunc.smoothing function. The process of convolving a map shouldn't change the overall power. However when I compute the total energy/power of the map before and after the smoothing I get vastly different values which also depending on the smoothing beam size. I wonder whether this is a product of my choice of lmax or perhaps something deeper going on inside the healpy smoothing function that I am not aware of. 

Here is example code to demonstrate the problem:

import healpy as hp
import numpy as np
import matplotlib.pyplot as plt

def compute_cl_alm(example_map, lmax):
    cl, alm = hp.sphtfunc.anafast(example_map ,alm = True, lmax = lmax)
    return cl, alm

def plot_ang_pspec(cl):
    ell = np.arange(len(cl))
    plt.figure(figsize=(10, 5))
    plt.title(r'Angular Power Spectrum', fontsize = 20)
    plt.plot(ell, ell * (ell + 1) * cl)
    plt.xlabel("$\ell$")
    plt.ylabel("$\ell(\ell+1)C_{\ell}$")
    plt.show()
    plt.close()
    

smoothing_scales = np.array([0.001, 0.01, 0.05, 0.1, 0.2, 0.3])
lmax = 360

for i in range(len(smoothing_scales)):
    
    print('Smoothing scale in degrees ' , smoothing_scales[i]*(360./(2*np.pi)))
    cl_base, alm_bas = compute_cl_alm(base_408, lmax)
    
    smoothed_map = hp.sphtfunc.smoothing(base_408, sigma=smoothing_scales[i] , lmax = lmax)  
    cl, alm = compute_cl_alm(smoothed_map,lmax)
    
    print('Sum c_l of non-smoothed map', np.sum(cl))
    print('Sum c_l of smoothed map' ,np.sum(cl_base))
    print('Difference', np.sum(cl_base)-np.sum(cl))
    plot_ang_pspec(cl)
    plot_ang_pspec(cl_base)

    
    hp.visufunc.mollview(smoothed_map,  cmap = 'RdBu',  title = 'Smoothed at scale ' + str(smoothing_scales[i]))

The sum of the Cl's in the angular power spectrum gives us the total power/energy of the map given (right hand side , first equation [here](https://en.wikipedia.org/wiki/Spherical_harmonics#Spectrum_analysis)). So the smoothing has not conserved those quantities.

**Comment by hivon** [comment]
Hi Michael,
the [Parseval's theorem](https://en.wikipedia.org/wiki/Plancherel_theorem) only states that the power of a signal is the same whether you compute it in real space or Fourier space.
Precisely because a "smoothing" is a convolution in real space, therefore a multiplication in Fourier space, it will alter the
power of the resulting signal.
The whole purpose of smoothing is to down-weigh or iron-out the small scale fluctuations (which are a source of power too) resulting in a reduced power, with the only contribution of the large scale fluctuations.

**Comment by pagano-michael** [comment]
That makes sense, thank you!
