### ISSUE TITLE
alpha ignored if the array is binary (e.g. 0 and 0.8)

### ISSUE THREAD

**Issue by carlosggarcia** [healpy/healpy#765]
When trying to plot a map with transparency. If `alpha` is just a binary array (e.g. filled with 0's and some other constant value), healpy ignores the chosen value. This happens because the array is normalized here https://github.com/healpy/healpy/blob/0f46774cf626b3fe0385bcc0f946d95354be4cc2/healpy/projaxes.py#L189

It would be great if the normalization could be avoided in certain cases or if healpy could skip it if it detects the array is binary. 

For context, I was trying to plot 3 maps that overlap in certain regions and I wanted map2 and map3 to have a constant alpha across the sky (so alpha_map2 is filled with 0's and 0.8's).
```
map1[map1 == 0] = hp.UNSEEN
hp.mollview(map1, badcolor='lightgray', cbar=False, title='')
hp.mollview(map2, reuse_axes=True, alpha=alpha_map2, cbar=False, title='')
hp.mollview(map3, reuse_axes=True, alpha=alpha_map3, cbar=False, title='')
```

**Comment by zonca** [comment]
Can you please provide an example which is directly executable?

**Comment by zonca** [comment]
very good thanks, it would be great if you can provide a pull request to fix the issue.
