### ISSUE TITLE
New healpy release to remove cfitsio warnings (1.16.1)

### ISSUE THREAD

**Issue by parejkoj** [healpy/healpy#770]
What are the plans for a new release of healpy/healpix, now that #764 has fixed the cfitsio warning bug (thank you!)? Could those of us in the community help with a new release candidate, to move this forward?

**Comment by zonca** [comment]
Yes, please,
Can you check that all pull requests have been mentioned in the Changelog?

**Comment by zonca** [comment]
@hivon we will release a new version of healpy in the next week or so. I have updated the C++ sources to fix the warning about versioning of cfitsio. This modification is minor so I don't think we need to do a joint release.
What do you think?

**Comment by parejkoj** [comment]
@zonca : see #771 for a changelog update.

**Comment by zonca** [comment]
updating C++ sources to the latest version of HEALPix C++ https://github.com/healpy/healpy/pull/772

**Comment by zonca** [comment]
Release:
* [ ] Github: https://github.com/healpy/healpy/releases/
* [ ] PyPI: https://pypi.org/project/healpy/
* [ ] conda-forge: https://anaconda.org/conda-forge/healpy
* [ ] wheels on PyPI for linux and Mac OS 

@lpsinger @hivon @mreineck I think that we should tag the new release `1.16.0` to signal that we changed the underlying C++ sources, even if changes are minor. Anyone disagrees?

**Comment by zonca** [comment]
released 1.16.0 on Github, waiting for PyPI and Conda builds

**Comment by lpsinger** [comment]
I'll need the release of healpix-cxx before I can update:

1. [ ] MacPorts
2. [ ] Debian

**Comment by lpsinger** [comment]
> @lpsinger Do you want a tarball for testing?

Yes, please.

**Comment by mreineck** [comment]
Please try the attached tarball; I hope I thought of everything this time!
[healpix_cxx-3.82.0.tar.gz](https://github.com/healpy/healpy/files/9147109/healpix_cxx-3.82.0.tar.gz)

**Comment by zonca** [comment]
Releasing 1.16.1 which also includes CFITSIO 4.1.0, see #775 

Release:
* [x] Github: https://github.com/healpy/healpy/releases/
* [x] PyPI: https://pypi.org/project/healpy/
* [x] conda-forge: https://anaconda.org/conda-forge/healpy
* [x] wheels on PyPI for linux and Mac OS

**Comment by zonca** [comment]
@lpsinger any news on Macports and Debian?

**Comment by lpsinger** [comment]
I'll try to do MacPorts this week. I'll have to Debian next week because I need to renew my gpg key.

**Comment by lpsinger** [comment]
@mreineck, would you please generate the autotools tarballs?

**Comment by mreineck** [comment]
If you were happy with the test tarball above, I'll simply release that one!

**Comment by lpsinger** [comment]
It looks good to me.

**Comment by zonca** [comment]
@lpsinger are Macports and Debian packages done yet?

**Comment by lpsinger** [comment]
No. I think I'm still waiting for @mreineck to upload the healpix-cxx tarballs.

**Comment by mreineck** [comment]
Sorry if I was not clear, but they have been released since a few weeks (https://sourceforge.net/projects/healpix/files/Healpix_3.82/healpix_cxx-3.82.0.tar.gz/download).

**Comment by lpsinger** [comment]
I see. I'll work on the MacPorts package right away. Debian will take me about 2 weeks since I don't have my Debian key with me while I am traveling.
