### ISSUE TITLE
Why is default iterations 3 in healpy?

### ISSUE THREAD

**Issue by jyothischandran1597** [healpy/healpy#774]
I was just wondering why healpy has a default value of 3 iterations while doing spherical harmonic transforms while Healpix has a default of 0. I have noticed that using a higher number of iterations will amplify noisy data towards the higher multiples.

Also, it is mentioned in Healpix documentation (anafast, f90) that " iter_order>0 can not be used together with won=2." This means when pixel weights are used (which is preferred if high precision is required), iterations are not to be used.

So, is there a reason for this default value?

**Comment by mreineck** [comment]
If you know how accurately you need your result `alm` to be, I'd recommend trying the new `map2alm_lsq` method.

**Comment by mreineck** [comment]
... oops, I just realized that this is not officially released yet. But it probably will be soon! :-)

**Comment by hivon** [comment]
It also depends whether the input map is band-limited < lmax, which may not the case for experimental noisy data, or if a sharp masking is applied

**Comment by jyothischandran1597** [comment]
@zonca What you said is right. Running 3 iterations gave me almost the same result as 0 iterations. But I tried running a higher number of iterations hoping to get better accuracy, which made my extracted CMB map from full-sky data noisier. I will try to make a reproducible simpler version and follow up. Thank you for the pointer that using pixel weights automatically sets iterations to 0.

@mreineck and @hivon I was following the discussion that lead to the creation of `map2alm_lsq`. I am eagerly waiting for it to added to the official release. 

Currently I am using the usually accepted convention of lmax = 2*nside. The input maps are not well band-limited (Planck like data) and the masks are apodized. Nside is 2048, so I take lmax 4096. 
The reason I was exploring the iterations and weights is that I encountered covariances matrices of negative eigenvalues. These covariances were calculated with healpy alm2cl. The covariances were calculated with maps of the full sky at different frequency observations. It looked like a precision problem. This problem was occurring towards the higher multiples ~3000-3500. So what configuration of iterations and weights would be the best option?

Another problem when I tried working with more than double precision is that healpy functions does not accept objects like the high precision floats from ´mpmath'library in python.

My problematic covariance matrix with negative eigen values from around l=3300.[cov_matrix_eig_10_arcmin_healpy_01July22_1.txt](https://github.com/healpy/healpy/files/9150223/cov_matrix_weights_eig_10_arcmin_healpy_no_0.1_noise01July22_1.txt)

**Comment by mreineck** [comment]
> Currently I am using the usually accepted convention of lmax = 2*nside. The input maps are not well band-limited 

This is probably the crucial point. If the input is not properly band-limited, it's meaningless to discuss the "accuracy" of the `map2alm` result, because this implies that a "correct" result exists. For non-bandlimited inputs, this simply doesn't exist.
I know how unsatisfactory that is, especially since Cartesian grids don't have this problem, but for grids on the sphere it's unfortunately unfixable.

> Another problem when I tried working with more than double precision is that healpy functions does not accept objects like the high precision floats from ´mpmath'library in python.

Yes, the spherical harmonic transforms accept at most double precision inputs. Allowing long double or even multiprecision inputs would slow the computations down so much that they would become practically useless; I would expect factors of at least 100x slower.

**Comment by jyothischandran1597** [comment]
@mreineck Thank you once again for the information! So, can keep using the pixel weights even though my lmax/nside ratio is 2? Or ring weights with 3 iterations will be better? I will try to compare the cases by myself too.

**Comment by mreineck** [comment]
@jyothischandran1597, sorry for the late reply ... I'm travelling at the moment.

> So, can keep using the pixel weights even though my lmax/nside ratio is 2? 

No, that will give you really wrong a_lm for `l > 1.5*nside` and slightly wrong a_lm for `nside < l < 1.5*nside`.

> Or ring weights with 3 iterations will be better?

Yes, that should give you better results overall. It's slower, but with the band limits you are using the run time should be fairly acceptable.

**Comment by jyothischandran1597** [comment]
@mreineck Thanks a lot for the advice! It was really helpful.
