### ISSUE TITLE
cfitsio 4.1.0 as default

### ISSUE THREAD

**Issue by hivon** [healpy/healpy#775]
Hi,
Healpix-f90, and any other Fortran code, requires cfitsio 4.1.0  or higher to work properly on Apple ARM chips. Currently healpy is shipped with 4.0.0. Could you switch to 4.1.0 to be consistent ?

**Comment by zonca** [comment]
ok, see https://github.com/healpy/healpy/pull/776

**Comment by zonca** [comment]
healpy 1.16.1 ships with cfitsio 4.1.0
