### ISSUE TITLE
Instructions for installing an optimized version?

### ISSUE THREAD

**Issue by mreineck** [healpy/healpy#778]
I realized that our current installation instructions will always produce binaries that are not optimized for a given target platform.
While that is perfectly fine in very many scenarios, it sacrifices a lot of performance in some critical situations, e.g. when `healpy` is installed on a supercomputer. There the standard binaries will have, e.g., SHTs that perform seriously worse than they could (by a factor of 2 to 4).

A simple way to address this would be a `pip` command like
```
CC=gcc CXX=g++ CFLAGS='-fPIC -O3 -march=native' CXXFLAGS='-fPIC -O3 -march=native' pip3 install --user --verbose --no-binary healpy healpy
```

Should we add a short section to `INSTALL.rst` mentioning this? I can provide a patch.

**Comment by zonca** [comment]
Yes, sure!

**Comment by mreineck** [comment]
Does #779 look OK? I'm not absolutely sure about the paragraph at the top, but I think that too few people are aware of the performance issues of installing binary wheels.

**Comment by mreineck** [comment]
Is there an analogous process for conda? It would be great to have instructions for that as well, if it exists.

**Comment by zonca** [comment]
the recipe for building the conda package is in the feedstock repository:

https://github.com/conda-forge/healpy-feedstock/blob/main/recipe/build.sh

**Comment by mreineck** [comment]
If I understand things correctly, this recipe is executed on Conda's build servers when the binary packages are compiled. After some research it doesn't seem like `conda install` can be used to download a source package and compile it locally.
Please let me know if I'm wrong!

**Comment by zonca** [comment]
yes correct, so let's consider this closed.
