### ISSUE TITLE
numpy update error

### ISSUE THREAD

**Issue by YaoQianli** [healpy/healpy#780]
After updating `numpy` to 1.23.2, an error occured when `import healpy` as numpy removed asscalar() function
I found online that "You should replace the function np.asscalar (a) with the suggested a.item () function to prevent your code from not working in the future. Please note that a represents your numpy array. In this case, replacing np.asscalar (your_numpy_array) with your_numpy_array.item ()."
Hope this can be solved in the next version.

**Comment by zonca** [comment]
would you be able to submit a pull request fixing this?

**Comment by zonca** [comment]
I don't see `asscalar` used anywhere in `healpy`.
