### ISSUE TITLE
New healpy release to build wheels for Python 3.11

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#794]
`1.16.2`, nothing new except building wheels for Python 3.11

Release:
* [x] Github: https://github.com/healpy/healpy/releases/
* [x] PyPI: https://pypi.org/project/healpy
* [x] conda-forge: https://anaconda.org/conda-forge/healpy
* [x] wheels on PyPI for linux and Mac OS 

@zonca @lpsinger @hivon @mreineck

**Comment by zonca** [comment]
it looks like there are errors on Mac OS, here is a warning:

        /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-40brwhcy/overlay/lib/python3.7/site-packages/setuptools/_distutils/extension.py:134: UserWarning: Unknown Extension options: 'cython_directives'

here the error:

        configure: error: in `/Users/runner/work/healpy/healpy/build/temp.macosx-10.9-x86_64-cpython-37/cfitsio':
        configure: error: C compiler cannot create executables

any suggestions?

**Comment by zonca** [comment]
See https://github.com/healpy/healpy/pull/795, the branch is `release_1.16.2`

**Comment by zonca** [comment]
@lpsinger @mreineck any suggestion about the Mac OS error above?

**Comment by mreineck** [comment]
I'd have to see the `config.log`, but I'm not sure if this is archived by the CI anywhere.

**Comment by lpsinger** [comment]
> @lpsinger @mreineck any suggestion about the Mac OS error above?

@zonca, this is fixed by #804.

**Comment by zonca** [comment]
it looks like there is an issue on conda-forge https://github.com/conda-forge/healpy-feedstock/issues/55

**Comment by zonca** [comment]
PyPI seems fine

**Comment by zonca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release healpy 1.16.2](https://trello.com/c/MPNTjG8M/348-release-healpy-1162)

**Comment by zonca** [comment]
packages are on conda forge
