### ISSUE TITLE
smoothing for partial sky

### ISSUE THREAD

**Issue by liuwei840305** [healpy/healpy#796]
Deal all,
I want to smooth a partial sky due to observation limit.
Can I use the smooth function in healpy or healpix to do the same thing for partial sky?
How does healpy do smoothing?

Thank you very much.

**Comment by liuwei840305** [comment]
why do you close my issue?

**Comment by liuwei840305** [comment]
Why did you close my issue? Any problem? @zonca

**Comment by liuwei840305** [comment]
Could you answer my question? @zonca

**Comment by zonca** [comment]
No, sorry, no time for individual support.
