### ISSUE TITLE
Fit_dipole function yields incorrect results

### ISSUE THREAD

**Issue by VasundharaShaw** [healpy/healpy#798]
Hello

I am doing a test using the healpy.pixelfunc.fit_dipole() and healpy.pixelfunc.vec2ang() functions. 
I create an array ('f_theta_phi') with a pure dipole with the dimension of NSIDE = 32 and f_theta_phi = cos(lat), here lat is the co-latitude (horizontal lines on the map) values obtained by healpy. The code and the skymap of this are below. 
Based on the skymap, the dipole seems to be in the direction of lat = 90 and longitude (vertical lines on the map), lon = 0 (degrees). To be clear lat = 90, lon = 0 will be the red northern pole of the map (see the plot attached). 
If now I pass this skymap through fit_dipole() function, I will obtain the value of the monopole and the dipole vectors (dip_vec = [a11,a10,a01]). Subsequently, I can use the dipole vectors to recover my dipole direction by passing the vectors through  vec2ang(dip_vec[1], lonlat =True). When I print the recovered direction I obtain the value of lon = 87.2045747 and lat = 90. The value of the recovered lon is incorrect since the initial value of the longitude as it can be seen from the map is 0 degrees. 

I am unsure if the problem lies with the way I use the 'fit_dipole' and 'vec2ang' functions or if there is some issue with projection. Why is the longitude affected this way? 

I have attached my code here:

import healpy as hp
import numpy as np

NSIDE          = 2**5
lat, lon         = np.degrees( hp.pix2ang( NSIDE, np.arange(hp.nside2npix(NSIDE) ) ) )
dim              = hp.nside2npix(NSIDE)
f_theta_phi = np.zeros(dim)

## Creating the dipole map
for i in range(0,dim):
    f_theta_phi[i] =cos(rad(lat[i]))
    
    
## Plotting the dipole map
hp.mollview(f_theta_phi, cmap='twilight_shifted', title='North South dipole')
hp.graticule()    

## Fit dipole, to get monopole and dipole values. 

dip_vec = hp.fit_dipole(f_theta_phi)[1]

## Printing the recovered direction, based on the dipole vector 

print( (hp.vec2dir(dip_vec, lonlat=True) ) )

[87.20457471 90.        ]

## The recovered direction does not match the original dipole direction which ought to be
![Pure dipole NS](https://user-images.githubusercontent.com/51244533/198828018-be5992b8-be96-4989-b858-7252d19cd430.png)

**Comment by mreineck** [comment]
Maybe I'm misunderstanding something, but if your dipole is oriented along the z-axis (i.e. lat=90deg), then  its longitude is irrelevant. The dipole map should look identical whether you specify a dipole of (lat=90deg, lon=0deg) or (lat=90deg, lon=90deg).

Consequently the routine determining the dipole direction may give you any value for the longitude, if the latitude is at 90 (or -90) degrees.

**Comment by VasundharaShaw** [comment]
> Maybe I'm misunderstanding something, but if your dipole is oriented along the z-axis (i.e. lat=90deg), then its longitude is irrelevant. The dipole map should look identical whether you specify a dipole of (lat=90deg, lon=0deg) or (lat=90deg, lon=90deg).
> 
> Consequently the routine determining the dipole direction may give you any value for the longitude if the latitude is at 90 (or -90) degrees.

Hi 
Thanks a lot for responding. But I do not think that's the case, because if I know impose a dipole in the East-West or Front Back direction (see plots attached) then I do get the correct value of lon lat from these skymaps.

Also to generate the skymaps I used this bit of code:

## East West Dipole

 f_theta_phi[i] = sin(bb[i])*sin(ll[i])
 
## Front Back Dipole

f_theta_phi[i] = sin(bb[i])*cos(ll[i])


The recovered dipole direction depends on the 'alm' values which are calculated by the fit_dipole function so I don't see why for the 'North South' case the 'alm' values do not give the correct dipole direction.



<img width="540" alt="EW dip" src="https://user-images.githubusercontent.com/51244533/198836504-a5069b56-8a9a-4697-b9ee-e2aa6e07c60a.png">
<img width="540" alt="FB_dip" src="https://user-images.githubusercontent.com/51244533/198836505-bb2299df-fcac-4534-a157-238655826991.png">

**Comment by mreineck** [comment]
> The recovered dipole direction depends on the 'alm' values which are calculated by the fit_dipole function so I don't see why for the 'North South' case the 'alm' values do not give the correct dipole direction.

For the North-South dipole, the `alm` values will not depend on `phi`. Please give it a try :)

If you are using (theta, phi) cordinates, the North-South direction is special, other than East-West or Front-Back. As a lose analogon, imagine standing exactly on Earth's North pole: at this point, the directions "East" and "West" have no meaning.

**Comment by VasundharaShaw** [comment]
> > The recovered dipole direction depends on the 'alm' values which are calculated by the fit_dipole function so I don't see why for the 'North South' case the 'alm' values do not give the correct dipole direction.
> 
> For the North-South dipole, the `alm` values will not depend on `phi`. Please give it a try :)
> 
> If you are using (theta, phi) coordinates, the North-South direction is special, other than East-West or Front-Back. As a loose analogon, imagine standing exactly on Earth's North pole: at this point, the directions "East" and "West" have no meaning.

so I see what you are implying and I did think of that. But this test which I have shown you is actually a test for a case where I was investigating a dipole where I was varying latitudes. Here in the plot attached you will see that that the recovered 
longitude value deviates from the original longitude value of  0 degrees in a weird fashion. I want to understand what exactly is the cause of the weirdly varying longitude values. 

since 'alm' values of different types of North-South case does not depend on the 'phi' value then how does healpy compute these weird values of recovered longitude values.

![Weird_2](https://user-images.githubusercontent.com/51244533/198867999-c731522d-1f13-433b-8205-391b02d38844.png)

**Comment by mreineck** [comment]
Sorry, now I'm totally confused ... how can the initial dipole latitude have values outside [-90;90]?

**Comment by VasundharaShaw** [comment]
> Sorry, now I'm totally confused ... how can the initial dipole latitude have values outside [-90;90]?
Well, you can just transform the values to go back to the desired range of HEALPix. But if you omit the region beyond -90 to +90 there is still the issue of the longitude values increasing for each increasing value of latitude.

**Comment by mreineck** [comment]
I cannot really judge what is going wrong without seeing the whole code that produced the plot above, but here is a snippet which demonstrated that the dipole vector seems to be recovered quite well for all (lon, lat) pairs I'm trying:

```python
import healpy as hp
import numpy as np

# make a map with given nside and a dipole pointing towards lat, lon (in degrees)
def make_dipole_map(nside, dipole_lon, dipole_lat):
    npix = hp.nside2npix(nside)
    lon, lat = hp.pix2ang(nside, np.arange(npix), lonlat=True)
    # convert lon, lat to Cartesian vector
    vec = hp.ang2vec(lon, lat, lonlat=True)
    dipvec = hp.ang2vec(dipole_lon, dipole_lat, lonlat=True)
    # get dipole values via dot product
    res = np.zeros(npix)
    for i in range(npix):
        res[i] = np.sum(dipvec*vec[i,:])
    return res

maxangdiff = 0
# iterate over many dipole directions
for lat in range(-90, 90, 10):
    for lon in range(0, 360, 10):
        # make the map with a dipole oriented towards (lon, lat)
        map = make_dipole_map(32, lon, lat)
        # the Cartesian representation of the input dipole vector
        dipvec_input = hp.ang2vec(lon, lat, lonlat=True)
        # reconstruct the dipole vector from the map
        dip_vec = hp.fit_dipole(map)[1]
        # compute angle between input and output dipole vector
        angdiff = np.degrees(hp.rotator.angdist(dipvec_input, dip_vec)) #np.arccos(np.sum(dipvec_input*dip_vec)))
        print(lon, lat, angdiff)
        maxangdiff = max(maxangdiff, angdiff)

print("maximum angular difference found: ", maxangdiff, "degrees")
```

I could imagine that perhaps somewhere in your code `lon` and `lat` may be swapped, but that's just a guess ...
