### ISSUE TITLE
ValueError: nside 16384 of map cannot be larger than MAX_NSIDE 8192

### ISSUE THREAD

**Issue by JegerBroxterman** [healpy/healpy#812]
I have been using multiple healpy functions (e.g. healpy.map2alm() and healpy.sphtfunc.anafast()) which all seem to allow a maximum NSIDE of 8192. As I don't understand where this limitation comes from, is there an easy way to extend this to allow for maps with a higher resolution or will this lead to issues?

**Comment by mreineck** [comment]
The limitation comes from the fact that for Nside=16384 the number of pixels in a map is larger than the maximum signed 32bit integer value, and this causes problems with traditional Fortran compilers, so the maximum official supported side for Healpix maps is 8192. There are ways around this problem, but nothing that's really satisfactory and really portable. Also, a single Nside 16384 map is at least 12GB in size - at this kind of resolution it may be better to think about working with partial maps.
