### ISSUE TITLE
rotator.Rotator.rotate_map_alms decreases signal 

### ISSUE THREAD

**Issue by JegerBroxterman** [healpy/healpy#813]
I am rotating a healpy map using a code similar to 

```
rot = healpy.Rotator(rot=[phi, theta], inv=True)
rotated_map = rot.rotate_map_alms(hmap)
```

With theta and phi galactic coordinates in degrees. Visually, the structures in the map seem to be rotated as I expect. However, I encounter some unexpected characteristics.  In the new rotated map, some pixels get negative values (e.g. `min(rotated_map) = -5.27e+20,` whereas `min(hmap) = 0`. More general, the values seem to deviate. For example, when I rotate using ` phi = theta = 0.` , the values between the different maps differ by up to an order of magnitude (absolutely). With mean `np.mean(hmap/rotated_map) = 0.91....` which should be 1. The mean values of the full maps still agree within e--8. 

Do I not understand the behavior and this is expected? If not, is there a way around this?

**Comment by mreineck** [comment]
If your map is not sufficiently smooth, then yes, this is expected. The code tries to approximate the original map by a set of spherical harmonic coefficients and then rotates those. If you have sharp steps in the input, you will see a lot of overshooting in the output. Unfortunately I'm not aware of any criterion that tells you quantitatively when a map is smooth enough for rotation via a_lm; but as a rule of thumb, if its power spectrum doesn't fall off with increasing l, this sort of rotation will not work.

**Comment by JegerBroxterman** [comment]
Smoothing the map indeed helped. Thank you.
