### ISSUE TITLE
Vectorize hp.get_interp_val over multiple input maps

### ISSUE THREAD

**Issue by jvavrek** [healpy/healpy#815]
It would be really useful performance-wise to be able to call `hp.get_interp_val` with a sequence of maps and have the interpolations for all the maps, theta, and phi be computed in a vectorized fashion. It should be possible to do this manually via `hp.get_interp_weights` and some array manipulation, but it would be really nice if `hp.get_interp_val` supported it out of the box.

**Comment by zonca** [comment]
Agreed, it would be useful.
Would you be able to implement it in a Pull Request?

**Comment by jvavrek** [comment]
Sure, see https://github.com/healpy/healpy/pull/816
