### ISSUE TITLE
'pip install' fails on ARM platforms, including Apple Silicon

### ISSUE THREAD

**Issue by spenczar** [healpy/healpy#818]
So here's a Dockerfile:
```Dockerfile
FROM ubuntu:jammy

RUN apt-get update
RUN apt-get install python3 pip -y
RUN pip install healpy
```
(note that this will install python3.10, today)

Try `docker build` with that, and you'll get an error:

```
#7 39.94         File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
#7 39.94           raise CalledProcessError(retcode, cmd)
#7 39.94       subprocess.CalledProcessError: Command '['/bin/sh', '/tmp/pip-install-m3p7snpr/healpy_d012e8a7590242d9b4afdb9a97bef27c/healpixsubmodule/src/cxx/configure', '--prefix=/tmp/pip-install-m3p7snpr/healpy_d012e8a7590242d9b4afdb9a97bef27c/build/temp.linux-aarch64-3.10', '--disable-shared', '--with-pic', '--disable-maintainer-mode']' returned non-zero exit status 1.
#7 39.94       [end of output]
#7 39.94
#7 39.94   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 39.94   ERROR: Failed building wheel for healpy
#7 39.94 ERROR: Could not build wheels for healpy, which is required to install pyproject.toml-based projects
#7 39.94 Failed to build healpy
```
There's a lot more in the scrollback, but crawling up through it, this seems to be related to the cfitsio redistribution:

```
#7 39.94       checking for cfitsio... yes
#7 39.94       checking for ffgnrwll in -lcfitsio... no
#7 39.94       configure: error: could not find the cfitsio library
```
The first and third lines of that seem to be in some disagreement.

The full output is very long. I've placed it here: https://gist.github.com/spenczar/f49c4a427dcb1bc961d93125e1847efa

**Comment by spenczar** [comment]
After some more investigation, this looks like it's because I'm on Apple Silicon. The prebuilt binaries are only for x86.

Fortunately, the Docker for Mac daemon can virtualize x86. So `docker build --platform=linux/amd64` actually works just fine.

Still, running in a virtualized environment is painful, and I don't see any other issue requesting Apple Silicon wheels, so maybe this becomes that?

**Comment by zonca** [comment]
Ok,
Please change the issue title.

**Comment by spenczar** [comment]
I don't know anything about how healpy builds, and its cfitsio and healpix_cxx portions may require special work. But `cibuildwheel` may make this easy. It should build `aarch64` platformed wheels as part of its manylinux builds, as long as the GitHub Actions runner has an `arch` of `aarch64`.

Then, those `aarch64` builds should work in any Docker container running on M1 (or M2, I guess) Macs. As a bonus, it would work on other ARM64 Linux machines.

Native Apple Silicon builds are probably similar; I think cibuildwheel can build them under emulation.

**Comment by lpsinger** [comment]
#819 adds Linux aarch64 builds under emulation. This should fix your use case in Docker (i.e., under Linux) on Apple Silicon.

macOS arm64, I think, is a little harder. Rosetta2 emulates x86_64 on Apple Silicon, but I don't think that it emulates Apple Silicon on x86_64. And unfortunately GitHub is being very slow to add Apple Silicon GitHub Actions runners (github/roadmap#528).

**Comment by zonca** [comment]
Should we do another release to publish those wheels?
Moreover, as we have dropped support for python 3.7, we should tag a minor release i.e. 1.17.0

**Comment by hivon** [comment]
@zonca did you consider synchronizing it with a Healpix release ?
Does it include the latest cfitsio, recommended for security reasons ?

**Comment by lpsinger** [comment]
> Should we do another release to publish those wheels?
> Moreover, as we have dropped support for python 3.7, we should tag a minor release i.e. 1.17.0

Yes.
