### ISSUE TITLE
How to split mask/map into 2 parts?

### ISSUE THREAD

**Issue by Nestak2** [healpy/healpy#825]
I have actually a question, not an issue, but I hope the community can help me! Thanks, if you allow the question
I have a mask/map as a fits file, downloadable [here][1], and I can plot this mask with healpy using this code:

    import healpy as hp
    from healpy.newvisufunc import projview, newprojplot

    wmap_map_I = hp.read_map('mask.fits')
    projview(
        wmap_map_I,
        graticule=True, graticule_labels=True, xlabel="longitude", ylabel="latitude",
        projection_type="mollweide",
        coord=["E"],
        title="Histogram equalized Ecliptic",
        unit="mK",
        norm="hist",
        min=-1,
        max=1,
    );

It produces this figure:

[![enter image description here][2]][2]

What I want to do is split the mask into 2 new masks - one should contain only part A and the other should contain only part B. I don't know how to do this, I thought of making some conditional expression about all points for which longitude + latitude < xyz and then the opposite, but the fits file doesn't contain longitude and latitude.

So how can I split the mask into 2? Thx

  [1]: https://drive.google.com/file/d/18S-jbfF3fxwhmthnTQLkyRJ8DkaS5FSp/view?usp=sharing
  [2]: https://i.stack.imgur.com/4Z1RA.png

**Comment by zonca** [comment]
see https://stackoverflow.com/questions/75165688/in-healpy-how-to-split-mask-map-into-2-parts

**Comment by Nestak2** [comment]
@zonca Can you please reopen the issue, if this is acceptable? I would like for the community to see it's open, so that someone can help me. It was me who posted the StackOverflow question and it has received almost no attention (no answer and only 8 views within a full day). thx

**Comment by hivon** [comment]
Hi @Nestak2, see my reply on https://stackoverflow.com/questions/75165688/in-healpy-how-to-split-mask-map-into-2-parts .
It is more an application of Healpix and astronomy than related to a healpy code development, so I guess it more fitted to StackOverflow than to this bug tracker.

**Comment by Nestak2** [comment]
@hivon Thanks, I used your advice to solve my problem and answered my question in StackOverflow

@zonca Thanks for maintaining healpy! When I did the coordinate transformation of my map with `rot_gal2eq = hp.Rotator(coord=['G', 'C'], inv=True)`, I discovered that the values of the pixels of my map slightly changed. I discovered that you have also written about in in your post [here](https://www.zonca.dev/posts/2021-03-11-rotate-maps-healpy.html). Is there something one can do to not loose precision? Have I maybe used a wrong approach? Or maybe I should have set `inv=False`? If you want, you can look up my code [here](https://stackoverflow.com/questions/75165688/in-healpy-how-to-split-mask-map-into-2-parts/75193164#75193164). Thanks for a reply!
