### ISSUE TITLE
Error on cfitsio library

### ISSUE THREAD

**Issue by GustavoMagro** [healpy/healpy#844]
Hello guys, i'm having problems while installing healpy through the .tar file, i'm running ubuntu's most recent version and i can ./configure the files but when i try sudo make healpy-all it gives a error about cfitsio library, the logs are in the images, i appreciate the help

![Captura de tela de 2023-04-13 16-27-14](https://user-images.githubusercontent.com/131320398/233231228-7d51aede-aba4-4727-8056-771d83cc3159.png)

**Comment by zonca** [comment]
Cannot install from the tar file. Please check the installation instructions.
