### ISSUE TITLE
Warning: cannot import _healpy_pixel_lib module

### ISSUE THREAD

**Issue by AstroTzj** [healpy/healpy#846]
Hi,
I have a MacOS High Sierra (10.13.6) on which is installed Python 3.9.13 and Clang 6.0 (clang-600.0.57)] on darwin.

I installed and upgraded healpy:

pip install --user --upgrade healpy
healpy in ./Library/Python/3.9/lib/python/site-packages (1.16.2)
matplotlib in ./Library/Python/3.9/lib/python/site-packages (from healpy) (3.7.1)
numpy>=1.13 in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.24.2)
astropy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (5.2.2)
scipy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.10.1)
pyerfa>=2.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (2.0.0.3)
PyYAML>=3.13 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (6.0)
packaging>=19.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (23.1)
contourpy>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.0.7)
cycler>=0.10 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (0.11.0)
fonttools>=4.22.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (4.39.3)
kiwisolver>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.4.4)
pillow>=6.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (9.5.0)
pyparsing>=2.3.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (3.0.9)
python-dateutil>=2.7 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (2.8.2)
importlib-resources>=3.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (5.12.0)
zipp>=3.1.0 in ./Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->healpy) (3.15.0)
six>=1.5 in ./Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.7->matplotlib->healpy) (1.16.0)

and everything seems to be ok but when I run python and try to import healpy I have the following error:

Warning: cannot import _healpy_pixel_lib module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/__init__.py", line 67, in <module>
    from .sphtfunc import (
  File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/sphtfunc.py", line 33, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: dlopen(/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/_healpy_sph_transform_lib.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib

How can I solve the problem?
Thanks!

**Comment by zonca** [comment]
Sorry, no idea, have you tried using one of the conda packages?

**Comment by jpbrandtu** [comment]
I have the same problem (also using MacOS High Sierra (10.13.6)) when I import healpy after installing it using pip.
And if I try to use a conda environment, when running jupyter notebook, I get the "Segmentation fault: 11" error.

**Comment by alizamustafaa** [comment]
Have the same issue!

**Comment by alizamustafaa** [comment]
> Hi, I have a MacOS High Sierra (10.13.6) on which is installed Python 3.9.13 and Clang 6.0 (clang-600.0.57)] on darwin.
> 
> I installed and upgraded healpy:
> 
> pip install --user --upgrade healpy healpy in ./Library/Python/3.9/lib/python/site-packages (1.16.2) matplotlib in ./Library/Python/3.9/lib/python/site-packages (from healpy) (3.7.1) numpy>=1.13 in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.24.2) astropy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (5.2.2) scipy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.10.1) pyerfa>=2.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (2.0.0.3) PyYAML>=3.13 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (6.0) packaging>=19.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (23.1) contourpy>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.0.7) cycler>=0.10 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (0.11.0) fonttools>=4.22.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (4.39.3) kiwisolver>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.4.4) pillow>=6.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (9.5.0) pyparsing>=2.3.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (3.0.9) python-dateutil>=2.7 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (2.8.2) importlib-resources>=3.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (5.12.0) zipp>=3.1.0 in ./Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->healpy) (3.15.0) six>=1.5 in ./Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.7->matplotlib->healpy) (1.16.0)
> 
> and everything seems to be ok but when I run python and try to import healpy I have the following error:
> 
> Warning: cannot import _healpy_pixel_lib module Traceback (most recent call last): File "", line 1, in File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/**init**.py", line 67, in from .sphtfunc import ( File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/sphtfunc.py", line 33, in from . import _healpy_sph_transform_lib as sphtlib ImportError: dlopen(/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/_healpy_sph_transform_lib.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc Referenced from: /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib in /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib
> 
> How can I solve the problem? Thanks!

were you able to solve this?

**Comment by lpsinger** [comment]
I'd be a little surprised if Healpy works on macOS 10.13.x because our wheels are built against macOS 11. Can you try updating to a more recent version of macOS?

FYI, High Sierra stopped receiving security updates almost 3 years ago (see https://endoflife.date/macos).

**Comment by alizamustafaa** [comment]
I have the recent version macOS 14

**Comment by AstroTzj** [comment]
> > Hi, I have a MacOS High Sierra (10.13.6) on which is installed Python 3.9.13 and Clang 6.0 (clang-600.0.57)] on darwin.
> > I installed and upgraded healpy:
> > pip install --user --upgrade healpy healpy in ./Library/Python/3.9/lib/python/site-packages (1.16.2) matplotlib in ./Library/Python/3.9/lib/python/site-packages (from healpy) (3.7.1) numpy>=1.13 in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.24.2) astropy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (5.2.2) scipy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.10.1) pyerfa>=2.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (2.0.0.3) PyYAML>=3.13 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (6.0) packaging>=19.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (23.1) contourpy>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.0.7) cycler>=0.10 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (0.11.0) fonttools>=4.22.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (4.39.3) kiwisolver>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.4.4) pillow>=6.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (9.5.0) pyparsing>=2.3.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (3.0.9) python-dateutil>=2.7 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (2.8.2) importlib-resources>=3.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (5.12.0) zipp>=3.1.0 in ./Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->healpy) (3.15.0) six>=1.5 in ./Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.7->matplotlib->healpy) (1.16.0)
> > and everything seems to be ok but when I run python and try to import healpy I have the following error:
> > Warning: cannot import _healpy_pixel_lib module Traceback (most recent call last): File "", line 1, in File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/**init**.py", line 67, in from .sphtfunc import ( File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/sphtfunc.py", line 33, in from . import _healpy_sph_transform_lib as sphtlib ImportError: dlopen(/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/_healpy_sph_transform_lib.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc Referenced from: /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib in /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib
> > How can I solve the problem? Thanks!
> 
> were you able to solve this?

No. And you?

**Comment by AstroTzj** [comment]
> I'd be a little surprised if Healpy works on macOS 10.13.x because our wheels are built against macOS 11. Can you try updating to a more recent version of macOS?
> 
> FYI, High Sierra stopped receiving security updates almost 3 years ago (see https://endoflife.date/macos).

I upgraded to a recent version of MacOS last year but I was obliged to downgrade cause some important tools I use at work were not supported or able to run.

**Comment by alizamustafaa** [comment]
> > > Hi, I have a MacOS High Sierra (10.13.6) on which is installed Python 3.9.13 and Clang 6.0 (clang-600.0.57)] on darwin.
> > > I installed and upgraded healpy:
> > > pip install --user --upgrade healpy healpy in ./Library/Python/3.9/lib/python/site-packages (1.16.2) matplotlib in ./Library/Python/3.9/lib/python/site-packages (from healpy) (3.7.1) numpy>=1.13 in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.24.2) astropy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (5.2.2) scipy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.10.1) pyerfa>=2.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (2.0.0.3) PyYAML>=3.13 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (6.0) packaging>=19.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (23.1) contourpy>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.0.7) cycler>=0.10 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (0.11.0) fonttools>=4.22.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (4.39.3) kiwisolver>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.4.4) pillow>=6.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (9.5.0) pyparsing>=2.3.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (3.0.9) python-dateutil>=2.7 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (2.8.2) importlib-resources>=3.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (5.12.0) zipp>=3.1.0 in ./Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->healpy) (3.15.0) six>=1.5 in ./Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.7->matplotlib->healpy) (1.16.0)
> > > and everything seems to be ok but when I run python and try to import healpy I have the following error:
> > > Warning: cannot import _healpy_pixel_lib module Traceback (most recent call last): File "", line 1, in File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/**init**.py", line 67, in from .sphtfunc import ( File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/sphtfunc.py", line 33, in from . import _healpy_sph_transform_lib as sphtlib ImportError: dlopen(/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/_healpy_sph_transform_lib.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc Referenced from: /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib in /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib
> > > How can I solve the problem? Thanks!
> > 
> > 
> > were you able to solve this?
> 
> No. And you?

nope

**Comment by abbyschleigh** [comment]
> > > Hi, I have a MacOS High Sierra (10.13.6) on which is installed Python 3.9.13 and Clang 6.0 (clang-600.0.57)] on darwin.
> > > I installed and upgraded healpy:
> > > pip install --user --upgrade healpy healpy in ./Library/Python/3.9/lib/python/site-packages (1.16.2) matplotlib in ./Library/Python/3.9/lib/python/site-packages (from healpy) (3.7.1) numpy>=1.13 in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.24.2) astropy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (5.2.2) scipy in ./Library/Python/3.9/lib/python/site-packages (from healpy) (1.10.1) pyerfa>=2.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (2.0.0.3) PyYAML>=3.13 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (6.0) packaging>=19.0 in ./Library/Python/3.9/lib/python/site-packages (from astropy->healpy) (23.1) contourpy>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.0.7) cycler>=0.10 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (0.11.0) fonttools>=4.22.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (4.39.3) kiwisolver>=1.0.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (1.4.4) pillow>=6.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (9.5.0) pyparsing>=2.3.1 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (3.0.9) python-dateutil>=2.7 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (2.8.2) importlib-resources>=3.2.0 in ./Library/Python/3.9/lib/python/site-packages (from matplotlib->healpy) (5.12.0) zipp>=3.1.0 in ./Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->healpy) (3.15.0) six>=1.5 in ./Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.7->matplotlib->healpy) (1.16.0)
> > > and everything seems to be ok but when I run python and try to import healpy I have the following error:
> > > Warning: cannot import _healpy_pixel_lib module Traceback (most recent call last): File "", line 1, in File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/**init**.py", line 67, in from .sphtfunc import ( File "/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/sphtfunc.py", line 33, in from . import _healpy_sph_transform_lib as sphtlib ImportError: dlopen(/Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/_healpy_sph_transform_lib.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc Referenced from: /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib in /Users/astrotzj/Library/Python/3.9/lib/python/site-packages/healpy/.dylibs/libstdc++.6.dylib
> > > How can I solve the problem? Thanks!
> > 
> > 
> > were you able to solve this?
> 
> No. And you?

I was having the same issue but managed to fix it -- Install it by using `conda config --add channels conda-forge
conda install healpy` . It took a while to fully install this way, but I was no longer getting the error after it was done. Hopefully this works for you!

**Comment by lpsinger** [comment]
This error message is due to an older, unsupported version of macOS.
