### ISSUE TITLE
Dealing with other sky maps

### ISSUE THREAD

**Issue by Daniel12345abcde** [healpy/healpy#851]
Hi, I'm dealing with other sky maps or images based on healpy to get the auto-power spectrum. However, I noticed that the initial alm [almI = np.empty(n_alm, dtype=np.complex128)  in map2alm (/healpy/healpy/tree/main/healpy/src/_sphtools.pyx)] is random. I doubt whether it will lead to errors which are out of our expections when dealing with other sky maps except CMB sky map.

Thank you!

**Comment by zonca** [comment]
no, it is just allocating an empty vector in Python that will be overwritten by the C++ code.
