### ISSUE TITLE
New release to generate Linux aarch64 wheels

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#857]
@zonca, would you please do a release of healpy? We added Linux aarch64 wheels to the CI script a while ago and I need binaries for this platform and architecture for one of my LIGO projects.

**Comment by zonca** [comment]
ok

**Comment by zonca** [comment]
released 1.16.3

Release:
* [ ] Github: https://github.com/healpy/healpy/releases/
* [ ] PyPI: https://pypi.org/project/healpy
* [ ] conda-forge: https://anaconda.org/conda-forge/healpy
* [ ] wheels on PyPI for linux and Mac OS

**Comment by lpsinger** [comment]
Thanks!
