### ISSUE TITLE
New minor release 1.16.4

### ISSUE THREAD

**Issue by zonca** [healpy/healpy#866]
Mostly triggered by https://github.com/conda-forge/healpy-feedstock/pull/57#issuecomment-1664756525

**Comment by zonca** [comment]
@lpsinger

**Comment by lpsinger** [comment]
You created a tag but not a release. The deployment workflow is triggered by releases. Would you please create a release?

**Comment by pkgw** [comment]
It looks like this release has mostly gone through, but PyPI is saying that there's no source distribution, here:

https://pypi.org/project/healpy/#files

In order to update the conda-forge package (e.g. https://github.com/conda-forge/healpy-feedstock/pull/57) that will need to be fixed.

**Comment by lpsinger** [comment]
Yes, exactly. See #870.
