### ISSUE TITLE
healpy.write_alm produces too large files

### ISSUE THREAD

**Issue by carronj** [healpy/healpy#889]
Both on my Mac OS laptop and NERSC systems the file written by healpy.write_alm is significantly larger than I'd expect (and used by numpy.save for example), is this normal behavior ?

Example:

import healpy as hp, numpy as np
alm = hp.synalm(np.ones(4097, dtype=float))
print("Memory size of numpy array in bytes which I expect to see on disk:", alm.size * alm.itemsize)

np.save('./testarr.npy', alm)
! ls ./testarr.npy -all
hp.write_alm('./testarr.fits', alm)
! ls ./testarr.fits -all

------------
​I see this:

Memory size of numpy array in bytes which I expect to see on disk: 134316048
-rw-rw---- 1 jcarron jcarron 134316176 Sep 21 10:09 ./testarr.npy
-rw-rw---- 1 jcarron jcarron 167901120 Sep 21 10:09 ./testarr.fits

**Comment by zonca** [comment]
Probably because it is storing the index:

https://github.com/healpy/healpy/blob/b7a39f044020df838c097fbb80364ac25f618b7a/healpy/fitsfunc.py#L567-L572

**Comment by carronj** [comment]
ah ok, thanks! Intended then...
