### ISSUE TITLE
New release 1.16.6 to generate wheels for Python 3.12

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#890]
It would be great to do a release at the earliest opportunity so that we publish wheels for Python 3.12. The CI/CD pipeline is all ready for it.

**Comment by zonca** [comment]
Release:
* [ ] Github: https://github.com/healpy/healpy/releases/
* [ ] PyPI: https://pypi.org/project/healpy
* [ ] conda-forge: https://anaconda.org/conda-forge/healpy
* [ ] wheels on PyPI for linux and Mac OS

**Comment by zonca** [comment]
I see Linux x86 Linux aarch64 and Mac os wheels for Python 3.9 to 3.12 on Pypi
@lpsinger is there anything missing?

**Comment by lpsinger** [comment]
Nope, all done. I just updated the Conda package.
