### ISSUE TITLE
Cannot Build Healpy

### ISSUE THREAD

**Issue by kjkoeller** [healpy/healpy#897]
When I try to build healpy for testing on my package it fails (log can be found here: https://github.com/kjkoeller/EclipsingBinaries/actions/runs/7681153636/job/21134933677)

Other people who install my package are also reporting issues with building healpy on windows all of a sudden. I haven't changed my package requirements in months to potentially a year and this happened within the last like 1-3 months or so. Any ideas about why this could be happening?

**Comment by lpsinger** [comment]
We don't have Healpy builds for Windows (see #25).

**Comment by kjkoeller** [comment]
Thanks for replying and I found the issue with another package that uses Healpy as a required dependency instead of optional.
