### ISSUE TITLE
projview() return_only_data argument

### ISSUE THREAD

**Issue by Wasim04** [healpy/healpy#909]
If one chooses to use 'cart' as projection type and only returns the data (let's say the data returned was shaped: (num_sample, 500, 1000) for a nside 64). I am wondering, after performing some study on 'flat data', if there is a way to return back to spherical projection with (num_sample, 49152) shape. I guess what I am asking is that if my input data is now (num_sample, 500, 1000) how can I get back to mollweide projection from here. Thanks

**Comment by zonca** [comment]
please provide an executable simple example where you simulate some simple data, call `projview` and explain what you want to get back to.

**Comment by zonca** [comment]
you can also look into `pixell` which provides rectangular pixels in curved space and can convert to healpix:
https://github.com/simonsobs/pixell/blob/a5e44701c4f63106bc105f48c14d99f8fe233ca9/pixell/reproject.py#L246C5-L246C16

**Comment by Wasim04** [comment]
> you can also look into `pixell` which provides rectangular pixels in curved space and can convert to healpix: https://github.com/simonsobs/pixell/blob/a5e44701c4f63106bc105f48c14d99f8fe233ca9/pixell/reproject.py#L246C5-L246C16

Hi Andrea, This looks like a great suggestion. I shall look into it and get back. Many Thanks.
