### ISSUE TITLE
How to understand the function 'alm2cl' in healpy?

### ISSUE THREAD

**Issue by lizcphysics** [healpy/healpy#911]
Using healpy, I get a series of values of 'alm',  and then get the values of 'cl' using healpy.alm2cl.
But it seems the 'cl' values are different from the values I calculated using the belowing formula (and codes).

![1709280683611](https://github.com/healpy/healpy/assets/84276704/7d8a8a1e-ce5b-4d25-bf89-4646373d7cd8)

Cl = np.zeros(lmax+1)
for l in range(0, lmax+1):
    Cl[l] = np.sum(np.abs(alm)[l**2:(l+1)**2]**2.0) / (2.0*l+1.0) 

Why?

**Comment by mreineck** [comment]
I think that's because your assumption about the ordering of the `alm` in memory is incorrect. They are stored in the order `a_0,0, a_1,0, a_2,0,[...], a_lmax,0, a_1,1, a_2,1, [...]`.Extracting the subset of coefficients with the same `l` is unfortunately not trivial in this storage scheme.

**Comment by lizcphysics** [comment]
> I think that's because your assumption about the ordering of the `alm` in memory is incorrect. They are stored in the order `a_0,0, a_1,0, a_2,0,[...], a_lmax,0, a_1,1, a_2,1, [...]`.Extracting the subset of coefficients with the same `l` is unfortunately not trivial in this storage scheme.

Thank you very much! Now I understand.
