### ISSUE TITLE
Unable to compile cpp file generated from _pixelfunc.pyx

### ISSUE THREAD

**Issue by lrbison** [healpy/healpy#925]
While trying to build from source I found the following error:

```
877      healpy/src/_pixelfunc.cpp: In function 'PyObject* __pyx_pf_6healp
            y_10_pixelfunc_ringinfo(PyObject*, PyObject*, PyArrayObject*)':
  >> 878    healpy/src/_pixelfunc.cpp:2185:32: error: 'PyArrayObject' {aka 'str
            uct tagPyArrayObject'} has no member named 'dimensions'
     879       2185 |   __pyx_v_num = (__pyx_v_ring->dimensions[0]);
     880            |                                ^~~~~~~~~~
```

It appears cython generated code which uses a numpy API which is no longer supported.  Removing the NPY_NO_DEPRECATED_API option (https://github.com/healpy/healpy/blob/main/setup.py#L316) caused a few warnings but successfully built.  Likewise setting the value to `None` works as well.

Here is my environment:

```
$ python -V
Python 3.9.7
$ python -c 'import numpy; print(numpy.__version__)'
1.19.5
$ cython --version
Cython version 0.29.36
$ git log -n 1
commit e952ac4fddcaa187d23f97a12859f4c222aea164 (HEAD -> main, origin/main, origin/HEAD)
Author: Leo Singer <leo.singer@ligo.org>
Date:   Thu Mar 14 11:39:47 2024 -0400

    Move vendored sources to cextern directory

    This source layout is more similar to Astropy affiliated packages.
ubuntu@ip-172-31-47-127:/fsx/lrbison/code/healpy$
```

And my build command

```
python setup.py build_ext
```

**Comment by lrbison** [comment]
Oddly, I just noticed the offending lines are still in the .cpp file.  It must be something that the define is triggering in the numpy libraries to change the public definition of the PyArrayObject type?

**Comment by lpsinger** [comment]
You might be building with an older version of Numpy. Instead of `python setup.py build_ext`, please try `pip install -e .`.

See #926.
