### ISSUE TITLE
rotate_alm appear not to be reproducible between machines

### ISSUE THREAD

**Issue by tanveerkarim** [healpy/healpy#927]
I downloaded the Planck lensing sims provided in a_lm `COM_Lensing-SimMap-inputs_4096_R3.00/sky_klm_*.fits`. These a_lms are given in Galactic Coordinate and I am interested in rotating them into Equatorial Coordinate. I first initiate a rotator object `r = hp.Rotator(coord = ['G', 'C'])` and then apply on the sims as `rotated_sim_alm = r.rotate_alm(galactic_sim_alm)`. 

What I notice is that while the rotations are deterministic in a given machine, they slightly vary between machines. Specifically, I am running jobs on NERSC Perlmutter on their Jupyter nodes and the debug nodes. For comparison, I am including outputs from the first five elements, and you will see that they slightly disagree (the relevant lines are "kappa input alm eq first five elements"). 

Output from debug node:
<img width="835" alt="image" src="https://github.com/healpy/healpy/assets/8379724/012e765a-330d-413e-ad1f-b5afa5d08156">

Output from Jypter node:
<img width="820" alt="image" src="https://github.com/healpy/healpy/assets/8379724/02bea5d5-6dd0-4101-bd75-2e313aa9116c">

I thought that the `rotate_alm` function is deterministic since there is no random number generator needed to do the rotation. So I am puzzled by this behavior. Any explanation would be appreciated.

**Comment by zonca** [comment]
Please provide a script to reproduce this

**Comment by tanveerkarim** [comment]
Here is the script I used:

```import numpy as np
import healpy as hp

# parameters
NSIDE = 1024

# define rotator object
r = hp.Rotator(coord = ['G', 'C'])

def gal_alm_to_eq_map2(idx, NSIDE):
    """
    This function takes idx of Planck sims in alm and converts
    to equatorial maps with NSIDE.
    """

    # read input convergence alm sim
    kappa_input_alm = hp.read_alm('/path/to/planck/sims/COM_Lensing-SimMap-inputs_4096_R3.00/sky_klm_%03d.fits' % idx)
    print(f"kappa input alm first five elements: {kappa_input_alm[:5]}")

   # rotate map
    kappa_input_alm_eq = r.rotate_alm(kappa_input_alm)
    print(f"kappa input alm eq first five elements: {kappa_input_alm_eq[:5]}")

   # generate real space map 
    map_input_eq = hp.alm2map(kappa_input_alm_eq, nside = NSIDE, pol = False, verbose = False)

    return map_input_eq


idx = 289
print(gal_alm_to_eq_map2(idx, NSIDE)[:10])```

**Comment by zonca** [comment]
can you simplify to script I can run without having your data?

**Comment by tanveerkarim** [comment]
Here is a simplified stand-alone case. For reference, my Python version is 3.7.10 and healpy is 1.14.0.

```
import numpy as np
import healpy as hp

# parameters
NSIDE = 1024
NSIMS = 300
LMAX = 3 * NSIDE - 1
NMIN = 0

# define rotator object
r = hp.Rotator(coord = ['G', 'C'])

cl_fake = 1.67e-7 * np.ones(4096)
np.random.seed(2024)
alm_fake = hp.synalm(cl_fake)

def gal_alm_to_eq_map2(NSIDE):
    """
    This function takes idx of Planck sims in alm and converts
    to equatorial maps with NSIDE.
    """

    # read input convergence alm sim
    ## this file does not have any Planck noise
    original_alm = alm_fake
    print(f"original 50th - 60th elements: {original_alm[50:60]}")
    rotated_alm = r.rotate_alm(original_alm)
    print(f"rotated 50th - 60th elements: {rotated_alm[50:60]}")
    rotated_map = hp.alm2map(rotated_alm, nside = NSIDE, pol = False, verbose = False)

    return rotated_map

tst = gal_alm_to_eq_map2(1024)```

**Comment by zonca** [comment]
have you checked if this happens with a more recent version of healpy?

**Comment by mreineck** [comment]
Just a small remark: mathematically you are right, `rotate_alm` should be perfectly deterministic. On real hardware, with finite-precision numbers, different compilers, mulithreaded execution etc., however, it is quite possible that different runs produce results which differ on the level of numerical noise. When you are uing multiple threads, this can even occur on two successive runs of the same script on the same computer!

However, the differences you are seeing appear too large to be caused by this. This feels more like a slight difference in the coordinate systems... is it possible that you have two different versions of `astropy` on the two machines which have different definitions of ecliptic and galactic coordinate systems?

**Comment by tanveerkarim** [comment]
Apologies for the delay in response. Turns out @mreineck is right and indeed two versions of `astropy` were giving giving different answers. Once I fixed for that issue, the results are reproducible once again.
