### ISSUE TITLE
Tiling the sky in 15 deg patches

### ISSUE THREAD

**Issue by DebajyotiS** [healpy/healpy#945]
Hello,
I came across this packaeg recently and was wondering if (and if so how) I could use it for my use-case.
I have a bunch of files containing sources with galactic l and b values. What I want is to redistribute the sources such that each file contain sources that fall within 15 degrees of a central l,b value. Ideally these l,b value span out a uniform grid in the sky and the patches may have overlap between them.

I know healpy has the pixelating method - but I wasn't sure how exactly to use it in this case.
Any help is extremely appreciated.

Deb

**Comment by zonca** [comment]
you can use one of the query methods to find the pixels:
https://healpy.readthedocs.io/en/latest/healpy_query.html

then you can put all the tiles back into a single map and make sure you are not missing any pixels.

Then you loop through the sources, do ang2pix so you find the pixel value, so you know which tile you want to put that source in.
