### ISSUE TITLE
Installing `healpy` from source

### ISSUE THREAD

**Issue by keewis** [healpy/healpy#949]
I've been trying to install a recent version of `healpy` from source and always get a `ImportError`:
```sh
pip install --no-binary healpy healpy
# or
pip install git+https://github.com/healpy/healpy

python -c 'import healpy'
# ImportError: libhealpix_cxx.so.4: cannot open shared object file: No such file or directory
```

As far as I can tell, the reason for this is that while the vendored `healpix_cxx` is built, it is never included in the generated wheel.

It seems the wheel you upload to PyPI would *also* have this issue. However, `cibuildwheel` runs `auditwheel repair` on the wheel, which copies the built shared libraries into the wheel. This works because those shared libraries will not be cleaned up after the build finished when building from a clone of the repository (so the build isolation does not appear to work for `build_clib`).

In other words, instead of the above, I've only been able to install `healpy` from source using:
```sh
# clone the repository and initialize submodules
git clone --filter=blob:none --quiet https://github.com/healpy/healpy
pushd healpy
git submodule update --init --recursive -q

mkdir -p built_wheel repared_wheel
# build the wheel
pip wheel --no-deps ./healpy --wheel_dir built_wheel
# repair the built wheel. This copies the built but ignored shared libraries into a separate directory in `site-packages` called `healpy.libs`
# might need to specify the platform (e.g. `--plat linux_x86_64`)
auditwheel repair -w repaired_wheel built_wheel/healpy-*.whl
# install the repaired wheel
pip install --force-reinstall repaired_wheel/healpy-*.whl
# clean up
popd; rm -rf healpy
```
(and I'd expect something similar to work with the source tarball)

Not sure this is worth fixing since a lot of this will change if you switch build systems (for example as in #937), but I thought it would be good to document somewhere.

**Comment by lpsinger** [comment]
This is the expected behavior. These days we expect users to install Healpy via the prebuilt wheels or via the Conda packages, not from source.

An editable install (`pip install -e .`) ought to work, though. Would that be appropriate for your application?

**Comment by keewis** [comment]
It does, but that just links to the build artifacts, it doesn't move the shared libraries into the environment.

My main use case is nightly CI (the idea is to have a early warning system of what is going to fail in the future), where the most convenient way to install the library would be to install from github. I tried that, and noticed the `ImportError`. The next thing I tried was pulling `healpix_cxx` from `conda-forge`, but that currently is not binary compatible with the version of `healpy` from the repository. This is why I started looking into why the wheels from PyPI work but the one from github does not.

In any case, I have the build working now, and simply wanted to share my findings.

**Comment by mcepl** [comment]
> This is the expected behavior. These days we expect users to install Healpy via the prebuilt wheels or via the Conda packages, not from source.

I am talking for openSUSE, and we apparently have the same problem here (https://build.opensuse.org/request/show/1188796#comment-1963052). Should I understand that your package is not buildable out of your sources? Should we remove it from our distro then? Is the building of your package dependent on some kind of secret sauce, which cannot be changed into the building scripts?

**Comment by lpsinger** [comment]
No, of course you can build it from source. However for the purpose of creating packages, I would suggest building the dependencies separately and distributing them as separate packages rather than using the vendored sources. This is what we do for the Debian packages.

When you install healpy from source, it will use pkg-config to try to detect existing installations of the dependencies before it resorts to building the vendored sources.

We used to statically link the vendored libraries, but we recently switched to dynamic linking because it resulted in much smaller wheels. Unfortunately, that had the unintended consequence of making it harder to build from source.

**Comment by badshah400** [comment]
Indeed this is what we (continue to) do with healpy 1.16.x, but version 1.17.0 introduces a dependency on unreleased `healpix 3.83` which causes our builds to fail the pkg-config test on the installed version of the library (still at 3.82) and goes on to build the healpy bundled lib instead:

```log
[   20s]   checking if library 'healpix_cxx' is installed
[   20s]   Package dependency requirement 'healpix_cxx >= 3.83.0' could not be satisfied.
[   20s]   Package 'healpix_cxx' has version '3.82.0', required version is '>= 3.83.0'
[   20s]   building library 'healpix_cxx' from source
```

**Comment by mcepl** [comment]
> Indeed this is what we (continue to) do with healpy 1.16.x, but version 1.17.0 introduces a dependency on unreleased `healpix 3.83` which causes our builds to fail the pkg-config test on the installed version of the library (still at 3.82) and goes on to build the healpy bundled lib instead:
> 
> ```
> [   20s]   checking if library 'healpix_cxx' is installed
> [   20s]   Package dependency requirement 'healpix_cxx >= 3.83.0' could not be satisfied.
> [   20s]   Package 'healpix_cxx' has version '3.82.0', required version is '>= 3.83.0'
> [   20s]   building library 'healpix_cxx' from source
> ```

I think The Right Thing™ to do in such case is still NOT use vendored files, but to patch healpix_cxx (or whatever is the source package) accordingly or use pre-release version [1] (either Pre-Release packages or SCM snapshots).

[1] https://en.opensuse.org/openSUSE:Package_versioning_guidelines

**Comment by lpsinger** [comment]
I think it was simply an oversight that we didn't have a healpix-cxx tarball released. @mreineck, would you please release healpix-cxx?

**Comment by badshah400** [comment]
> 
> I think The Right Thing™ to do in such case is still **NOT** to use the vendored files, but to patch `healpix_cxx` (or whatever is the source package) accordingly or use [pre-release version](https://en.opensuse.org/openSUSE:Package_versioning_guidelines) (either Pre-Release packages or SCM snapshots).

Not in this case as it seems healpix 3.83 may soon be released (big thanks @lpsinger ), but in general doing the above means forcing an unstable, unreleased lib on unsuspecting users. There may be software other than `healpy` depending on `healpix`, for example, and devs of most of them would prefer we stick to stable, released (or at least tagged for release) versions of libraries. Not to mention, the additional burden on packagers to create tarballs out of git sources. As a packager, I would be weary of doing that... much rather postpone everything until the main lib gets a release.

**Comment by badshah400** [comment]
Unfortunately, there seems to be no movement on the `healpix` vcs over on sourceforge. The last commit to trunk is from April and the last tagged release remains at version 3.82. Upstream there seems to be also pretty unresponsive to open tickets <https://sourceforge.net/p/healpix/bugs/142/>

**Comment by lpsinger** [comment]
Upstream does respond to issues; it's simply a very mature project.

That said we would really prefer that they move to Git and a more mainstream build system to make it easier for projects like healpy to interact with healpix-cxx as a dependency.

**Comment by Hellseher** [comment]
Hi,

I've come here while preparing HEALPix and related dependent packages for Guix,
facing the same issue as described above.

The latest available released for HEALPix is 3.8.2 which was successfully built
from provided source. The problem starts when I tried to pack the latest
version of healpy (1.17.3) which starts depending on non existing in upstream
version of HEALPix >= 3.8.3, which quite confusing.

Fail over solution is to pack healpy 1.16.6 which is still requires HEALPix >=
3.8.2.

Hope upstream will accept proposed changes and healpy may be built with system
library instead of custom twicked one.

P.S.
@lpsinger 
> This is what we do for the Debian packages.
```
healpy (1.16.6-2) unstable; urgency=medium

```
https://salsa.debian.org/debian-astro-team/healpy/-/blob/master/debian/changelog?ref_type=heads#L1

Debian astroteam is still on 1.16.6

Thanks,
Oleg

**Comment by lpsinger** [comment]
See also https://github.com/healpy/healpy/issues/965#issuecomment-2339165208. @mreineck, how is the release coming?

**Comment by mreineck** [comment]
I'm really sorry for the delay! I was travelling and fogot about putting the tarball on the web.
I'll try to add the fix for #968 today and will let you know when the updated tarball is uploaded.

**Comment by mreineck** [comment]
@lpsinger, is it OK if I use version 3.82.1, in contrast to the 3.83 I had in the last tarball? This would be more in line with the Healpix policy of releasing "new" versions (as 3.83 would be) synchronously for all languages.

**Comment by mreineck** [comment]
I've now gone ahead and released the file at https://sourceforge.net/projects/healpix/files/Healpix_3.82/healpix_cxx-3.82.1.tar.gz/download
If that turns out to be a problem, we can always add a 3.83 release.

**Comment by lpsinger** [comment]
> @lpsinger, is it OK if I use version 3.82.1, in contrast to the 3.83 I had in the last tarball? This would be more in line with the Healpix policy of releasing "new" versions (as 3.83 would be) synchronously for all languages.

Well, it means we'll have to do another release of Healpy in order to update the minimum required version.

**Comment by mreineck** [comment]
@hivon, is it OK with you if I release a C++-only tarball of Healpix 3.83? I admit that I don't know if/for when 3.83 is currently  planned.

**Comment by hivon** [comment]
@mreineck, @lpsinger, @zonca, there will be a Healpix 3.83 release, hopefully within 2 weeks.

**Comment by lpsinger** [comment]
@hivon, any updates on that?

**Comment by hivon** [comment]
I am working on Healpix 3.83, but have problems with the C compilers on my Mac.
I should ship it with healpy 1.17.3, right ?

**Comment by lpsinger** [comment]
> I am working on Healpix 3.83, but have problems with the C compilers on my Mac. I should ship it with healpy 1.17.3, right ?

Yes.

**Comment by Hellseher** [comment]
Hi,

@lpsinger and @hivon 

I try to refresh python-healpy in Guix astro packages. 

May you clearyfy the status of https://github.com/healpy/healpixmirror/pull/4 and how it's related to 
https://sourceforge.net/projects/healpix/files/Healpix_3.82/ the package  `healpix_cxx-3.82.1.tar.gz	2024-09-22`

Thanks
