### ISSUE TITLE
Mac M1 libomp problem with conda-forge package

### ISSUE THREAD

**Issue by joezuntz** [healpy/healpy#950]
Hi all,

When I install healpy using conda-forge on an M1 mac it includes its own copy of libomp in (for e.g. py3.12) `${CONDA_PREFIX}/lib/python3.12/site-packages/healpy/.dylibs/libomp.dylib`.  When I use healpy at the same time as, for example, `scipy`, which links to a shared conda version in `${CONDA_PREFIX}/lib/libomp.dylib`, this causes a crash at runtime with this message:

```
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
```

The workaround it suggests works for me I don't yet know if any of the problems it warns about actually occur. 

Cheers,
Joe

**Comment by lpsinger** [comment]
If you are using Conda, I suggest that you install healpy with conda too.

**Comment by joezuntz** [comment]
I am installing everything with conda (conda-forge) here.

**Comment by joezuntz** [comment]
Would you consider re-opening this issue? It is a problem with the healpix conda-forge feedstock.

**Comment by lpsinger** [comment]
In that case, would you please open a new issue at https://github.com/conda-forge/healpy-feedstock?

**Comment by joezuntz** [comment]
Will do - thanks.
