### ISSUE TITLE
Release healpy 1.17.3

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#955]
We need a new release so that Healpy is compatible with the latest version of Scipy.

**Comment by zonca** [comment]
Release:
* [ ] Github: https://github.com/healpy/healpy/releases/
* [ ] PyPI: https://pypi.org/project/healpy
* [ ] conda-forge: https://anaconda.org/conda-forge/healpy
* [ ] wheels on PyPI for linux and Mac OS 

@zonca @lpsinger @hivon @mreineck

**Comment by lpsinger** [comment]
Uh oh. GitHub has retired their macOS 11 runners so the macOS wheel build is stuck.

**Comment by lpsinger** [comment]
> Uh oh. GitHub has retired their macOS 11 runners so the macOS wheel build is stuck.

See https://github.com/healpy/healpy/pull/956.

**Comment by zonca** [comment]
Release completed! thanks @lpsinger
