### ISSUE TITLE
Add lonlat parameter in newprojplot

### ISSUE THREAD

**Issue by dreamthreebs** [healpy/healpy#962]
The newprojplot function currently requires coordinates in radians (θ,ϕ), which can be cumbersome for users working primarily in longitude and latitude in degrees. Many healpy functions (e.g., ang2pix, pix2ang) already support a lonlat parameter for direct input in longitude and latitude degrees. Adding this parameter to newprojplot would enhance usability by providing consistency across the library and simplifying the plotting process.

**Comment by zonca** [comment]
agreed, would you be willing to implement this in a pull request?

**Comment by dreamthreebs** [comment]
hi, I have made a pull request to fix this issue, but the readthedocs build seems not work. What should I do to fix that? @zonca

**Comment by zonca** [comment]
implemented in https://github.com/healpy/healpy/pull/963, thanks @dreamthreebs
