### ISSUE TITLE
alm2map(map2alm(input maps)) does not match to input maps

### ISSUE THREAD

**Issue by yoshinori-0778** [healpy/healpy#982]
Dear all,

I did not get the same maps as input via alm2map(map2alm(input maps)).
My codes and ouput is below.
I hope input map (mi in my code) is band-limited because this was made from hp.synfast with lmax = lmax.
In this case, I expected that I got the same maps as input, but there is some difference, which looks something systematical.
So there should be my fault somewhere.
Could you let me where I am wrong?

Thank you for taking your time in advance!

```
cli = hp.read_cl('cl.fits') # This is came from Healpix_3.83/test/cl.fits
nside = 128
lmax = 383 # 3*nside - 1
mi, almi = hp.synfast(cli, nside = nside, lmax = lmax, mmax = lmax, alm = True)
mi2  = hp.alm2map(almi, nside = nside, lmax = lmax, mmax = lmax)
almo = hp.map2alm(mi, lmax=lmax, mmax = lmax, iter = 3, use_pixel_weights=True)
mo  = hp.alm2map(almo, nside = nside, lmax = lmax, mmax = lmax)

plt.figure(figsize = (10,9))
for i, imap in enumerate(mi):
    hp.mollview(imap, sub = (3,3,i+1), title = 'Input maps')
for i, imap in enumerate(mo):
    hp.mollview(imap, sub = (3,3,i+4), title = 'Output maps')
for i, imap in enumerate(mi):
    hp.mollview(mo[i] - mi[i], sub = (3,3,i+7), title = '(Output - Input) maps')
```

![Screenshot 2024-12-20 at 1 27 34 PM](https://github.com/user-attachments/assets/38717d6d-eedb-4716-a37b-873c76bec063)

**Comment by zonca** [comment]
that is expected.
see the docs of anafast: https://healpix.sourceforge.io/html/fac_anafast.htm

you can use pixel weights with good performance only up to 1.5 Nside.

if you need a higher ell max, I recommend:

* disable nside
* use https://healpy.readthedocs.io/en/latest/generated/healpy.sphtfunc.map2alm_lsq.html
* go up to 2.5 Nside

**Comment by yoshinori-0778** [comment]
Thank you for your answer!
